import type { ItemExplanation } from "./item-explanation.ts";

// Per-item explanations for the gustar-style quiz (docs/explanation-quality.md).
// Each names the subject that sets the verb's number and the cue for the pronoun.
export const GUSTAR_EXPLANATIONS: Record<number, ItemExplanation> = {
  1: { cue: "usar zapatos", explanation: "Usar zapatos is the subject, and an infinitive subject always takes singular gusta. A la niña pequeña is one person, so le." },
  2: { cue: "los conciertos", explanation: "Los conciertos is the subject and is plural, so gustan. Me is the pronoun for I." },
  3: { cue: "viajar", explanation: "Viajar is the subject, and an infinitive subject always takes singular gusta. Te is the pronoun for you." },
  4: { cue: "esta canción", explanation: "Esta canción is the subject and is singular, so gusta. Nos is the pronoun for we." },
  5: { cue: "las ciudades", explanation: "Las ciudades is the subject and is plural, so gustan. A mis padres is more than one person, so les." },
  6: { cue: "levantarse", explanation: "Levantarse is the subject, and an infinitive subject always takes singular gusta. Le is the pronoun for he or she." },
  7: { cue: "la comida", explanation: "La comida is the subject and is singular, so gusta. A Juan is one person, so le." },
  8: { cue: "estos ejercicios", explanation: "Estos ejercicios is the subject and is plural, so gustan. A ustedes takes les." },
  9: { cue: "caminar", explanation: "Caminar is the subject, and an infinitive subject always takes singular gusta. Les is the pronoun for they." },
  10: { cue: "las películas", explanation: "Las películas is the subject and is plural, so gustan. A mí goes with me." },
  11: { cue: "bailar", explanation: "Bailar is the subject, and an infinitive subject always takes singular gusta. A Laura is one person, so le." },
  12: { cue: "los hoteles", explanation: "Los hoteles is the subject and is plural, so gustan. Nos is the pronoun for we." },
  13: { cue: "esta chaqueta", explanation: "Esta chaqueta is the subject and is singular, so gusta. Le is the pronoun for he or she." },
  14: { cue: "los cuentos", explanation: "Los cuentos is the subject and is plural, so gustan. A los niños is more than one person, so les." },
  15: { cue: "cocinar", explanation: "Cocinar is the subject, and an infinitive subject always takes singular gusta. Te is the pronoun for you." },
  16: { cue: "la música", explanation: "La música is the subject and is singular, so gusta. Me is the pronoun for I." },
  17: { cue: "las rutas", explanation: "Las rutas is the subject and is plural, so gustan. A Pedro y Ana is more than one person, so les." },
  18: { cue: "aprender", explanation: "Aprender is the subject, and an infinitive subject always takes singular gusta. Nos is the pronoun for we." },
  19: { cue: "el nuevo restaurante", explanation: "El nuevo restaurante is the subject and is singular, so gusta. Les is the pronoun for they." },
  20: { cue: "estas botas", explanation: "Estas botas is the subject and is plural, so gustan. Te is the pronoun for you." },
  21: { cue: "leer", explanation: "Leer is the subject, and an infinitive subject always takes singular gusta. A usted takes le." },
  22: { cue: "los domingos", explanation: "Los domingos is the subject and is plural, so gustan. Me is the pronoun for I." },
  23: { cue: "la cerveza", explanation: "La cerveza is the subject and is singular, so gusta. A Carlos is one person, so le." },
  24: { cue: "las excursiones", explanation: "Las excursiones is the subject and is plural, so gustan. Nos is the pronoun for we." },
  25: { cue: "trabajar", explanation: "Trabajar is the subject, and an infinitive subject always takes singular gusta. Te is the pronoun for you." },
  26: { cue: "este barrio", explanation: "Este barrio is the subject and is singular, so gusta. A ellas takes les." },
  27: { cue: "los vuelos", explanation: "Los vuelos is the subject and is plural, so gustan. Me is the pronoun for I." },
  28: { cue: "nadar", explanation: "Nadar is the subject, and an infinitive subject always takes singular gusta. A Pablo is one person, so le." },
  29: { cue: "la paella", explanation: "La paella is the subject and is singular, so gusta. A ustedes takes les." },
  30: { cue: "estas fotografías", explanation: "Estas fotografías is the subject and is plural, so gustan. Les is the pronoun for they." },
  31: { cue: "salir", explanation: "Salir is the subject, and an infinitive subject always takes singular gusta. A nosotros goes with nos." },
  32: { cue: "el clima", explanation: "El clima is the subject and is singular, so gusta. Te is the pronoun for you." },
  33: { cue: "los libros", explanation: "Los libros is the subject and is plural, so gustan. A Sofía is one person, so le." },
  34: { cue: "conducir", explanation: "Conducir is the subject, and an infinitive subject always takes singular gusta. Me is the pronoun for I." },
  35: { cue: "las clases", explanation: "Las clases is the subject and is plural, so gustan. Le is the pronoun for he or she." },
  36: { cue: "esta banda", explanation: "Esta banda is the subject and is singular, so encanta. Me is the pronoun for I." },
  37: { cue: "los mercados", explanation: "Los mercados is the subject and is plural, so encantan. A Elena is one person, so le." },
  38: { cue: "viajar", explanation: "Viajar is the subject, and an infinitive subject always takes singular encanta. Nos is the pronoun for we." },
  39: { cue: "estas tapas", explanation: "Estas tapas is the subject and is plural, so encantan. Te is the pronoun for you." },
  40: { cue: "el chocolate", explanation: "El chocolate is the subject and is singular, so encanta. A los niños is more than one person, so les." },
  41: { cue: "bailar", explanation: "Bailar is the subject, and an infinitive subject always takes singular encanta. Le is the pronoun for he or she." },
  42: { cue: "las playas", explanation: "Las playas is the subject and is plural, so encantan. A ustedes takes les." },
  43: { cue: "la guitarra", explanation: "La guitarra is the subject and is singular, so encanta. A mí goes with me." },
  44: { cue: "hacer", explanation: "Hacer is the subject, and an infinitive subject always takes singular encanta. Les is the pronoun for they." },
  45: { cue: "los pueblos", explanation: "Los pueblos is the subject and is plural, so encantan. Nos is the pronoun for we." },
  46: { cue: "esta novela", explanation: "Esta novela is the subject and is singular, so encanta. A Julia is one person, so le." },
  47: { cue: "los desayunos", explanation: "Los desayunos is the subject and is plural, so encantan. Te is the pronoun for you." },
  48: { cue: "cocinar", explanation: "Cocinar is the subject, and an infinitive subject always takes singular encanta. A mis amigos is more than one person, so les." },
  49: { cue: "las montañas", explanation: "Las montañas is the subject and is plural, so encantan. Me is the pronoun for I." },
  50: { cue: "el arte", explanation: "El arte is the subject and is singular, so encanta. A usted takes le." },
  51: { cue: "escuchar", explanation: "Escuchar is the subject, and an infinitive subject always takes singular encanta. Nos is the pronoun for we." },
  52: { cue: "estas vistas", explanation: "Estas vistas is the subject and is plural, so encantan. Les is the pronoun for they." },
  53: { cue: "la arquitectura", explanation: "La arquitectura is the subject and is singular, so encanta. A Roberto is one person, so le." },
  54: { cue: "los viajes", explanation: "Los viajes is the subject and is plural, so encantan. A ustedes takes les." },
  55: { cue: "aprender", explanation: "Aprender is the subject, and an infinitive subject always takes singular encanta. Te is the pronoun for you." },
  56: { cue: "la historia", explanation: "La historia is the subject and is singular, so interesa. Me is the pronoun for I." },
  57: { cue: "los idiomas", explanation: "Los idiomas is the subject and is plural, so interesan. A Daniel is one person, so le." },
  58: { cue: "aprender", explanation: "Aprender is the subject, and an infinitive subject always takes singular interesa. Nos is the pronoun for we." },
  59: { cue: "estas noticias", explanation: "Estas noticias is the subject and is plural, so interesan. Te is the pronoun for you." },
  60: { cue: "el ciclismo", explanation: "El ciclismo is the subject and is singular, so interesa. A ellos takes les." },
  61: { cue: "hablar", explanation: "Hablar is the subject, and an infinitive subject always takes singular interesa. Le is the pronoun for he or she." },
  62: { cue: "los museos", explanation: "Los museos is the subject and is plural, so interesan. A ustedes takes les." },
  63: { cue: "la tecnología", explanation: "La tecnología is the subject and is singular, so interesa. A mí goes with me." },
  64: { cue: "conocer", explanation: "Conocer is the subject, and an infinitive subject always takes singular interesa. Les is the pronoun for they." },
  65: { cue: "estos cursos", explanation: "Estos cursos is the subject and is plural, so interesan. Nos is the pronoun for we." },
  66: { cue: "la fotografía", explanation: "La fotografía is the subject and is singular, so interesa. A Paula is one person, so le." },
  67: { cue: "los documentales", explanation: "Los documentales is the subject and is plural, so interesan. Te is the pronoun for you." },
  68: { cue: "mejorar", explanation: "Mejorar is the subject, and an infinitive subject always takes singular interesa. A mis compañeros is more than one person, so les." },
  69: { cue: "las rutas", explanation: "Las rutas is the subject and is plural, so interesan. Me is the pronoun for I." },
  70: { cue: "el proyecto", explanation: "El proyecto is the subject and is singular, so interesa. A usted takes le." },
  71: { cue: "entender", explanation: "Entender is the subject, and an infinitive subject always takes singular interesa. Nos is the pronoun for we." },
  72: { cue: "estas propuestas", explanation: "Estas propuestas is the subject and is plural, so interesan. Les is the pronoun for they." },
  73: { cue: "la economía", explanation: "La economía is the subject and is singular, so interesa. A Tomás is one person, so le." },
  74: { cue: "los deportes", explanation: "Los deportes is the subject and is plural, so interesan. A ustedes takes les." },
  75: { cue: "leer", explanation: "Leer is the subject, and an infinitive subject always takes singular interesa. Te is the pronoun for you." },
  76: { cue: "el ruido", explanation: "El ruido is the subject and is singular, so molesta. Me is the pronoun for I." },
  77: { cue: "las luces", explanation: "Las luces is the subject and is plural, so molestan. A Sara is one person, so le." },
  78: { cue: "esperar", explanation: "Esperar is the subject, and an infinitive subject always takes singular molesta. Nos is the pronoun for we." },
  79: { cue: "estos comentarios", explanation: "Estos comentarios is the subject and is plural, so molestan. Te is the pronoun for you." },
  80: { cue: "el humo", explanation: "El humo is the subject and is singular, so molesta. A ellos takes les." },
  81: { cue: "trabajar", explanation: "Trabajar is the subject, and an infinitive subject always takes singular molesta. Le is the pronoun for he or she." },
  82: { cue: "los precios", explanation: "Los precios is the subject and is plural, so molestan. A ustedes takes les." },
  83: { cue: "la música", explanation: "La música is the subject and is singular, so molesta. A mí goes with me." },
  84: { cue: "levantarse", explanation: "Levantarse is the subject, and an infinitive subject always takes singular molesta. Les is the pronoun for they." },
  85: { cue: "estas interrupciones", explanation: "Estas interrupciones is the subject and is plural, so molestan. Nos is the pronoun for we." },
  86: { cue: "el frío", explanation: "El frío is the subject and is singular, so molesta. A David is one person, so le." },
  87: { cue: "los vuelos", explanation: "Los vuelos is the subject and is plural, so molestan. Te is the pronoun for you." },
  88: { cue: "oír", explanation: "Oír is the subject, and an infinitive subject always takes singular molesta. A mis vecinos is more than one person, so les." },
  89: { cue: "las habitaciones", explanation: "Las habitaciones is the subject and is plural, so molestan. Me is the pronoun for I." },
  90: { cue: "este olor", explanation: "Este olor is the subject and is singular, so molesta. A usted takes le." },
  91: { cue: "la calidad", explanation: "La calidad is the subject and is singular, so importa. Me is the pronoun for I." },
  92: { cue: "los pequeños detalles", explanation: "Los pequeños detalles is the subject and is plural, so importan. A Luis is one person, so le." },
  93: { cue: "llegar", explanation: "Llegar is the subject, and an infinitive subject always takes singular importa. Nos is the pronoun for we." },
  94: { cue: "estas diferencias", explanation: "Estas diferencias is the subject and is plural, so importan. Te is the pronoun for you." },
  95: { cue: "el resultado", explanation: "El resultado is the subject and is singular, so importa. A ellos takes les." },
  96: { cue: "trabajar", explanation: "Trabajar is the subject, and an infinitive subject always takes singular importa. Le is the pronoun for he or she." },
  97: { cue: "los horarios", explanation: "Los horarios is the subject and is plural, so importan. A ustedes takes les." },
  98: { cue: "la opinión", explanation: "La opinión is the subject and is singular, so importa. A mí goes with me." },
  99: { cue: "mantenerse", explanation: "Mantenerse is the subject, and an infinitive subject always takes singular importa. Les is the pronoun for they." },
  100: { cue: "estos cambios", explanation: "Estos cambios is the subject and is plural, so importan. Nos is the pronoun for we." },
  101: { cue: "el medio ambiente", explanation: "El medio ambiente is the subject and is singular, so importa. A Eva is one person, so le." },
  102: { cue: "las condiciones", explanation: "Las condiciones is the subject and is plural, so importan. Te is the pronoun for you." },
  103: { cue: "terminar", explanation: "Terminar is the subject, and an infinitive subject always takes singular importa. A mis colegas is more than one person, so les." },
  104: { cue: "las respuestas", explanation: "Las respuestas is the subject and is plural, so importan. Me is the pronoun for I." },
  105: { cue: "esta decisión", explanation: "Esta decisión is the subject and is singular, so importa. A usted takes le." },
  106: { cue: "un billete", explanation: "Un billete is the subject and is singular, so falta. Me is the pronoun for I." },
  107: { cue: "dos documentos", explanation: "Dos documentos is the subject and is plural, so faltan. A Clara is one person, so le." },
  108: { cue: "terminar", explanation: "Terminar is the subject, and an infinitive subject always takes singular falta. Nos is the pronoun for we." },
  109: { cue: "estas páginas", explanation: "Estas páginas is the subject and is plural, so faltan. Te is the pronoun for you." },
  110: { cue: "un poco de tiempo", explanation: "Un poco de tiempo is the subject and is singular, so falta. A ellos takes les." },
  111: { cue: "practicar", explanation: "Practicar is the subject, and an infinitive subject always takes singular falta. Le is the pronoun for he or she." },
  112: { cue: "las entradas", explanation: "Las entradas is the subject and is plural, so faltan. A ustedes takes les." },
  113: { cue: "una buena mochila", explanation: "Una buena mochila is the subject and is singular, so falta. A mí goes with me." },
  114: { cue: "visitar", explanation: "Visitar is the subject, and an infinitive subject always takes singular falta. Les is the pronoun for they." },
  115: { cue: "algunas sillas", explanation: "Algunas sillas is the subject and is plural, so faltan. Nos is the pronoun for we." },
  116: { cue: "una semana", explanation: "Una semana is the subject and is singular, so queda. Me is the pronoun for I." },
  117: { cue: "tres preguntas", explanation: "Tres preguntas is the subject and is plural, so quedan. A Raúl is one person, so le." },
  118: { cue: "reservar", explanation: "Reservar is the subject, and an infinitive subject always takes singular queda. Nos is the pronoun for we." },
  119: { cue: "estos pantalones", explanation: "Estos pantalones is the subject and is plural, so quedan. Te is the pronoun for you." },
  120: { cue: "poco dinero", explanation: "Poco dinero is the subject and is singular, so queda. A ellos takes les." },
  121: { cue: "preparar", explanation: "Preparar is the subject, and an infinitive subject always takes singular queda. Le is the pronoun for he or she." },
  122: { cue: "dos días", explanation: "Dos días is the subject and is plural, so quedan. A ustedes takes les." },
  123: { cue: "esta camisa", explanation: "Esta camisa is the subject and is singular, so queda. A mí goes with me." },
  124: { cue: "recorrer", explanation: "Recorrer is the subject, and an infinitive subject always takes singular queda. Les is the pronoun for they." },
  125: { cue: "suficientes botellas", explanation: "Suficientes botellas is the subject and is plural, so quedan. Nos is the pronoun for we." },
  126: { cue: "la espalda", explanation: "La espalda is the subject and is singular, so duele. Me is the pronoun for I." },
  127: { cue: "las rodillas", explanation: "Las rodillas is the subject and is plural, so duelen. A Carmen is one person, so le." },
  128: { cue: "caminar", explanation: "Caminar is the subject, and an infinitive subject always takes singular duele. Nos is the pronoun for we." },
  129: { cue: "los hombros", explanation: "Los hombros is the subject and is plural, so duelen. Te is the pronoun for you." },
  130: { cue: "la cabeza", explanation: "La cabeza is the subject and is singular, so duele. A ellos takes les." },
  131: { cue: "subir", explanation: "Subir is the subject, and an infinitive subject always takes singular duele. Le is the pronoun for he or she." },
  132: { cue: "los pies", explanation: "Los pies is the subject and is plural, so duelen. A ustedes takes les." },
  133: { cue: "el brazo", explanation: "El brazo is the subject and is singular, so duele. A mí goes with me." },
  134: { cue: "hacer", explanation: "Hacer is the subject, and an infinitive subject always takes singular duele. Les is the pronoun for they." },
  135: { cue: "las piernas", explanation: "Las piernas is the subject and is plural, so duelen. Nos is the pronoun for we." },
  136: { cue: "la garganta", explanation: "La garganta is the subject and is singular, so duele. A Andrés is one person, so le." },
  137: { cue: "los dedos", explanation: "Los dedos is the subject and is plural, so duelen. Te is the pronoun for you." },
  138: { cue: "dormir", explanation: "Dormir is the subject, and an infinitive subject always takes singular duele. A mis amigos is more than one person, so les." },
  139: { cue: "las muñecas", explanation: "Las muñecas is the subject and is plural, so duelen. Me is the pronoun for I." },
  140: { cue: "el cuello", explanation: "El cuello is the subject and is singular, so duele. A usted takes le." },
  141: { cue: "esta idea", explanation: "Esta idea is the subject and is singular, so parece. Me is the pronoun for I." },
  142: { cue: "estos hoteles", explanation: "Estos hoteles is the subject and is plural, so parecen. A Laura is one person, so le." },
  143: { cue: "practicar", explanation: "Practicar is the subject, and an infinitive subject always takes singular parece. Nos is the pronoun for we." },
  144: { cue: "estas instrucciones", explanation: "Estas instrucciones is the subject and is plural, so parecen. Te is the pronoun for you." },
  145: { cue: "la propuesta", explanation: "La propuesta is the subject and is singular, so parece. A ellos takes les." },
  146: { cue: "conducir", explanation: "Conducir is the subject, and an infinitive subject always takes singular parece. Le is the pronoun for he or she." },
  147: { cue: "los ejercicios", explanation: "Los ejercicios is the subject and is plural, so parecen. A ustedes takes les." },
  148: { cue: "esta solución", explanation: "Esta solución is the subject and is singular, so parece. A mí goes with me." },
  149: { cue: "salir", explanation: "Salir is the subject, and an infinitive subject always takes singular parece. Les is the pronoun for they." },
  150: { cue: "estas respuestas", explanation: "Estas respuestas is the subject and is plural, so parecen. Nos is the pronoun for we." },
};
