import type { ItemExplanation } from "./item-explanation.ts";

// Per-item explanations for the ser vs estar quiz (docs/explanation-quality.md).
export const SER_ESTAR_EXPLANATIONS: Record<number, ItemExplanation> = {
  2001: { cue: "de México", explanation: "De México states where you come from, and origin uses ser." },
  2002: { cue: "médica", explanation: "Médica is a profession, and professions use ser." },
  2003: { cue: "estudiantes", explanation: "Estudiantes says what you are, an identity or role, so ser." },
  2004: { cue: "muy corta", explanation: "Muy corta judges the skirt itself, so ser. Está would also work if you meant it looks short right now, for example after washing." },
  2005: { cue: "lunes", explanation: "Lunes names the day, and days and dates use ser." },
  2006: { cue: "de Ana", explanation: "De Ana says who owns the keys, and possession uses ser de." },
  2007: { cue: "el concierto", explanation: "El concierto is an event, and where an event takes place uses ser, not estar." },
  2008: { cue: "grande y luminosa", explanation: "Grande y luminosa describes what the window is like, a defining description, so ser." },
  2009: { cue: "en casa", explanation: "En casa says where you are, and physical location uses estar." },
  2010: { cue: "debajo de la mesa", explanation: "Debajo de la mesa says where the bags are, and physical location uses estar." },
  2011: { cue: "esta mañana", explanation: "Esta mañana asks how you are right now, a current state, so estar." },
  2012: { cue: "caliente", explanation: "Caliente is how the coffee is at the moment, a temporary state, so estar." },
  2013: { cue: "después del viaje", explanation: "Después del viaje shows cansados is a result of the trip, a resulting state, so estar." },
  2014: { cue: "cerrada", explanation: "Cerrada is the door's current condition, so estar." },
  2015: { cue: "cerca de la estación", explanation: "Cerca de la estación says where the museum is, and physical location uses estar." },
  2016: { cue: "hoy", explanation: "Hoy shows muy buena is how the soup tastes today, an experienced result, so estar." },
  2017: { cue: "para salir", explanation: "Listo para salir means ready to go, and estar listo means to be ready." },
  2018: { cue: "curiosa", explanation: "Lista sits next to curiosa, a trait, so it means clever: ser listo is to be smart. Estar lista would mean ready." },
  2019: { cue: "por la noche", explanation: "Por la noche describes what the area is normally like at night, a characteristic, so ser." },
  2020: { cue: "esta noche", explanation: "Esta noche limits vacío to tonight, a current state, so estar." },
  2021: { cue: "azul", explanation: "Azul is the shirt's colour, a characteristic, so ser." },
  2022: { cue: "mojada", explanation: "Mojada is a temporary condition of the shirt, so estar." },
  2023: { cue: "a las tres", explanation: "A las tres gives when the meeting happens, and event time uses ser." },
  2024: { cue: "en el jardín", explanation: "En el jardín says where the children are, and people's location uses estar." },
  2025: { cue: "aburrida para mí", explanation: "Aburrida para mí presents boring as a quality of the film, so ser. Estar aburrido would describe a bored person." },
  2026: { cue: "durante la película", explanation: "Durante la película shows aburrido is how you feel at that time, a current state, so estar." },
  2027: { cue: "esta semana", explanation: "Esta semana marks enfermo as a temporary health state, and health states use estar." },
  2028: { cue: "muy paciente", explanation: "Muy paciente is a personal characteristic of the teacher, so ser." },
  2029: { cue: "abierta", explanation: "Abierta is the door's current condition, a result of someone opening it, so estar." },
  2030: { cue: "la conferencia", explanation: "La conferencia is an event, and an event's location uses ser." },
  2031: { cue: "ingeniera", explanation: "Ingeniera is a profession, and professions use ser." },
  2032: { cue: "mi mejor amigo", explanation: "Mi mejor amigo states a relationship, who you are to me, so ser." },
  2033: { cue: "periodista", explanation: "Periodista is a profession, and professions use ser." },
  2034: { cue: "vecinos", explanation: "Vecinos is a lasting relationship, so ser, even with desde hace años." },
  2035: { cue: "los dueños", explanation: "Los dueños says who they are, an identity, so ser." },
  2036: { cue: "abogado", explanation: "Abogado is a profession, so ser, even though en Madrid follows." },
  2037: { cue: "la capitana", explanation: "La capitana is a role or title, and roles use ser." },
  2038: { cue: "dentistas", explanation: "Dentistas is a profession, and professions use ser." },
  2039: { cue: "un buen compañero", explanation: "Un buen compañero describes your role and character, so ser." },
  2040: { cue: "el director", explanation: "El director is a title or position, so ser." },
  2041: { cue: "hermanos", explanation: "Hermanos is a family relationship, so ser." },
  2042: { cue: "los organizadores", explanation: "Los organizadores is their role at the event, and roles use ser." },
  2043: { cue: "cliente habitual", explanation: "Cliente habitual is an ongoing role, so ser." },
  2044: { cue: "los nuevos socios", explanation: "Los nuevos socios is a role or position, so ser." },
  2045: { cue: "la autora", explanation: "La autora says who she is in relation to the novel, an identity, so ser." },
  2046: { cue: "de Polonia", explanation: "De Polonia states where you come from, and origin uses ser." },
  2047: { cue: "de una familia italiana", explanation: "De una familia italiana states your origin, so ser." },
  2048: { cue: "de Francia", explanation: "De Francia says where the cheeses come from, and origin uses ser." },
  2049: { cue: "de la región de Rioja", explanation: "De la región de Rioja says where the wine comes from, and origin uses ser." },
  2050: { cue: "de la misma ciudad", explanation: "De la misma ciudad states where you come from, and origin uses ser." },
  2051: { cue: "de un pueblo pequeño", explanation: "De un pueblo pequeño states where she comes from, and origin uses ser." },
  2052: { cue: "de Valencia", explanation: "De Valencia says where the oranges come from, and origin uses ser." },
  2053: { cue: "de padres extranjeros", explanation: "De padres extranjeros states your background, and origin uses ser." },
  2054: { cue: "de Argentina", explanation: "De Argentina states where the teacher comes from, and origin uses ser." },
  2055: { cue: "de la India", explanation: "De la India says where the fabrics come from, and origin uses ser." },
  2056: { cue: "originaria", explanation: "Originaria de says where you come from, and origin uses ser." },
  2057: { cue: "de distintas partes del país", explanation: "De distintas partes del país states where they come from, and origin uses ser." },
  2058: { cue: "de Colombia", explanation: "De Colombia says where the coffee comes from, and origin uses ser." },
  2059: { cue: "de una tradición familiar", explanation: "De una tradición familiar states your heritage, and origin uses ser." },
  2060: { cue: "de ascendencia mexicana", explanation: "De ascendencia mexicana states her heritage, and origin uses ser." },
  2061: { cue: "un refrán", explanation: "Un refrán classifies what the quote is, so ser. Estar never links two nouns like this." },
  2062: { cue: "alto y delgado", explanation: "Alto y delgado describes your build, a physical characteristic, so ser." },
  2063: { cue: "muy antiguo", explanation: "Muy antiguo is a defining quality of the building, so ser." },
  2064: { cue: "por naturaleza", explanation: "Por naturaleza marks curiosos as an inherent trait, so ser." },
  2065: { cue: "paciente", explanation: "Paciente is a personality trait, so ser." },
  2066: { cue: "muy ruidosa", explanation: "Muy ruidosa is what the city is like in general, a defining characteristic, so ser." },
  2067: { cue: "trabajadores", explanation: "Trabajadores is a personality trait, so ser." },
  2068: { cue: "bastante difícil", explanation: "Bastante difícil is a quality of the exam itself, so ser." },
  2069: { cue: "verdes", explanation: "Verdes is the colour of the eyes, a physical feature, so ser." },
  2070: { cue: "conocido por sus restaurantes", explanation: "Conocido por sus restaurantes is a defining feature of the area, so ser." },
  2071: { cue: "muy creativa", explanation: "Muy creativa is a personality trait, so ser." },
  2072: { cue: "muy exigente", explanation: "Muy exigente is a personality trait of the teacher, so ser." },
  2073: { cue: "bastante estrictos", explanation: "Bastante estrictos is a personality trait, so ser." },
  2074: { cue: "larga y lenta", explanation: "Larga y lenta describes what the film is like, a defining quality, so ser." },
  2075: { cue: "ancho y profundo", explanation: "Ancho y profundo is a geographic characteristic of the river, so ser." },
  2076: { cue: "de plástico", explanation: "De plástico says what the chair is made of, and material uses ser." },
  2077: { cue: "miércoles", explanation: "Miércoles names the day, and days of the week use ser." },
  2078: { cue: "las ocho", explanation: "Las ocho gives the time, and clock time uses ser." },
  2079: { cue: "el próximo sábado", explanation: "El próximo sábado gives when the concert happens, and event dates use ser." },
  2080: { cue: "de metal", explanation: "De metal says what the table is made of, and material uses ser." },
  2081: { cue: "el cumpleaños", explanation: "El cumpleaños is a date on the calendar, and dates use ser." },
  2082: { cue: "de oro", explanation: "De oro says what the ring is made of, and material uses ser." },
  2083: { cue: "tres de mayo", explanation: "Tres de mayo is a calendar date, and dates use ser." },
  2084: { cue: "a las cinco", explanation: "A las cinco gives when the interview happens, and event time uses ser." },
  2085: { cue: "de cristal", explanation: "De cristal says what the glasses are made of, and material uses ser." },
  2086: { cue: "la una y media", explanation: "La una y media gives the time, and clock time uses ser." },
  2087: { cue: "el viernes", explanation: "El viernes gives when the exam happens, and event dates use ser." },
  2088: { cue: "de bronce", explanation: "De bronce says what the statue is made of, and material uses ser." },
  2089: { cue: "en agosto", explanation: "En agosto gives when the wedding happens, and event dates use ser." },
  2090: { cue: "de lana", explanation: "De lana says what the blanket is made of, and material uses ser." },
  2091: { cue: "a dos calles de aquí", explanation: "A dos calles de aquí says where the supermarket is, and physical location uses estar." },
  2092: { cue: "encima de la mesa", explanation: "Encima de la mesa says where the glasses are, and physical location uses estar." },
  2093: { cue: "la boda", explanation: "La boda is an event, and where an event takes place uses ser." },
  2094: { cue: "al lado de la farmacia", explanation: "Al lado de la farmacia says where the hospital is, and physical location uses estar." },
  2095: { cue: "la exposición", explanation: "La exposición is an event, and where an event takes place uses ser." },
  2096: { cue: "en la estantería", explanation: "En la estantería says where the books are, and physical location uses estar." },
  2097: { cue: "en la sala de espera", explanation: "En la sala de espera says where you are, and physical location uses estar." },
  2098: { cue: "la ceremonia", explanation: "La ceremonia is an event, and where an event takes place uses ser." },
  2099: { cue: "detrás del colegio", explanation: "Detrás del colegio says where the park is, and physical location uses estar." },
  2100: { cue: "en la última fila", explanation: "En la última fila says where you are, and physical location uses estar." },
  2101: { cue: "la feria", explanation: "La feria is an event, and where an event takes place uses ser." },
  2102: { cue: "dentro del cajón", explanation: "Dentro del cajón says where the keys are, and physical location uses estar." },
  2103: { cue: "lejos del centro", explanation: "Lejos del centro says where the airport is, and physical location uses estar." },
  2104: { cue: "la reunión anual", explanation: "La reunión anual is an event, and where an event takes place uses ser." },
  2105: { cue: "en el patio", explanation: "En el patio says where the children are, and people's location uses estar." },
  2106: { cue: "hoy", explanation: "Hoy marks muy cansada as how you feel today, a temporary physical state, so estar." },
  2107: { cue: "abierta", explanation: "Abierta is the window's current condition, so estar." },
  2108: { cue: "enfadado conmigo", explanation: "Enfadado conmigo is an emotional state, so estar." },
  2109: { cue: "helada", explanation: "Helada is the water's temperature right now, a temporary condition, so estar." },
  2110: { cue: "preocupados", explanation: "Preocupados is a temporary emotional state, so estar." },
  2111: { cue: "cerradas", explanation: "Cerradas is a resulting condition, so estar, even though los domingos makes it regular." },
  2112: { cue: "emocionada", explanation: "Emocionada is a temporary emotional state, so estar." },
  2113: { cue: "todavía caliente", explanation: "Todavía caliente is a temporary condition that will change, so estar." },
  2114: { cue: "de vacaciones", explanation: "De vacaciones is a temporary situation, so estar." },
  2115: { cue: "resfriado", explanation: "Resfriado is a temporary health condition, so estar." },
  2116: { cue: "a punto de caducar", explanation: "A punto de caducar describes the milk's situation right now, so estar." },
  2117: { cue: "antes del partido", explanation: "Antes del partido marks nervioso as a temporary emotional state, so estar." },
  2118: { cue: "después de la lluvia", explanation: "Después de la lluvia shows mojadas is a result of the rain, so estar." },
  2119: { cue: "con esta pregunta", explanation: "Con esta pregunta ties confundida to this moment, a temporary mental state, so estar." },
  2120: { cue: "hoy", explanation: "Hoy limits tenso to today, a temporary state of the atmosphere, so estar." },
  2121: { cue: "terminado", explanation: "Terminado is the result of finishing the work, a resulting condition, so estar." },
  2122: { cue: "desde ayer", explanation: "Desde ayer shows rota is the result of something that happened, so estar." },
  2123: { cue: "después de la operación", explanation: "Después de la operación shows mucho mejor is a changed condition, so estar." },
  2124: { cue: "llevaba días fuera", explanation: "Llevaba días fuera explains why the bread became duro, a resulting condition, so estar." },
  2125: { cue: "desde que empezó a estudiar más", explanation: "Desde que empezó a estudiar más shows más segura is a change over time, so estar." },
  2126: { cue: "en pedazos", explanation: "Roto en pedazos is the vase's state after breaking, a resulting state, so estar." },
  2127: { cue: "después de tantos cambios", explanation: "Después de tantos cambios shows irreconocible is a result of change, so estar." },
  2128: { cue: "ya", explanation: "Ya shows madura is a condition the fruit has reached, so estar." },
  2129: { cue: "que el año pasado", explanation: "Más alto que el año pasado describes a change you notice, so estar. Es alto would describe his normal height." },
  2130: { cue: "por fin", explanation: "Por fin shows ordenada is a result someone finally achieved, so estar." },
  2131: { cue: "después del susto", explanation: "Después del susto shows más tranquilos is a resulting emotional state, so estar." },
  2132: { cue: "casi acabado", explanation: "Casi acabado describes how far the project has got, a resulting condition, so estar." },
  2133: { cue: "que antes", explanation: "Mucho mejor que antes describes an improvement you notice, so estar." },
  2134: { cue: "después de tantos días de calor", explanation: "Después de tantos días de calor shows secas is a result of the heat, so estar." },
  2135: { cue: "desde el lunes", explanation: "Desde el lunes shows reparado is the result of a repair, so estar." },
  2136: { cue: "ese documental", explanation: "Ese documental is the boring thing itself, and ser aburrido describes a boring quality." },
  2137: { cue: "en la clase de historia", explanation: "En la clase de historia shows aburrido is how you feel there, and estar aburrido means feeling bored." },
  2138: { cue: "muy rico", explanation: "Muy rico describes a person, and ser rico means to be wealthy. Estar rico is for how food tastes." },
  2139: { cue: "esta sopa", explanation: "Esta sopa is food, and estar rico describes how food tastes. Ser rico would mean wealthy." },
  2140: { cue: "para cruzar", explanation: "Seguro para cruzar describes the bridge as safe, a reliable quality, so ser." },
  2141: { cue: "de mi respuesta", explanation: "Segura de mi respuesta means feeling certain, and estar seguro means to feel sure." },
  2142: { cue: "no lo pruebes", explanation: "No lo pruebes warns about the dish, and ser malo describes poor quality. Está malo would mean it has gone off." },
  2143: { cue: "desde ayer", explanation: "Desde ayer shows malo is a recent condition, and estar malo means to feel unwell." },
  2144: { cue: "todavía", explanation: "Todavía shows verde is a stage the banana will pass, so estar verde means unripe." },
  2145: { cue: "su color favorito", explanation: "Su color favorito is identified as green, an inherent colour, so ser." },
  2146: { cue: "para su edad", explanation: "Muy vivo para su edad describes how lively he is now, so estar." },
  2147: { cue: "por las noches", explanation: "Muy viva por las noches describes the city's lively character, so ser." },
  2148: { cue: "tan temprano", explanation: "Tan temprano shows despierto means awake or alert right now, so estar." },
  2149: { cue: "aprende rápido", explanation: "Aprende rápido shows despierta means quick-witted, a personality trait, so ser." },
  2150: { cue: "a cada detalle", explanation: "Atentos a cada detalle describes their attention on this project now, so estar." },
};
