import type { ItemExplanation } from "./item-explanation.ts";

// Per-item explanations for the preterite vs imperfect quiz (docs/explanation-quality.md).
export const PRETERITE_IMPERFECT_EXPLANATIONS: Record<number, ItemExplanation> = {
  3001: { cue: "ayer", explanation: "Ayer marks one completed past action, so preterite fui." },
  3002: { cue: "cada tarde", explanation: "De niño and cada tarde describe a repeated past habit, so imperfect iba." },
  3003: { cue: "a las ocho", explanation: "Anoche and a las ocho frame one completed event, so preterite preparó." },
  3004: { cue: "cuando llegaban", explanation: "Cuando llegaban sets a repeated background scene in the past, so imperfect preparaba. The preterite would make it one finished event." },
  3005: { cue: "el sábado", explanation: "El sábado points to one completed occasion, so preterite salimos." },
  3006: { cue: "normalmente", explanation: "Normalmente signals a repeated past routine, so imperfect salíamos." },
  3007: { cue: "de repente", explanation: "De repente introduces a sudden completed action, so preterite llegó." },
  3008: { cue: "cuando empezó la lluvia", explanation: "Cuando empezó la lluvia interrupts the arrival, which was in progress, so imperfect llegaba." },
  3009: { cue: "en 2020", explanation: "En 2020 closes off a bounded period, so preterite vivió presents it as a finished whole." },
  3010: { cue: "cuando la conocí", explanation: "Cuando la conocí is the event; where Ana lived is background to it, so imperfect vivía." },
  3011: { cue: "y luego", explanation: "Y luego links a sequence of completed actions, so preterite explicó." },
  3012: { cue: "cuando entró el director", explanation: "Cuando entró el director interrupts the explanation, which was in progress, so imperfect explicaba." },
  3013: { cue: "al ver las noticias", explanation: "Al ver las noticias marks the moment the change happened, so preterite se puso." },
  3014: { cue: "cada vez que", explanation: "Cada vez que describes repeated past behaviour, so imperfect se ponía." },
  3015: { cue: "a las diez", explanation: "A las diez pins the start to one moment, a completed event, so preterite empezó." },
  3016: { cue: "cuando llegué", explanation: "Cuando llegué is the event; the meeting starting was already in progress, so imperfect empezaba." },
  3017: { cue: "ayer", explanation: "Ayer marks one completed past action, so preterite escribió." },
  3018: { cue: "anoche", explanation: "Anoche marks one completed event, so preterite comimos." },
  3019: { cue: "el lunes pasado", explanation: "El lunes pasado is a specific past date, so the purchase is a completed event: preterite compré." },
  3020: { cue: "anoche", explanation: "Anoche marks a completed action, and toda la tarea shows it was finished, so preterite hizo." },
  3021: { cue: "el sábado", explanation: "El sábado points to one specific occasion, so preterite pusieron." },
  3022: { cue: "por fin", explanation: "Por fin marks the moment she finally did it, a completed action, so preterite dijo." },
  3023: { cue: "a tiempo", explanation: "Terminar a tiempo is one successful attempt, and preterite pudimos means managed to." },
  3024: { cue: "esta mañana", explanation: "Esta mañana marks a specific completed action, so preterite dije." },
  3025: { cue: "con dos horas de retraso", explanation: "Con dos horas de retraso describes one specific arrival, a completed event, so preterite llegó." },
  3026: { cue: "el domingo", explanation: "El domingo marks one completed action, so preterite escribí." },
  3027: { cue: "sin problemas", explanation: "Sin problemas sums up one finished exam, a single completed event, so preterite hicieron." },
  3028: { cue: "sin dudarlo", explanation: "Sin dudarlo describes one answer given at one moment, a single completed statement, so preterite dijo." },
  3029: { cue: "en la entrevista", explanation: "En la entrevista refers to one specific past event, so preterite hablaste." },
  3030: { cue: "la semana pasada", explanation: "La semana pasada marks when the decision was made, a completed action, so preterite decidió." },
  3031: { cue: "en un fin de semana", explanation: "En un fin de semana shows the novel was read from start to finish, so preterite leí." },
  3032: { cue: "enseguida", explanation: "Enseguida marks the moment of finding out, and preterite supimos means found out." },
  3033: { cue: "tres años", explanation: "Tres años is a bounded period that ended antes de mudarse, so preterite vivió." },
  3034: { cue: "el diagnóstico", explanation: "Explaining el diagnóstico is a single completed action, so preterite explicó." },
  3035: { cue: "en la reunión", explanation: "En la reunión places one specific completed action, so preterite di." },
  3036: { cue: "a las nueve", explanation: "A las nueve marks the moment they arrived, a completed event, so preterite llegaron." },
  3037: { cue: "primero", explanation: "Primero and y luego list completed steps in a sequence, so preterite preparé." },
  3038: { cue: "luego", explanation: "Luego marks the next step in a sequence, so preterite escribió." },
  3039: { cue: "después de desayunar", explanation: "Después de desayunar marks the next step in a sequence, so preterite salimos." },
  3040: { cue: "entonces", explanation: "Entonces marks the next step in a sequence, so preterite empezó." },
  3041: { cue: "finalmente", explanation: "Finalmente marks the last step in a sequence, so preterite dijeron." },
  3042: { cue: "después", explanation: "Después marks the next step in a sequence, so preterite escribí." },
  3043: { cue: "luego", explanation: "Luego marks the next step in a sequence, so preterite preparó." },
  3044: { cue: "primero", explanation: "Primero marks the first step in a sequence, so preterite leyó." },
  3045: { cue: "después de eso", explanation: "Después de eso marks the next step in a sequence, so preterite compramos." },
  3046: { cue: "finalmente", explanation: "Finalmente marks the last step in a sequence, so preterite explicó." },
  3047: { cue: "primero", explanation: "Primero and después list steps in a sequence, so preterite hablé." },
  3048: { cue: "luego", explanation: "Luego marks the next step, and antes de la fiesta shows it was completed, so preterite preparó." },
  3049: { cue: "después", explanation: "Después marks the next step in a sequence, so preterite dio." },
  3050: { cue: "entonces", explanation: "Entonces marks the next step in a sequence, so preterite dijo." },
  3051: { cue: "primero", explanation: "Primero marks the first step in a sequence, so preterite escribimos." },
  3052: { cue: "luego", explanation: "Luego and y descansaron list completed steps in a sequence, so preterite llegaron." },
  3053: { cue: "antes de firmar", explanation: "Antes de firmar places this as one step before the next, so preterite leyeron." },
  3054: { cue: "finalmente", explanation: "Finalmente marks the last step in a sequence, so preterite dije." },
  3055: { cue: "después del discurso", explanation: "Después del discurso marks the next step, one completed reaction, so preterite dio." },
  3056: { cue: "de repente", explanation: "De repente marks the sudden start of an action, so preterite empezó." },
  3057: { cue: "a las cuatro en punto", explanation: "A las cuatro en punto gives an exact starting time, so preterite empezó." },
  3058: { cue: "cuando oyó la noticia", explanation: "Cuando oyó la noticia marks the moment of a change of state, so preterite se puso." },
  3059: { cue: "al final del año", explanation: "Al final del año marks when one decision was taken, so preterite decidieron." },
  3060: { cue: "tras el accidente", explanation: "Tras el accidente marks the point where his behaviour changed, so preterite se puso." },
  3061: { cue: "en enero", explanation: "En enero gives a specific starting point, so preterite empecé." },
  3062: { cue: "en ese momento", explanation: "En ese momento marks the moment of finding out, and preterite supimos means found out." },
  3063: { cue: "después de la charla", explanation: "Después de la charla marks the point of a change of state, so preterite se pusieron." },
  3064: { cue: "de repente", explanation: "De repente marks a sudden starting point, so preterite empezó." },
  3065: { cue: "cuando vio el examen", explanation: "Cuando vio el examen marks the moment of a sudden change, so preterite se puso." },
  3066: { cue: "el mes pasado", explanation: "El mes pasado gives a specific starting date, so preterite empezó." },
  3067: { cue: "la noche antes", explanation: "La noche antes places one specific decision, so preterite decidimos." },
  3068: { cue: "tan pronto como", explanation: "Tan pronto como marks the precise moment she started, so preterite empezó." },
  3069: { cue: "después de años dudando", explanation: "Después de años dudando leads to one turning-point decision, so preterite decidió." },
  3070: { cue: "cuando sonó la alarma", explanation: "Cuando sonó la alarma marks the moment of a sudden change of state, so preterite se pusieron." },
  3071: { cue: "hace dos años", explanation: "Hace dos años gives a specific starting point, so preterite empezó." },
  3072: { cue: "al oír el ruido", explanation: "Al oír el ruido is the trigger, and the barking starts at that moment, so preterite empezó." },
  3073: { cue: "en esa reunión", explanation: "En esa reunión places one specific decision, so preterite decidieron." },
  3074: { cue: "al saber la verdad", explanation: "Al saber la verdad marks the moment of a change of state, so preterite se puso." },
  3075: { cue: "de niño", explanation: "De niño signals a repeated past habit, so imperfect comía." },
  3076: { cue: "todos los veranos", explanation: "Todos los veranos signals a repeated habit, so imperfect escribían." },
  3077: { cue: "antes", explanation: "Antes signals a past habit that no longer happens, so imperfect comprábamos." },
  3078: { cue: "cuando era estudiante", explanation: "Cuando era estudiante and todas las noches frame a repeated habit, so imperfect estudiaba." },
  3079: { cue: "siempre", explanation: "Siempre and antes de dormir signal a repeated habit, so imperfect decía." },
  3080: { cue: "cada domingo", explanation: "Cada domingo signals a repeated habit, so imperfect hablábamos." },
  3081: { cue: "en aquella época", explanation: "En aquella época signals an ongoing past situation, so imperfect trabajaba." },
  3082: { cue: "de pequeños", explanation: "De pequeños and todo el verano signal a repeated habit, so imperfect leíamos." },
  3083: { cue: "a menudo", explanation: "A menudo signals something that happened again and again, so imperfect tenían." },
  3084: { cue: "cuando vivíamos en el pueblo", explanation: "Cuando vivíamos en el pueblo frames a repeated past routine, so imperfect hacía." },
  3085: { cue: "normalmente", explanation: "Normalmente signals a repeated habit, so imperfect decía." },
  3086: { cue: "cada verano", explanation: "Cada verano signals a repeated habit, so imperfect preparaban." },
  3087: { cue: "de adolescente", explanation: "De adolescente signals a habit from that stage of life, so imperfect hablabas." },
  3088: { cue: "habitualmente", explanation: "Habitualmente signals a repeated habit, so imperfect compraban." },
  3089: { cue: "todas las tardes", explanation: "En esos años and todas las tardes describe a repeated routine, so imperfect ponía." },
  3090: { cue: "todos los veranos", explanation: "Cuando éramos niños and todos los veranos describe a childhood habit, so imperfect escribíamos." },
  3091: { cue: "frecuentemente", explanation: "Frecuentemente signals a repeated habit, so imperfect daba." },
  3092: { cue: "cada mañana", explanation: "Cada mañana signals a repeated habit, so imperfect preparaba." },
  3093: { cue: "de joven", explanation: "De joven describes a general ability she had at that stage of life, so imperfect podía." },
  3094: { cue: "todos los años", explanation: "Todos los años signals a repeated habit, so imperfect hacía." },
  3095: { cue: "a esa hora", explanation: "A esa hora and todavía show an action in progress at that time, so imperfect trabajaba." },
  3096: { cue: "en aquel momento", explanation: "En aquel momento frames an action in progress, so imperfect preparábamos." },
  3097: { cue: "aquella tarde", explanation: "Aquella tarde sets the scene with a background action in progress, so imperfect leían." },
  3098: { cue: "mientras tanto", explanation: "Mientras tanto frames a background action happening at the same time, so imperfect escribía." },
  3099: { cue: "a esa edad", explanation: "A esa edad describes a background mental state, not an event, so imperfect sabía." },
  3100: { cue: "en esos días", explanation: "En esos días describes a background situation, so imperfect tenía." },
  3101: { cue: "aquel verano", explanation: "Aquel verano describes a background situation, so imperfect teníamos." },
  3102: { cue: "por aquel entonces", explanation: "Por aquel entonces frames a background situation, so imperfect trabajaba." },
  3103: { cue: "esa mañana", explanation: "Esa mañana sets the scene with the weather, a background description, so imperfect hacía." },
  3104: { cue: "a esa hora", explanation: "A esa hora describes what usually went on in that house, a background situation, so imperfect hacían." },
  3105: { cue: "aquel día", explanation: "Aquel día describes how you were, a background physical state, so imperfect tenía." },
  3106: { cue: "en aquella época", explanation: "En aquella época describes a background situation, so imperfect tenía." },
  3107: { cue: "a esa hora", explanation: "A esa hora and todavía show an action in progress at that time, so imperfect preparábamos." },
  3108: { cue: "aquel invierno", explanation: "Aquel invierno frames an ongoing topic of conversation, so imperfect hablaban." },
  3109: { cue: "en aquellos años", explanation: "En aquellos años describes a background situation, so imperfect tenía." },
  3110: { cue: "como ahora", explanation: "Tanto tráfico como ahora compares how the city used to be, a background description, so imperfect tenía." },
  3111: { cue: "esa noche", explanation: "Esa noche sets the scene with the weather, a background description, so imperfect hacía." },
  3112: { cue: "en aquel restaurante", explanation: "En aquel restaurante describes what the service was like in general, so imperfect daban." },
  3113: { cue: "mientras tanto", explanation: "Mientras tanto frames a background action happening at the same time, so imperfect daba." },
  3114: { cue: "en aquella foto", explanation: "En aquella foto describes her age at the time, and past age uses imperfect tenía." },
  3115: { cue: "cuando lo conocí", explanation: "Cuando lo conocí is the event; his appearance is background description, so imperfect tenía." },
  3116: { cue: "aquella tarde", explanation: "Aquella tarde sets the scene with the weather, so imperfect hacía." },
  3117: { cue: "esa mañana", explanation: "Esa mañana sets the scene with the weather, so imperfect hacía." },
  3118: { cue: "de joven", explanation: "De joven describes knowledge he had at that stage of life, so imperfect sabía." },
  3119: { cue: "de oído", explanation: "Tocar el piano de oído is a skill she had, a background description, so imperfect sabía." },
  3120: { cue: "de niño", explanation: "De niño describes a general past ability, so imperfect podía." },
  3121: { cue: "cuando era joven", explanation: "Cuando era joven describes a general past ability, so imperfect podía." },
  3122: { cue: "dos días a la semana", explanation: "Dos días a la semana describes a general arrangement, so imperfect podían." },
  3123: { cue: "de pequeño", explanation: "De pequeño and siempre describe a lasting childhood wish, so imperfect quería." },
  3124: { cue: "siempre", explanation: "Siempre describes a lasting trait or wish, so imperfect quería." },
  3125: { cue: "antes de la operación", explanation: "Antes de la operación describes how he felt, a background emotional state, so imperfect tenía." },
  3126: { cue: "antes de mudarnos", explanation: "Antes de mudarnos describes what the flat was like, a background description, so imperfect tenía." },
  3127: { cue: "por las tardes", explanation: "Por las tardes describes something that happened every afternoon, so imperfect daba." },
  3128: { cue: "en aquel momento", explanation: "En aquel momento describes what the room was like, a background description, so imperfect tenía." },
  3129: { cue: "cuando era joven", explanation: "Cuando era joven describes a quality she had, a background description, so imperfect tenía." },
  3130: { cue: "ese día", explanation: "Ese día describes what the exam was like, a background description, so imperfect tenía." },
  3131: { cue: "cuando yo tenía diez años", explanation: "Cuando yo tenía diez años sets the time frame for a background description, so imperfect tenía." },
  3132: { cue: "esa tarde", explanation: "Esa tarde describes the scene in the park, a background description, so imperfect tenía." },
  3133: { cue: "mientras", explanation: "Mientras sets an ongoing background action, and se apagó la luz interrupts it, so imperfect preparaba." },
  3134: { cue: "cuando sonó el teléfono", explanation: "Cuando sonó el teléfono interrupts an ongoing action, so imperfect escribía." },
  3135: { cue: "cuando empezó a llover", explanation: "Cuando empezó a llover interrupts an ongoing action, so imperfect comíamos." },
  3136: { cue: "mientras", explanation: "Mientras sets an ongoing action, and un alumno llegó tarde interrupts it, so imperfect explicaba." },
  3137: { cue: "cuando se cortó la luz", explanation: "Cuando se cortó la luz interrupts an ongoing action, so imperfect trabajaba." },
  3138: { cue: "mientras", explanation: "Mientras sets an ongoing action, and llegó la solución interrupts it, so imperfect hablábamos." },
  3139: { cue: "cuando su madre los llamó", explanation: "Cuando su madre los llamó interrupts an ongoing action, so imperfect leían." },
  3140: { cue: "mientras", explanation: "Mientras sets an ongoing action, and él empezó a llorar happens during it, so imperfect decía." },
  3141: { cue: "cuando te llamé", explanation: "Cuando te llamé interrupts an ongoing action, so imperfect estudiabas." },
  3142: { cue: "mientras", explanation: "Mientras sets an ongoing action, and se rompió un vaso interrupts it, so imperfect preparaba." },
  3143: { cue: "cuando empezó el incendio", explanation: "Cuando empezó el incendio interrupts an ongoing action, so imperfect trabajábamos." },
  3144: { cue: "cuando se cortó internet", explanation: "Cuando se cortó internet interrupts an ongoing action, so imperfect escribía." },
  3145: { cue: "mientras", explanation: "Mientras sets an ongoing action, and empezó a nevar happens during it, so imperfect trabajaba." },
  3146: { cue: "cuando se apagaron las luces", explanation: "Cuando se apagaron las luces interrupts an ongoing action, so imperfect hablaba." },
  3147: { cue: "mientras", explanation: "Mientras sets an ongoing action, and yo puse la mesa happens during it, so imperfect preparaban." },
  3148: { cue: "cuando por fin llegó la noticia", explanation: "Cuando por fin llegó la noticia interrupts an ongoing action, so imperfect trabajaba." },
  3149: { cue: "mientras", explanation: "Mientras sets an ongoing action, and se fue la luz interrupts it, so imperfect leía." },
  3150: { cue: "cuando sonó la alarma", explanation: "Cuando sonó la alarma interrupts an ongoing action, so imperfect estudiaban." },
};
