import type { ItemExplanation } from "./item-explanation.ts";

// Per-item explanations for the object pronouns quiz (docs/explanation-quality.md).
// Shortened from the #94 rewrites to fit two sentences and 200 characters.
export const OBJECT_PRONOUN_EXPLANATIONS: Record<number, ItemExplanation> = {
  5001: { cue: "el café", explanation: "El café is masculine singular, and a direct object pronoun copies its gender and number, so lo. La would replace a feminine noun, like la leche." },
  5002: { cue: "la sopa", explanation: "La sopa is feminine singular, so the direct object pronoun is la. Lo is for masculine nouns, like el pan." },
  5003: { cue: "los zapatos", explanation: "Los zapatos is masculine plural, so the pronoun is los. Las would replace a feminine plural noun, like las botas." },
  5004: { cue: "las llaves", explanation: "Las llaves is feminine plural, so las, even though Pablo is a man. The pronoun takes the gender of the thing, not of the person who has it." },
  5005: { cue: "una revista", explanation: "Una revista is what I read, the direct object, and it is feminine singular, so la. Lo would need a masculine noun, like un periódico." },
  5006: { cue: "dos entradas", explanation: "Dos entradas is feminine plural (las entradas), so las. The order is no, then the pronoun, then the verb: no las necesito." },
  5007: { cue: "el mando", explanation: "El mando, from the previous sentence, is masculine singular, so lo. La would need a feminine noun, like la llave." },
  5008: { cue: "esta película", explanation: "Esta película is feminine singular, so la. Lo would mean you saw something masculine, such as el partido." },
  5009: { cue: "galletas", explanation: "Galletas is feminine plural, so las. Los niños just before the blank is who wants them, and the pronoun agrees with what is wanted." },
  5010: { cue: "los deberes", explanation: "Los deberes is the thing I finished, a direct object, so los. Les is an indirect pronoun for people who receive something." },
  5011: { cue: "el pan", explanation: "El pan is masculine singular, so lo. La would need a feminine noun, like la fruta." },
  5012: { cue: "la maleta", explanation: "La maleta is feminine singular, so la. Mi padre is masculine, but the pronoun agrees with the thing carried, not the person carrying it." },
  5013: { cue: "el coche", explanation: "El coche is masculine singular, so lo. Coche ends in -e, so the article el, not the ending, tells you the gender." },
  5014: { cue: "las gafas", explanation: "Las gafas is always plural in Spanish, even for one pair, so las. Los would only work for a masculine plural noun, like los guantes." },
  5015: { cue: "estas manzanas", explanation: "Estas manzanas is feminine plural, as estas shows, so las. Los would need a masculine noun, like estos plátanos." },
  5016: { cue: "una tarta", explanation: "Una tarta is feminine singular, so la. Mis amigos is the subject doing the tasting, so it does not affect the pronoun." },
  5017: { cue: "las noticias", explanation: "Las noticias is feminine plural and is the thing we listen to, so las. Les is an indirect pronoun for people, never for things." },
  5018: { cue: "mi abuela", explanation: "Visitar takes a direct object, and mi abuela is feminine singular, so la. Lo would be for a man, like mi abuelo." },
  5019: { cue: "Juan", explanation: "Recoger a alguien takes a direct object, and Juan is a man, so lo. La would be for a woman." },
  5020: { cue: "¿Me oyes bien?", explanation: "¿Me oyes bien? asks about me, so in the reply the person heard is you: te. Me would mean I can hear myself." },
  5021: { cue: "llegamos", explanation: "Llegamos shows the speaker means nosotros, so the people the teacher looks at are us: nos. Los would mean them." },
  5022: { cue: "mis padres", explanation: "Mis padres love me, and me is the object pronoun for yo. Mí is only used after a preposition, as in a mí." },
  5023: { cue: "mis primos", explanation: "Mis primos is masculine plural, so los, and a mixed group of cousins also takes los. Las would only fit a group of women, like mis primas." },
  5024: { cue: "Ana y Lucía", explanation: "Ana y Lucía are the ones inviting, and the people invited are us, so nos. Los would mean them." },
  5025: { cue: "mi hermana", explanation: "Adorar takes a direct object, and mi hermana is feminine singular, so la. Le is for indirect objects, the person who receives something." },
  5026: { cue: "si tienes problemas", explanation: "Si tienes problemas shows the person helped is you, so te. Ti only appears after a preposition." },
  5027: { cue: "éramos", explanation: "Éramos (we were) shows the people taken to the park are us, so nos. Los would mean other people." },
  5028: { cue: "¿Me esperas?", explanation: "¿Me esperas? asks about waiting for me, so in the reply the speaker waits for you: te. Me would mean waiting for yourself." },
  5029: { cue: "nuestros amigos", explanation: "Nuestros amigos are the ones calling, and the people called are us, so nos. Los would make them the people called." },
  5030: { cue: "las fotos", explanation: "Las fotos is feminine plural, so las, and in a compound tense it goes before haber: no las he visto." },
  5031: { cue: "el correo", explanation: "El correo is a masculine singular direct object, so lo goes before haber: lo he leído." },
  5032: { cue: "la carta", explanation: "La carta is feminine singular, so la goes before haber: la ha abierto." },
  5033: { cue: "los platos", explanation: "Los platos is masculine plural, so los goes before haber: los ha lavado." },
  5034: { cue: "ese chico", explanation: "Ese chico is looking at you, so te. With estar + gerund the pronoun can go before estar: te está mirando." },
  5035: { cue: "el partido", explanation: "El partido is a masculine singular direct object, so lo, which can go before estar: lo estamos viendo." },
  5036: { cue: "las flores", explanation: "Las flores is feminine plural, so las. With ir a + infinitive it can go before the conjugated verb: las va a poner." },
  5037: { cue: "el libro", explanation: "El libro gives lo, attached to the gerund: leyendo + lo = leyéndolo. The written accent keeps the stress on the same syllable." },
  5038: { cue: "la cena", explanation: "La cena is feminine, so la: preparándola. Preparándolo would mean preparing something masculine, like el desayuno." },
  5039: { cue: "los ejercicios", explanation: "Los ejercicios is masculine plural, so haciéndolos. Haciéndolas would need a feminine noun, like las tareas." },
  5040: { cue: "las camisas", explanation: "Las camisas gives las: planchando + las = planchándolas. Attaching a pronoun to a gerund always needs a written accent." },
  5041: { cue: "tu hermano", explanation: "Tu hermano gives lo: llamando + lo = llamándolo. The accent keeps the stress on -man-." },
  5042: { cue: "esta chaqueta", explanation: "Esta chaqueta is feminine, so la attaches to the infinitive: comprarla. One pronoun on an infinitive needs no accent." },
  5043: { cue: "los documentos", explanation: "Los documentos is masculine plural, so firmarlos. Firmarlas would need a feminine noun, like las cartas." },
  5044: { cue: "mi amiga", explanation: "Buscar a alguien takes a direct object, and mi amiga is a woman, so buscarla. Le is for indirect objects." },
  5045: { cue: "el piso", explanation: "El piso is masculine singular, so venderlo. Venderla would need a feminine noun, like la casa." },
  5046: { cue: "Carla se muda", explanation: "Lo stands for the whole idea that Carla se muda. A whole idea is always lo." },
  5047: { cue: "cierran el museo", explanation: "Neuter lo replaces the whole statement that cierran el museo: no lo creo." },
  5048: { cue: "a su hermana", explanation: "A su hermana is a direct object placed before the verb, so Spanish repeats it with la: a su hermana la vi." },
  5049: { cue: "los tomates", explanation: "Los tomates is a direct object placed before the verb, so los repeats it: los tomates los compré." },
  5050: { cue: "esa canción", explanation: "Esa canción is the direct object placed first, so la repeats it. Todo el mundo is the subject doing the singing." },
  5051: { cue: "mi madre", explanation: "Mi madre receives the flowers, so she is the indirect object: le. La would make your mother the thing being given." },
  5052: { cue: "a tu jefe", explanation: "A tu jefe receives the message, so the indirect pronoun is le. A tu jefe clarifies who le refers to." },
  5053: { cue: "mis alumnos", explanation: "Mis alumnos write emails to me, so I am the indirect object: me. Mi without an accent means my." },
  5054: { cue: "a los niños", explanation: "A los niños receives the explanation, so the plural indirect pronoun is les, even with a los niños also in the sentence." },
  5055: { cue: "a Carlos", explanation: "A Carlos is who gets the bike, the indirect object, so le. Lo would make Carlos the thing being lent." },
  5056: { cue: "a mis padres", explanation: "A mis padres is who receives the postcards, so the indirect pronoun is les. Los would mean you post your parents themselves." },
  5057: { cue: "el dinero", explanation: "El dinero comes back to you, so you are the indirect object: te. Ti only appears after a preposition, as in a ti." },
  5058: { cue: "la cuenta", explanation: "La cuenta is what is brought, and we get it, so the indirect pronoun is nos. Los is a direct pronoun and means them." },
  5059: { cue: "a mi mejor amiga", explanation: "A mi mejor amiga is the person told, the indirect object, so le, for women as well as men." },
  5060: { cue: "a los estudiantes", explanation: "Preguntar a alguien takes an indirect object, and a los estudiantes is plural, so les." },
  5061: { cue: "una manta", explanation: "Una manta is the thing given, and I am the one who gets it, so the indirect pronoun is me. Mi without an accent means my." },
  5062: { cue: "a mi padre", explanation: "Unas pastillas is what is prescribed, and a mi padre is who gets it, so the indirect pronoun le. Lo would make your father the thing prescribed." },
  5063: { cue: "a Lucía", explanation: "Pasar works like gustar here, so a Lucía is the indirect object: le, even for a woman. La would be a direct object pronoun." },
  5064: { cue: "a los estudiantes", explanation: "Pedir treats the person asked as an indirect object, and a los estudiantes is plural, so les, not los." },
  5065: { cue: "tú nunca contestas", explanation: "The person written to is you, as tú nunca contestas shows, and escribir a alguien takes an indirect object: te. Ti only follows a preposition." },
  5066: { cue: "una sorpresa", explanation: "Una sorpresa is what is given, and we receive it, so the indirect pronoun is nos. Los would mean them, and it is a direct pronoun." },
  5067: { cue: "el cartero", explanation: "Una propina is what is given, and el cartero is who gets it, so le. Lo would make the postman the thing given." },
  5068: { cue: "a tu hermana", explanation: "A tu hermana is who the present is for, the indirect object. Indirect pronouns do not change for gender, so le, not la." },
  5069: { cue: "a mis hijos", explanation: "Encantar works like gustar, so a mis hijos is the indirect object, and plural: les." },
  5070: { cue: "a nosotros", explanation: "Interesar works like gustar, and a nosotros points to us, so nos." },
  5071: { cue: "a tus primos", explanation: "Las fotos is what is sent, and a tus primos receive them, so the plural indirect pronoun is les. Los would replace a plural thing." },
  5072: { cue: "a Elena", explanation: "A Elena is who gets the offer, the indirect object, so le even for a woman. La would treat Elena as the thing offered." },
  5073: { cue: "a los clientes", explanation: "El dinero is returned to a los clientes, the indirect object, so les. Los would replace a plural thing being returned." },
  5074: { cue: "mi novio", explanation: "Mi novio brings flowers to me, so I am the indirect object: me. Mi without an accent means my, as in mi novio." },
  5075: { cue: "a sus amigos", explanation: "Mentiras is what is told, and a sus amigos is who hears it, so les. Los would replace a masculine plural thing." },
  5076: { cue: "a los turistas", explanation: "A los turistas receive the explanation, so les. With estar + gerund it can go before estar." },
  5077: { cue: "a tu novia", explanation: "A tu novia is who gets the present, the indirect object, so le. Le is used for men and women alike." },
  5078: { cue: "cuando era niño", explanation: "Cuando era niño shows the stories were read to me, so the indirect pronoun is me. Mi without an accent means my." },
  5079: { cue: "a tus padres", explanation: "A tus padres are the people told, an indirect object, so les, not the direct los." },
  5080: { cue: "a sus nietos", explanation: "La casa is what is left, and a sus nietos receive it, so les, not los." },
  5081: { cue: "mi coche", explanation: "Mi coche is lent to you, so the indirect pronoun is te. Ti never stands alone before a verb." },
  5082: { cue: "a Pedro", explanation: "Una mala nota is the direct object, and a Pedro is the indirect object, so le. Lo would make Pedro the thing given." },
  5083: { cue: "a su abuela", explanation: "Pedir treats the person asked as an indirect object, so a su abuela takes le even for a woman. La would be wrong." },
  5084: { cue: "mi jefe", explanation: "Mi jefe has not answered me, and contestar a alguien takes an indirect object, so me before haber. Mi without an accent means my." },
  5085: { cue: "señora García", explanation: "Señora García is usted, the person receiving the documents, and usted as an indirect object is le, for women as well as men." },
  5086: { cue: "a mi hermano", explanation: "A mi hermano is the person affected, and Spanish marks that with the indirect pronoun le." },
  5087: { cue: "a ti", explanation: "Tocar (to be someone's turn) takes an indirect object: te toca. A ti adds emphasis but never replaces te." },
  5088: { cue: "a ella", explanation: "A ella clarifies and contrasts, but the indirect pronoun le must still appear." },
  5089: { cue: "a usted", explanation: "A usted is the person owed, so the indirect pronoun is le. The a + person phrase only adds clarity." },
  5090: { cue: "a ustedes", explanation: "A ustedes receives the information, an indirect object, so les. Ustedes as an indirect object is always les, never los." },
  5091: { cue: "a Marta", explanation: "A Marta receives the message, so le attaches to the infinitive: escribirle. La would be wrong for a receiver." },
  5092: { cue: "a mis padres", explanation: "La verdad is what is said, and a mis padres hear it, so les attaches to the gerund: diciéndoles." },
  5093: { cue: "la sal", explanation: "La sal is passed to the speaker, so the pronoun is me: pasarme. Pasarte would mean passing it to yourself." },
  5094: { cue: "profesora", explanation: "Profesora is the usted being asked, so le attaches: hacerle. Una pregunta is the direct object." },
  5095: { cue: "a los Reyes Magos", explanation: "A los Reyes Magos is who the letter is written to, an indirect object, so les attaches: escribiéndoles." },
  5096: { cue: "el libro", explanation: "With two pronouns the person comes first, then the thing: me (to me) + lo (el libro) = me lo. Lo me is never possible." },
  5097: { cue: "la foto", explanation: "Indirect comes before direct: te (to you) + la (la foto) = te la. La te is the wrong order." },
  5098: { cue: "el postre", explanation: "Indirect comes before direct: nos (to us) + lo (el postre) = nos lo. Lo nos is the wrong order." },
  5099: { cue: "las fotos", explanation: "Las fotos is feminine even though foto ends in -o (short for la fotografía), so nos las, not nos los." },
  5100: { cue: "mi bolígrafo", explanation: "Mi bolígrafo is masculine (el bolígrafo), so the thing is lo: te lo. Te la would need a feminine noun, like la goma." },
  5101: { cue: "esa bufanda", explanation: "Me comes first because I received it, and esa bufanda is feminine, so me la. Me lo would need something masculine, like el gorro." },
  5102: { cue: "si necesitas", explanation: "Si necesitas shows the person is tú, so the pair is te lo. Se only replaces le or les." },
  5103: { cue: "a mí", explanation: "A mí points to me, so the pair is me lo. Se only replaces le or les." },
  5104: { cue: "a nosotras", explanation: "A nosotras means us, so the indirect pronoun is nos, not se. Only le and les turn into se." },
  5105: { cue: "a ti", explanation: "A ti points to tú, so the pair is te los. Se only replaces le or les." },
  5106: { cue: "las gafas", explanation: "Las gafas is feminine plural, so te las, placed before haber as a block. Te los would need a masculine noun, like los guantes." },
  5107: { cue: "la mesa", explanation: "La mesa is feminine, so me la, placed before haber. Me lo would need a masculine noun, like el sofá." },
  5108: { cue: "el vestido", explanation: "El vestido is masculine, so me lo, not me la. A mí only adds emphasis; me must still appear." },
  5109: { cue: "mi diccionario", explanation: "Mi diccionario is masculine (el diccionario), so te lo. Te comes first because you receive it." },
  5110: { cue: "la moto", explanation: "La moto ends in -o but is feminine (short for la motocicleta), so me la, not me lo." },
  5111: { cue: "¿Me explicas el problema?", explanation: "In ¿Me explicas el problema? me is the person asking, so in the answer it becomes te: te lo. Me lo would mean explaining it to yourself." },
  5112: { cue: "tu dirección", explanation: "Tu dirección ends in -ción, and those nouns are feminine, so the pair is te la, not te lo." },
  5113: { cue: "tus apuntes", explanation: "Tus apuntes is masculine plural (los apuntes), so te los. Te las would need a feminine noun, like las notas." },
  5114: { cue: "a su hermana", explanation: "Le (a su hermana) + las (the keys) cannot be le las, so le becomes se: se las. A su hermana shows who se refers to." },
  5115: { cue: "a Pablo", explanation: "Le (a Pablo) + lo (the present) is never le lo: le becomes se, so se lo." },
  5116: { cue: "a sus compañeros", explanation: "Les (a sus compañeros) + los (los apuntes) becomes se los, because les turns into se before lo, la, los or las." },
  5117: { cue: "a mis padres", explanation: "Les (a mis padres) + la (la verdad) becomes se la. Spanish never puts le or les right before lo, la, los or las." },
  5118: { cue: "a la profesora", explanation: "Le + la becomes se la, and a la profesora tells you who se means." },
  5119: { cue: "a ustedes", explanation: "Les + lo becomes se lo, and a ustedes clarifies that se means you all." },
  5120: { cue: "a mi madre", explanation: "Le (for a mi madre) + las (las flores) becomes se las. A mi madre at the end shows who se is." },
  5121: { cue: "a la paciente", explanation: "Le (a la paciente) + los (los resultados) cannot be le los, so le becomes se: se los. A la paciente shows who se refers to." },
  5122: { cue: "a mis vecinos", explanation: "Les + lo (el paquete) becomes se lo. Se does not show singular or plural; a mis vecinos does." },
  5123: { cue: "a nadie", explanation: "Le (a nadie) + la becomes se la, and the pair goes before the conjugated verb: no se la puedo decir." },
  5124: { cue: "al director", explanation: "Le (al director) + lo becomes se lo, placed before haber: se lo he enviado." },
  5125: { cue: "a los niños", explanation: "Les (a los niños) + las becomes se las, placed before haber: no se las han contado." },
  5126: { cue: "tu número", explanation: "Le (a Laura) becomes se, and tu número is masculine, so the pair is se lo." },
  5127: { cue: "a su novia", explanation: "Le (a su novia) + la becomes se la. With estar + gerund both pronouns can go before estar." },
  5128: { cue: "a todo el mundo", explanation: "Le (a todo el mundo) + lo (the secret) becomes se lo, placed before estar." },
  5129: { cue: "a la abuela", explanation: "Le (a la abuela) + la becomes se la. With ir a + infinitive the pair can go before the conjugated verb." },
  5130: { cue: "a mi hermano", explanation: "Le (for a mi hermano) + los (the toys) becomes se los, placed before ir." },
  5131: { cue: "a él", explanation: "Le + lo always becomes se lo. Se could mean him, her, you or them, so a él clarifies it." },
  5132: { cue: "a ustedes", explanation: "Les + las becomes se las. A ustedes clarifies who se refers to." },
  5133: { cue: "a Mario", explanation: "The question uses le for a Mario. In the answer le meets las (the keys) and becomes se: se las." },
  5134: { cue: "a tus tíos", explanation: "Les (a tus tíos) + la (la invitación) becomes se la, placed before haber: no se la he mandado." },
  5135: { cue: "a Ana", explanation: "Le (for a Ana) + lo (el pastel) would be le lo, which Spanish never allows, so se lo." },
  5136: { cue: "los pendientes", explanation: "Le becomes se, and los pendientes is masculine plural, so se los. Se las would need a feminine noun, like las pulseras." },
  5137: { cue: "a los alumnos", explanation: "The question uses les for a los alumnos. In the answer les meets lo (el problema) and becomes se: se lo." },
  5138: { cue: "permiso", explanation: "Lo stands for permiso, and le (a tu padre) cannot come right before lo, so it changes to se: se lo." },
  5139: { cue: "la chaqueta", explanation: "Se is right, so the question is gender: la chaqueta is feminine, so se la. Se lo would need a masculine noun, like el abrigo." },
  5140: { cue: "a mi hija", explanation: "Le (a mi hija) becomes se before lo (el cuento): leyendo + se + lo = leyéndoselo. The accent keeps the stress." },
  5141: { cue: "a los alumnos", explanation: "Les (a los alumnos) becomes se before la (la lección): explicando + se + la = explicándosela." },
  5142: { cue: "las fotos", explanation: "Las fotos is feminine (short for las fotografías), so mandándotelas. Mandándotelos would need a masculine noun, like los vídeos." },
  5143: { cue: "el menú", explanation: "El menú is masculine, so lo: trayéndonoslo. Trayéndonosla would need a feminine noun, like la carta." },
  5144: { cue: "los regalos", explanation: "Les (a los niños) becomes se, and los regalos is masculine plural, so dándoselos. Dándoselas would need a feminine noun." },
  5145: { cue: "el libro", explanation: "El libro gives lo and the receiver is you: devolver + te + lo = devolvértelo. With two pronouns attached, the infinitive takes an accent." },
  5146: { cue: "a mi primo", explanation: "Le (a mi primo) becomes se before la (la bicicleta): prestar + se + la = prestársela." },
  5147: { cue: "los documentos", explanation: "Le (al abogado) becomes se, and los documentos is masculine plural: mandárselos. Mandárselas would need a feminine noun." },
  5148: { cue: "la canción", explanation: "La canción ends in -ción, so it is feminine: me + la = cantármela. Cantármelo would need a masculine noun, like el poema." },
  5149: { cue: "el plan", explanation: "Les (a nuestros jefes) becomes se, and lo is singular because it stands for el plan: explicárselo." },
  5150: { cue: "las fotos", explanation: "Las fotos is feminine even though foto ends in -o, so te + las: enviártelas. With two pronouns attached, the infinitive takes an accent." },
};
