import type { ItemExplanation } from "./item-explanation.ts";

// Per-item explanations for the saber vs conocer quiz (docs/explanation-quality.md).
export const SABER_CONOCER_EXPLANATIONS: Record<number, ItemExplanation> = {
  6001: { cue: "dónde", explanation: "Dónde introduces a piece of information, and knowing information uses saber." },
  6002: { cue: "qué hora es", explanation: "Qué hora es asks for a fact, the time, and knowing facts uses saber." },
  6003: { cue: "el número de teléfono", explanation: "El número de teléfono is a specific piece of information, so saber." },
  6004: { cue: "que la carretera sigue cerrada", explanation: "Que la carretera sigue cerrada is a fact learned from the notice, so saber. Conocer is for people, places and things you are familiar with." },
  6005: { cue: "la respuesta", explanation: "La respuesta is information, and knowing information uses saber." },
  6006: { cue: "cuánto cuesta", explanation: "Cuánto cuesta introduces a piece of information, the price, so saber." },
  6007: { cue: "de memoria", explanation: "Knowing a fact de memoria (by heart) uses saber." },
  6008: { cue: "por qué", explanation: "Por qué introduces a reason, a piece of information, so saber." },
  6009: { cue: "si el museo abre", explanation: "Saber si asks whether someone has a piece of information: si el museo abre los lunes." },
  6010: { cue: "cómo se llama", explanation: "Cómo se llama asks for a name as information, so saber." },
  6011: { cue: "la noticia", explanation: "La noticia is information, and knowing news uses saber." },
  6012: { cue: "que el agua hierve", explanation: "Saber que introduces a known fact: que el agua hierve a cien grados." },
  6013: { cue: "quién ganó", explanation: "Quién ganó introduces a piece of information, so saber." },
  6014: { cue: "nada de este asunto", explanation: "No saber nada de este asunto means having no information about it, so saber." },
  6015: { cue: "cuándo es la fiesta", explanation: "Cuándo es la fiesta introduces a piece of information, so saber." },
  6016: { cue: "adónde vamos", explanation: "Adónde vamos introduces a piece of information, so saber." },
  6017: { cue: "qué pasó", explanation: "Qué pasó introduces a piece of information, so saber." },
  6018: { cue: "la fecha del examen", explanation: "La fecha del examen is a fact, and knowing facts uses saber." },
  6019: { cue: "el resultado", explanation: "El resultado is information, so saber." },
  6020: { cue: "que tienes razón", explanation: "Saber que introduces a fact you know: que tienes razón." },
  6021: { cue: "mucho de historia", explanation: "Saber mucho de historia means having a lot of knowledge about a subject, so saber." },
  6022: { cue: "lo que pasó", explanation: "Lo que pasó is information about what happened, so saber." },
  6023: { cue: "a qué hora sale", explanation: "A qué hora sale introduces a piece of information, so saber." },
  6024: { cue: "si Marta viene", explanation: "Saber si asks whether you have a piece of information: si Marta viene a cenar." },
  6025: { cue: "lo que quiere", explanation: "Lo que quiere is information about what you want, so saber." },
  6026: { cue: "cuál es", explanation: "Cuál es introduces a piece of information, so saber." },
  6027: { cue: "dónde dejó", explanation: "Dónde dejó introduces a piece of information, so saber." },
  6028: { cue: "eso", explanation: "Eso refers to a fact, and knowing a fact uses saber." },
  6029: { cue: "de memoria", explanation: "Saber de memoria means knowing something by heart, so saber." },
  6030: { cue: "qué decir", explanation: "No saber qué decir means not knowing what to say, so saber." },
  6031: { cue: "nadar", explanation: "Nadar is an infinitive, and saber + infinitive means knowing how to do something." },
  6032: { cue: "cocinar", explanation: "Cocinar is an infinitive, and saber + infinitive means knowing how to do something." },
  6033: { cue: "tocar el piano", explanation: "Tocar el piano is a learned skill, and saber + infinitive describes skills." },
  6034: { cue: "conducir", explanation: "Conducir is a learned skill, and saber + infinitive describes skills." },
  6035: { cue: "bailar tango", explanation: "Bailar tango is an infinitive, and saber + infinitive means knowing how to do something." },
  6036: { cue: "leer y escribir", explanation: "Leer y escribir are learned skills, and saber + infinitive describes skills." },
  6037: { cue: "hablar alemán", explanation: "Hablar alemán is a skill, and saber + infinitive describes skills such as speaking a language." },
  6038: { cue: "usar este programa", explanation: "Usar este programa is an infinitive, and saber + infinitive means knowing how to do something." },
  6039: { cue: "arreglar bicicletas", explanation: "Arreglar bicicletas is a learned skill, and saber + infinitive describes skills." },
  6040: { cue: "esquiar", explanation: "Esquiar is an infinitive, and saber + infinitive means knowing how to do something." },
  6041: { cue: "abrir la puerta", explanation: "Abrir la puerta is an ability, and saber + infinitive describes abilities." },
  6042: { cue: "jugar al ajedrez", explanation: "Jugar al ajedrez is an infinitive, and saber + infinitive means knowing how to do something." },
  6043: { cue: "escuchar a los demás", explanation: "Escuchar a los demás is a personal ability, and saber + infinitive describes abilities." },
  6044: { cue: "hacer una tortilla", explanation: "Hacer una tortilla is an infinitive, and saber + infinitive means knowing how to do something." },
  6045: { cue: "nadar", explanation: "Nadar is a skill, and no saber nadar means not being able to swim." },
  6046: { cue: "resolver estas ecuaciones", explanation: "Resolver estas ecuaciones is a learned skill, and saber + infinitive describes skills." },
  6047: { cue: "montar a caballo", explanation: "Montar a caballo is an infinitive, and saber + infinitive means knowing how to do something." },
  6048: { cue: "cambiar una rueda", explanation: "Cambiar una rueda is a practical skill, and saber + infinitive describes skills." },
  6049: { cue: "dibujar retratos", explanation: "Dibujar retratos is an ability, and saber + infinitive describes abilities." },
  6050: { cue: "programar", explanation: "Programar is an infinitive, and after querer, saber + infinitive still means knowing how to do something." },
  6051: { cue: "a tu hermano", explanation: "A tu hermano is a person, with the personal a, and knowing a person uses conocer." },
  6052: { cue: "a mis padres", explanation: "A mis padres are people, with the personal a, and knowing people uses conocer." },
  6053: { cue: "a mucha gente", explanation: "A mucha gente is people, with the personal a, and knowing people uses conocer." },
  6054: { cue: "al nuevo profesor", explanation: "Al nuevo profesor is a person, and knowing a person uses conocer. A + el becomes al." },
  6055: { cue: "a un actor famoso", explanation: "A un actor famoso is a person, with the personal a, and knowing a person uses conocer." },
  6056: { cue: "al director", explanation: "Al director is a person, and knowing a person uses conocer. A + el becomes al." },
  6057: { cue: "a Laura", explanation: "A Laura is a person you have known for years, and being acquainted with someone uses conocer." },
  6058: { cue: "a alguien", explanation: "Conocer a alguien means being acquainted with someone, so conocer." },
  6059: { cue: "a nadie", explanation: "A nadie refers to people, with the personal a, and knowing people uses conocer." },
  6060: { cue: "a nuestros vecinos", explanation: "A nuestros vecinos are people you know well, so conocer." },
  6061: { cue: "a tu novia", explanation: "A tu novia is a person, and conocer a alguien can mean meeting someone for the first time." },
  6062: { cue: "a tus abuelos", explanation: "A tus abuelos are people, and conocer a alguien can mean meeting someone for the first time." },
  6063: { cue: "a todos mis compañeros", explanation: "A todos mis compañeros are people, with the personal a, and knowing people uses conocer." },
  6064: { cue: "a Pablo", explanation: "A Pablo is a person you know well, so conocer." },
  6065: { cue: "a la directora", explanation: "A la directora is a person, with the personal a, and knowing a person uses conocer." },
  6066: { cue: "personalmente", explanation: "Personalmente stresses real acquaintance with the author, a person, so conocer." },
  6067: { cue: "al alcalde", explanation: "Al alcalde is a person, and knowing a person uses conocer. A + el becomes al." },
  6068: { cue: "a todos los clientes", explanation: "A todos los clientes are people, so conocer, even when you also know their names." },
  6069: { cue: "de verdad", explanation: "Knowing someone de verdad means knowing the person, so conocer, even when the person is the pronoun me." },
  6070: { cue: "a una chica", explanation: "A una chica is a person, with the personal a, and knowing a person uses conocer." },
  6071: { cue: "al médico", explanation: "Al médico is a person, and knowing a person uses conocer. A + el becomes al." },
  6072: { cue: "del colegio", explanation: "Knowing someone del colegio means knowing a person, so conocer, even when the person is the pronoun la." },
  6073: { cue: "a su profesora", explanation: "A su profesora is a person they know well, so conocer." },
  6074: { cue: "al chico", explanation: "Al chico is a person, and knowing a person uses conocer. A + el becomes al." },
  6075: { cue: "a gente nueva", explanation: "Conocer a gente nueva means meeting new people, so conocer." },
  6076: { cue: "Barcelona", explanation: "Barcelona is a place, and being familiar with a place uses conocer." },
  6077: { cue: "México", explanation: "México is a place, and conocer a place means having been there or knowing it." },
  6078: { cue: "Sevilla", explanation: "Sevilla is a place, and conocer a place means having been there or knowing it." },
  6079: { cue: "un restaurante", explanation: "Un restaurante is a place, and knowing a place uses conocer." },
  6080: { cue: "todos los museos", explanation: "Todos los museos are places, and knowing places uses conocer." },
  6081: { cue: "este barrio", explanation: "Este barrio is a place, and being familiar with a place uses conocer." },
  6082: { cue: "Japón", explanation: "Japón is a country, and conocer a country can mean getting to know it by visiting." },
  6083: { cue: "cada rincón de su pueblo", explanation: "Cada rincón de su pueblo is a place known in detail, so conocer." },
  6084: { cue: "la playa de La Concha", explanation: "La playa de La Concha is a place, and conocer a place means having been there or knowing it." },
  6085: { cue: "esta parte de la ciudad", explanation: "Esta parte de la ciudad is a place, and being familiar with a place uses conocer." },
  6086: { cue: "todas las calles", explanation: "Todas las calles de Madrid are places, and knowing places uses conocer." },
  6087: { cue: "un buen lugar", explanation: "Un buen lugar para cenar is a place, and knowing a place uses conocer." },
  6088: { cue: "el nuevo centro comercial", explanation: "El nuevo centro comercial is a place, and conocer a place means having been there." },
  6089: { cue: "muchos países", explanation: "Muchos países are places, and conocer a country means having been there." },
  6090: { cue: "Buenos Aires", explanation: "Buenos Aires is a city, and conocer a city can mean getting to know it by visiting." },
  6091: { cue: "un hotel", explanation: "Un hotel barato is a place, and knowing a place uses conocer." },
  6092: { cue: "como la palma de su mano", explanation: "Conocer algo como la palma de su mano means knowing a place thoroughly, so conocer." },
  6093: { cue: "una tienda", explanation: "Una tienda is a place, and knowing a place uses conocer." },
  6094: { cue: "el norte de España", explanation: "El norte de España is a region, and conocer a region means having been there or knowing it." },
  6095: { cue: "las montañas de Asturias", explanation: "Las montañas de Asturias are a place, and being familiar with a place uses conocer." },
  6096: { cue: "este libro", explanation: "Este libro is a work you are familiar with, so conocer." },
  6097: { cue: "la música de Rosalía", explanation: "La música de Rosalía is someone's work, and being familiar with it uses conocer." },
  6098: { cue: "la cocina peruana", explanation: "La cocina peruana is a field you are familiar with, so conocer." },
  6099: { cue: "la obra de Cervantes", explanation: "La obra de Cervantes is someone's work, and being familiar with it uses conocer." },
  6100: { cue: "este programa", explanation: "Este programa de televisión is a thing you can be familiar with, so conocer." },
  6101: { cue: "esa película", explanation: "Esa película is a work, and being familiar with a film uses conocer." },
  6102: { cue: "el mercado del arte", explanation: "El mercado del arte is a field, and being familiar with a field uses conocer." },
  6103: { cue: "esta marca de café", explanation: "Esta marca de café is a thing, and being familiar with a thing uses conocer." },
  6104: { cue: "el juego del mus", explanation: "El juego del mus is a game you are familiar with, so conocer. Knowing how to play it would be saber jugar." },
  6105: { cue: "todos los cuadros", explanation: "Todos los cuadros de Goya are works of art, and being familiar with them uses conocer." },
  6106: { cue: "este tipo de problemas", explanation: "Este tipo de problemas is a kind of situation you are familiar with, so conocer." },
  6107: { cue: "este modelo de coche", explanation: "Este modelo de coche is a thing, and being familiar with a thing uses conocer." },
  6108: { cue: "la obra de ese pintor", explanation: "La obra de ese pintor is someone's work, and being familiar with it uses conocer." },
  6109: { cue: "alguna aplicación", explanation: "Alguna aplicación is a thing, and being familiar with a thing uses conocer." },
  6110: { cue: "los efectos", explanation: "Los efectos de este medicamento are something doctors are familiar with, so conocer." },
  6111: { cue: "las novelas", explanation: "Las novelas de Isabel Allende are works, and being familiar with them uses conocer." },
  6112: { cue: "todos los tipos de vino", explanation: "Todos los tipos de vino are things, and being familiar with things uses conocer." },
  6113: { cue: "la cultura japonesa", explanation: "La cultura japonesa is a culture, and being familiar with a culture uses conocer." },
  6114: { cue: "este estilo", explanation: "Este estilo de arquitectura is a style, and being familiar with a style uses conocer." },
  6115: { cue: "pero no lo dominan", explanation: "Pero no lo dominan shows familiarity with el subjuntivo, not mastery, so conocer." },
  6116: { cue: "en la fiesta", explanation: "Ayer en la fiesta marks one moment with a person, so preterite conocí means met for the first time." },
  6117: { cue: "en la universidad", explanation: "Conocerse in the preterite means met each other, here en la universidad." },
  6118: { cue: "a tu mejor amigo", explanation: "A tu mejor amigo is a person, and preterite conocer means met someone for the first time." },
  6119: { cue: "por primera vez", explanation: "Por primera vez with a place, Lisboa, makes preterite conocimos mean saw or visited it for the first time." },
  6120: { cue: "a su novio", explanation: "A su novio is a person, and preterite conocer means met someone for the first time." },
  6121: { cue: "al nuevo maestro", explanation: "Al nuevo maestro is a person, and preterite conocer means met someone for the first time." },
  6122: { cue: "al presidente", explanation: "Al presidente is a person, and preterite conocer means met someone for the first time." },
  6123: { cue: "Machu Picchu", explanation: "Machu Picchu is a place, and preterite conocer with a place means saw or visited it for the first time." },
  6124: { cue: "que te casas", explanation: "Que te casas is news, and preterite saber means found out." },
  6125: { cue: "la noticia", explanation: "La noticia is information, and preterite saber means found out." },
  6126: { cue: "al leer la carta", explanation: "Al leer la carta marks the moment she learned la verdad, and preterite saber means found out." },
  6127: { cue: "el resultado", explanation: "El resultado is information, and preterite saber means found out." },
  6128: { cue: "por la radio", explanation: "Por la radio is how they heard the news, and preterite saber means found out." },
  6129: { cue: "por fin", explanation: "Por fin marks the moment you found out, and preterite saber means found out." },
  6130: { cue: "quién era el ladrón", explanation: "Quién era el ladrón is information, and preterite saber means found out." },
  6131: { cue: "que estaba enfermo", explanation: "Que estaba enfermo is information, and preterite saber means found out." },
  6132: { cue: "por qué", explanation: "Por qué se cerró is information, and nunca supieron means they never found out." },
  6133: { cue: "nadar", explanation: "Nadar is an infinitive, and imperfect saber + infinitive describes a skill you had in the past." },
  6134: { cue: "que tenías un hermano", explanation: "Que tenías un hermano is information, and imperfect saber describes what you knew, or did not, in the past." },
  6135: { cue: "tocar la guitarra", explanation: "Tocar la guitarra is an infinitive, and imperfect saber + infinitive describes a past skill." },
  6136: { cue: "que el examen era hoy", explanation: "Que el examen era hoy is information, and imperfect saber describes what you knew in the past." },
  6137: { cue: "dónde estaba el hotel", explanation: "Dónde estaba el hotel is information, and imperfect saber describes what you knew, or did not, in the past." },
  6138: { cue: "la respuesta", explanation: "La respuesta is information, and imperfect saber describes what people knew in the past." },
  6139: { cue: "que iba a llover", explanation: "Que iba a llover is information, and imperfect saber describes what someone knew in the past." },
  6140: { cue: "lo que pasaba", explanation: "Lo que pasaba is information, and imperfect saber describes what someone knew in the past." },
  6141: { cue: "a todos los vecinos", explanation: "A todos los vecinos are people, and imperfect conocer describes being acquainted with people in the past." },
  6142: { cue: "la ciudad", explanation: "La ciudad is a place, and imperfect conocer describes familiarity with a place in the past." },
  6143: { cue: "a Marcos", explanation: "A Marcos is a person, and imperfect conocer describes an acquaintance that already existed." },
  6144: { cue: "ese restaurante", explanation: "Ese restaurante is a place, and imperfect conocer describes familiarity with a place in the past." },
  6145: { cue: "al autor", explanation: "Al autor is a person, and imperfect conocer describes being acquainted with someone in the past." },
  6146: { cue: "Roma", explanation: "Roma is a place, and imperfect conocer describes familiarity with a place in the past." },
  6147: { cue: "a muchos músicos", explanation: "A muchos músicos are people, and imperfect conocer describes being acquainted with people in the past." },
  6148: { cue: "de vista", explanation: "Conocer de vista means knowing someone by sight, and the imperfect describes that earlier state." },
  6149: { cue: "anoche", explanation: "Anoche marks the moment of learning it, and preterite saber (lo supe) means found out." },
  6150: { cue: "en 2015", explanation: "En 2015 marks when it happened, and conocerse in the preterite means met each other." },
};
