// Issue #24, Stage 3: one meaningful, project-authored Spanish example sentence and its
// English translation for every one of the 500 flashcard verbs. Keyed by the exact
// infinitive spelling used in flashcards-verbs-part1.ts / flashcards-verbs-part2.ts.
//
// Replaces the old SPECIAL_EXAMPLES map (Spanish only, 47 verbs) and the buildExample()
// generic fallback ("Voy a <verb> hoy.") that covered the other 453 verbs.
export const FLASHCARD_EXAMPLES: Record<string, { example: string; exampleEnglish: string }> = {
  // --- from flashcards-verbs-part1.ts, rank order ---
  ser: { example: "Quiero ser más paciente.", exampleEnglish: "I want to be more patient." },
  estar: { example: "Voy a estar en casa esta tarde.", exampleEnglish: "I'm going to be home this afternoon." },
  haber: { example: "Tiene que haber otra solución.", exampleEnglish: "There has to be another solution." },
  hacer: { example: "Tengo que hacer la cena.", exampleEnglish: "I have to make dinner." },
  poder: { example: "Quiero poder hablar español con confianza.", exampleEnglish: "I want to be able to speak Spanish with confidence." },
  decir: { example: "Necesito decirte algo importante.", exampleEnglish: "I need to tell you something important." },
  ir: { example: "Vamos a ir al mercado el sábado.", exampleEnglish: "We're going to go to the market on Saturday." },
  ver: { example: "Quiero ver esa película nueva.", exampleEnglish: "I want to see that new film." },
  dar: { example: "Voy a dar mi opinión en la reunión.", exampleEnglish: "I'm going to give my opinion at the meeting." },
  saber: { example: "Quiero saber la verdad.", exampleEnglish: "I want to know the truth." },
  querer: { example: "Quiero aprender español.", exampleEnglish: "I want to learn Spanish." },
  llegar: { example: "El tren va a llegar tarde.", exampleEnglish: "The train is going to arrive late." },
  pasar: { example: "No sé qué va a pasar mañana.", exampleEnglish: "I don't know what's going to happen tomorrow." },
  deber: { example: "Debes descansar un poco.", exampleEnglish: "You should rest a little." },
  poner: { example: "Voy a poner la mesa para la cena.", exampleEnglish: "I'm going to set the table for dinner." },
  parecer: { example: "Esto puede parecer difícil al principio.", exampleEnglish: "This can seem difficult at first." },
  quedar: { example: "Podemos quedar mañana por la tarde.", exampleEnglish: "We can meet up tomorrow afternoon." },
  creer: { example: "No puedo creer esta noticia.", exampleEnglish: "I can't believe this news." },
  hablar: { example: "Ana habla tres idiomas.", exampleEnglish: "Ana speaks three languages." },
  llevar: { example: "Voy a llevar el paraguas por si llueve.", exampleEnglish: "I'm going to take the umbrella in case it rains." },
  dejar: { example: "Voy a dejar las llaves en la mesa.", exampleEnglish: "I'm going to leave the keys on the table." },
  seguir: { example: "Vamos a seguir las instrucciones con cuidado.", exampleEnglish: "We're going to follow the instructions carefully." },
  encontrar: { example: "Espero encontrar mis gafas pronto.", exampleEnglish: "I hope to find my glasses soon." },
  llamar: { example: "Voy a llamar a mi madre esta noche.", exampleEnglish: "I'm going to call my mother tonight." },
  venir: { example: "Mis amigos van a venir a la fiesta.", exampleEnglish: "My friends are going to come to the party." },
  pensar: { example: "Necesito pensar en esta decisión.", exampleEnglish: "I need to think about this decision." },
  salir: { example: "Vamos a salir temprano mañana.", exampleEnglish: "We're going to leave early tomorrow." },
  volver: { example: "Espero volver antes de las diez.", exampleEnglish: "I hope to come back before ten." },
  tomar: { example: "Voy a tomar un café antes de trabajar.", exampleEnglish: "I'm going to have a coffee before work." },
  conocer: { example: "Me gustaría conocer mejor la ciudad.", exampleEnglish: "I would like to get to know the city better." },
  vivir: { example: "Quiero vivir cerca del mar algún día.", exampleEnglish: "I want to live near the sea someday." },
  sentir: { example: "Puedo sentir el frío en las manos.", exampleEnglish: "I can feel the cold in my hands." },
  tratar: { example: "Voy a tratar de llegar a tiempo.", exampleEnglish: "I'm going to try to arrive on time." },
  mirar: { example: "Los niños miran las estrellas por la noche.", exampleEnglish: "The children look at the stars at night." },
  contar: { example: "Mi abuelo siempre cuenta historias interesantes.", exampleEnglish: "My grandfather always tells interesting stories." },
  empezar: { example: "Vamos a empezar la clase en cinco minutos.", exampleEnglish: "We're going to start class in five minutes." },
  esperar: { example: "Voy a esperar tu respuesta con calma.", exampleEnglish: "I'm going to wait for your answer calmly." },
  buscar: { example: "Necesito buscar un regalo para mi hermana.", exampleEnglish: "I need to look for a gift for my sister." },
  existir: { example: "Debe existir una forma más sencilla.", exampleEnglish: "There must exist a simpler way." },
  entrar: { example: "Vamos a entrar por la puerta principal.", exampleEnglish: "We're going to go in through the main door." },
  trabajar: { example: "Mi padre trabaja en un hospital.", exampleEnglish: "My father works at a hospital." },
  escribir: { example: "Quiero escribir un correo a mi jefe.", exampleEnglish: "I want to write an email to my boss." },
  perder: { example: "No quiero perder el autobús.", exampleEnglish: "I don't want to miss the bus." },
  producir: { example: "Esta fábrica va a producir más piezas este año.", exampleEnglish: "This factory is going to produce more parts this year." },
  ocurrir: { example: "Eso puede ocurrir en cualquier momento.", exampleEnglish: "That can happen at any moment." },
  entender: { example: "Necesito entender mejor esta lección.", exampleEnglish: "I need to understand this lesson better." },
  pedir: { example: "Voy a pedir ayuda a mi vecino.", exampleEnglish: "I'm going to ask my neighbour for help." },
  recibir: { example: "Espero recibir buenas noticias hoy.", exampleEnglish: "I hope to receive good news today." },
  recordar: { example: "Quiero recordar este viaje para siempre.", exampleEnglish: "I want to remember this trip forever." },
  terminar: { example: "Voy a terminar el informe esta noche.", exampleEnglish: "I'm going to finish the report tonight." },
  permitir: { example: "El médico no le va a permitir viajar todavía.", exampleEnglish: "The doctor isn't going to allow him to travel yet." },
  aparecer: { example: "Espero que el gato vuelva a aparecer pronto.", exampleEnglish: "I hope the cat shows up again soon." },
  conseguir: { example: "Quiero conseguir un trabajo mejor.", exampleEnglish: "I want to get a better job." },
  comenzar: { example: "La reunión va a comenzar en diez minutos.", exampleEnglish: "The meeting is going to begin in ten minutes." },
  servir: { example: "Vamos a servir la cena a las ocho.", exampleEnglish: "We're going to serve dinner at eight." },
  sacar: { example: "Necesito sacar dinero del banco.", exampleEnglish: "I need to take out money from the bank." },
  necesitar: { example: "Vas a necesitar un abrigo hoy.", exampleEnglish: "You're going to need a coat today." },
  mantener: { example: "Quiero mantener esta rutina de ejercicio.", exampleEnglish: "I want to keep up this exercise routine." },
  resultar: { example: "La tarea puede resultar más fácil de lo esperado.", exampleEnglish: "The task can turn out easier than expected." },
  leer: { example: "Me gusta leer antes de dormir.", exampleEnglish: "I like to read before going to sleep." },
  caer: { example: "Ten cuidado, esa taza puede caer.", exampleEnglish: "Be careful, that cup might fall." },
  cambiar: { example: "Vamos a cambiar los muebles de sitio.", exampleEnglish: "We're going to move the furniture around." },
  presentar: { example: "Voy a presentar mi proyecto mañana.", exampleEnglish: "I'm going to present my project tomorrow." },
  crear: { example: "Queremos crear una aplicación útil.", exampleEnglish: "We want to create a useful app." },
  abrir: { example: "Voy a abrir la ventana un momento.", exampleEnglish: "I'm going to open the window for a moment." },
  considerar: { example: "Vamos a considerar todas las opciones.", exampleEnglish: "We're going to consider all the options." },
  oír: { example: "Creo que puedo oír música lejos.", exampleEnglish: "I think I can hear music in the distance." },
  acabar: { example: "Voy a acabar este libro esta semana.", exampleEnglish: "I'm going to finish this book this week." },
  convertir: { example: "Quieren convertir la fábrica en un museo.", exampleEnglish: "They want to turn the factory into a museum." },
  ganar: { example: "El equipo quiere ganar el próximo partido.", exampleEnglish: "The team wants to win the next match." },
  formar: { example: "Vamos a formar un equipo nuevo.", exampleEnglish: "We're going to form a new team." },
  traer: { example: "¿Puedes traer el postre a la cena?", exampleEnglish: "Can you bring dessert to dinner?" },
  partir: { example: "El tren va a partir en unos minutos.", exampleEnglish: "The train is about to depart in a few minutes." },
  morir: { example: "Nadie quiere morir joven.", exampleEnglish: "No one wants to die young." },
  aceptar: { example: "Voy a aceptar la oferta de trabajo.", exampleEnglish: "I'm going to accept the job offer." },
  realizar: { example: "Queremos realizar un buen trabajo este trimestre.", exampleEnglish: "We want to do a good job this quarter." },
  suponer: { example: "Voy a suponer que todo va bien.", exampleEnglish: "I'm going to assume everything is fine." },
  comprender: { example: "Necesito comprender mejor este tema.", exampleEnglish: "I need to understand this topic better." },
  lograr: { example: "Vamos a lograr terminar a tiempo.", exampleEnglish: "We're going to manage to finish on time." },
  explicar: { example: "El profesor va a explicar la lección de nuevo.", exampleEnglish: "The teacher is going to explain the lesson again." },
  preguntar: { example: "Voy a preguntar la hora del tren.", exampleEnglish: "I'm going to ask what time the train leaves." },
  tocar: { example: "Mi hermana sabe tocar el piano.", exampleEnglish: "My sister knows how to play the piano." },
  reconocer: { example: "Apenas pude reconocer la calle.", exampleEnglish: "I could barely recognize the street." },
  estudiar: { example: "Carla estudia medicina en la universidad.", exampleEnglish: "Carla studies medicine at university." },
  alcanzar: { example: "Vamos a alcanzar la meta este mes.", exampleEnglish: "We're going to reach the goal this month." },
  nacer: { example: "El bebé va a nacer en septiembre.", exampleEnglish: "The baby is going to be born in September." },
  dirigir: { example: "Ella va a dirigir el nuevo proyecto.", exampleEnglish: "She is going to direct the new project." },
  correr: { example: "Diego corre cinco kilómetros cada mañana.", exampleEnglish: "Diego runs five kilometres every morning." },
  utilizar: { example: "Vamos a utilizar este programa para el informe.", exampleEnglish: "We're going to use this program for the report." },
  pagar: { example: "Voy a pagar la cuenta con tarjeta.", exampleEnglish: "I'm going to pay the bill by card." },
  ayudar: { example: "Quiero ayudar a mis vecinos con la mudanza.", exampleEnglish: "I want to help my neighbours with the move." },
  gustar: { example: "A Marta le puede gustar esta canción.", exampleEnglish: "Marta might like this song." },
  jugar: { example: "Los niños quieren jugar en el parque.", exampleEnglish: "The children want to play at the park." },
  escuchar: { example: "Me gusta escuchar música mientras trabajo.", exampleEnglish: "I like listening to music while I work." },
  cumplir: { example: "Voy a cumplir mi promesa esta vez.", exampleEnglish: "I'm going to keep my promise this time." },
  ofrecer: { example: "El hotel va a ofrecer un descuento este mes.", exampleEnglish: "The hotel is going to offer a discount this month." },
  descubrir: { example: "Quiero descubrir pueblos nuevos este verano.", exampleEnglish: "I want to discover new villages this summer." },
  levantar: { example: "Necesito levantar esta caja pesada.", exampleEnglish: "I need to lift this heavy box." },
  intentar: { example: "Voy a intentar terminar hoy mismo.", exampleEnglish: "I'm going to try to finish today." },
  usar: { example: "Puedes usar mi ordenador si quieres.", exampleEnglish: "You can use my computer if you want." },
  decidir: { example: "Tenemos que decidir el destino del viaje.", exampleEnglish: "We have to decide on the trip's destination." },
  repetir: { example: "El profesor va a repetir la pregunta.", exampleEnglish: "The teacher is going to repeat the question." },
  olvidar: { example: "No quiero olvidar este momento.", exampleEnglish: "I don't want to forget this moment." },
  aprender: { example: "Quiero aprender a tocar la guitarra.", exampleEnglish: "I want to learn to play the guitar." },
  cerrar: { example: "Voy a cerrar la puerta con llave.", exampleEnglish: "I'm going to lock the door." },
  comer: { example: "Vamos a comer en aquel restaurante nuevo.", exampleEnglish: "We're going to eat at that new restaurant." },
  cantar: { example: "A mi hija le encanta cantar en el coro.", exampleEnglish: "My daughter loves singing in the choir." },
  bailar: { example: "Vamos a bailar en la boda de mi prima.", exampleEnglish: "We're going to dance at my cousin's wedding." },
  comprar: { example: "Necesito comprar pan de camino a casa.", exampleEnglish: "I need to buy bread on the way home." },
  vender: { example: "Mis padres quieren vender la casa vieja.", exampleEnglish: "My parents want to sell the old house." },
  viajar: { example: "Sueño con viajar por toda Sudamérica.", exampleEnglish: "I dream of traveling all over South America." },
  caminar: { example: "Prefiero caminar en vez de coger el autobús.", exampleEnglish: "I prefer to walk instead of taking the bus." },
  conducir: { example: "Todavía no sé conducir un coche manual.", exampleEnglish: "I still don't know how to drive a manual car." },
  dormir: { example: "Necesito dormir ocho horas para rendir bien.", exampleEnglish: "I need to sleep eight hours to perform well." },
  beber: { example: "Es importante beber suficiente agua.", exampleEnglish: "It's important to drink enough water." },
  cocinar: { example: "Me relaja cocinar los domingos.", exampleEnglish: "Cooking on Sundays relaxes me." },
  lavar: { example: "Voy a lavar el coche este fin de semana.", exampleEnglish: "I'm going to wash the car this weekend." },
  limpiar: { example: "Tenemos que limpiar la cocina antes de salir.", exampleEnglish: "We have to clean the kitchen before we leave." },
  cortar: { example: "Necesito cortar el pan para la cena.", exampleEnglish: "I need to cut the bread for dinner." },
  romper: { example: "Ten cuidado, ese jarrón se puede romper.", exampleEnglish: "Be careful, that vase can break." },
  enviar: { example: "Voy a enviar el paquete mañana por la mañana.", exampleEnglish: "I'm going to send the package tomorrow morning." },
  enseñar: { example: "Mi tía enseña matemáticas en el instituto.", exampleEnglish: "My aunt teaches maths at the high school." },
  mostrar: { example: "Te voy a mostrar las fotos del viaje.", exampleEnglish: "I'm going to show you the trip photos." },
  compartir: { example: "Me gusta compartir recetas con mis amigas.", exampleEnglish: "I like sharing recipes with my friends." },
  elegir: { example: "Tenemos que elegir un nombre para el perro.", exampleEnglish: "We have to choose a name for the dog." },
  incluir: { example: "El precio va a incluir el desayuno.", exampleEnglish: "The price is going to include breakfast." },
  excluir: { example: "Esta oferta va a excluir los fines de semana.", exampleEnglish: "This offer is going to exclude weekends." },
  mejorar: { example: "Quiero mejorar mi pronunciación en español.", exampleEnglish: "I want to improve my Spanish pronunciation." },
  empeorar: { example: "El tiempo puede empeorar por la tarde.", exampleEnglish: "The weather might get worse in the afternoon." },
  crecer: { example: "Esta planta va a crecer muy rápido.", exampleEnglish: "This plant is going to grow very fast." },
  reducir: { example: "Queremos reducir el gasto este mes.", exampleEnglish: "We want to reduce spending this month." },
  aumentar: { example: "La empresa va a aumentar los precios.", exampleEnglish: "The company is going to raise prices." },
  bajar: { example: "Voy a bajar la música un poco.", exampleEnglish: "I'm going to turn the music down a bit." },
  subir: { example: "Vamos a subir la montaña este sábado.", exampleEnglish: "We're going to climb the mountain this Saturday." },
  regresar: { example: "Espero regresar antes de que oscurezca.", exampleEnglish: "I hope to return before it gets dark." },
  permanecer: { example: "Vamos a permanecer aquí unos días más.", exampleEnglish: "We're going to stay here a few more days." },
  mover: { example: "Necesito mover el sofá de sitio.", exampleEnglish: "I need to move the sofa to another spot." },
  parar: { example: "El autobús va a parar en la próxima esquina.", exampleEnglish: "The bus is going to stop at the next corner." },
  continuar: { example: "Vamos a continuar la clase después del descanso.", exampleEnglish: "We're going to continue the class after the break." },
  preparar: { example: "Voy a preparar la cena esta noche.", exampleEnglish: "I'm going to prepare dinner tonight." },
  responder: { example: "Voy a responder tu mensaje enseguida.", exampleEnglish: "I'm going to answer your message right away." },
  añadir: { example: "Puedes añadir más sal si quieres.", exampleEnglish: "You can add more salt if you want." },
  quitar: { example: "Voy a quitar el polvo de la estantería.", exampleEnglish: "I'm going to dust off the shelf." },
  quitarse: { example: "Voy a quitarme los zapatos al entrar.", exampleEnglish: "I'm going to take off my shoes when I come in." },
  vestir: { example: "Mi madre suele vestir muy elegante.", exampleEnglish: "My mother usually dresses very elegantly." },
  llevarse: { example: "Voy a llevarme el paraguas por si acaso.", exampleEnglish: "I'm going to take the umbrella just in case." },
  levantarse: { example: "Suelo levantarme a las siete cada día.", exampleEnglish: "I usually get up at seven every day." },
  sentarse: { example: "Vamos a sentarnos cerca de la ventana.", exampleEnglish: "We're going to sit near the window." },
  acostarse: { example: "Los niños van a acostarse a las nueve.", exampleEnglish: "The children are going to go to bed at nine." },
  despertarse: { example: "Suelo despertarme antes de que suene el despertador.", exampleEnglish: "I usually wake up before the alarm goes off." },
  ducharse: { example: "Voy a ducharme antes de salir.", exampleEnglish: "I'm going to shower before I go out." },
  bañarse: { example: "A los niños les encanta bañarse en el mar.", exampleEnglish: "The kids love bathing in the sea." },
  peinarse: { example: "Voy a peinarme antes de la entrevista.", exampleEnglish: "I'm going to comb my hair before the interview." },
  afeitarse: { example: "Mi padre suele afeitarse cada mañana.", exampleEnglish: "My father usually shaves every morning." },
  casar: { example: "El sacerdote va a casar a la pareja el sábado.", exampleEnglish: "The priest is going to marry the couple on Saturday." },
  casarse: { example: "Mis amigos van a casarse en junio.", exampleEnglish: "My friends are going to get married in June." },
  reunir: { example: "Vamos a reunir a toda la familia este año.", exampleEnglish: "We're going to gather the whole family this year." },
  reunirse: { example: "Vamos a reunirnos el lunes para hablar del proyecto.", exampleEnglish: "We're going to meet on Monday to talk about the project." },
  encontrarse: { example: "Solemos encontrarnos en la misma cafetería.", exampleEnglish: "We usually meet up at the same café." },
  preocupar: { example: "Ese ruido raro me empieza a preocupar.", exampleEnglish: "That strange noise is starting to worry me." },
  preocuparse: { example: "No hace falta preocuparse tanto por eso.", exampleEnglish: "There's no need to worry so much about that." },
  ocupar: { example: "Esta caja va a ocupar mucho espacio.", exampleEnglish: "This box is going to take up a lot of space." },
  ocuparse: { example: "Yo me voy a ocupar de las reservas.", exampleEnglish: "I'm going to take care of the reservations." },
  llamarse: { example: "Mi sobrina se llama Sofía.", exampleEnglish: "My niece's name is Sofía." },
  sentirse: { example: "Espero sentirme mejor mañana.", exampleEnglish: "I hope to feel better tomorrow." },
  acordar: { example: "Vamos a acordar una fecha para la reunión.", exampleEnglish: "We're going to agree on a date for the meeting." },
  acordarse: { example: "No consigo acordarme de su nombre.", exampleEnglish: "I can't manage to remember his name." },
  olvidarse: { example: "Espero no olvidarme las llaves otra vez.", exampleEnglish: "I hope I don't forget my keys again." },
  contestar: { example: "Voy a contestar el correo por la tarde.", exampleEnglish: "I'm going to answer the email in the afternoon." },
  describir: { example: "Voy a describir la casa con detalle.", exampleEnglish: "I'm going to describe the house in detail." },
  comparar: { example: "Vamos a comparar los dos presupuestos.", exampleEnglish: "We're going to compare the two budgets." },
  cambiarse: { example: "Voy a cambiarme antes de salir a cenar.", exampleEnglish: "I'm going to change clothes before going out to dinner." },
  probar: { example: "Quiero probar este plato nuevo del menú.", exampleEnglish: "I want to try this new dish on the menu." },
  prohibir: { example: "Van a prohibir fumar en la terraza.", exampleEnglish: "They're going to prohibit smoking on the terrace." },
  obligar: { example: "Nadie te va a obligar a decidir hoy.", exampleEnglish: "No one is going to force you to decide today." },
  recomendar: { example: "Te voy a recomendar un buen restaurante.", exampleEnglish: "I'm going to recommend a good restaurant to you." },
  aconsejar: { example: "Mi médico me suele aconsejar caminar más.", exampleEnglish: "My doctor usually advises me to walk more." },
  sugerir: { example: "Voy a sugerir otra fecha para la cita.", exampleEnglish: "I'm going to suggest a different date for the appointment." },
  invitar: { example: "Vamos a invitar a todos nuestros primos.", exampleEnglish: "We're going to invite all our cousins." },
  rechazar: { example: "Decidí rechazar la oferta de trabajo.", exampleEnglish: "I decided to reject the job offer." },
  negar: { example: "No puedo negar que estoy nervioso.", exampleEnglish: "I can't deny that I'm nervous." },
  afirmar: { example: "El testigo va a afirmar lo que vio.", exampleEnglish: "The witness is going to state what he saw." },
  prometer: { example: "Te prometo llamarte en cuanto llegue.", exampleEnglish: "I promise to call you as soon as I arrive." },
  fallar: { example: "El plan no puede fallar esta vez.", exampleEnglish: "The plan can't fail this time." },
  ahorrar: { example: "Quiero ahorrar dinero para el viaje.", exampleEnglish: "I want to save money for the trip." },
  gastar: { example: "No quiero gastar demasiado en regalos.", exampleEnglish: "I don't want to spend too much on gifts." },
  cobrar: { example: "El taller va a cobrar la reparación mañana.", exampleEnglish: "The garage is going to charge for the repair tomorrow." },
  costar: { example: "El viaje puede costar más de cien euros.", exampleEnglish: "The trip can cost more than a hundred euros." },
  valer: { example: "Este reloj puede valer mucho dinero.", exampleEnglish: "This watch could be worth a lot of money." },
  preferir: { example: "Prefiero viajar en tren.", exampleEnglish: "I prefer to travel by train." },
  odiar: { example: "Odio esperar en filas largas.", exampleEnglish: "I hate waiting in long lines." },
  amar: { example: "Es fácil amar este lugar.", exampleEnglish: "It's easy to love this place." },
  encantar: { example: "A los niños les va a encantar el museo.", exampleEnglish: "The kids are going to love the museum." },
  molestar: { example: "El ruido puede molestar a los vecinos.", exampleEnglish: "The noise can bother the neighbours." },
  importar: { example: "Lo que piensas puede importar mucho.", exampleEnglish: "What you think can matter a lot." },
  faltar: { example: "Puede faltar una pieza.", exampleEnglish: "A piece might be missing." },
  doler: { example: "Me puede doler la espalda después del viaje.", exampleEnglish: "My back might hurt after the trip." },
  aburrir: { example: "La película puede aburrir a los niños.", exampleEnglish: "The film can bore the children." },
  divertir: { example: "El juego puede divertir a toda la familia.", exampleEnglish: "The game can entertain the whole family." },
  interesar: { example: "Este tema puede interesar a los estudiantes.", exampleEnglish: "This topic might interest the students." },
  sorprender: { example: "La respuesta puede sorprenderte.", exampleEnglish: "The answer might surprise you." },
  cansar: { example: "Caminar tanto puede cansar a cualquiera.", exampleEnglish: "Walking that much can tire anyone out." },
  alegrar: { example: "La noticia puede alegrar a tu madre.", exampleEnglish: "The news might cheer up your mother." },
  entristecer: { example: "La despedida puede entristecer a todos.", exampleEnglish: "The farewell can sadden everyone." },
  asustar: { example: "Ese ruido puede asustar al perro.", exampleEnglish: "That noise can scare the dog." },
  enfadar: { example: "Esa broma le puede enfadar un poco.", exampleEnglish: "That joke might make him a little angry." },
  calmar: { example: "Un té caliente puede calmar los nervios.", exampleEnglish: "A hot tea can calm the nerves." },
  relajar: { example: "Escuchar música me ayuda a relajar la mente.", exampleEnglish: "Listening to music helps me relax my mind." },
  temer: { example: "No debes temer el cambio.", exampleEnglish: "You shouldn't fear change." },
  confiar: { example: "Puedes confiar en ella.", exampleEnglish: "You can trust her." },
  dudar: { example: "Es normal dudar al principio.", exampleEnglish: "It's normal to doubt yourself at first." },
  planear: { example: "Vamos a planear el viaje con calma.", exampleEnglish: "We're going to plan the trip calmly." },
  organizar: { example: "Necesito organizar mi escritorio hoy.", exampleEnglish: "I need to organize my desk today." },
  reservar: { example: "Voy a reservar una mesa para dos.", exampleEnglish: "I'm going to book a table for two." },
  cancelar: { example: "Tuvimos que cancelar la reserva del hotel.", exampleEnglish: "We had to cancel the hotel booking." },
  visitar: { example: "Queremos visitar a mis abuelos este fin de semana.", exampleEnglish: "We want to visit my grandparents this weekend." },
  explorar: { example: "Nos encanta explorar pueblos pequeños.", exampleEnglish: "We love exploring small villages." },
  quedarse: { example: "Vamos a quedarnos en casa este fin de semana.", exampleEnglish: "We're going to stay home this weekend." },
  alojar: { example: "El hotel puede alojar hasta cien personas.", exampleEnglish: "The hotel can accommodate up to a hundred people." },
  alojarse: { example: "Vamos a alojarnos cerca del centro.", exampleEnglish: "We're going to stay near the city centre." },
  volar: { example: "Vamos a volar directamente a Madrid.", exampleEnglish: "We're going to fly directly to Madrid." },
  montar: { example: "A mi hijo le gusta montar en bicicleta.", exampleEnglish: "My son likes riding his bike." },
  nadar: { example: "Marta nada todas las mañanas en la piscina.", exampleEnglish: "Marta swims every morning at the pool." },
  andar: { example: "Prefiero andar en vez de coger el coche.", exampleEnglish: "I prefer to walk instead of taking the car." },
  pasear: { example: "Nos gusta pasear por la playa al atardecer.", exampleEnglish: "We like strolling along the beach at sunset." },
  cruzar: { example: "Vamos a cruzar el puente a pie.", exampleEnglish: "We're going to cross the bridge on foot." },
  girar: { example: "Tienes que girar a la derecha en la próxima calle.", exampleEnglish: "You have to turn right at the next street." },
  detener: { example: "La policía va a detener el tráfico un momento.", exampleEnglish: "The police are going to stop traffic for a moment." },
  detenerse: { example: "El coche se va a detener en el semáforo.", exampleEnglish: "The car is going to stop at the traffic light." },
  aparcar: { example: "Voy a aparcar cerca de la entrada.", exampleEnglish: "I'm going to park near the entrance." },
  arrancar: { example: "El coche no quiere arrancar esta mañana.", exampleEnglish: "The car doesn't want to start this morning." },
  frenar: { example: "Tuve que frenar de golpe en el cruce.", exampleEnglish: "I had to brake suddenly at the crossing." },
  acelerar: { example: "No hace falta acelerar tanto en esta curva.", exampleEnglish: "There's no need to accelerate so much on this curve." },
  saltar: { example: "El perro puede saltar la valla del jardín.", exampleEnglish: "The dog can jump over the garden fence." },
  lanzar: { example: "Van a lanzar el nuevo producto en abril.", exampleEnglish: "They're going to launch the new product in April." },
  tirar: { example: "Voy a tirar estas cajas viejas.", exampleEnglish: "I'm going to throw away these old boxes." },
  recoger: { example: "Voy a recoger a los niños del colegio.", exampleEnglish: "I'm going to pick up the kids from school." },
  guardar: { example: "Voy a guardar estos documentos en el cajón.", exampleEnglish: "I'm going to keep these documents in the drawer." },
  hallar: { example: "Espero hallar una solución pronto.", exampleEnglish: "I hope to find a solution soon." },
  esconder: { example: "Vamos a esconder los regalos antes de la fiesta.", exampleEnglish: "We're going to hide the gifts before the party." },
  esconderse: { example: "El gato suele esconderse debajo del sofá.", exampleEnglish: "The cat usually hides under the sofa." },
  observar: { example: "Nos gusta observar los pájaros en el parque.", exampleEnglish: "We like to observe the birds in the park." },
  oler: { example: "La cocina huele a pan recién hecho.", exampleEnglish: "The kitchen smells like freshly baked bread." },
  comentar: { example: "Vamos a comentar el libro en clase.", exampleEnglish: "We're going to discuss the book in class." },
  conversar: { example: "Nos gusta conversar tomando un café.", exampleEnglish: "We like to chat over a coffee." },
  discutir: { example: "No quiero discutir por algo tan pequeño.", exampleEnglish: "I don't want to argue over something so small." },
  gritar: { example: "El entrenador no necesita gritar tanto.", exampleEnglish: "The coach doesn't need to shout so much." },
  susurrar: { example: "Me gusta susurrar el secreto a mi hermana.", exampleEnglish: "I like whispering the secret to my sister." },
  firmar: { example: "Voy a firmar el contrato esta tarde.", exampleEnglish: "I'm going to sign the contract this afternoon." },
  copiar: { example: "Necesito copiar estos apuntes para el examen.", exampleEnglish: "I need to copy these notes for the exam." },

  // --- from flashcards-verbs-part2.ts, rank order ---
  borrar: { example: "Voy a borrar estos archivos antiguos.", exampleEnglish: "I'm going to delete these old files." },
  dibujar: { example: "A mi hijo le encanta dibujar animales.", exampleEnglish: "My son loves drawing animals." },
  pintar: { example: "Queremos pintar el salón de otro color.", exampleEnglish: "We want to paint the living room a different colour." },
  imprimir: { example: "Voy a imprimir los billetes esta noche.", exampleEnglish: "I'm going to print the tickets tonight." },
  publicar: { example: "Vamos a publicar el artículo la próxima semana.", exampleEnglish: "We're going to publish the article next week." },
  encender: { example: "Voy a encender la luz de la cocina.", exampleEnglish: "I'm going to turn on the kitchen light." },
  apagar: { example: "No olvides apagar el ordenador al salir.", exampleEnglish: "Don't forget to turn off the computer when you leave." },
  conectar: { example: "Necesito conectar el portátil al proyector.", exampleEnglish: "I need to connect the laptop to the projector." },
  desconectar: { example: "Voy a desconectar el router un momento.", exampleEnglish: "I'm going to disconnect the router for a moment." },
  cargar: { example: "Voy a cargar el móvil antes de salir.", exampleEnglish: "I'm going to charge my phone before I leave." },
  descargar: { example: "Necesito descargar la aplicación primero.", exampleEnglish: "I need to download the app first." },
  instalar: { example: "Vamos a instalar el programa nuevo mañana.", exampleEnglish: "We're going to install the new program tomorrow." },
  actualizar: { example: "Tengo que actualizar el sistema esta noche.", exampleEnglish: "I have to update the system tonight." },
  reparar: { example: "El técnico va a reparar la lavadora mañana.", exampleEnglish: "The technician is going to repair the washing machine tomorrow." },
  funcionar: { example: "Espero que la impresora vuelva a funcionar.", exampleEnglish: "I hope the printer works again." },
  seleccionar: { example: "Vamos a seleccionar tres candidatos.", exampleEnglish: "We're going to select three candidates." },
  pulsar: { example: "Solo tienes que pulsar este botón.", exampleEnglish: "You just have to press this button." },
  clicar: { example: "Vas a tener que clicar en el enlace.", exampleEnglish: "You're going to have to click on the link." },
  navegar: { example: "Me gusta navegar por internet por las tardes.", exampleEnglish: "I like browsing the internet in the evenings." },
  eliminar: { example: "Voy a eliminar el correo por error.", exampleEnglish: "I'm going to delete the email by mistake." },
  editar: { example: "Necesito editar estas fotos antes de enviarlas.", exampleEnglish: "I need to edit these photos before sending them." },
  revisar: { example: "Voy a revisar el informe una vez más.", exampleEnglish: "I'm going to review the report one more time." },
  comprobar: { example: "Vamos a comprobar que todo funciona bien.", exampleEnglish: "We're going to check that everything works well." },
  medir: { example: "Necesito medir la puerta antes de comprar la mesa.", exampleEnglish: "I need to measure the door before buying the table." },
  calcular: { example: "Voy a calcular el precio total del viaje.", exampleEnglish: "I'm going to calculate the total cost of the trip." },
  sumar: { example: "Vamos a sumar todos los gastos del mes.", exampleEnglish: "We're going to add up all of this month's expenses." },
  restar: { example: "Tienes que restar el descuento del precio final.", exampleEnglish: "You have to subtract the discount from the final price." },
  multiplicar: { example: "Los niños están aprendiendo a multiplicar.", exampleEnglish: "The children are learning to multiply." },
  dividir: { example: "Vamos a dividir la tarta en ocho trozos.", exampleEnglish: "We're going to divide the cake into eight pieces." },
  ordenar: { example: "Necesito ordenar mi habitación este fin de semana.", exampleEnglish: "I need to tidy my room this weekend." },
  clasificar: { example: "Vamos a clasificar los libros por tema.", exampleEnglish: "We're going to classify the books by topic." },
  agrupar: { example: "Podemos agrupar las preguntas por dificultad.", exampleEnglish: "We can group the questions by difficulty." },
  mezclar: { example: "Vas a mezclar la harina con el azúcar.", exampleEnglish: "You're going to mix the flour with the sugar." },
  separar: { example: "Vamos a separar la ropa de color y la blanca.", exampleEnglish: "We're going to separate the coloured clothes from the white ones." },
  pegar: { example: "Voy a pegar el cartel en la pared.", exampleEnglish: "I'm going to stick the poster on the wall." },
  unir: { example: "Vamos a unir las dos empresas el año que viene.", exampleEnglish: "We're going to merge the two companies next year." },
  llenar: { example: "Voy a llenar la botella de agua.", exampleEnglish: "I'm going to fill the water bottle." },
  vaciar: { example: "Tenemos que vaciar el armario antes de la mudanza.", exampleEnglish: "We have to empty the wardrobe before the move." },
  cubrir: { example: "Vamos a cubrir el jardín con una lona.", exampleEnglish: "We're going to cover the garden with a tarp." },
  pausar: { example: "Voy a pausar la serie y seguir mañana.", exampleEnglish: "I'm going to pause the show and continue tomorrow." },
  reiniciar: { example: "Voy a reiniciar el ordenador para ver si funciona.", exampleEnglish: "I'm going to restart the computer to see if it works." },
  practicar: { example: "Necesito practicar español todos los días.", exampleEnglish: "I need to practise Spanish every day." },
  memorizar: { example: "Tengo que memorizar estos verbos para el examen.", exampleEnglish: "I have to memorize these verbs for the exam." },
  imaginar: { example: "No puedo imaginar la ciudad sin ese parque.", exampleEnglish: "I can't imagine the city without that park." },
  soñar: { example: "Me gusta soñar con viajes largos.", exampleEnglish: "I like to dream about long trips." },
  desear: { example: "Todos podemos desear algo mejor.", exampleEnglish: "We can all wish for something better." },
  evitar: { example: "Prefiero evitar las horas punta en el metro.", exampleEnglish: "I prefer to avoid rush hour on the metro." },
  tener: { example: "Quiero tener más tiempo libre.", exampleEnglish: "I want to have more free time." },
  convertirse: { example: "La idea puede convertirse en un proyecto.", exampleEnglish: "The idea can turn into a project." },
  disminuir: { example: "Las ventas van a disminuir este trimestre.", exampleEnglish: "Sales are going to decrease this quarter." },
  desarrollar: { example: "Vamos a desarrollar una nueva estrategia.", exampleEnglish: "We're going to develop a new strategy." },
  construir: { example: "Van a construir un puente nuevo aquí.", exampleEnglish: "They're going to build a new bridge here." },
  destruir: { example: "La tormenta pudo destruir varias casas.", exampleEnglish: "The storm was able to destroy several houses." },
  fabricar: { example: "Esta fábrica va a fabricar piezas de coche.", exampleEnglish: "This factory is going to manufacture car parts." },
  alquilar: { example: "Queremos alquilar un piso cerca del centro.", exampleEnglish: "We want to rent a flat near the centre." },
  devolver: { example: "Tengo que devolver este libro a la biblioteca.", exampleEnglish: "I have to return this book to the library." },
  prestar: { example: "¿Me puedes prestar tu paraguas?", exampleEnglish: "Can you lend me your umbrella?" },
  mandar: { example: "Voy a mandar la carta esta tarde.", exampleEnglish: "I'm going to send the letter this afternoon." },
  entregar: { example: "Tengo que entregar el proyecto el viernes.", exampleEnglish: "I have to hand in the project on Friday." },
  invertir: { example: "Queremos invertir en un negocio pequeño.", exampleEnglish: "We want to invest in a small business." },
  descansar: { example: "Necesito descansar un poco esta tarde.", exampleEnglish: "I need to rest a little this afternoon." },
  despertar: { example: "El café me va a despertar por fin.", exampleEnglish: "The coffee is finally going to wake me up." },
  sentar: { example: "Voy a sentar al bebé en la trona.", exampleEnglish: "I'm going to sit the baby in the high chair." },
  acostar: { example: "Esta noche voy a acostar a los niños temprano.", exampleEnglish: "Tonight I'm going to put the kids to bed early." },
  vestirse: { example: "Voy a vestirme antes de que lleguen.", exampleEnglish: "I'm going to get dressed before they arrive." },
  desnudar: { example: "La enfermera va a desnudar al paciente para la revisión.", exampleEnglish: "The nurse is going to undress the patient for the check-up." },
  desnudarse: { example: "El niño se va a desnudar para el baño.", exampleEnglish: "The child is going to undress for the bath." },
  lavarse: { example: "Voy a lavarme las manos antes de comer.", exampleEnglish: "I'm going to wash my hands before eating." },
  duchar: { example: "Voy a duchar al perro después del paseo.", exampleEnglish: "I'm going to shower the dog after the walk." },
  bañar: { example: "Voy a bañar al bebé antes de dormir.", exampleEnglish: "I'm going to bathe the baby before bed." },
  peinar: { example: "Voy a peinar a mi hija para el colegio.", exampleEnglish: "I'm going to comb my daughter's hair for school." },
  afeitar: { example: "El barbero va a afeitar al cliente con cuidado.", exampleEnglish: "The barber is going to shave the customer carefully." },
  maquillar: { example: "Mi amiga va a maquillar a la novia el día de la boda.", exampleEnglish: "My friend is going to do the bride's makeup on the wedding day." },
  maquillarse: { example: "Voy a maquillarme antes de la fiesta.", exampleEnglish: "I'm going to put on makeup before the party." },
  desayunar: { example: "Solemos desayunar juntos los domingos.", exampleEnglish: "We usually have breakfast together on Sundays." },
  almorzar: { example: "Vamos a almorzar en aquel restaurante cerca de la oficina.", exampleEnglish: "We're going to have lunch at that restaurant near the office." },
  cenar: { example: "Vamos a cenar temprano hoy.", exampleEnglish: "We're going to have dinner early today." },
  merendar: { example: "A los niños les gusta merendar fruta después del colegio.", exampleEnglish: "The kids like having fruit as an afternoon snack after school." },
  calentar: { example: "Voy a calentar la sopa para la cena.", exampleEnglish: "I'm going to heat up the soup for dinner." },
  enfriar: { example: "Vamos a dejar enfriar el pastel antes de cortarlo.", exampleEnglish: "We're going to let the cake cool before cutting it." },
  hervir: { example: "Voy a hervir agua para el té.", exampleEnglish: "I'm going to boil water for the tea." },
  freír: { example: "Voy a freír unos huevos para el desayuno.", exampleEnglish: "I'm going to fry some eggs for breakfast." },
  hornear: { example: "Vamos a hornear galletas este fin de semana.", exampleEnglish: "We're going to bake cookies this weekend." },
  pelar: { example: "Necesito pelar las patatas para la tortilla.", exampleEnglish: "I need to peel the potatoes for the omelette." },
  echar: { example: "Voy a echar un poco más de sal a la sopa.", exampleEnglish: "I'm going to add a bit more salt to the soup." },
  secar: { example: "Voy a secar la ropa antes de guardarla.", exampleEnglish: "I'm going to dry the clothes before putting them away." },
  planchar: { example: "Tengo que planchar estas camisas para el viaje.", exampleEnglish: "I have to iron these shirts for the trip." },
  barrer: { example: "Voy a barrer la cocina después de cenar.", exampleEnglish: "I'm going to sweep the kitchen after dinner." },
  fregar: { example: "Me toca fregar los platos esta noche.", exampleEnglish: "It's my turn to do the dishes tonight." },
  arreglar: { example: "Necesito arreglar la bicicleta este fin de semana.", exampleEnglish: "I need to fix the bike this weekend." },
  reciclar: { example: "Intentamos reciclar todo el vidrio y el papel.", exampleEnglish: "We try to recycle all the glass and paper." },
  plantar: { example: "Vamos a plantar tomates en el jardín.", exampleEnglish: "We're going to plant tomatoes in the garden." },
  regar: { example: "Necesito regar las plantas antes de irme.", exampleEnglish: "I need to water the plants before I leave." },
  cuidar: { example: "Voy a cuidar del perro de mi vecina este fin de semana.", exampleEnglish: "I'm going to take care of my neighbour's dog this weekend." },
  alimentar: { example: "Es mi turno de alimentar a los peces.", exampleEnglish: "It's my turn to feed the fish." },
  adoptar: { example: "Queremos adoptar un gato del refugio.", exampleEnglish: "We want to adopt a cat from the shelter." },
  criar: { example: "Mis abuelos suelen criar gallinas en el pueblo.", exampleEnglish: "My grandparents usually raise chickens in the village." },
  cazar: { example: "Mi gato solo sale a cazar por la noche.", exampleEnglish: "My cat only goes out to hunt at night." },
  pescar: { example: "A mi padre le gusta pescar los fines de semana.", exampleEnglish: "My father likes fishing on weekends." },
  morder: { example: "Ese perro nunca va a morder a nadie.", exampleEnglish: "That dog is never going to bite anyone." },
  ladrar: { example: "El perro suele ladrar cuando llega alguien.", exampleEnglish: "The dog usually barks when someone arrives." },
  maullar: { example: "El gato empieza a maullar cuando tiene hambre.", exampleEnglish: "The cat starts meowing when it's hungry." },
  fotografiar: { example: "Voy a fotografiar la puesta de sol.", exampleEnglish: "I'm going to photograph the sunset." },
  grabar: { example: "Vamos a grabar el concierto con el móvil.", exampleEnglish: "We're going to record the concert on our phone." },
  filmar: { example: "El equipo va a filmar la escena mañana.", exampleEnglish: "The crew is going to film the scene tomorrow." },
  entrenar: { example: "Suelo entrenar en el gimnasio tres veces por semana.", exampleEnglish: "I usually train at the gym three times a week." },
  competir: { example: "Nuestro equipo va a competir el sábado.", exampleEnglish: "Our team is going to compete on Saturday." },
  empatar: { example: "Los dos equipos van a empatar seguramente.", exampleEnglish: "The two teams are probably going to draw." },
  marcar: { example: "El delantero necesita marcar un gol pronto.", exampleEnglish: "The striker needs to score a goal soon." },
  atrapar: { example: "El portero va a atrapar el balón.", exampleEnglish: "The goalkeeper is going to catch the ball." },
  golpear: { example: "Ten cuidado de no golpear la mesa con la silla.", exampleEnglish: "Be careful not to hit the table with the chair." },
  patear: { example: "El niño va a patear el balón hacia la portería.", exampleEnglish: "The boy is going to kick the ball towards the goal." },
  pedalear: { example: "Vamos a pedalear despacio cuesta arriba.", exampleEnglish: "We're going to pedal slowly uphill." },
  esquiar: { example: "Queremos esquiar en los Pirineos este invierno.", exampleEnglish: "We want to ski in the Pyrenees this winter." },
  patinar: { example: "A mi sobrina le encanta patinar en el parque.", exampleEnglish: "My niece loves skating in the park." },
  escalar: { example: "Vamos a escalar esa montaña el próximo verano.", exampleEnglish: "We're going to climb that mountain next summer." },
  despegar: { example: "El avión va a despegar en diez minutos.", exampleEnglish: "The plane is going to take off in ten minutes." },
  aterrizar: { example: "Vamos a aterrizar en Barcelona sobre las seis.", exampleEnglish: "We're going to land in Barcelona around six." },
  facturar: { example: "Tenemos que facturar las maletas antes de las nueve.", exampleEnglish: "We have to check in the luggage before nine." },
  embarcar: { example: "Vamos a embarcar por la puerta doce.", exampleEnglish: "We're going to board through gate twelve." },
  informar: { example: "Voy a informar al equipo de los cambios.", exampleEnglish: "I'm going to inform the team of the changes." },
  confirmar: { example: "Necesito confirmar la reserva del restaurante.", exampleEnglish: "I need to confirm the restaurant reservation." },
  avisar: { example: "Voy a avisar a mis padres de que llego tarde.", exampleEnglish: "I'm going to let my parents know I'll be late." },
  anunciar: { example: "Van a anunciar los resultados esta tarde.", exampleEnglish: "They're going to announce the results this afternoon." },
  comunicar: { example: "Vamos a comunicar la decisión mañana.", exampleEnglish: "We're going to communicate the decision tomorrow." },
  traducir: { example: "Necesito traducir este documento al inglés.", exampleEnglish: "I need to translate this document into English." },
  pronunciar: { example: "Me cuesta pronunciar algunas palabras en español.", exampleEnglish: "I find it hard to pronounce some words in Spanish." },
  deletrear: { example: "¿Puedes deletrear tu apellido, por favor?", exampleEnglish: "Can you spell your last name, please?" },
  corregir: { example: "El profesor va a corregir los exámenes este fin de semana.", exampleEnglish: "The teacher is going to correct the exams this weekend." },
  aprobar: { example: "Espero aprobar el examen de conducir.", exampleEnglish: "I hope to pass the driving test." },
  suspender: { example: "No quiero suspender esta asignatura.", exampleEnglish: "I don't want to fail this subject." },
  examinar: { example: "El médico va a examinar al paciente ahora.", exampleEnglish: "The doctor is going to examine the patient now." },
  evaluar: { example: "Vamos a evaluar los resultados del proyecto.", exampleEnglish: "We're going to evaluate the project's results." },
  completar: { example: "Necesito completar este formulario hoy.", exampleEnglish: "I need to complete this form today." },
  rellenar: { example: "Tienes que rellenar todos los campos del formulario.", exampleEnglish: "You have to fill in all the fields on the form." },
  investigar: { example: "Vamos a investigar el caso con más detalle.", exampleEnglish: "We're going to investigate the case in more detail." },
  analizar: { example: "Necesitamos analizar los datos antes de decidir.", exampleEnglish: "We need to analyze the data before deciding." },
  experimentar: { example: "Me gusta experimentar con recetas nuevas.", exampleEnglish: "I like experimenting with new recipes." },
  demostrar: { example: "Voy a demostrar que tengo razón.", exampleEnglish: "I'm going to prove that I'm right." },
  concluir: { example: "Vamos a concluir la reunión en cinco minutos.", exampleEnglish: "We're going to conclude the meeting in five minutes." },
  gestionar: { example: "Ella va a gestionar el nuevo equipo.", exampleEnglish: "She is going to manage the new team." },
  liderar: { example: "Va a liderar el proyecto desde enero.", exampleEnglish: "They're going to lead the project starting in January." },
  colaborar: { example: "Vamos a colaborar con otra empresa este año.", exampleEnglish: "We're going to collaborate with another company this year." },
  participar: { example: "Queremos participar en la carrera benéfica.", exampleEnglish: "We want to take part in the charity race." },
  asistir: { example: "Voy a asistir a la conferencia el jueves.", exampleEnglish: "I'm going to attend the conference on Thursday." },
  proponer: { example: "Voy a proponer una idea nueva en la reunión.", exampleEnglish: "I'm going to propose a new idea at the meeting." },
  negociar: { example: "Vamos a negociar el precio del coche.", exampleEnglish: "We're going to negotiate the price of the car." },
  contratar: { example: "La empresa va a contratar a dos personas más.", exampleEnglish: "The company is going to hire two more people." },
  despedir: { example: "No quiero despedir a nadie del equipo.", exampleEnglish: "I don't want to fire anyone from the team." },
  emplear: { example: "Esta fábrica va a emplear a cien trabajadores.", exampleEnglish: "This factory is going to employ a hundred workers." },
  solicitar: { example: "Voy a solicitar el puesto de gerente.", exampleEnglish: "I'm going to apply for the manager position." },
  contactar: { example: "Voy a contactar con el proveedor mañana.", exampleEnglish: "I'm going to contact the supplier tomorrow." },
  apoyar: { example: "Vamos a apoyar tu decisión pase lo que pase.", exampleEnglish: "We're going to support your decision no matter what." },
  resolver: { example: "Tenemos que resolver este problema hoy.", exampleEnglish: "We have to solve this problem today." },
  solucionar: { example: "Vamos a solucionar el error cuanto antes.", exampleEnglish: "We're going to fix the bug as soon as possible." },
  implementar: { example: "Vamos a implementar los cambios la próxima semana.", exampleEnglish: "We're going to implement the changes next week." },
  diseñar: { example: "Vamos a diseñar el logo de la empresa.", exampleEnglish: "We're going to design the company logo." },
  programar: { example: "Voy a programar una nueva función esta semana.", exampleEnglish: "I'm going to program a new feature this week." },
  depurar: { example: "Necesito depurar este código antes de publicarlo.", exampleEnglish: "I need to debug this code before publishing it." },
  desplegar: { example: "Vamos a desplegar la nueva versión esta noche.", exampleEnglish: "We're going to deploy the new version tonight." },
  documentar: { example: "Voy a documentar los cambios en el manual.", exampleEnglish: "I'm going to document the changes in the manual." },
  planificar: { example: "Necesitamos planificar mejor la semana.", exampleEnglish: "We need to plan the week better." },
  estimar: { example: "Vamos a estimar el coste total del proyecto.", exampleEnglish: "We're going to estimate the total cost of the project." },
  priorizar: { example: "Tenemos que priorizar las tareas más urgentes.", exampleEnglish: "We have to prioritize the most urgent tasks." },
  asignar: { example: "Voy a asignar esta tarea a Marta.", exampleEnglish: "I'm going to assign this task to Marta." },
  monitorizar: { example: "Vamos a monitorizar el servidor toda la noche.", exampleEnglish: "We're going to monitor the server all night." },
  controlar: { example: "Necesito controlar mejor mis gastos.", exampleEnglish: "I need to control my spending better." },
  asegurar: { example: "Voy a asegurar que todo esté listo mañana.", exampleEnglish: "I'm going to make sure everything is ready tomorrow." },
  proteger: { example: "Queremos proteger la playa de la contaminación.", exampleEnglish: "We want to protect the beach from pollution." },
  bloquear: { example: "Voy a bloquear este número desconocido.", exampleEnglish: "I'm going to block this unknown number." },
  desbloquear: { example: "Necesito desbloquear el móvil con la huella.", exampleEnglish: "I need to unlock the phone with my fingerprint." },
  registrarse: { example: "Tienes que registrarte antes de entrar.", exampleEnglish: "You have to register before entering." },
  iniciar: { example: "Vamos a iniciar la reunión en cinco minutos.", exampleEnglish: "We're going to start the meeting in five minutes." },
  acceder: { example: "No consigo acceder a mi cuenta.", exampleEnglish: "I can't manage to access my account." },
  denegar: { example: "El banco puede denegar la solicitud.", exampleEnglish: "The bank might deny the request." },
  recuperar: { example: "Voy a intentar recuperar los archivos borrados.", exampleEnglish: "I'm going to try to recover the deleted files." },
  renombrar: { example: "Voy a renombrar esta carpeta.", exampleEnglish: "I'm going to rename this folder." },
  sincronizar: { example: "Necesito sincronizar el calendario con el móvil.", exampleEnglish: "I need to sync the calendar with my phone." },
  exportar: { example: "Voy a exportar los datos a una hoja de cálculo.", exampleEnglish: "I'm going to export the data to a spreadsheet." },
  filtrar: { example: "Vamos a filtrar los resultados por fecha.", exampleEnglish: "We're going to filter the results by date." },
  desmarcar: { example: "Voy a desmarcar esta casilla por error.", exampleEnglish: "I'm going to accidentally uncheck this box." },
  avanzar: { example: "Vamos a avanzar despacio con este plan.", exampleEnglish: "We're going to move forward slowly with this plan." },
  retroceder: { example: "Vamos a retroceder un poco en el vídeo.", exampleEnglish: "We're going to go back a bit in the video." },
  ocultar: { example: "No quiero ocultar la verdad por más tiempo.", exampleEnglish: "I don't want to hide the truth any longer." },
  expandir: { example: "Queremos expandir el negocio a otras ciudades.", exampleEnglish: "We want to expand the business to other cities." },
  contraer: { example: "El panel se va a contraer al hacer clic.", exampleEnglish: "The panel is going to collapse when clicked." },
  activar: { example: "Necesito activar las notificaciones del correo.", exampleEnglish: "I need to activate the email notifications." },
  desactivar: { example: "Voy a desactivar la alarma antes de entrar.", exampleEnglish: "I'm going to deactivate the alarm before going in." },
  configurar: { example: "Voy a configurar el router esta tarde.", exampleEnglish: "I'm going to configure the router this afternoon." },
  ajustar: { example: "Necesito ajustar el volumen de la tele.", exampleEnglish: "I need to adjust the TV volume." },
  restablecer: { example: "Voy a restablecer la contraseña de mi cuenta.", exampleEnglish: "I'm going to reset my account password." },
  duplicar: { example: "Voy a duplicar esta hoja de cálculo.", exampleEnglish: "I'm going to duplicate this spreadsheet." },
  arrastrar: { example: "Solo tienes que arrastrar el archivo a esta carpeta.", exampleEnglish: "You just have to drag the file into this folder." },
  soltar: { example: "Puedes soltar el ratón ahora.", exampleEnglish: "You can release the mouse now." },
  deslizar: { example: "Tienes que deslizar el dedo hacia la derecha.", exampleEnglish: "You have to swipe your finger to the right." },
  acercar: { example: "Voy a acercar la imagen para ver mejor.", exampleEnglish: "I'm going to zoom in on the image to see better." },
  alejar: { example: "Vamos a alejar el mapa un poco.", exampleEnglish: "We're going to zoom out on the map a bit." },
  escanear: { example: "Necesito escanear estos documentos hoy.", exampleEnglish: "I need to scan these documents today." },
  archivar: { example: "Voy a archivar estos correos antiguos.", exampleEnglish: "I'm going to archive these old emails." },
  mencionar: { example: "Quiero mencionar tu ayuda en el informe.", exampleEnglish: "I want to mention your help in the report." },
  notificar: { example: "Vamos a notificar el cambio a todos los clientes.", exampleEnglish: "We're going to notify all customers of the change." },
  suscribir: { example: "Voy a suscribir a mi hijo al club de fútbol.", exampleEnglish: "I'm going to sign my son up for the football club." },
  renovar: { example: "Tengo que renovar el pasaporte este año.", exampleEnglish: "I have to renew my passport this year." },
  vencer: { example: "El contrato va a vencer en marzo.", exampleEnglish: "The contract is going to expire in March." },
  caducar: { example: "Esta leche va a caducar mañana.", exampleEnglish: "This milk is going to expire tomorrow." },
  reclamar: { example: "Voy a reclamar por el retraso del vuelo.", exampleEnglish: "I'm going to file a complaint about the flight delay." },
  reembolsar: { example: "La tienda va a reembolsar el importe completo.", exampleEnglish: "The shop is going to refund the full amount." },
  donar: { example: "Queremos donar ropa a la asociación local.", exampleEnglish: "We want to donate clothes to the local charity." },
  regalar: { example: "Voy a regalar un libro a mi sobrina.", exampleEnglish: "I'm going to give my niece a book as a gift." },
  inspeccionar: { example: "El técnico va a inspeccionar la instalación eléctrica.", exampleEnglish: "The technician is going to inspect the electrical wiring." },
  pesar: { example: "Voy a pesar la maleta antes de salir.", exampleEnglish: "I'm going to weigh the suitcase before I leave." },
  registrar: { example: "Vamos a registrar la nueva dirección en el sistema.", exampleEnglish: "We're going to register the new address in the system." },
  vigilar: { example: "El guardia va a vigilar el edificio esta noche.", exampleEnglish: "The guard is going to watch the building tonight." },
  denunciar: { example: "Vamos a denunciar el robo a la policía.", exampleEnglish: "We're going to report the theft to the police." },
  rescatar: { example: "Los bomberos van a rescatar al gato del árbol.", exampleEnglish: "The firefighters are going to rescue the cat from the tree." },
  salvar: { example: "El médico pudo salvar al paciente a tiempo.", exampleEnglish: "The doctor was able to save the patient in time." },
  atacar: { example: "El equipo va a atacar con más fuerza en la segunda parte.", exampleEnglish: "The team is going to attack harder in the second half." },
  defender: { example: "Voy a defender mi punto de vista en la reunión.", exampleEnglish: "I'm going to defend my point of view at the meeting." },
  luchar: { example: "Vamos a luchar por mantener nuestros derechos.", exampleEnglish: "We're going to fight to keep our rights." },
  matar: { example: "Ese producto puede matar las plantas si usas demasiado.", exampleEnglish: "That product can kill the plants if you use too much." },
  herir: { example: "No quiero herir tus sentimientos.", exampleEnglish: "I don't want to hurt your feelings." },
  curar: { example: "Este jarabe va a curar la tos en unos días.", exampleEnglish: "This syrup is going to cure the cough in a few days." },
  sanar: { example: "Espero sanar pronto de esta gripe.", exampleEnglish: "I hope to recover from this flu soon." },
  diagnosticar: { example: "El médico va a diagnosticar el problema mañana.", exampleEnglish: "The doctor is going to diagnose the problem tomorrow." },
  recetar: { example: "El médico me va a recetar unas pastillas.", exampleEnglish: "The doctor is going to prescribe me some pills." },
  respirar: { example: "Necesito respirar aire fresco un momento.", exampleEnglish: "I need to breathe some fresh air for a moment." },
  toser: { example: "Empezó a toser mucho durante la reunión.", exampleEnglish: "Someone started coughing a lot during the meeting." },
  estornudar: { example: "El polen me hace estornudar todo el día.", exampleEnglish: "Pollen makes me sneeze all day." },
  sangrar: { example: "La herida va a sangrar un poco al principio.", exampleEnglish: "The wound is going to bleed a little at first." },
  suceder: { example: "Algo parecido puede suceder otra vez.", exampleEnglish: "Something similar can happen again." },
  pertenecer: { example: "Este libro puede pertenecer a Ana.", exampleEnglish: "This book might belong to Ana." },
  depender: { example: "Todo puede depender del tiempo.", exampleEnglish: "Everything can depend on the weather." },
  significar: { example: "Esa palabra puede significar varias cosas.", exampleEnglish: "That word can mean several things." },
  representar: { example: "Este símbolo puede representar la libertad.", exampleEnglish: "This symbol can represent freedom." },
  establecer: { example: "Vamos a establecer nuevas normas para el equipo.", exampleEnglish: "We're going to establish new rules for the team." },
  celebrar: { example: "Vamos a celebrar su cumpleaños el sábado.", exampleEnglish: "We're going to celebrate his birthday on Saturday." },
  aprovechar: { example: "Quiero aprovechar el buen tiempo este fin de semana.", exampleEnglish: "I want to take advantage of the good weather this weekend." },
  manejar: { example: "Todavía no sé manejar bien esta herramienta.", exampleEnglish: "I still don't know how to handle this tool well." },
  admitir: { example: "Tengo que admitir que me equivoqué.", exampleEnglish: "I have to admit that I was wrong." },
  abandonar: { example: "No quiero abandonar el proyecto ahora.", exampleEnglish: "I don't want to abandon the project now." },
  aplicar: { example: "Voy a aplicar los mismos cambios al otro archivo.", exampleEnglish: "I'm going to apply the same changes to the other file." },
  causar: { example: "Ese ruido puede causar problemas en el vecindario.", exampleEnglish: "That noise can cause problems in the neighbourhood." },
  conceder: { example: "El banco va a conceder el préstamo la próxima semana.", exampleEnglish: "The bank is going to grant the loan next week." },
  conservar: { example: "Queremos conservar esta tradición familiar.", exampleEnglish: "We want to preserve this family tradition." },
  contener: { example: "Esta caja puede contener hasta veinte kilos.", exampleEnglish: "This box can hold up to twenty kilos." },
  contribuir: { example: "Todos queremos contribuir a este proyecto.", exampleEnglish: "We all want to contribute to this project." },
  desaparecer: { example: "El sol va a desaparecer detrás de las montañas.", exampleEnglish: "The sun is going to disappear behind the mountains." },
  exigir: { example: "Los clientes van a exigir una explicación.", exampleEnglish: "The customers are going to demand an explanation." },
  expresar: { example: "Quiero expresar mi agradecimiento a todos.", exampleEnglish: "I want to express my gratitude to everyone." },
  indicar: { example: "El cartel va a indicar el camino correcto.", exampleEnglish: "The sign is going to indicate the right way." },
};
