import type { Question } from "./quiz-data";

/** Filter values for this quiz. They live in `infinitive`, the field the shared
 * second filter already matches on, so the existing picker filters by pronoun type. */
export const OBJECT_PRONOUN_TYPES = ["direct object", "indirect object", "double pronouns"] as const;
export type ObjectPronounType = (typeof OBJECT_PRONOUN_TYPES)[number];

type Seed = readonly [
  type: ObjectPronounType,
  before: string,
  after: string,
  answer: string,
  distractor: string,
  en: string,
  level: Question["level"],
  explanation: string,
  /** Only for attachment items: the bare gerund/infinitive shown in the blank. */
  blankHint?: string,
];

const seed: readonly Seed[] = [
  // --- Direct object: lo, la, los, las before a conjugated verb ---
  ["direct object", "¿El café? Yo", "tomo sin azúcar.", "lo", "la", "The coffee? I drink it without sugar.", "basic", "A direct object pronoun copies the gender and number of the noun it replaces. El café is masculine singular, so it becomes lo. La would only replace a feminine noun, like la leche."],
  ["direct object", "¿La sopa? Mi hijo nunca", "come.", "la", "lo", "The soup? My son never eats it.", "basic", "A direct object pronoun agrees with the noun it replaces, and la sopa is feminine singular, so it becomes la. Lo is for masculine nouns, like el pan."],
  ["direct object", "¿Los zapatos nuevos? Ana", "lleva hoy.", "los", "las", "The new shoes? Ana is wearing them today.", "basic", "Direct object pronouns match the gender and number of the noun. Zapatos is masculine plural (los zapatos), so the pronoun is los. Las would replace a feminine plural noun, like las botas."],
  ["direct object", "¿Las llaves? Pablo", "tiene en el bolsillo.", "las", "los", "The keys? Pablo has them in his pocket.", "basic", "The pronoun takes the gender of the thing, not of the person who has it. Llaves is feminine plural (las llaves), so it is las, even though Pablo is a man."],
  ["direct object", "Compré una revista y", "leí en el tren.", "la", "lo", "I bought a magazine and read it on the train.", "basic", "Ask what did I read? The answer, una revista, is the direct object. It is feminine singular, so the pronoun is la. Lo would need a masculine noun, like un periódico."],
  ["direct object", "Tengo dos entradas, pero no", "necesito.", "las", "los", "I have two tickets, but I don't need them.", "basic", "Entradas is feminine plural (las entradas), so the pronoun is las. Los would need a masculine noun, like los billetes. Note the order: no, then the pronoun, then the verb (no las necesito)."],
  ["direct object", "¿Dónde está el mando? No", "encuentro.", "lo", "la", "Where is the remote? I can't find it.", "basic", "The noun the pronoun replaces is in the previous sentence: el mando. It is masculine singular, so the pronoun is lo. La would need a feminine noun, like la llave."],
  ["direct object", "Esta película es muy buena; yo", "vi el sábado.", "la", "lo", "This film is very good; I saw it on Saturday.", "basic", "Película takes la, so it is feminine singular and the pronoun is la. Lo would mean you saw something masculine, such as el partido."],
  ["direct object", "Hay galletas en la mesa, pero los niños no", "quieren.", "las", "los", "There are biscuits on the table, but the children don't want them.", "basic", "Galletas is feminine plural, so the pronoun is las. Don't be misled by los niños just before the blank: the pronoun agrees with what is wanted (the biscuits), not with who wants it."],
  ["direct object", "¿Los deberes? Ya", "terminé.", "los", "les", "The homework? I already finished it.", "basic", "Ask what did I finish? The answer, los deberes, is a thing, so it is a direct object: los (masculine plural). Les is an indirect object pronoun, used for people who receive something."],
  ["direct object", "El pan está duro; ¿por qué no", "tiras?", "lo", "la", "The bread is hard; why don't you throw it away?", "basic", "El pan is masculine singular, so the pronoun is lo. La would need a feminine noun, like la fruta. In a negative question the order is still no + pronoun + verb: ¿por qué no lo tiras?"],
  ["direct object", "La maleta ya está lista; mi padre", "lleva al coche.", "la", "lo", "The suitcase is ready; my father is taking it to the car.", "basic", "La maleta is feminine singular, so the pronoun is la. Mi padre is masculine, but that doesn't matter: the pronoun agrees with the thing carried, not with the person carrying it."],
  ["direct object", "¿El coche? Carlos", "aparca siempre en la calle.", "lo", "la", "The car? Carlos always parks it on the street.", "basic", "Coche ends in -e, so the ending doesn't tell you the gender; the article does. El coche is masculine singular, so the pronoun is lo. La would need a feminine noun, like la moto."],
  ["direct object", "¿Tienes las gafas? No,", "dejé en casa.", "las", "los", "Do you have the glasses? No, I left them at home.", "basic", "Gafas is always plural in Spanish (las gafas), even for one pair, so the pronoun is las. Los would only work for a masculine plural noun, like los guantes."],
  ["direct object", "¿Quieres probar estas manzanas? Yo ya", "probé.", "las", "los", "Do you want to try these apples? I already tried them.", "basic", "The demonstrative estas shows that manzanas is feminine plural, so the pronoun is las. Los would need a masculine noun, like estos plátanos."],
  ["direct object", "Hice una tarta y mis amigos", "probaron enseguida.", "la", "lo", "I made a cake and my friends tried it straight away.", "basic", "Una tarta is feminine singular (una, not un), so the pronoun is la. Mis amigos is the subject doing the tasting, so it doesn't affect the pronoun."],
  ["direct object", "¿Las noticias? Siempre", "escuchamos en la radio.", "las", "les", "The news? We always listen to it on the radio.", "basic", "Las noticias is plural in Spanish (unlike news in English) and it is the thing we listen to, so the direct pronoun is las. Les is an indirect pronoun for people who receive something, never for things."],

  // --- Direct object: people (me, te, lo, la, nos, los, las) ---
  ["direct object", "Mi abuela me llama y yo", "visito los domingos.", "la", "lo", "My grandmother calls me and I visit her on Sundays.", "intermediate", "Visitar a alguien takes a direct object: you visit someone, not to someone. Mi abuela is feminine singular, so the pronoun is la. Lo would be for a man, like mi abuelo."],
  ["direct object", "Juan está en la estación. ¿Tú", "recoges?", "lo", "la", "Juan is at the station. Will you pick him up?", "intermediate", "Recoger a alguien takes a direct object: you pick someone up. Juan is a man, so the pronoun is lo. La would be for a woman, like Ana."],
  ["direct object", "¿Me oyes bien? —Sí,", "oigo perfectamente.", "te", "me", "Can you hear me well? —Yes, I can hear you perfectly.", "basic", "In a reply, the roles swap. ¿Me oyes? asks about me; in the answer the person heard is you (tú), so the pronoun is te. Me would mean I can hear myself."],
  ["direct object", "Cuando llegamos tarde, el profesor", "mira con cara seria.", "nos", "los", "When we arrive late, the teacher looks at us with a serious face.", "intermediate", "The verb llegamos shows the speaker means nosotros, so the people the teacher looks at are us: nos. Los would mean them, a different group."],
  ["direct object", "Mis padres", "quieren mucho.", "me", "mi", "My parents love me a lot.", "basic", "Me is the object pronoun for yo. Mí is only used after a preposition (a mí, para mí)."],
  ["direct object", "Mis primos viven lejos y casi nunca", "veo.", "los", "las", "My cousins live far away and I almost never see them.", "basic", "Primos is masculine plural, so the pronoun is los. A mixed group of male and female cousins also takes the masculine: los primos, los. Las would only fit a group of all women, like mis primas."],
  ["direct object", "Ana y Lucía", "invitaron a su boda.", "nos", "los", "Ana and Lucía invited us to their wedding.", "intermediate", "Invitar a alguien takes a direct object, and the people invited are us, so the pronoun is nos. Ana y Lucía are the subject doing the inviting, so they don't decide the pronoun. Los would mean them."],
  ["direct object", "Mi hermana es muy simpática; todos", "adoran.", "la", "le", "My sister is very friendly; everyone adores her.", "intermediate", "Adorar a alguien takes a direct object, so you choose from lo, la, los or las, not le. Mi hermana is feminine singular, so it is la. Le is for indirect objects, the person who receives something."],
  ["direct object", "Si tienes problemas, yo", "ayudo.", "te", "ti", "If you have problems, I'll help you.", "basic", "The person helped is you, so the pronoun is te. Ti only appears after a preposition."],
  ["direct object", "Cuando éramos pequeños, nuestros abuelos", "llevaban al parque.", "nos", "los", "When we were little, our grandparents took us to the park.", "intermediate", "Éramos (we were) shows the speaker is talking about us, so the people taken to the park are us: nos. Los would mean other people (them)."],
  ["direct object", "¿Me esperas? —Sí,", "espero en la puerta.", "te", "me", "Will you wait for me? —Yes, I'll wait for you at the door.", "basic", "The question ¿Me esperas? asks about waiting for me. In the answer the roles swap: the speaker waits for you, so the pronoun is te. Me would mean waiting for yourself."],
  ["direct object", "Nuestros amigos", "llaman cada semana.", "nos", "los", "Our friends call us every week.", "basic", "The friends call us, so the pronoun is nos. Don't let nuestros amigos pull you toward los: they are the subject, the ones doing the calling, not the people called."],

  // --- Direct object: placement with haber, estar + gerund and ir a + infinitive ---
  ["direct object", "¿Las fotos? Todavía no", "he visto.", "las", "los", "The photos? I still haven't seen them.", "intermediate", "In a compound tense the pronoun goes before haber: no las he visto. Las fotos is feminine plural."],
  ["direct object", "¿El correo de Sonia? Ya", "he leído.", "lo", "le", "Sonia's email? I've already read it.", "intermediate", "El correo is a masculine singular direct object, so lo goes before haber: lo he leído."],
  ["direct object", "¿Y la carta? Nadie", "ha abierto.", "la", "lo", "And the letter? Nobody has opened it.", "intermediate", "La carta is feminine singular, so la goes before haber: la ha abierto."],
  ["direct object", "¿Los platos? Mi hermano ya", "ha lavado.", "los", "las", "The dishes? My brother has already washed them.", "intermediate", "Los platos is masculine plural, so los goes before haber: los ha lavado."],
  ["direct object", "Ese chico", "está mirando desde la ventana.", "te", "ti", "That guy is looking at you from the window.", "intermediate", "With estar + gerund the pronoun can go before estar: te está mirando (or está mirándote)."],
  ["direct object", "¿El partido? Nosotros", "estamos viendo en casa de Luis.", "lo", "le", "The match? We're watching it at Luis's place.", "intermediate", "El partido is a masculine singular direct object. It can go before estar: lo estamos viendo."],
  ["direct object", "¿Las flores? Mi madre", "va a poner en la mesa.", "las", "los", "The flowers? My mother is going to put them on the table.", "intermediate", "With ir a + infinitive the pronoun can go before the conjugated verb: las va a poner (or va a ponerlas)."],

  // --- Direct object: attached to a gerund or infinitive ---
  ["direct object", "¿El libro? Estoy", "ahora mismo.", "leyéndolo", "leyendolo", "The book? I'm reading it right now.", "intermediate", "A pronoun can attach to a gerund: leyendo + lo = leyéndolo. The written accent keeps the stress on the same syllable.", "leyendo"],
  ["direct object", "¿La cena? Mi padre está", "en la cocina.", "preparándola", "preparándolo", "Dinner? My father is making it in the kitchen.", "intermediate", "The pronoun replaces la cena, which is feminine, so it must be la: preparándola. Preparándolo would mean preparing something masculine, like el desayuno.", "preparando"],
  ["direct object", "¿Los ejercicios? Seguimos", "con el profesor.", "haciéndolos", "haciéndolas", "The exercises? We're still doing them with the teacher.", "advanced", "Ejercicios takes los, so the pronoun is los: haciéndolos. Haciéndolas would need a feminine noun, like las tareas. The accent keeps the stress on -cien-.", "haciendo"],
  ["direct object", "¿Las camisas? Estoy", "ahora.", "planchándolas", "planchandolas", "The shirts? I'm ironing them now.", "intermediate", "Planchando + las = planchándolas. Attaching a pronoun to a gerund always needs a written accent.", "planchando"],
  ["direct object", "¿Tu hermano? Estoy", "ahora mismo.", "llamándolo", "llamandolo", "Your brother? I'm calling him right now.", "intermediate", "Llamando + lo = llamándolo. The accent keeps the stress on -man-.", "llamando"],
  ["direct object", "¿Esta chaqueta? Quiero", "hoy.", "comprarla", "comprarlo", "This jacket? I want to buy it today.", "intermediate", "After an infinitive the pronoun attaches to the end: comprar + la = comprarla. One pronoun on an infinitive needs no accent.", "comprar"],
  ["direct object", "¿Los documentos? Tienes que", "antes del viernes.", "firmarlos", "firmarlas", "The documents? You have to sign them before Friday.", "intermediate", "Los documentos is masculine plural, so los attaches to the infinitive: firmarlos. Firmarlas would need a feminine noun, like las cartas. You can also put it in front: los tienes que firmar.", "firmar"],
  ["direct object", "Mi amiga llega a las seis y voy a", "al aeropuerto.", "buscarla", "buscarle", "My friend arrives at six and I'm going to pick her up at the airport.", "intermediate", "Buscar a alguien (to pick someone up) takes a direct object, so the pronoun comes from lo, la, los or las. Mi amiga is a woman, so it is buscarla. Le is for indirect objects, such as the person something is given to.", "buscar"],
  ["direct object", "¿El piso? Van a", "el mes que viene.", "venderlo", "venderla", "The flat? They're going to sell it next month.", "intermediate", "El piso is masculine singular, so lo attaches to the infinitive: venderlo. Venderla would need a feminine noun, like la casa. You could also say lo van a vender.", "vender"],

  // --- Direct object: neuter lo and a fronted object repeated by a pronoun ---
  ["direct object", "¿Sabes que Carla se muda? —Sí, ya", "sé.", "lo", "la", "Do you know that Carla is moving? —Yes, I already know.", "intermediate", "Lo can stand for a whole idea: here it replaces that Carla is moving. Ideas are always lo."],
  ["direct object", "¿Es verdad que cierran el museo? —No", "creo.", "lo", "la", "Is it true that they're closing the museum? —I don't think so.", "advanced", "Neuter lo replaces the whole statement that they're closing the museum: no lo creo."],
  ["direct object", "A su hermana", "vi ayer en el mercado.", "la", "le", "I saw his sister yesterday at the market.", "advanced", "When the direct object comes before the verb, Spanish repeats it with a pronoun: a su hermana la vi."],
  ["direct object", "Los tomates", "compré en el mercado.", "los", "las", "I bought the tomatoes at the market.", "advanced", "A direct object placed before the verb is repeated with a pronoun: los tomates los compré."],
  ["direct object", "Esa canción", "canta todo el mundo.", "la", "le", "Everyone sings that song.", "advanced", "Esa canción is the direct object placed first, so la repeats it: esa canción la canta todo el mundo."],

  // --- Indirect object: me, te, le, nos, les before a conjugated verb ---
  ["indirect object", "Mañana es el cumpleaños de mi madre y", "voy a regalar flores.", "le", "la", "Tomorrow is my mother's birthday and I'm going to give her flowers.", "basic", "Ask to whom am I giving the flowers? To my mother. The person who receives something is the indirect object, so the pronoun is le. La is a direct object pronoun, which would make your mother the thing being given."],
  ["indirect object", "¿Qué", "vas a decir a tu jefe?", "le", "lo", "What are you going to tell your boss?", "intermediate", "Tu jefe receives the message, so the indirect pronoun is le. A tu jefe clarifies who le refers to."],
  ["indirect object", "Mis alumnos", "escriben correos a menudo.", "me", "mi", "My students often write emails to me.", "basic", "Escribir algo a alguien: the emails are written to me, so I am the indirect object: me. Mi without an accent means my, and mí with an accent only follows a preposition (a mí)."],
  ["indirect object", "¿Quién", "explicó la lección a los niños?", "les", "los", "Who explained the lesson to the children?", "intermediate", "A los niños receives the explanation, so the plural indirect pronoun is les, even with a los niños also in the sentence."],
  ["indirect object", "Ana", "prestó su bicicleta a Carlos.", "le", "lo", "Ana lent her bike to Carlos.", "intermediate", "Prestar algo a alguien: the thing lent (su bicicleta) is the direct object, and the person who gets it (Carlos) is the indirect object. The indirect pronoun for one person is le; lo would make Carlos the thing being lent."],
  ["indirect object", "Cuando viajo,", "mando postales a mis padres.", "les", "los", "When I travel, I send postcards to my parents.", "basic", "Mandar algo a alguien: postales is what is sent, mis padres is who receives it. People who receive something take the indirect pronoun, so it is les. Los is a direct pronoun, so it would mean you post your parents themselves."],
  ["indirect object", "¿Tu hermano", "devolvió el dinero?", "te", "ti", "Did your brother give the money back to you?", "basic", "The money comes back to you, so you are the indirect object: te. Ti only appears after a preposition (a ti, para ti), never on its own before a verb."],
  ["indirect object", "El camarero", "trajo la cuenta.", "nos", "los", "The waiter brought us the bill.", "basic", "Traer algo a alguien: la cuenta is what is brought, and we are the ones who get it, so the indirect pronoun is nos. Los is wrong twice: it is a direct pronoun and it means them, not us."],
  ["indirect object", "Siempre", "cuento mis secretos a mi mejor amiga.", "le", "la", "I always tell my secrets to my best friend.", "intermediate", "Mi mejor amiga is the person told, so she is the indirect object: le, for women as well as men."],
  ["indirect object", "La profesora", "preguntó a los estudiantes por el examen.", "les", "los", "The teacher asked the students about the exam.", "intermediate", "Preguntar a alguien takes an indirect object. Los estudiantes are plural, so the pronoun is les."],
  ["indirect object", "Tengo frío; ¿tú", "puedes dar una manta?", "me", "mi", "I'm cold; can you give me a blanket?", "basic", "Dar algo a alguien: the blanket is the direct object, and I am the one who gets it, so the indirect pronoun is me. Mi without an accent means my, so it can't stand before a verb."],
  ["indirect object", "El médico", "recetó unas pastillas a mi padre.", "le", "lo", "The doctor prescribed some pills for my father.", "intermediate", "Recetar algo a alguien: unas pastillas is what is prescribed (direct object), mi padre is who gets it (indirect object). The indirect pronoun for one person is le; lo would make your father the thing prescribed."],
  ["indirect object", "¿Qué", "pasa a Lucía? Está muy callada.", "le", "la", "What's wrong with Lucía? She's very quiet.", "intermediate", "Pasar works like gustar here: the thing that happens is the subject, and the person it happens to is the indirect object. So it is ¿qué le pasa a Lucía?, with le even though Lucía is a woman. La would be a direct object pronoun."],
  ["indirect object", "Los vecinos", "pidieron silencio a los estudiantes del piso de arriba.", "les", "los", "The neighbours asked the students upstairs to be quiet.", "intermediate", "Pedir algo a alguien: silencio is what is asked for, the students are who it is asked of. Pedir always treats the person as an indirect object, so the plural pronoun is les, not los."],
  ["indirect object", "Yo", "escribo todos los días, pero tú nunca contestas.", "te", "ti", "I write to you every day, but you never answer.", "basic", "Escribir a alguien: the person written to is the indirect object, so tú becomes te. Ti only appears after a preposition, as in te escribo a ti."],
  ["indirect object", "Nuestros padres", "dieron una sorpresa el fin de semana.", "nos", "los", "Our parents gave us a surprise at the weekend.", "basic", "Dar algo a alguien: una sorpresa is what is given, and we receive it, so the indirect pronoun is nos. Los would mean them, and it is a direct pronoun, not an indirect one."],
  ["indirect object", "Cuando llegó el cartero,", "di una propina.", "le", "lo", "When the postman arrived, I gave him a tip.", "basic", "Dar algo a alguien: una propina is what is given (direct object), the postman is who gets it (indirect object). For one person the indirect pronoun is le; lo would make the postman the thing given."],
  ["indirect object", "¿Por qué no", "compras un regalo a tu hermana?", "le", "la", "Why don't you buy your sister a present?", "intermediate", "Comprar algo a alguien (to buy something for someone): the present is the direct object and tu hermana is the indirect object. Indirect pronouns don't change for gender, so it is le, not la."],
  ["indirect object", "A mis hijos", "encanta el helado.", "les", "los", "My children love ice cream.", "basic", "Encantar works like gustar: the people who love it are the indirect object, so the plural pronoun is les."],
  ["indirect object", "A nosotros", "interesa mucho la historia.", "nos", "los", "We're very interested in history.", "basic", "Interesar works like gustar. A nosotros points to us, so the indirect pronoun is nos."],
  ["indirect object", "¿Ya", "mandaste las fotos a tus primos?", "les", "los", "Did you already send the photos to your cousins?", "intermediate", "Mandar algo a alguien: las fotos is what is sent, tus primos are who receive it. Receivers are indirect objects, so the plural pronoun is les. Los would replace a masculine plural thing being sent."],
  ["indirect object", "El jefe", "ofreció un contrato nuevo a Elena.", "le", "la", "The boss offered Elena a new contract.", "intermediate", "Ofrecer algo a alguien: un contrato is what is offered, Elena is who gets the offer. Indirect pronouns don't show gender, so it is le even for a woman; la would treat Elena as the thing offered."],
  ["indirect object", "La tienda", "devolvió el dinero a los clientes.", "les", "los", "The shop gave the customers their money back.", "intermediate", "Devolver algo a alguien: el dinero is the direct object, the customers are the indirect object. The plural indirect pronoun is les; los would replace a plural thing being returned."],
  ["indirect object", "Mi novio siempre", "trae flores.", "me", "mi", "My boyfriend always brings me flowers.", "basic", "Traer algo a alguien: the flowers are brought, and I am the one who gets them, so the indirect pronoun is me. Mi without an accent means my (mi novio), so it can't stand before a verb."],
  ["indirect object", "Ella nunca", "dice mentiras a sus amigos.", "les", "los", "She never tells her friends lies.", "intermediate", "Decir algo a alguien: mentiras is what is told (direct object), sus amigos are who it is told to (indirect object). The plural indirect pronoun is les; los would replace a masculine plural thing."],
  ["indirect object", "El guía", "está explicando la historia del castillo a los turistas.", "les", "los", "The guide is explaining the history of the castle to the tourists.", "intermediate", "The tourists receive the explanation, so the pronoun is les. With estar + gerund it can go before estar."],
  ["indirect object", "¿Qué", "regalaste a tu novia por su cumpleaños?", "le", "la", "What did you give your girlfriend for her birthday?", "intermediate", "Regalar algo a alguien: the present is the direct object, tu novia is the indirect object. Le is used for men and women alike, so it is le, not la."],
  ["indirect object", "Cuando era niño, mi madre", "leía cuentos cada noche.", "me", "mi", "When I was a child, my mother read me stories every night.", "basic", "Leer algo a alguien: los cuentos are what is read, and I am the one they are read to, so the indirect pronoun is me. Mi without an accent means my and can't replace a person."],
  ["indirect object", "¿Ya", "contaste a tus padres lo del viaje?", "les", "los", "Have you told your parents about the trip yet?", "intermediate", "Contar algo a alguien (to tell): lo del viaje is what is told, tus padres are who are told. People who are told something are indirect objects, so the plural pronoun is les, not the direct los."],
  ["indirect object", "Los abuelos", "dejaron la casa a sus nietos.", "les", "los", "The grandparents left the house to their grandchildren.", "intermediate", "Dejar algo a alguien (to leave something to someone): la casa is what is left, sus nietos are who get it. People receiving something take les, not los."],
  ["indirect object", "¿Quieres que", "preste mi coche?", "te", "ti", "Do you want me to lend you my car?", "intermediate", "Prestar algo a alguien: mi coche is what is lent, and you would get it, so the indirect pronoun is te. Ti never stands alone before a verb; it only follows a preposition (a ti)."],
  ["indirect object", "El profesor", "puso una mala nota a Pedro.", "le", "lo", "The teacher gave Pedro a bad mark.", "intermediate", "Poner una nota a alguien (to give someone a mark): una mala nota is the direct object, Pedro is the indirect object. One person as an indirect object is le; lo would make Pedro the thing given."],
  ["indirect object", "Los niños", "piden dulces a su abuela.", "le", "la", "The children ask their grandmother for sweets.", "basic", "Pedir algo a alguien: dulces is what is asked for, the grandmother is who is asked. Pedir always treats the person as an indirect object, so it is le even for a woman; la would be wrong."],
  ["indirect object", "Mi jefe no", "ha contestado todavía.", "me", "mi", "My boss hasn't answered me yet.", "intermediate", "Contestar a alguien takes an indirect object: you answer to someone. So the speaker becomes me, placed before haber: no me ha contestado. Mi without an accent means my."],

  // --- Indirect object: usted/ustedes and clarification with a + person ---
  ["indirect object", "Señora García,", "traigo los documentos que pidió.", "le", "la", "Mrs García, I'm bringing you the documents you asked for.", "advanced", "Usted as an indirect object is le, for women as well as men."],
  ["indirect object", "El dentista", "sacó una muela a mi hermano.", "le", "lo", "The dentist pulled one of my brother's teeth.", "advanced", "Spanish marks the person affected with an indirect object: le sacó una muela a mi hermano."],
  ["indirect object", "Hoy", "toca a ti fregar los platos.", "te", "ti", "Today it's your turn to wash the dishes.", "intermediate", "Tocar (to be someone's turn) takes an indirect object: te toca. A ti adds emphasis but never replaces te."],
  ["indirect object", "A ella", "dieron el premio, no a él.", "le", "la", "They gave the prize to her, not to him.", "advanced", "A ella clarifies and contrasts, but the indirect pronoun le must still appear."],
  ["indirect object", "A usted", "debo una explicación.", "le", "lo", "I owe you an explanation.", "advanced", "A usted is the person owed, so the indirect pronoun is le. The a + person phrase only adds clarity."],
  ["indirect object", "A ustedes", "mando la información por correo.", "les", "los", "I'll send you all the information by email.", "intermediate", "A ustedes receives the information, so it is an indirect object and the pronoun is les. Ustedes as an indirect object is always les, never los, whether the group is men or women."],

  // --- Indirect object: attached to a gerund or infinitive ---
  ["indirect object", "Voy a", "un mensaje a Marta.", "escribirle", "escribirla", "I'm going to write Marta a message.", "intermediate", "After an infinitive the pronoun attaches: escribir + le. Marta receives the message, so it's le, not la.", "escribir"],
  ["indirect object", "Estoy", "la verdad a mis padres.", "diciéndoles", "diciéndolos", "I'm telling my parents the truth.", "advanced", "Decir algo a alguien: la verdad is what is said, mis padres are who hear it, so the indirect pronoun les attaches to the gerund: diciéndoles. Diciéndolos would treat your parents as the thing being said.", "diciendo"],
  ["indirect object", "¿Puedes", "la sal, por favor?", "pasarme", "pasarte", "Can you pass me the salt, please?", "intermediate", "Ask who gets the salt? The speaker, so the pronoun is me: pasarme. Pasarte would mean passing it to yourself.", "pasar"],
  ["indirect object", "Necesito", "una pregunta, profesora.", "hacerle", "hacerla", "I need to ask you a question, teacher.", "advanced", "Usted is the person asked, so le attaches: hacerle. Una pregunta is the direct object.", "hacer"],
  ["indirect object", "Estamos", "una carta a los Reyes Magos.", "escribiéndoles", "escribiéndolos", "We're writing a letter to the Three Kings.", "advanced", "Escribir algo a alguien: una carta is what is written, the Three Kings are who it is written to. Receivers are indirect objects, so les attaches: escribiéndoles. Los would treat the Kings as what is written.", "escribiendo"],

  // --- Double pronouns: indirect before direct (me/te/nos + lo/la/los/las) ---
  ["double pronouns", "¿El libro? Mi hermano", "prestó ayer.", "me lo", "lo me", "The book? My brother lent it to me yesterday.", "basic", "With two pronouns, the indirect one (the person) always comes first, then the direct one (the thing). Me (to me) + lo (el libro) = me lo. Lo me is never possible in Spanish."],
  ["double pronouns", "¿La foto? Yo", "mando ahora.", "te la", "la te", "The photo? I'll send it to you now.", "basic", "The order is always person first, then thing: indirect before direct. Te (to you) + la (la foto) = te la. La te is the wrong order."],
  ["double pronouns", "¿El postre? El camarero", "trae enseguida.", "nos lo", "lo nos", "The dessert? The waiter will bring it to us right away.", "basic", "Indirect (the person) always comes before direct (the thing). Nos (to us) + lo (el postre) = nos lo. Lo nos is the wrong order."],
  ["double pronouns", "¿Las fotos del viaje? Ana", "enseñó ayer.", "nos las", "nos los", "The trip photos? Ana showed them to us yesterday.", "basic", "Nos comes first, so the question is gender. Foto ends in -o but is feminine (la foto, short for la fotografía), so it is nos las, not nos los."],
  ["double pronouns", "¿Mi bolígrafo? Sí, ahora", "devuelvo.", "te lo", "te la", "My pen? Yes, I'll give it back to you now.", "basic", "Te comes first, so the question is gender. El bolígrafo is masculine, so the thing is lo: te lo. Te la would need a feminine noun, like la goma."],
  ["double pronouns", "¿Quién te regaló esa bufanda? Mi abuela", "regaló.", "me la", "me lo", "Who gave you that scarf? My grandmother gave it to me.", "basic", "Me comes first because I am the one who received it. The second pronoun copies the thing: la bufanda is feminine, so me la. Me lo would need something masculine, like el gorro."],
  ["double pronouns", "Si necesitas el coche, yo", "presto.", "te lo", "se lo", "If you need the car, I'll lend it to you.", "basic", "The person is tú, so the pair is te lo. Se only replaces le or les."],
  ["double pronouns", "El profesor explicó el ejercicio a Marta y luego", "explicó a mí.", "me lo", "se lo", "The teacher explained the exercise to Marta and then explained it to me.", "intermediate", "A mí points to me, so the pair is me lo. Se only replaces le or les."],
  ["double pronouns", "¿La receta? Mi tía", "dio a nosotras.", "nos la", "se la", "The recipe? My aunt gave it to us.", "advanced", "A nosotras means us, so the indirect pronoun is nos, not se. Only le and les turn into se."],
  ["double pronouns", "¿Los billetes? Yo", "compro a ti si quieres.", "te los", "se los", "The tickets? I'll buy them for you if you want.", "intermediate", "A ti points to tú, so the pair is te los. Se only replaces le or les."],
  ["double pronouns", "¿Las gafas? Mamá", "ha guardado.", "te las", "te los", "The glasses? Mum has put them away for you.", "intermediate", "Gafas is always feminine plural (las gafas), so the direct pronoun is las: te las. Te los would need a masculine plural noun, like los guantes. Both pronouns go before haber as a block."],
  ["double pronouns", "¿La mesa? Mis amigos", "han vendido a buen precio.", "me la", "me lo", "The table? My friends have sold it to me at a good price.", "intermediate", "La mesa is feminine, so the direct pronoun after me is la: me la. Me lo would need a masculine noun, like el sofá. Both pronouns go in front of haber: me la han vendido."],
  ["double pronouns", "¿El vestido? Mi madre", "hizo a mí para la boda.", "me lo", "me la", "The dress? My mother made it for me for the wedding.", "intermediate", "Vestido is masculine (el vestido), so the pair is me lo, not me la. A mí only adds emphasis; the pronoun me must still appear."],
  ["double pronouns", "¿Necesitas mi diccionario? Ahora", "dejo.", "te lo", "te la", "Do you need my dictionary? I'll lend it to you now.", "basic", "Diccionario takes el, so it is masculine and the pair is te lo. Te la would need a feminine noun, like la regla. Te comes first because you are the one who receives it."],
  ["double pronouns", "¿Tus padres te compraron la moto? Sí,", "compraron el año pasado.", "me la", "me lo", "Did your parents buy you the motorbike? Yes, they bought it for me last year.", "basic", "Moto ends in -o but is feminine: la moto (short for la motocicleta). So the pair is me la, not me lo."],
  ["double pronouns", "¿Me explicas el problema? Claro, ahora", "explico.", "te lo", "me lo", "Will you explain the problem to me? Sure, I'll explain it to you now.", "basic", "In the question, me means the person asking. In the answer the speaker explains it to that person, so the indirect pronoun becomes te: te lo. Me lo would mean explaining it to yourself."],
  ["double pronouns", "¿Me das tu dirección? Sí,", "doy ahora.", "te la", "te lo", "Will you give me your address? Yes, I'll give it to you now.", "basic", "Nouns ending in -ción are always feminine: la dirección. So the pair is te la, not te lo."],
  ["double pronouns", "¿Me prestas tus apuntes? Sí,", "presto mañana.", "te los", "te las", "Will you lend me your notes? Yes, I'll lend them to you tomorrow.", "basic", "Apuntes is masculine plural (los apuntes), so the direct pronoun is los: te los. Te las would need a feminine plural noun, like las notas."],

  // --- Double pronouns: le/les become se before lo/la/los/las ---
  ["double pronouns", "¿Las llaves? Juan", "dio a su hermana.", "se las", "le las", "The keys? Juan gave them to his sister.", "intermediate", "Le can never stand right before lo, la, los or las; it changes to se. Le (to his sister) + las (the keys) = se las. A su hermana clarifies who se refers to."],
  ["double pronouns", "¿El regalo? Nosotros", "dimos a Pablo ayer.", "se lo", "le lo", "The present? We gave it to Pablo yesterday.", "intermediate", "Le (to Pablo) + lo (the present) is never le lo: le becomes se, so se lo."],
  ["double pronouns", "¿Los apuntes? Carmen", "presta a sus compañeros.", "se los", "les los", "The notes? Carmen lends them to her classmates.", "intermediate", "Les behaves just like le: before lo, la, los or las it changes to se. Les (to her classmates) + los (los apuntes) = se los. Les los never appears in Spanish."],
  ["double pronouns", "¿La verdad? No", "dije a mis padres.", "se la", "les la", "The truth? I didn't tell it to my parents.", "intermediate", "Spanish never puts le or les right before lo, la, los or las, so les turns into se. Les (to my parents) + la (la verdad) = se la."],
  ["double pronouns", "¿La pregunta? Ya", "hice a la profesora.", "se la", "le la", "The question? I already asked the teacher.", "intermediate", "Le + la would put two l- pronouns side by side, which Spanish avoids, so le becomes se: se la. A la profesora tells you who se means."],
  ["double pronouns", "¿El dinero? Mañana", "devuelvo a ustedes.", "se lo", "les lo", "The money? I'll give it back to you all tomorrow.", "advanced", "Les + lo becomes se lo. A ustedes clarifies that se means you all."],
  ["double pronouns", "¿Las flores? Mi padre", "compró a mi madre.", "se las", "le las", "The flowers? My father bought them for my mother.", "intermediate", "Le changes to se whenever it comes before lo, la, los or las. Le (for my mother) + las (las flores) = se las. A mi madre at the end shows who se is."],
  ["double pronouns", "¿Los resultados? El médico", "explicó a la paciente.", "se los", "le los", "The results? The doctor explained them to the patient.", "intermediate", "Le (to the patient) + los (the results) can't stay as le los: le becomes se. So it is se los, with a la paciente showing who se refers to."],
  ["double pronouns", "¿El paquete? El cartero", "entregó a mis vecinos.", "se lo", "les lo", "The parcel? The postman delivered it to my neighbours.", "intermediate", "Les (to my neighbours) + lo (el paquete) can't stay as les lo, so les turns into se: se lo. Se doesn't show singular or plural; a mis vecinos does."],
  ["double pronouns", "¿La contraseña? No", "puedo decir a nadie.", "se la", "le la", "The password? I can't tell it to anyone.", "advanced", "Le + la becomes se la, and the pair goes before the conjugated verb: no se la puedo decir."],
  ["double pronouns", "¿El informe? Ya", "he enviado al director.", "se lo", "le lo", "The report? I've already sent it to the director.", "intermediate", "Le + lo becomes se lo, placed before haber: se lo he enviado."],
  ["double pronouns", "¿Las noticias? Todavía no", "han contado a los niños.", "se las", "les las", "The news? They haven't told the children yet.", "intermediate", "Les + las becomes se las, placed before haber: no se las han contado."],
  ["double pronouns", "¿Tu número? Ya", "he dado a Laura.", "se lo", "se la", "Your number? I've already given it to Laura.", "intermediate", "Le (to Laura) becomes se, and el número is masculine, so the pair is se lo."],
  ["double pronouns", "¿La carta? Mi hermano", "está escribiendo a su novia.", "se la", "le la", "The letter? My brother is writing it to his girlfriend.", "intermediate", "With estar + gerund both pronouns can go before estar. Le + la becomes se la."],
  ["double pronouns", "¿El secreto? Mis amigos", "están contando a todo el mundo.", "se lo", "les lo", "The secret? My friends are telling it to everyone.", "intermediate", "Le (a todo el mundo) + lo (the secret) becomes se lo, placed before estar."],
  ["double pronouns", "¿La tarta? Nosotros", "vamos a llevar a la abuela.", "se la", "le la", "The cake? We're going to take it to grandma.", "intermediate", "Le + la becomes se la. With ir a + infinitive the pair can go before the conjugated verb."],
  ["double pronouns", "¿Los juguetes? Mis padres", "van a comprar a mi hermano.", "se los", "les los", "The toys? My parents are going to buy them for my brother.", "intermediate", "Le (for my brother) + los (the toys) becomes se los, placed before ir."],
  ["double pronouns", "¿El mensaje? Ya", "mandé a él, no a ella.", "se lo", "le lo", "The message? I already sent it to him, not to her.", "advanced", "Se could mean to him, her, you or them, so a él clarifies it. Le + lo always becomes se lo."],
  ["double pronouns", "¿Las entradas? Ya", "di a ustedes, ¿no?", "se las", "les las", "The tickets? I already gave them to you all, didn't I?", "advanced", "Les + las becomes se las. A ustedes clarifies who se refers to."],
  ["double pronouns", "¿Le diste las llaves a Mario? Sí, ya", "di.", "se las", "le las", "Did you give the keys to Mario? Yes, I already gave them to him.", "intermediate", "The question already uses le (to Mario). In the answer you add las (the keys), and le before las changes to se: se las. Le las never appears in Spanish."],
  ["double pronouns", "¿Les mandaste la invitación a tus tíos? No, todavía no", "he mandado.", "se la", "les la", "Did you send the invitation to your aunt and uncle? No, I haven't sent it yet.", "intermediate", "Les (to your aunt and uncle) + la (la invitación) can't stand together, so les turns into se: se la. The pair goes before haber: no se la he mandado."],
  ["double pronouns", "¿Le compraste el pastel a Ana? Sí,", "compré esta mañana.", "se lo", "le lo", "Did you buy the cake for Ana? Yes, I bought it for her this morning.", "basic", "Le (for Ana) + lo (el pastel) would be le lo, which Spanish never allows. Le becomes se, so the answer is se lo."],
  ["double pronouns", "¿Le regalas los pendientes a tu madre? Sí,", "regalo para su cumpleaños.", "se los", "se las", "Are you giving the earrings to your mother? Yes, I'm giving them to her for her birthday.", "intermediate", "Le becomes se, so the question is gender. Pendientes is masculine plural (los pendientes), so it is se los. Se las would need a feminine noun, like las pulseras."],
  ["double pronouns", "¿Quién les explicó el problema a los alumnos? La directora", "explicó.", "se lo", "les lo", "Who explained the problem to the students? The head teacher explained it to them.", "intermediate", "The question uses les (to the students). In the answer, les before lo (el problema) changes to se: se lo. Les lo never appears in Spanish."],
  ["double pronouns", "¿Le pediste permiso a tu padre? Sí,", "pedí ayer.", "se lo", "le lo", "Did you ask your father for permission? Yes, I asked him for it yesterday.", "intermediate", "Lo stands for el permiso. Le (to your father) can't come right before lo, so it changes to se: se lo."],
  ["double pronouns", "¿Le devolviste la chaqueta a Sara? Sí, ya", "devolví.", "se la", "se lo", "Did you give the jacket back to Sara? Yes, I already gave it back to her.", "intermediate", "Se is right, so the question is the gender of the thing. La chaqueta is feminine, so it is se la. Se lo would need a masculine noun, like el abrigo."],

  // --- Double pronouns: attached to a gerund or infinitive ---
  ["double pronouns", "¿El cuento? Estoy", "a mi hija.", "leyéndoselo", "leyéndolelo", "The story? I'm reading it to my daughter.", "advanced", "Leyendo + se + lo = leyéndoselo. Le turns into se before lo, and the accent keeps the stress.", "leyendo"],
  ["double pronouns", "¿La lección? El profesor está", "a los alumnos.", "explicándosela", "explicándolesla", "The lesson? The teacher is explaining it to the students.", "advanced", "Explicando + se + la = explicándosela. Les turns into se before la.", "explicando"],
  ["double pronouns", "¿Las fotos? Estoy", "ahora mismo.", "mandándotelas", "mandándotelos", "The photos? I'm sending them to you right now.", "advanced", "Foto is feminine (la foto, short for la fotografía), so the direct pronoun is las: mandándotelas. Mandándotelos would need a masculine noun, like los vídeos. Te comes first because you receive them.", "mandando"],
  ["double pronouns", "¿El menú? El camarero está", "ahora.", "trayéndonoslo", "trayéndonosla", "The menu? The waiter is bringing it to us now.", "advanced", "Menú takes el, so it is masculine and the direct pronoun is lo: trayéndonoslo. Trayéndonosla would need a feminine noun, like la carta. The order is gerund + nos (to us) + lo.", "trayendo"],
  ["double pronouns", "¿Los regalos? Papá está", "a los niños.", "dándoselos", "dándoselas", "The presents? Dad is giving them to the children.", "advanced", "Les (to the children) becomes se, and los regalos is masculine plural, so the thing is los: dándoselos. Dándoselas would need a feminine noun, like las galletas.", "dando"],
  ["double pronouns", "¿El libro? Voy a", "mañana.", "devolvértelo", "devolvérselo", "The book? I'm going to give it back to you tomorrow.", "advanced", "Devolver + te + lo = devolvértelo. With two pronouns attached, the infinitive takes a written accent.", "devolver"],
  ["double pronouns", "¿La bicicleta? Quiero", "a mi primo.", "prestársela", "prestárlela", "The bike? I want to lend it to my cousin.", "advanced", "Prestar + se + la = prestársela. Le becomes se before la.", "prestar"],
  ["double pronouns", "¿Los documentos? Tengo que", "al abogado hoy.", "mandárselos", "mandárselas", "The documents? I have to send them to the lawyer today.", "advanced", "Le (to the lawyer) becomes se, and los documentos is masculine plural: mandárselos. Mandárselas would need a feminine noun, like las cartas.", "mandar"],
  ["double pronouns", "¿La canción? ¿Puedes", "otra vez?", "cantármela", "cantármelo", "The song? Can you sing it to me again?", "intermediate", "Canción ends in -ción, so it is feminine, and the pair is me + la: cantármela. Cantármelo would need a masculine noun, like el poema.", "cantar"],
  ["double pronouns", "¿El plan? Queremos", "a nuestros jefes.", "explicárselo", "explicárselos", "The plan? We want to explain it to our bosses.", "advanced", "Explicar + se + lo = explicárselo. Les becomes se; lo is singular because it stands for el plan.", "explicar"],
  ["double pronouns", "Si quieres las fotos, puedo", "esta noche.", "enviártelas", "enviártelos", "If you want the photos, I can send them to you tonight.", "intermediate", "Foto is feminine even though it ends in -o (las fotos), so it is te + las: enviártelas. With two pronouns attached, the infinitive takes a written accent: enviár-.", "enviar"],
];

export const OBJECT_PRONOUN_QUESTIONS: Question[] = seed.map(([type, before, after, answer, distractor, en, level, explanation, blankHint], index) => ({
  id: 5001 + index,
  before,
  after,
  infinitive: type,
  answer,
  verbAnswer: answer,
  objectPronoun: distractor,
  explanation,
  translations: { en, pl: "" },
  subjectNumber: "singular",
  isActivity: false,
  indirectObject: "",
  tense: "present",
  level,
  ...(blankHint ? { blankHint } : {}),
}));

/** One entry per pronoun type, so the shared "second filter" and chart can list them. */
export const OBJECT_PRONOUN_FORMS: Record<string, [string, string]> = {
  "direct object": ["me, te, lo, la", "nos, los, las"],
  "indirect object": ["me, te, le", "nos, les"],
  "double pronouns": ["me lo, te la, se lo…", "nos los, se las…"],
};

/** Reference tables for the in-round "Pronoun chart": who or what each pronoun stands for. */
export const OBJECT_PRONOUN_CHART: Record<ObjectPronounType, Array<{ label: string; form: string }>> = {
  "direct object": [
    { label: "yo", form: "me" },
    { label: "tú", form: "te" },
    { label: "él / usted / masc. thing", form: "lo" },
    { label: "ella / usted / fem. thing", form: "la" },
    { label: "nosotros / nosotras", form: "nos" },
    { label: "ellos / ustedes / masc. things", form: "los" },
    { label: "ellas / ustedes / fem. things", form: "las" },
  ],
  "indirect object": [
    { label: "yo", form: "me" },
    { label: "tú", form: "te" },
    { label: "él / ella / usted", form: "le" },
    { label: "nosotros / nosotras", form: "nos" },
    { label: "ellos / ellas / ustedes", form: "les" },
  ],
  "double pronouns": [
    { label: "me + lo", form: "me lo" },
    { label: "te + la", form: "te la" },
    { label: "nos + los", form: "nos los" },
    { label: "le + lo", form: "se lo" },
    { label: "le + la", form: "se la" },
    { label: "les + los", form: "se los" },
    { label: "les + las", form: "se las" },
  ],
};
