import type { Question } from "./quiz-data";

type Level = Question["level"];

type Template = {
  before: string;
  after: string;
  infinitive: string;
  preterite: string;
  imperfect: string;
  answerTense: "preterite" | "imperfect";
  en: string;
  level: Level;
  reason: string;
};

const templates: Template[] = [
  { before: "Ayer yo", after: " al mercado.", infinitive: "ir", preterite: "fui", imperfect: "iba", answerTense: "preterite", en: "Yesterday I went to the market.", level: "basic", reason: "Ayer marks one completed past action." },
  { before: "De niño, yo", after: " al parque cada tarde.", infinitive: "ir", preterite: "fui", imperfect: "iba", answerTense: "imperfect", en: "As a child, I used to go to the park every afternoon.", level: "basic", reason: "De niño and cada tarde describe a repeated past habit." },
  { before: "Anoche Marta", after: " la cena a las ocho.", infinitive: "preparar", preterite: "preparó", imperfect: "preparaba", answerTense: "preterite", en: "Last night Marta prepared dinner at eight.", level: "basic", reason: "Anoche and a las ocho frame a completed event." },
  { before: "Mientras Marta", after: " la cena, sonó el teléfono.", infinitive: "preparar", preterite: "preparó", imperfect: "preparaba", answerTense: "imperfect", en: "While Marta was preparing dinner, the phone rang.", level: "basic", reason: "Mientras sets background action in progress." },
  { before: "El sábado nosotros", after: " temprano.", infinitive: "salir", preterite: "salimos", imperfect: "salíamos", answerTense: "preterite", en: "On Saturday we left early.", level: "basic", reason: "El sábado points to one completed occasion." },
  { before: "Normalmente nosotros", after: " temprano para la escuela.", infinitive: "salir", preterite: "salimos", imperfect: "salíamos", answerTense: "imperfect", en: "Normally we used to leave early for school.", level: "basic", reason: "Normalmente signals repeated past routine." },
  { before: "De repente, el tren", after: " en la estación.", infinitive: "llegar", preterite: "llegó", imperfect: "llegaba", answerTense: "preterite", en: "Suddenly, the train arrived at the station.", level: "intermediate", reason: "De repente introduces a completed interrupting action." },
  { before: "El tren", after: " cuando empezó la lluvia.", infinitive: "llegar", preterite: "llegó", imperfect: "llegaba", answerTense: "imperfect", en: "The train was arriving when the rain started.", level: "intermediate", reason: "The arrival was in progress when another event happened." },
  { before: "En 2020 Ana", after: " en Sevilla.", infinitive: "vivir", preterite: "vivió", imperfect: "vivía", answerTense: "preterite", en: "In 2020 Ana lived in Seville.", level: "intermediate", reason: "A bounded time period can use preterite." },
  { before: "Cuando la conocí, Ana", after: " en Sevilla.", infinitive: "vivir", preterite: "vivió", imperfect: "vivía", answerTense: "imperfect", en: "When I met her, Ana was living in Seville.", level: "intermediate", reason: "The living situation is background information." },
  { before: "El profesor", after: " la regla y luego dio ejemplos.", infinitive: "explicar", preterite: "explicó", imperfect: "explicaba", answerTense: "preterite", en: "The teacher explained the rule and then gave examples.", level: "intermediate", reason: "A sequence of completed actions uses preterite." },
  { before: "El profesor", after: " la regla cuando entró el director.", infinitive: "explicar", preterite: "explicó", imperfect: "explicaba", answerTense: "imperfect", en: "The teacher was explaining the rule when the principal came in.", level: "intermediate", reason: "The explanation was ongoing background action." },
  { before: "Al ver las noticias, Luis", after: " nervioso.", infinitive: "ponerse", preterite: "se puso", imperfect: "se ponía", answerTense: "preterite", en: "When he saw the news, Luis became nervous.", level: "advanced", reason: "A change of state at a moment uses preterite." },
  { before: "Cada vez que hablaba en público, Luis", after: " nervioso.", infinitive: "ponerse", preterite: "se puso", imperfect: "se ponía", answerTense: "imperfect", en: "Every time he spoke in public, Luis would get nervous.", level: "advanced", reason: "Cada vez que describes repeated past behavior." },
  { before: "La reunión", after: " a las diez.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "The meeting started at ten.", level: "advanced", reason: "A starting point is a completed event." },
  { before: "La reunión ya", after: " cuando llegué.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "imperfect", en: "The meeting was already starting when I arrived.", level: "advanced", reason: "The starting was in progress when another action happened." },

  // --- Issue #24, Stage 5: completed events (a single finished past action) ---
  { before: "Ayer, Marta", after: " una carta a su amiga.", infinitive: "escribir", preterite: "escribió", imperfect: "escribía", answerTense: "preterite", en: "Yesterday, Marta wrote a letter to her friend.", level: "basic", reason: "Ayer marks one completed past action." },
  { before: "Anoche nosotros", after: " en aquel restaurante nuevo.", infinitive: "comer", preterite: "comimos", imperfect: "comíamos", answerTense: "preterite", en: "Last night we ate at that new restaurant.", level: "basic", reason: "Anoche marks a completed event." },
  { before: "El lunes pasado, yo", after: " un coche nuevo.", infinitive: "comprar", preterite: "compré", imperfect: "compraba", answerTense: "preterite", en: "Last Monday, I bought a new car.", level: "basic", reason: "A specific past date marks a completed event." },
  { before: "Diego", after: " toda la tarea anoche.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "preterite", en: "Diego did all the homework last night.", level: "basic", reason: "Anoche marks a completed action." },
  { before: "El sábado, mis padres", after: " la mesa para la cena especial.", infinitive: "poner", preterite: "pusieron", imperfect: "ponían", answerTense: "preterite", en: "On Saturday, my parents set the table for the special dinner.", level: "intermediate", reason: "A specific occasion marks a completed action." },
  { before: "Ella", after: " la verdad por fin.", infinitive: "decir", preterite: "dijo", imperfect: "decía", answerTense: "preterite", en: "She finally told the truth.", level: "basic", reason: "Por fin signals a completed action." },
  { before: "Nosotros", after: " terminar el proyecto a tiempo.", infinitive: "poder", preterite: "pudimos", imperfect: "podíamos", answerTense: "preterite", en: "We managed to finish the project on time.", level: "intermediate", reason: "Preterite of poder expresses a specific successful attempt." },
  { before: "Yo le", after: " la noticia esta mañana.", infinitive: "decir", preterite: "dije", imperfect: "decía", answerTense: "preterite", en: "I told him the news this morning.", level: "basic", reason: "Esta mañana marks a specific completed action." },
  { before: "El tren", after: " con dos horas de retraso.", infinitive: "llegar", preterite: "llegó", imperfect: "llegaba", answerTense: "preterite", en: "The train arrived two hours late.", level: "basic", reason: "A specific arrival is a completed event." },
  { before: "Yo les", after: " un mensaje a mis abuelos el domingo.", infinitive: "escribir", preterite: "escribí", imperfect: "escribía", answerTense: "preterite", en: "I wrote a message to my grandparents on Sunday.", level: "basic", reason: "El domingo marks one completed action." },
  { before: "Los estudiantes", after: " el examen sin problemas.", infinitive: "hacer", preterite: "hicieron", imperfect: "hacían", answerTense: "preterite", en: "The students did the exam without any problems.", level: "basic", reason: "A single completed event uses preterite." },
  { before: "Carla", after: " que sí sin dudarlo.", infinitive: "decir", preterite: "dijo", imperfect: "decía", answerTense: "preterite", en: "Carla said yes without hesitation.", level: "basic", reason: "A single completed statement uses preterite." },
  { before: "Tú", after: " muy bien en la entrevista.", infinitive: "hablar", preterite: "hablaste", imperfect: "hablabas", answerTense: "preterite", en: "You spoke very well in the interview.", level: "basic", reason: "A specific past event uses preterite." },
  { before: "Mi jefe", after: " el proyecto la semana pasada.", infinitive: "decidir", preterite: "decidió", imperfect: "decidía", answerTense: "preterite", en: "My boss decided on the project last week.", level: "intermediate", reason: "La semana pasada marks a completed decision." },
  { before: "Yo", after: " toda la novela en un fin de semana.", infinitive: "leer", preterite: "leí", imperfect: "leía", answerTense: "preterite", en: "I read the whole novel in one weekend.", level: "intermediate", reason: "A specific finished action uses preterite." },
  { before: "Nosotros", after: " la respuesta correcta enseguida.", infinitive: "saber", preterite: "supimos", imperfect: "sabíamos", answerTense: "preterite", en: "We found out the correct answer right away.", level: "intermediate", reason: "Preterite of saber expresses finding something out at a specific moment." },
  { before: "Ana", after: " tres años en Londres antes de mudarse.", infinitive: "vivir", preterite: "vivió", imperfect: "vivía", answerTense: "preterite", en: "Ana lived in London for three years before moving.", level: "intermediate", reason: "A bounded time period uses preterite." },
  { before: "El médico", after: " el diagnóstico al paciente.", infinitive: "explicar", preterite: "explicó", imperfect: "explicaba", answerTense: "preterite", en: "The doctor explained the diagnosis to the patient.", level: "intermediate", reason: "A single completed explanation uses preterite." },
  { before: "Yo", after: " mi opinión en la reunión.", infinitive: "dar", preterite: "di", imperfect: "daba", answerTense: "preterite", en: "I gave my opinion at the meeting.", level: "basic", reason: "A specific completed action uses preterite." },
  { before: "Mis amigos", after: " a la fiesta a las nueve.", infinitive: "llegar", preterite: "llegaron", imperfect: "llegaban", answerTense: "preterite", en: "My friends arrived at the party at nine.", level: "basic", reason: "A specific time marks a completed arrival." },

  // --- Sequences (a chain of completed actions, ordered by primero/luego/después/finalmente) ---
  { before: "Primero yo", after: " la cena y luego llamé a mi hermana.", infinitive: "preparar", preterite: "preparé", imperfect: "preparaba", answerTense: "preterite", en: "First I made dinner and then I called my sister.", level: "basic", reason: "A sequence of completed actions uses preterite." },
  { before: "Luego, Sara", after: " su nombre en el registro.", infinitive: "escribir", preterite: "escribió", imperfect: "escribía", answerTense: "preterite", en: "Then, Sara wrote her name in the register.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Después de desayunar, nosotros", after: " al trabajo juntos.", infinitive: "salir", preterite: "salimos", imperfect: "salíamos", answerTense: "preterite", en: "After having breakfast, we left for work together.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Entonces el profesor", after: " la lección con un ejemplo.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "Then the teacher started the lesson with an example.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Finalmente, ellos", after: " que sí a la propuesta.", infinitive: "decir", preterite: "dijeron", imperfect: "decían", answerTense: "preterite", en: "Finally, they said yes to the proposal.", level: "intermediate", reason: "The last step in a sequence uses preterite." },
  { before: "Después, yo", after: " un correo a mi jefe.", infinitive: "escribir", preterite: "escribí", imperfect: "escribía", answerTense: "preterite", en: "Afterwards, I wrote an email to my boss.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Luego, el camarero", after: " la mesa rápidamente.", infinitive: "preparar", preterite: "preparó", imperfect: "preparaba", answerTense: "preterite", en: "Then, the waiter prepared the table quickly.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Primero, Luis", after: " las instrucciones con cuidado.", infinitive: "leer", preterite: "leyó", imperfect: "leía", answerTense: "preterite", en: "First, Luis read the instructions carefully.", level: "basic", reason: "The first step in a sequence uses preterite." },
  { before: "Después de eso, nosotros", after: " un café rápido.", infinitive: "comprar", preterite: "compramos", imperfect: "comprábamos", answerTense: "preterite", en: "After that, we bought a quick coffee.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Finalmente, el director", after: " el nuevo plan al equipo.", infinitive: "explicar", preterite: "explicó", imperfect: "explicaba", answerTense: "preterite", en: "Finally, the director explained the new plan to the team.", level: "intermediate", reason: "The last step in a sequence uses preterite." },
  { before: "Primero yo", after: " con mi hermana y después con mis padres.", infinitive: "hablar", preterite: "hablé", imperfect: "hablaba", answerTense: "preterite", en: "First I talked with my sister and then with my parents.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Luego, Ana", after: " toda la casa antes de la fiesta.", infinitive: "preparar", preterite: "preparó", imperfect: "preparaba", answerTense: "preterite", en: "Then, Ana got the whole house ready before the party.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Después, el camarero nos", after: " la cuenta.", infinitive: "dar", preterite: "dio", imperfect: "daba", answerTense: "preterite", en: "Afterwards, the waiter gave us the bill.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Entonces, ella", after: " que necesitaba más tiempo.", infinitive: "decir", preterite: "dijo", imperfect: "decía", answerTense: "preterite", en: "Then, she said she needed more time.", level: "intermediate", reason: "A step in a sequence uses preterite." },
  { before: "Primero, nosotros", after: " el correo con cuidado.", infinitive: "escribir", preterite: "escribimos", imperfect: "escribíamos", answerTense: "preterite", en: "First, we wrote the email carefully.", level: "basic", reason: "The first step in a sequence uses preterite." },
  { before: "Luego, mis padres", after: " a casa y descansaron.", infinitive: "llegar", preterite: "llegaron", imperfect: "llegaban", answerTense: "preterite", en: "Then, my parents arrived home and rested.", level: "basic", reason: "A step in a sequence uses preterite." },
  { before: "Antes de firmar, ellos", after: " el contrato con calma.", infinitive: "leer", preterite: "leyeron", imperfect: "leían", answerTense: "preterite", en: "Before signing, they read the contract calmly.", level: "intermediate", reason: "A step in a sequence uses preterite." },
  { before: "Finalmente, yo", after: " la verdad a mi amigo.", infinitive: "decir", preterite: "dije", imperfect: "decía", answerTense: "preterite", en: "Finally, I told my friend the truth.", level: "intermediate", reason: "The last step in a sequence uses preterite." },
  { before: "Después del discurso, el público", after: " un fuerte aplauso.", infinitive: "dar", preterite: "dio", imperfect: "daba", answerTense: "preterite", en: "After the speech, the audience gave a big round of applause.", level: "intermediate", reason: "The final step in a sequence uses preterite." },

  // --- Starts/changes (the beginning of an action, or a change of state at a specific moment) ---
  { before: "De repente, la niña", after: " a llorar.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "Suddenly, the girl started crying.", level: "basic", reason: "De repente marks the specific start of an action." },
  { before: "El partido", after: " a las cuatro en punto.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "The match started at four o'clock sharp.", level: "basic", reason: "A specific starting time uses preterite." },
  { before: "Cuando oyó la noticia, Marta", after: " muy contenta.", infinitive: "ponerse", preterite: "se puso", imperfect: "se ponía", answerTense: "preterite", en: "When she heard the news, Marta became very happy.", level: "intermediate", reason: "A change of state at a specific moment uses preterite." },
  { before: "Al final del año, ellos", after: " trasladarse a otra ciudad.", infinitive: "decidir", preterite: "decidieron", imperfect: "decidían", answerTense: "preterite", en: "At the end of the year, they decided to move to another city.", level: "intermediate", reason: "A specific decision marks the start of a change." },
  { before: "Tras el accidente, Luis", after: " mucho más cuidadoso.", infinitive: "ponerse", preterite: "se puso", imperfect: "se ponía", answerTense: "preterite", en: "After the accident, Luis became much more careful.", level: "intermediate", reason: "A change of state uses preterite." },
  { before: "Yo", after: " a trabajar aquí en enero.", infinitive: "empezar", preterite: "empecé", imperfect: "empezaba", answerTense: "preterite", en: "I started working here in January.", level: "basic", reason: "A specific starting point uses preterite." },
  { before: "En ese momento, nosotros", after: " que el plan no iba a funcionar.", infinitive: "saber", preterite: "supimos", imperfect: "sabíamos", answerTense: "preterite", en: "At that moment, we found out the plan wasn't going to work.", level: "intermediate", reason: "Preterite of saber marks the moment of finding something out." },
  { before: "Después de la charla, los estudiantes", after: " muy motivados.", infinitive: "ponerse", preterite: "se pusieron", imperfect: "se ponían", answerTense: "preterite", en: "After the talk, the students became very motivated.", level: "intermediate", reason: "A change of state uses preterite." },
  { before: "La tormenta", after: " de repente por la tarde.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "The storm started suddenly in the afternoon.", level: "basic", reason: "De repente marks a specific starting point." },
  { before: "Cuando vio el examen, él", after: " pálido.", infinitive: "ponerse", preterite: "se puso", imperfect: "se ponía", answerTense: "preterite", en: "When he saw the exam, he turned pale.", level: "intermediate", reason: "A sudden change of state uses preterite." },
  { before: "El curso", after: " el mes pasado.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "The course started last month.", level: "basic", reason: "A specific starting date uses preterite." },
  { before: "Nosotros", after: " hacer las maletas la noche antes.", infinitive: "decidir", preterite: "decidimos", imperfect: "decidíamos", answerTense: "preterite", en: "We decided to pack the night before.", level: "intermediate", reason: "A specific decision uses preterite." },
  { before: "Tan pronto como llegó la carta, ella", after: " a llorar de alegría.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "As soon as the letter arrived, she started crying with joy.", level: "advanced", reason: "Tan pronto como marks a precise starting moment." },
  { before: "Después de años dudando, mi padre", after: " cambiar de trabajo.", infinitive: "decidir", preterite: "decidió", imperfect: "decidía", answerTense: "preterite", en: "After years of hesitating, my father decided to change jobs.", level: "advanced", reason: "A turning-point decision uses preterite." },
  { before: "Cuando sonó la alarma, todos", after: " nerviosos.", infinitive: "ponerse", preterite: "se pusieron", imperfect: "se ponían", answerTense: "preterite", en: "When the alarm went off, everyone got nervous.", level: "intermediate", reason: "A sudden change of state uses preterite." },
  { before: "La construcción", after: " hace dos años.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "The construction started two years ago.", level: "basic", reason: "A specific starting point uses preterite." },
  { before: "Al oír el ruido, el perro", after: " a ladrar.", infinitive: "empezar", preterite: "empezó", imperfect: "empezaba", answerTense: "preterite", en: "Upon hearing the noise, the dog started barking.", level: "intermediate", reason: "A precise triggering moment uses preterite." },
  { before: "En esa reunión, ellos", after: " cambiar toda la estrategia.", infinitive: "decidir", preterite: "decidieron", imperfect: "decidían", answerTense: "preterite", en: "In that meeting, they decided to change the whole strategy.", level: "intermediate", reason: "A specific decision uses preterite." },
  { before: "Al saber la verdad, Carla", after: " muy seria.", infinitive: "ponerse", preterite: "se puso", imperfect: "se ponía", answerTense: "preterite", en: "On learning the truth, Carla became very serious.", level: "intermediate", reason: "A change of state at a specific moment uses preterite." },

  // --- Habits (repeated past routines: todos los días, siempre, normalmente, cada verano...) ---
  { before: "De niño, yo", after: " mucho pan con mantequilla.", infinitive: "comer", preterite: "comí", imperfect: "comía", answerTense: "imperfect", en: "As a child, I used to eat a lot of bread with butter.", level: "basic", reason: "De niño signals a repeated past habit." },
  { before: "Todos los veranos, mis abuelos nos", after: " muchas cartas.", infinitive: "escribir", preterite: "escribieron", imperfect: "escribían", answerTense: "imperfect", en: "Every summer, my grandparents used to write us many letters.", level: "basic", reason: "Todos los veranos signals a repeated habit." },
  { before: "Antes, nosotros", after: " en aquella tienda pequeña.", infinitive: "comprar", preterite: "compramos", imperfect: "comprábamos", answerTense: "imperfect", en: "Before, we used to shop at that small store.", level: "basic", reason: "Antes signals a repeated past habit." },
  { before: "Cuando era estudiante, Marta", after: " todas las noches hasta tarde.", infinitive: "estudiar", preterite: "estudió", imperfect: "estudiaba", answerTense: "imperfect", en: "When she was a student, Marta used to study every night until late.", level: "basic", reason: "Cuando era estudiante frames a repeated habit." },
  { before: "Siempre, mi padre nos", after: " la misma historia antes de dormir.", infinitive: "decir", preterite: "dijo", imperfect: "decía", answerTense: "imperfect", en: "My father always used to tell us the same story before bed.", level: "basic", reason: "Siempre signals a repeated habit." },
  { before: "Cada domingo, nosotros", after: " con mis abuelos por teléfono.", infinitive: "hablar", preterite: "hablamos", imperfect: "hablábamos", answerTense: "imperfect", en: "Every Sunday, we used to talk with my grandparents on the phone.", level: "basic", reason: "Cada domingo signals a repeated habit." },
  { before: "En aquella época, yo", after: " muy poco.", infinitive: "trabajar", preterite: "trabajé", imperfect: "trabajaba", answerTense: "imperfect", en: "At that time, I used to work very little.", level: "basic", reason: "En aquella época signals a repeated past situation." },
  { before: "De pequeños, nosotros", after: " libros de aventuras todo el verano.", infinitive: "leer", preterite: "leímos", imperfect: "leíamos", answerTense: "imperfect", en: "As kids, we used to read adventure books all summer.", level: "basic", reason: "De pequeños signals a repeated habit." },
  { before: "A menudo, los vecinos", after: " quejas sobre el ruido.", infinitive: "tener", preterite: "tuvieron", imperfect: "tenían", answerTense: "imperfect", en: "The neighbours often had complaints about the noise.", level: "intermediate", reason: "A menudo signals a repeated habit." },
  { before: "Cuando vivíamos en el pueblo, mi madre", after: " el pan en casa.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "imperfect", en: "When we lived in the village, my mother used to make bread at home.", level: "intermediate", reason: "A repeated past routine uses imperfect." },
  { before: "Normalmente, yo le", after: " la verdad a todo el mundo.", infinitive: "decir", preterite: "dije", imperfect: "decía", answerTense: "imperfect", en: "Normally, I used to tell everyone the truth.", level: "basic", reason: "Normalmente signals a repeated habit." },
  { before: "Cada verano, mis padres", after: " la casa de la playa.", infinitive: "preparar", preterite: "prepararon", imperfect: "preparaban", answerTense: "imperfect", en: "Every summer, my parents used to get the beach house ready.", level: "basic", reason: "Cada verano signals a repeated habit." },
  { before: "De adolescente, tú", after: " muchísimo con tus amigos.", infinitive: "hablar", preterite: "hablaste", imperfect: "hablabas", answerTense: "imperfect", en: "As a teenager, you used to talk a lot with your friends.", level: "basic", reason: "De adolescente signals a repeated habit." },
  { before: "Habitualmente, ellos", after: " café en la misma cafetería.", infinitive: "comprar", preterite: "compraron", imperfect: "compraban", answerTense: "imperfect", en: "They habitually used to buy coffee at the same café.", level: "intermediate", reason: "Habitualmente signals a repeated habit." },
  { before: "En esos años, mi abuelo", after: " la radio todas las tardes.", infinitive: "poner", preterite: "puso", imperfect: "ponía", answerTense: "imperfect", en: "In those years, my grandfather used to put the radio on every afternoon.", level: "intermediate", reason: "A repeated routine uses imperfect." },
  { before: "Cuando éramos niños, nosotros", after: " cartas a nuestros primos todos los veranos.", infinitive: "escribir", preterite: "escribimos", imperfect: "escribíamos", answerTense: "imperfect", en: "When we were children, we used to write letters to our cousins every summer.", level: "intermediate", reason: "A repeated childhood habit uses imperfect." },
  { before: "Frecuentemente, el jefe nos", after: " instrucciones muy detalladas.", infinitive: "dar", preterite: "dio", imperfect: "daba", answerTense: "imperfect", en: "The boss would frequently give us very detailed instructions.", level: "intermediate", reason: "Frecuentemente signals a repeated habit." },
  { before: "Cada mañana, mi madre", after: " el desayuno para todos.", infinitive: "preparar", preterite: "preparó", imperfect: "preparaba", answerTense: "imperfect", en: "Every morning, my mother used to prepare breakfast for everyone.", level: "basic", reason: "Cada mañana signals a repeated habit." },
  { before: "De joven, ella", after: " resolver cualquier problema sola.", infinitive: "poder", preterite: "pudo", imperfect: "podía", answerTense: "imperfect", en: "As a young woman, she could handle any problem on her own.", level: "intermediate", reason: "A general past ability described as a habit uses imperfect." },
  { before: "Todos los años, la empresa", after: " una fiesta de fin de año.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "imperfect", en: "Every year, the company used to hold an end-of-year party.", level: "basic", reason: "Todos los años signals a repeated habit." },

  // --- Ongoing/background actions (scene-setting, no interruption required) ---
  { before: "A esa hora, yo todavía", after: " en la oficina.", infinitive: "trabajar", preterite: "trabajé", imperfect: "trabajaba", answerTense: "imperfect", en: "At that hour, I was still working at the office.", level: "basic", reason: "An action in progress at a specific past hour uses imperfect." },
  { before: "En aquel momento, nosotros", after: " un plan para el fin de semana.", infinitive: "preparar", preterite: "preparamos", imperfect: "preparábamos", answerTense: "imperfect", en: "At that moment, we were preparing a plan for the weekend.", level: "basic", reason: "En aquel momento frames an action in progress." },
  { before: "Aquella tarde, los niños", after: " tranquilamente en el jardín.", infinitive: "leer", preterite: "leyeron", imperfect: "leían", answerTense: "imperfect", en: "That afternoon, the children were reading quietly in the garden.", level: "basic", reason: "Aquella tarde frames a background action in progress." },
  { before: "Mientras tanto, Ana", after: " un correo importante.", infinitive: "escribir", preterite: "escribió", imperfect: "escribía", answerTense: "imperfect", en: "Meanwhile, Ana was writing an important email.", level: "basic", reason: "Mientras tanto frames a background action." },
  { before: "A esa edad, yo no", after: " nada sobre política.", infinitive: "saber", preterite: "supe", imperfect: "sabía", answerTense: "imperfect", en: "At that age, I didn't know anything about politics.", level: "intermediate", reason: "A background mental state uses imperfect." },
  { before: "En esos días, mi hermano", after: " un trabajo nuevo.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "In those days, my brother had a new job.", level: "basic", reason: "A background situation uses imperfect." },
  { before: "Aquel verano, nosotros", after: " mucho tiempo libre.", infinitive: "tener", preterite: "tuvimos", imperfect: "teníamos", answerTense: "imperfect", en: "That summer, we had a lot of free time.", level: "basic", reason: "A background situation uses imperfect." },
  { before: "Por aquel entonces, ella", after: " en una empresa pequeña.", infinitive: "trabajar", preterite: "trabajó", imperfect: "trabajaba", answerTense: "imperfect", en: "Back then, she was working at a small company.", level: "intermediate", reason: "Por aquel entonces frames a background situation." },
  { before: "Esa mañana", after: " mucho frío.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "imperfect", en: "That morning it was very cold.", level: "basic", reason: "A background weather description uses imperfect." },
  { before: "En aquella casa, los vecinos", after: " mucho ruido a esa hora.", infinitive: "hacer", preterite: "hicieron", imperfect: "hacían", answerTense: "imperfect", en: "In that house, the neighbours used to make a lot of noise at that hour.", level: "intermediate", reason: "A background situation uses imperfect." },
  { before: "Aquel día, yo", after: " un poco de fiebre.", infinitive: "tener", preterite: "tuve", imperfect: "tenía", answerTense: "imperfect", en: "That day, I had a slight fever.", level: "basic", reason: "A background physical state uses imperfect." },
  { before: "En aquella época, el equipo", after: " un entrenador muy exigente.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "At that time, the team had a very demanding coach.", level: "intermediate", reason: "A background situation uses imperfect." },
  { before: "A esa hora, nosotros todavía", after: " la cena.", infinitive: "preparar", preterite: "preparamos", imperfect: "preparábamos", answerTense: "imperfect", en: "At that hour, we were still preparing dinner.", level: "basic", reason: "An action in progress at a specific hour uses imperfect." },
  { before: "Aquel invierno, mis padres", after: " de vender la casa.", infinitive: "hablar", preterite: "hablaron", imperfect: "hablaban", answerTense: "imperfect", en: "That winter, my parents were talking about selling the house.", level: "intermediate", reason: "A background ongoing topic uses imperfect." },
  { before: "En aquellos años, yo", after: " muy poco dinero.", infinitive: "tener", preterite: "tuve", imperfect: "tenía", answerTense: "imperfect", en: "In those years, I had very little money.", level: "basic", reason: "A background situation uses imperfect." },
  { before: "Por entonces, la ciudad no", after: " tanto tráfico como ahora.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "Back then, the city didn't have as much traffic as now.", level: "intermediate", reason: "A background description uses imperfect." },
  { before: "Esa noche, afuera", after: " mucho viento.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "imperfect", en: "That night, it was very windy outside.", level: "basic", reason: "A background weather description uses imperfect." },
  { before: "En aquel restaurante, los camareros", after: " muy buen servicio.", infinitive: "dar", preterite: "dieron", imperfect: "daban", answerTense: "imperfect", en: "At that restaurant, the waiters used to give very good service.", level: "intermediate", reason: "A background characteristic uses imperfect." },
  { before: "Mientras tanto, mi jefe", after: " instrucciones por teléfono.", infinitive: "dar", preterite: "dio", imperfect: "daba", answerTense: "imperfect", en: "Meanwhile, my boss was giving instructions over the phone.", level: "intermediate", reason: "Mientras tanto frames a background action." },

  // --- Descriptions (background description: age, appearance, weather, knowledge, feelings) ---
  { before: "En aquella foto, mi madre", after: " solo veinte años.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "In that photo, my mother was only twenty years old.", level: "basic", reason: "Age in the past is described with imperfect." },
  { before: "Cuando lo conocí, él", after: " barba y el pelo largo.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "When I met him, he had a beard and long hair.", level: "intermediate", reason: "A physical description in the past uses imperfect." },
  { before: "Aquella tarde", after: " un día precioso.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "imperfect", en: "That afternoon it was a beautiful day.", level: "basic", reason: "A weather description uses imperfect." },
  { before: "Esa mañana", after: " mucho sol.", infinitive: "hacer", preterite: "hizo", imperfect: "hacía", answerTense: "imperfect", en: "That morning it was very sunny.", level: "basic", reason: "A weather description uses imperfect." },
  { before: "De joven, mi abuelo", after: " mucho de historia.", infinitive: "saber", preterite: "supo", imperfect: "sabía", answerTense: "imperfect", en: "As a young man, my grandfather knew a lot about history.", level: "intermediate", reason: "A background knowledge description uses imperfect." },
  { before: "Mi tía", after: " tocar el piano de oído.", infinitive: "saber", preterite: "supo", imperfect: "sabía", answerTense: "imperfect", en: "My aunt knew how to play the piano by ear.", level: "intermediate", reason: "A background skill description uses imperfect." },
  { before: "De niño, yo", after: " correr muy rápido.", infinitive: "poder", preterite: "pude", imperfect: "podía", answerTense: "imperfect", en: "As a child, I could run very fast.", level: "basic", reason: "A general past ability uses imperfect." },
  { before: "Mi padre", after: " levantar mucho peso cuando era joven.", infinitive: "poder", preterite: "pudo", imperfect: "podía", answerTense: "imperfect", en: "My father could lift a lot of weight when he was young.", level: "intermediate", reason: "A general past ability uses imperfect." },
  { before: "En aquella empresa, los empleados", after: " trabajar desde casa dos días a la semana.", infinitive: "poder", preterite: "pudieron", imperfect: "podían", answerTense: "imperfect", en: "At that company, employees could work from home two days a week.", level: "intermediate", reason: "A general past situation described with imperfect." },
  { before: "De pequeño, yo siempre", after: " ser piloto.", infinitive: "querer", preterite: "quise", imperfect: "quería", answerTense: "imperfect", en: "As a little kid, I always wanted to be a pilot.", level: "basic", reason: "A general past desire uses imperfect." },
  { before: "Mi hermana", after: " ayudar a los demás siempre.", infinitive: "querer", preterite: "quiso", imperfect: "quería", answerTense: "imperfect", en: "My sister always wanted to help others.", level: "intermediate", reason: "A general personality trait or desire uses imperfect." },
  { before: "Antes de la operación, mi abuelo", after: " mucho miedo.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "Before the surgery, my grandfather was very afraid.", level: "basic", reason: "A background emotional description uses imperfect." },
  { before: "Antes de mudarnos, nuestro piso", after: " muy poca luz natural.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "Before we moved, our flat had very little natural light.", level: "intermediate", reason: "A background description uses imperfect." },
  { before: "Por las tardes, el sol", after: " directamente en la ventana.", infinitive: "dar", preterite: "dio", imperfect: "daba", answerTense: "imperfect", en: "In the afternoons, the sun used to shine directly into the window.", level: "advanced", reason: "A background description uses imperfect." },
  { before: "En aquel momento, la habitación", after: " un olor extraño.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "At that moment, the room had a strange smell.", level: "intermediate", reason: "A background description uses imperfect." },
  { before: "Cuando era joven, mi abuela", after: " una voz preciosa.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "When she was young, my grandmother had a beautiful voice.", level: "basic", reason: "A background description uses imperfect." },
  { before: "Ese día, el examen", after: " cinco preguntas muy difíciles.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "That day, the exam had five very difficult questions.", level: "intermediate", reason: "A background description uses imperfect." },
  { before: "Cuando yo tenía diez años, mi familia", after: " un perro enorme.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "When I was ten, my family had a huge dog.", level: "basic", reason: "A background description uses imperfect." },
  { before: "Esa tarde, el parque", after: " mucha gente paseando.", infinitive: "tener", preterite: "tuvo", imperfect: "tenía", answerTense: "imperfect", en: "That afternoon, the park had a lot of people strolling around.", level: "intermediate", reason: "A background description uses imperfect." },

  // --- Interruptions (an ongoing imperfect action interrupted by a preterite event) ---
  { before: "Mientras yo", after: " la cena, se apagó la luz.", infinitive: "preparar", preterite: "preparé", imperfect: "preparaba", answerTense: "imperfect", en: "While I was preparing dinner, the light went out.", level: "basic", reason: "Mientras sets an ongoing background action interrupted by another event." },
  { before: "Yo", after: " cuando sonó el teléfono.", infinitive: "escribir", preterite: "escribí", imperfect: "escribía", answerTense: "imperfect", en: "I was writing when the phone rang.", level: "basic", reason: "The ongoing action interrupted by cuando uses imperfect." },
  { before: "Nosotros", after: " cuando empezó a llover.", infinitive: "comer", preterite: "comimos", imperfect: "comíamos", answerTense: "imperfect", en: "We were eating when it started to rain.", level: "basic", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras el profesor", after: " el examen, un alumno llegó tarde.", infinitive: "explicar", preterite: "explicó", imperfect: "explicaba", answerTense: "imperfect", en: "While the teacher was explaining the exam, a student arrived late.", level: "intermediate", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "Ana", after: " cuando se cortó la luz.", infinitive: "trabajar", preterite: "trabajó", imperfect: "trabajaba", answerTense: "imperfect", en: "Ana was working when the power went out.", level: "basic", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras nosotros", after: " del problema, llegó la solución por correo.", infinitive: "hablar", preterite: "hablamos", imperfect: "hablábamos", answerTense: "imperfect", en: "While we were talking about the problem, the solution arrived by email.", level: "intermediate", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "Los niños", after: " cuando su madre los llamó.", infinitive: "leer", preterite: "leyeron", imperfect: "leían", answerTense: "imperfect", en: "The children were reading when their mother called them.", level: "basic", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras yo le", after: " la verdad, él empezó a llorar.", infinitive: "decir", preterite: "dije", imperfect: "decía", answerTense: "imperfect", en: "While I was telling him the truth, he started to cry.", level: "intermediate", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "Tú", after: " cuando te llamé por primera vez.", infinitive: "estudiar", preterite: "estudiaste", imperfect: "estudiabas", answerTense: "imperfect", en: "You were studying when I called you for the first time.", level: "basic", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras el camarero", after: " la mesa, se rompió un vaso.", infinitive: "preparar", preterite: "preparó", imperfect: "preparaba", answerTense: "imperfect", en: "While the waiter was setting the table, a glass broke.", level: "intermediate", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "Nosotros", after: " cuando empezó el incendio.", infinitive: "trabajar", preterite: "trabajamos", imperfect: "trabajábamos", answerTense: "imperfect", en: "We were working when the fire started.", level: "intermediate", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Yo le", after: " el mensaje cuando se cortó internet.", infinitive: "escribir", preterite: "escribí", imperfect: "escribía", answerTense: "imperfect", en: "I was writing him the message when the internet cut out.", level: "intermediate", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras Carla", after: " en el jardín, empezó a nevar.", infinitive: "trabajar", preterite: "trabajó", imperfect: "trabajaba", answerTense: "imperfect", en: "While Carla was working in the garden, it started to snow.", level: "basic", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "El público", after: " cuando se apagaron las luces del teatro.", infinitive: "hablar", preterite: "habló", imperfect: "hablaba", answerTense: "imperfect", en: "The audience was talking when the theatre lights went out.", level: "intermediate", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras mis padres", after: " la cena, yo puse la mesa.", infinitive: "preparar", preterite: "prepararon", imperfect: "preparaban", answerTense: "imperfect", en: "While my parents were preparing dinner, I set the table.", level: "basic", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "Yo", after: " cuando por fin llegó la noticia.", infinitive: "trabajar", preterite: "trabajé", imperfect: "trabajaba", answerTense: "imperfect", en: "I was working when the news finally arrived.", level: "basic", reason: "The interrupted ongoing action uses imperfect." },
  { before: "Mientras el director", after: " el discurso, se fue la luz.", infinitive: "leer", preterite: "leyó", imperfect: "leía", answerTense: "imperfect", en: "While the director was reading the speech, the power went out.", level: "intermediate", reason: "Mientras sets an ongoing action interrupted by another event." },
  { before: "Los estudiantes", after: " cuando sonó la alarma de incendios.", infinitive: "estudiar", preterite: "estudiaron", imperfect: "estudiaban", answerTense: "imperfect", en: "The students were studying when the fire alarm went off.", level: "basic", reason: "The interrupted ongoing action uses imperfect." },
];

export const PRETERITE_IMPERFECT_QUESTIONS: Question[] = templates.map((template, index) => ({
  id: 3001 + index,
  before: template.before,
  after: template.after,
  infinitive: template.infinitive,
  answer: template[template.answerTense],
  verbAnswer: template.answerTense,
  objectPronoun: template.answerTense === "preterite" ? template.imperfect : template.preterite,
  explanation: `${template.reason} Correct tense: ${template.answerTense}.`,
  translations: { en: template.en, pl: "" },
  subjectNumber: "singular",
  isActivity: false,
  indirectObject: template.answerTense,
  tense: template.answerTense,
  level: template.level,
}));

export const PRETERITE_IMPERFECT_FORMS: Record<string, [string, string]> = Object.fromEntries(
  [...new Set(templates.map((template) => template.infinitive))].map((infinitive) => [infinitive, ["preterite", "imperfect"]]),
);

export const PRETERITE_IMPERFECT_CONJUGATIONS: Record<string, Array<{ subject: string; preterite: string; imperfect: string }>> = {
  ir: [
    { subject: "yo", preterite: "fui", imperfect: "iba" },
    { subject: "tú", preterite: "fuiste", imperfect: "ibas" },
    { subject: "él / ella / usted", preterite: "fue", imperfect: "iba" },
    { subject: "nosotros", preterite: "fuimos", imperfect: "íbamos" },
    { subject: "vosotros", preterite: "fuisteis", imperfect: "ibais" },
    { subject: "ellos / ellas / ustedes", preterite: "fueron", imperfect: "iban" },
  ],
  preparar: [
    { subject: "yo", preterite: "preparé", imperfect: "preparaba" },
    { subject: "tú", preterite: "preparaste", imperfect: "preparabas" },
    { subject: "él / ella / usted", preterite: "preparó", imperfect: "preparaba" },
    { subject: "nosotros", preterite: "preparamos", imperfect: "preparábamos" },
    { subject: "vosotros", preterite: "preparasteis", imperfect: "preparabais" },
    { subject: "ellos / ellas / ustedes", preterite: "prepararon", imperfect: "preparaban" },
  ],
  salir: [
    { subject: "yo", preterite: "salí", imperfect: "salía" },
    { subject: "tú", preterite: "saliste", imperfect: "salías" },
    { subject: "él / ella / usted", preterite: "salió", imperfect: "salía" },
    { subject: "nosotros", preterite: "salimos", imperfect: "salíamos" },
    { subject: "vosotros", preterite: "salisteis", imperfect: "salíais" },
    { subject: "ellos / ellas / ustedes", preterite: "salieron", imperfect: "salían" },
  ],
  llegar: [
    { subject: "yo", preterite: "llegué", imperfect: "llegaba" },
    { subject: "tú", preterite: "llegaste", imperfect: "llegabas" },
    { subject: "él / ella / usted", preterite: "llegó", imperfect: "llegaba" },
    { subject: "nosotros", preterite: "llegamos", imperfect: "llegábamos" },
    { subject: "vosotros", preterite: "llegasteis", imperfect: "llegabais" },
    { subject: "ellos / ellas / ustedes", preterite: "llegaron", imperfect: "llegaban" },
  ],
  vivir: [
    { subject: "yo", preterite: "viví", imperfect: "vivía" },
    { subject: "tú", preterite: "viviste", imperfect: "vivías" },
    { subject: "él / ella / usted", preterite: "vivió", imperfect: "vivía" },
    { subject: "nosotros", preterite: "vivimos", imperfect: "vivíamos" },
    { subject: "vosotros", preterite: "vivisteis", imperfect: "vivíais" },
    { subject: "ellos / ellas / ustedes", preterite: "vivieron", imperfect: "vivían" },
  ],
  explicar: [
    { subject: "yo", preterite: "expliqué", imperfect: "explicaba" },
    { subject: "tú", preterite: "explicaste", imperfect: "explicabas" },
    { subject: "él / ella / usted", preterite: "explicó", imperfect: "explicaba" },
    { subject: "nosotros", preterite: "explicamos", imperfect: "explicábamos" },
    { subject: "vosotros", preterite: "explicasteis", imperfect: "explicabais" },
    { subject: "ellos / ellas / ustedes", preterite: "explicaron", imperfect: "explicaban" },
  ],
  ponerse: [
    { subject: "yo", preterite: "me puse", imperfect: "me ponía" },
    { subject: "tú", preterite: "te pusiste", imperfect: "te ponías" },
    { subject: "él / ella / usted", preterite: "se puso", imperfect: "se ponía" },
    { subject: "nosotros", preterite: "nos pusimos", imperfect: "nos poníamos" },
    { subject: "vosotros", preterite: "os pusisteis", imperfect: "os poníais" },
    { subject: "ellos / ellas / ustedes", preterite: "se pusieron", imperfect: "se ponían" },
  ],
  empezar: [
    { subject: "yo", preterite: "empecé", imperfect: "empezaba" },
    { subject: "tú", preterite: "empezaste", imperfect: "empezabas" },
    { subject: "él / ella / usted", preterite: "empezó", imperfect: "empezaba" },
    { subject: "nosotros", preterite: "empezamos", imperfect: "empezábamos" },
    { subject: "vosotros", preterite: "empezasteis", imperfect: "empezabais" },
    { subject: "ellos / ellas / ustedes", preterite: "empezaron", imperfect: "empezaban" },
  ],
  hablar: [
    { subject: "yo", preterite: "hablé", imperfect: "hablaba" },
    { subject: "tú", preterite: "hablaste", imperfect: "hablabas" },
    { subject: "él / ella / usted", preterite: "habló", imperfect: "hablaba" },
    { subject: "nosotros", preterite: "hablamos", imperfect: "hablábamos" },
    { subject: "vosotros", preterite: "hablasteis", imperfect: "hablabais" },
    { subject: "ellos / ellas / ustedes", preterite: "hablaron", imperfect: "hablaban" },
  ],
  comer: [
    { subject: "yo", preterite: "comí", imperfect: "comía" },
    { subject: "tú", preterite: "comiste", imperfect: "comías" },
    { subject: "él / ella / usted", preterite: "comió", imperfect: "comía" },
    { subject: "nosotros", preterite: "comimos", imperfect: "comíamos" },
    { subject: "vosotros", preterite: "comisteis", imperfect: "comíais" },
    { subject: "ellos / ellas / ustedes", preterite: "comieron", imperfect: "comían" },
  ],
  escribir: [
    { subject: "yo", preterite: "escribí", imperfect: "escribía" },
    { subject: "tú", preterite: "escribiste", imperfect: "escribías" },
    { subject: "él / ella / usted", preterite: "escribió", imperfect: "escribía" },
    { subject: "nosotros", preterite: "escribimos", imperfect: "escribíamos" },
    { subject: "vosotros", preterite: "escribisteis", imperfect: "escribíais" },
    { subject: "ellos / ellas / ustedes", preterite: "escribieron", imperfect: "escribían" },
  ],
  trabajar: [
    { subject: "yo", preterite: "trabajé", imperfect: "trabajaba" },
    { subject: "tú", preterite: "trabajaste", imperfect: "trabajabas" },
    { subject: "él / ella / usted", preterite: "trabajó", imperfect: "trabajaba" },
    { subject: "nosotros", preterite: "trabajamos", imperfect: "trabajábamos" },
    { subject: "vosotros", preterite: "trabajasteis", imperfect: "trabajabais" },
    { subject: "ellos / ellas / ustedes", preterite: "trabajaron", imperfect: "trabajaban" },
  ],
  estudiar: [
    { subject: "yo", preterite: "estudié", imperfect: "estudiaba" },
    { subject: "tú", preterite: "estudiaste", imperfect: "estudiabas" },
    { subject: "él / ella / usted", preterite: "estudió", imperfect: "estudiaba" },
    { subject: "nosotros", preterite: "estudiamos", imperfect: "estudiábamos" },
    { subject: "vosotros", preterite: "estudiasteis", imperfect: "estudiabais" },
    { subject: "ellos / ellas / ustedes", preterite: "estudiaron", imperfect: "estudiaban" },
  ],
  comprar: [
    { subject: "yo", preterite: "compré", imperfect: "compraba" },
    { subject: "tú", preterite: "compraste", imperfect: "comprabas" },
    { subject: "él / ella / usted", preterite: "compró", imperfect: "compraba" },
    { subject: "nosotros", preterite: "compramos", imperfect: "comprábamos" },
    { subject: "vosotros", preterite: "comprasteis", imperfect: "comprabais" },
    { subject: "ellos / ellas / ustedes", preterite: "compraron", imperfect: "compraban" },
  ],
  leer: [
    { subject: "yo", preterite: "leí", imperfect: "leía" },
    { subject: "tú", preterite: "leíste", imperfect: "leías" },
    { subject: "él / ella / usted", preterite: "leyó", imperfect: "leía" },
    { subject: "nosotros", preterite: "leímos", imperfect: "leíamos" },
    { subject: "vosotros", preterite: "leísteis", imperfect: "leíais" },
    { subject: "ellos / ellas / ustedes", preterite: "leyeron", imperfect: "leían" },
  ],
  decidir: [
    { subject: "yo", preterite: "decidí", imperfect: "decidía" },
    { subject: "tú", preterite: "decidiste", imperfect: "decidías" },
    { subject: "él / ella / usted", preterite: "decidió", imperfect: "decidía" },
    { subject: "nosotros", preterite: "decidimos", imperfect: "decidíamos" },
    { subject: "vosotros", preterite: "decidisteis", imperfect: "decidíais" },
    { subject: "ellos / ellas / ustedes", preterite: "decidieron", imperfect: "decidían" },
  ],
  tener: [
    { subject: "yo", preterite: "tuve", imperfect: "tenía" },
    { subject: "tú", preterite: "tuviste", imperfect: "tenías" },
    { subject: "él / ella / usted", preterite: "tuvo", imperfect: "tenía" },
    { subject: "nosotros", preterite: "tuvimos", imperfect: "teníamos" },
    { subject: "vosotros", preterite: "tuvisteis", imperfect: "teníais" },
    { subject: "ellos / ellas / ustedes", preterite: "tuvieron", imperfect: "tenían" },
  ],
  hacer: [
    { subject: "yo", preterite: "hice", imperfect: "hacía" },
    { subject: "tú", preterite: "hiciste", imperfect: "hacías" },
    { subject: "él / ella / usted", preterite: "hizo", imperfect: "hacía" },
    { subject: "nosotros", preterite: "hicimos", imperfect: "hacíamos" },
    { subject: "vosotros", preterite: "hicisteis", imperfect: "hacíais" },
    { subject: "ellos / ellas / ustedes", preterite: "hicieron", imperfect: "hacían" },
  ],
  poder: [
    { subject: "yo", preterite: "pude", imperfect: "podía" },
    { subject: "tú", preterite: "pudiste", imperfect: "podías" },
    { subject: "él / ella / usted", preterite: "pudo", imperfect: "podía" },
    { subject: "nosotros", preterite: "pudimos", imperfect: "podíamos" },
    { subject: "vosotros", preterite: "pudisteis", imperfect: "podíais" },
    { subject: "ellos / ellas / ustedes", preterite: "pudieron", imperfect: "podían" },
  ],
  querer: [
    { subject: "yo", preterite: "quise", imperfect: "quería" },
    { subject: "tú", preterite: "quisiste", imperfect: "querías" },
    { subject: "él / ella / usted", preterite: "quiso", imperfect: "quería" },
    { subject: "nosotros", preterite: "quisimos", imperfect: "queríamos" },
    { subject: "vosotros", preterite: "quisisteis", imperfect: "queríais" },
    { subject: "ellos / ellas / ustedes", preterite: "quisieron", imperfect: "querían" },
  ],
  decir: [
    { subject: "yo", preterite: "dije", imperfect: "decía" },
    { subject: "tú", preterite: "dijiste", imperfect: "decías" },
    { subject: "él / ella / usted", preterite: "dijo", imperfect: "decía" },
    { subject: "nosotros", preterite: "dijimos", imperfect: "decíamos" },
    { subject: "vosotros", preterite: "dijisteis", imperfect: "decíais" },
    { subject: "ellos / ellas / ustedes", preterite: "dijeron", imperfect: "decían" },
  ],
  dar: [
    { subject: "yo", preterite: "di", imperfect: "daba" },
    { subject: "tú", preterite: "diste", imperfect: "dabas" },
    { subject: "él / ella / usted", preterite: "dio", imperfect: "daba" },
    { subject: "nosotros", preterite: "dimos", imperfect: "dábamos" },
    { subject: "vosotros", preterite: "disteis", imperfect: "dabais" },
    { subject: "ellos / ellas / ustedes", preterite: "dieron", imperfect: "daban" },
  ],
  poner: [
    { subject: "yo", preterite: "puse", imperfect: "ponía" },
    { subject: "tú", preterite: "pusiste", imperfect: "ponías" },
    { subject: "él / ella / usted", preterite: "puso", imperfect: "ponía" },
    { subject: "nosotros", preterite: "pusimos", imperfect: "poníamos" },
    { subject: "vosotros", preterite: "pusisteis", imperfect: "poníais" },
    { subject: "ellos / ellas / ustedes", preterite: "pusieron", imperfect: "ponían" },
  ],
  saber: [
    { subject: "yo", preterite: "supe", imperfect: "sabía" },
    { subject: "tú", preterite: "supiste", imperfect: "sabías" },
    { subject: "él / ella / usted", preterite: "supo", imperfect: "sabía" },
    { subject: "nosotros", preterite: "supimos", imperfect: "sabíamos" },
    { subject: "vosotros", preterite: "supisteis", imperfect: "sabíais" },
    { subject: "ellos / ellas / ustedes", preterite: "supieron", imperfect: "sabían" },
  ],
};

/**
 * Regularity scoped strictly to preterite/imperfect behavior — a verb irregular elsewhere
 * (e.g. salir's present-tense "salgo") can still be fully regular in these two tenses.
 * "spelling change" marks a yo-preterite orthographic shift (g→gu, c→qu, z→c before e) that
 * keeps the same sound rather than a true stem irregularity — a distinct, real category, not a
 * softened "irregular".
 */
export const PRETERITE_IMPERFECT_REGULARITY: Record<string, "regular" | "irregular" | "spelling change"> = {
  ir: "irregular",
  ponerse: "irregular",
  preparar: "regular",
  vivir: "regular",
  salir: "regular",
  llegar: "spelling change",
  explicar: "spelling change",
  empezar: "spelling change",
  hablar: "regular",
  comer: "regular",
  escribir: "regular",
  trabajar: "regular",
  estudiar: "regular",
  comprar: "regular",
  leer: "irregular",
  decidir: "regular",
  tener: "irregular",
  hacer: "irregular",
  poder: "irregular",
  querer: "irregular",
  decir: "irregular",
  dar: "irregular",
  poner: "irregular",
  saber: "irregular",
};
