import type { Question } from "./quiz-data";
import { applySourcedQuestionPair } from "./sourced-quiz-content.ts";
import { withItemExplanation } from "./item-explanation.ts";
import { SER_ESTAR_EXPLANATIONS } from "./explanations-ser-estar.ts";

const seed = [
  ["Yo", " de México.", "soy", "estoy", "I am from Mexico.", "basic"],
  ["Marta", " médica.", "es", "está", "Marta is a doctor.", "basic"],
  ["Nosotros", " estudiantes de español.", "somos", "estamos", "We are Spanish students.", "basic"],
  ["La mesa", " de madera.", "es", "está", "The table is made of wood.", "basic"],
  ["Hoy", " lunes.", "es", "está", "Today is Monday.", "basic"],
  ["Las llaves", " de Ana.", "son", "están", "The keys belong to Ana.", "basic"],
  ["El concierto", " en el teatro.", "es", "está", "The concert is at the theatre.", "basic"],
  ["La ventana", " grande y luminosa.", "es", "está", "The window is large and bright.", "basic"],
  ["Yo", " en casa ahora.", "estoy", "soy", "I am at home now.", "basic"],
  ["Las mochilas", " debajo de la mesa.", "están", "son", "The backpacks are under the table.", "basic"],
  ["¿Cómo", " tú esta mañana?", "estás", "eres", "How are you this morning?", "basic"],
  ["El café", " caliente.", "está", "es", "The coffee is hot.", "basic"],
  ["Mis amigos", " cansados después del viaje.", "están", "son", "My friends are tired after the trip.", "basic"],
  ["La puerta", " cerrada.", "está", "es", "The door is closed.", "basic"],
  ["El museo", " cerca de la estación.", "está", "es", "The museum is near the station.", "intermediate"],
  ["La sopa", " muy buena hoy.", "está", "es", "The soup tastes very good today.", "intermediate"],
  ["Mi hermano", " listo para salir.", "está", "es", "My brother is ready to leave.", "intermediate"],
  ["Clara", " lista y curiosa.", "es", "está", "Clara is clever and curious.", "intermediate"],
  ["El barrio", " tranquilo por la noche.", "es", "está", "The neighbourhood is quiet at night.", "intermediate"],
  ["El barrio", " vacío esta noche.", "está", "es", "The neighbourhood is empty tonight.", "intermediate"],
  ["La camisa", " azul.", "es", "está", "The shirt is blue.", "intermediate"],
  ["La camisa", " mojada.", "está", "es", "The shirt is wet.", "intermediate"],
  ["La reunión", " a las tres.", "es", "está", "The meeting is at three.", "advanced"],
  ["Los niños", " en el jardín.", "están", "son", "The children are in the garden.", "advanced"],
  ["La película", " aburrida para mí.", "es", "está", "The film is boring to me.", "advanced"],
  ["Yo", " aburrido durante la película.", "estoy", "soy", "I am bored during the film.", "advanced"],
  ["El profesor", " enfermo esta semana.", "está", "es", "The teacher is ill this week.", "advanced"],
  ["El profesor", " muy paciente.", "es", "está", "The teacher is very patient.", "advanced"],
  ["La puerta", " abierta porque hace calor.", "está", "es", "The door is open because it is hot.", "advanced"],
  ["La conferencia", " en el auditorio principal.", "es", "está", "The conference is in the main auditorium.", "advanced"],

  // --- Issue #24, Stage 5: identity (profession, role, relationship) ---
  ["Yo", " ingeniera.", "soy", "estoy", "I am an engineer.", "basic"],
  ["Tú", " mi mejor amigo.", "eres", "estás", "You are my best friend.", "basic"],
  ["Ella", " periodista.", "es", "está", "She is a journalist.", "basic"],
  ["Nosotros", " vecinos desde hace años.", "somos", "estamos", "We have been neighbours for years.", "basic"],
  ["Ellos", " los dueños de la tienda.", "son", "están", "They are the owners of the shop.", "basic"],
  ["Mi tío", " abogado en Madrid.", "es", "está", "My uncle is a lawyer in Madrid.", "basic"],
  ["Yo", " la capitana del equipo.", "soy", "estoy", "I am the team captain.", "basic"],
  ["Mis padres", " dentistas.", "son", "están", "My parents are dentists.", "basic"],
  ["Tú", " un buen compañero de trabajo.", "eres", "estás", "You are a good coworker.", "basic"],
  ["El señor García", " el director del colegio.", "es", "está", "Mr. García is the school principal.", "basic"],
  ["Nosotros", " hermanos, no primos.", "somos", "estamos", "We are brothers, not cousins.", "intermediate"],
  ["Ana y Luis", " los organizadores del evento.", "son", "están", "Ana and Luis are the organisers of the event.", "intermediate"],
  ["Yo", " cliente habitual de esta cafetería.", "soy", "estoy", "I am a regular customer at this café.", "intermediate"],
  ["Ustedes", " los nuevos socios de la empresa.", "son", "están", "You all are the new partners in the company.", "intermediate"],
  ["Ella", " la autora de esta novela.", "es", "está", "She is the author of this novel.", "intermediate"],

  // --- Origin ---
  ["Yo", " de Polonia.", "soy", "estoy", "I am from Poland.", "basic"],
  ["Tú", " de una familia italiana.", "eres", "estás", "You are from an Italian family.", "basic"],
  ["Estos quesos", " de Francia.", "son", "están", "These cheeses are from France.", "basic"],
  ["El vino", " de la región de Rioja.", "es", "está", "The wine is from the Rioja region.", "basic"],
  ["Nosotros", " de la misma ciudad.", "somos", "estamos", "We are from the same city.", "basic"],
  ["Mi abuela", " de un pueblo pequeño.", "es", "está", "My grandmother is from a small village.", "basic"],
  ["Esas naranjas", " de Valencia.", "son", "están", "Those oranges are from Valencia.", "intermediate"],
  ["Tú", " de padres extranjeros.", "eres", "estás", "You are the child of foreign parents.", "intermediate"],
  ["El profesor", " de Argentina.", "es", "está", "The teacher is from Argentina.", "basic"],
  ["Estas telas", " de la India.", "son", "están", "These fabrics are from India.", "intermediate"],
  ["Yo", " originaria de un pueblo costero.", "soy", "estoy", "I originally come from a coastal town.", "intermediate"],
  ["Mis compañeros", " de distintas partes del país.", "son", "están", "My colleagues are from different parts of the country.", "intermediate"],
  ["Este café", " de Colombia.", "es", "está", "This coffee is from Colombia.", "basic"],
  ["Nosotros", " de una tradición familiar muy antigua.", "somos", "estamos", "We come from a very old family tradition.", "advanced"],
  ["Ella", " de ascendencia mexicana.", "es", "está", "She is of Mexican descent.", "advanced"],

  // --- Defining characteristics (physical, personality, inherent qualities) ---
  ["Mi hermana", " muy generosa.", "es", "está", "My sister is very generous.", "basic"],
  ["Tú", " alto y delgado.", "eres", "estás", "You are tall and thin.", "basic"],
  ["Este edificio", " muy antiguo.", "es", "está", "This building is very old.", "basic"],
  ["Los niños", " curiosos por naturaleza.", "son", "están", "Children are curious by nature.", "basic"],
  ["Yo", " bastante paciente.", "soy", "estoy", "I am quite patient.", "basic"],
  ["Esta ciudad", " muy ruidosa.", "es", "está", "This city is very noisy.", "basic"],
  ["Nosotros", " muy trabajadores.", "somos", "estamos", "We are very hardworking.", "basic"],
  ["El examen", " bastante difícil.", "es", "está", "The exam is quite difficult.", "basic"],
  ["Sus ojos", " verdes.", "son", "están", "Her eyes are green.", "basic"],
  ["Este barrio", " conocido por sus restaurantes.", "es", "está", "This neighbourhood is known for its restaurants.", "intermediate"],
  ["Tú", " muy creativa.", "eres", "estás", "You are very creative.", "basic"],
  ["El profesor", " muy exigente.", "es", "está", "The teacher is very demanding.", "basic"],
  ["Mis padres", " bastante estrictos.", "son", "están", "My parents are quite strict.", "basic"],
  ["Esta película", " larga y lenta.", "es", "está", "This film is long and slow.", "intermediate"],
  ["El río", " ancho y profundo en esta parte.", "es", "está", "The river is wide and deep in this part.", "intermediate"],

  // --- Material and time/date ---
  ["La silla", " de plástico.", "es", "está", "The chair is made of plastic.", "basic"],
  ["Hoy", " miércoles.", "es", "está", "Today is Wednesday.", "basic"],
  ["", " las ocho de la mañana.", "son", "están", "It is eight in the morning.", "basic"],
  ["El concierto", " el próximo sábado.", "es", "está", "The concert is next Saturday.", "basic"],
  ["Esta mesa", " de metal.", "es", "está", "This table is made of metal.", "basic"],
  ["Mañana", " el cumpleaños de Sara.", "es", "está", "Tomorrow is Sara's birthday.", "basic"],
  ["El anillo", " de oro.", "es", "está", "The ring is made of gold.", "basic"],
  ["Hoy", " tres de mayo.", "es", "está", "Today is the third of May.", "basic"],
  ["La entrevista", " a las cinco.", "es", "está", "The interview is at five o'clock.", "basic"],
  ["Estas copas", " de cristal.", "son", "están", "These glasses are made of crystal.", "basic"],
  ["", " la una y media.", "es", "está", "It is half past one.", "basic"],
  ["El examen final", " el viernes.", "es", "está", "The final exam is on Friday.", "basic"],
  ["La estatua", " de bronce.", "es", "está", "The statue is made of bronze.", "intermediate"],
  ["La boda", " en agosto.", "es", "está", "The wedding is in August.", "intermediate"],
  ["Esta manta", " de lana.", "es", "está", "This blanket is made of wool.", "intermediate"],

  // --- Location (physical location vs. an event's location) ---
  ["El supermercado", " a dos calles de aquí.", "está", "es", "The supermarket is two streets from here.", "basic"],
  ["Mis gafas", " encima de la mesa.", "están", "son", "My glasses are on the table.", "basic"],
  ["La boda", " en un jardín.", "es", "está", "The wedding is in a garden.", "intermediate"],
  ["El hospital", " al lado de la farmacia.", "está", "es", "The hospital is next to the pharmacy.", "basic"],
  ["La exposición", " en el centro cultural.", "es", "está", "The exhibition is at the cultural centre.", "intermediate"],
  ["Los libros", " en la estantería.", "están", "son", "The books are on the shelf.", "basic"],
  ["Yo", " en la sala de espera.", "estoy", "soy", "I am in the waiting room.", "basic"],
  ["La ceremonia", " en la plaza principal.", "es", "está", "The ceremony is in the main square.", "intermediate"],
  ["El parque", " detrás del colegio.", "está", "es", "The park is behind the school.", "basic"],
  ["Nosotros", " en la última fila.", "estamos", "somos", "We are in the last row.", "basic"],
  ["La feria", " fuera de la ciudad este año.", "es", "está", "The fair is outside the city this year.", "intermediate"],
  ["Tus llaves", " dentro del cajón.", "están", "son", "Your keys are inside the drawer.", "basic"],
  ["El aeropuerto", " lejos del centro.", "está", "es", "The airport is far from the city centre.", "basic"],
  ["La reunión anual", " en otra ciudad este año.", "es", "está", "The annual meeting is in another city this year.", "intermediate"],
  ["Los niños", " en el patio.", "están", "son", "The children are in the playground.", "basic"],

  // --- Conditions (temporary physical or emotional states) ---
  ["Yo", " muy cansada hoy.", "estoy", "soy", "I am very tired today.", "basic"],
  ["La ventana", " abierta.", "está", "es", "The window is open.", "basic"],
  ["Mi hermano", " enfadado conmigo.", "está", "es", "My brother is angry with me.", "basic"],
  ["El agua", " helada.", "está", "es", "The water is freezing cold.", "basic"],
  ["Nosotros", " preocupados por el examen.", "estamos", "somos", "We are worried about the exam.", "basic"],
  ["Las tiendas", " cerradas los domingos.", "están", "son", "The shops are closed on Sundays.", "basic"],
  ["Yo", " emocionada por el viaje.", "estoy", "soy", "I am excited about the trip.", "basic"],
  ["El pastel", " todavía caliente.", "está", "es", "The cake is still warm.", "basic"],
  ["Mis padres", " de vacaciones esta semana.", "están", "son", "My parents are on vacation this week.", "basic"],
  ["Tú", " resfriado, ¿verdad?", "estás", "eres", "You have a cold, right?", "basic"],
  ["La leche", " a punto de caducar.", "está", "es", "The milk is about to expire.", "intermediate"],
  ["El equipo", " nervioso antes del partido.", "está", "es", "The team is nervous before the match.", "intermediate"],
  ["Las calles", " mojadas después de la lluvia.", "están", "son", "The streets are wet after the rain.", "basic"],
  ["Yo", " un poco confundida con esta pregunta.", "estoy", "soy", "I am a bit confused by this question.", "intermediate"],
  ["El ambiente", " tenso en la oficina hoy.", "está", "es", "The atmosphere is tense in the office today.", "intermediate"],

  // --- Changing states / results of a change ---
  ["El trabajo", " ya terminado.", "está", "es", "The work is already finished.", "basic"],
  ["La puerta", " rota desde ayer.", "está", "es", "The door has been broken since yesterday.", "basic"],
  ["Después de la operación, mi abuelo", " mucho mejor.", "está", "es", "After the surgery, my grandfather is much better.", "intermediate"],
  ["El pan", " duro; llevaba días fuera.", "está", "es", "The bread is hard; it had been out for days.", "intermediate"],
  ["Desde que empezó a estudiar más, ella", " mucho más segura en los exámenes.", "está", "es", "Since she started studying more, she is much more confident in exams.", "advanced"],
  ["El jarrón", " roto en pedazos.", "está", "es", "The vase is broken into pieces.", "basic"],
  ["Después de tantos cambios, la empresa", " irreconocible.", "está", "es", "After so many changes, the company is unrecognisable.", "advanced"],
  ["La fruta", " madura ya.", "está", "es", "The fruit is ripe now.", "basic"],
  ["El niño", " más alto que el año pasado.", "está", "es", "The boy has gotten taller than last year.", "intermediate"],
  ["La habitación", " ordenada por fin.", "está", "es", "The room is tidy at last.", "basic"],
  ["Después del susto, todos", " más tranquilos.", "están", "son", "After the scare, everyone is calmer now.", "intermediate"],
  ["El proyecto", " casi acabado.", "está", "es", "The project is almost finished.", "basic"],
  ["Tu español", " mucho mejor que antes.", "está", "es", "Your Spanish is much better than before.", "intermediate"],
  ["Las plantas", " secas después de tantos días de calor.", "están", "son", "The plants are dry after so many hot days.", "intermediate"],
  ["El coche", " reparado desde el lunes.", "está", "es", "The car has been repaired since Monday.", "intermediate"],

  // --- Idiomatic ser/estar pairs (the adjective's meaning shifts with the verb) ---
  ["Ese documental", " bastante aburrido.", "es", "está", "That documentary is quite boring.", "intermediate"],
  ["Yo", " aburrido en la clase de historia.", "estoy", "soy", "I am bored in history class.", "intermediate"],
  ["Mi tío", " muy rico.", "es", "está", "My uncle is very wealthy.", "intermediate"],
  ["Esta sopa", " riquísima.", "está", "es", "This soup tastes delicious.", "intermediate"],
  ["Este puente", " seguro para cruzar.", "es", "está", "This bridge is safe to cross.", "intermediate"],
  ["Yo", " segura de mi respuesta.", "estoy", "soy", "I am sure of my answer.", "intermediate"],
  ["Este plato", " malo; no lo pruebes.", "es", "está", "This dish is bad quality; don't try it.", "intermediate"],
  ["Mi hijo", " malo desde ayer.", "está", "es", "My son has been sick since yesterday.", "intermediate"],
  ["Este plátano", " verde todavía.", "está", "es", "This banana is still unripe.", "basic"],
  ["Su color favorito", " verde.", "es", "está", "Her favourite colour is green.", "basic"],
  ["Mi abuelo", " muy vivo para su edad.", "está", "es", "My grandfather is very lively for his age.", "advanced"],
  ["Esta ciudad", " muy viva por las noches.", "es", "está", "This city is very lively at night.", "advanced"],
  ["Tú", " muy despierto para ser tan temprano.", "estás", "eres", "You are very alert for it being so early.", "advanced"],
  ["Mi sobrina", " muy despierta; aprende rápido.", "es", "está", "My niece is very sharp; she learns quickly.", "advanced"],
  ["Ellos", " atentos a cada detalle del proyecto.", "están", "son", "They are attentive to every detail of the project right now.", "advanced"],
] as const;

export const SER_ESTAR_QUESTIONS: Question[] = seed.map(([before, after, answer, alternateAnswer, en, level], index) => ({
  id: 2001 + index,
  before,
  after,
  infinitive: "ser / estar",
  answer,
  verbAnswer: answer,
  objectPronoun: alternateAnswer,
  // Written per item in explanations-ser-estar.ts.
  explanation: "",
  translations: { en, pl: "" },
  subjectNumber: "singular",
  isActivity: false,
  indirectObject: "",
  tense: "present",
  level,
})).map(applySourcedQuestionPair).map(withItemExplanation(SER_ESTAR_EXPLANATIONS));

export const SER_ESTAR_FORMS: Record<string, [string, string]> = {
  "ser / estar": ["ser", "estar"],
};
