import type { Question } from "./quiz-data";

const seed = [
  ["Yo", " de México.", "soy", "estoy", "I am from Mexico.", "basic", "Origin is expressed with ser."],
  ["Marta", " médica.", "es", "está", "Marta is a doctor.", "basic", "Professions use ser."],
  ["Nosotros", " estudiantes de español.", "somos", "estamos", "We are Spanish students.", "basic", "Identity and roles use ser."],
  ["La mesa", " de madera.", "es", "está", "The table is made of wood.", "basic", "Material is expressed with ser."],
  ["Hoy", " lunes.", "es", "está", "Today is Monday.", "basic", "Dates and days use ser."],
  ["Las llaves", " de Ana.", "son", "están", "The keys belong to Ana.", "basic", "Possession uses ser de."],
  ["El concierto", " en el teatro.", "es", "está", "The concert is at the theatre.", "basic", "An event location uses ser."],
  ["La ventana", " grande y luminosa.", "es", "está", "The window is large and bright.", "basic", "A defining description uses ser."],
  ["Yo", " en casa ahora.", "estoy", "soy", "I am at home now.", "basic", "Physical location uses estar."],
  ["Las mochilas", " debajo de la mesa.", "están", "son", "The backpacks are under the table.", "basic", "Physical location uses estar."],
  ["¿Cómo", " tú esta mañana?", "estás", "eres", "How are you this morning?", "basic", "A current state uses estar."],
  ["El café", " caliente.", "está", "es", "The coffee is hot.", "basic", "A temporary state uses estar."],
  ["Mis amigos", " cansados después del viaje.", "están", "son", "My friends are tired after the trip.", "basic", "A resulting state uses estar."],
  ["La puerta", " cerrada.", "está", "es", "The door is closed.", "basic", "A current condition uses estar."],
  ["El museo", " cerca de la estación.", "está", "es", "The museum is near the station.", "intermediate", "Physical location uses estar."],
  ["La sopa", " muy buena hoy.", "está", "es", "The soup tastes very good today.", "intermediate", "A tasted or experienced result uses estar."],
  ["Mi hermano", " listo para salir.", "está", "es", "My brother is ready to leave.", "intermediate", "Estar listo means to be ready."],
  ["Clara", " lista y curiosa.", "es", "está", "Clara is clever and curious.", "intermediate", "Ser listo means clever or smart."],
  ["El barrio", " tranquilo por la noche.", "es", "está", "The neighbourhood is quiet at night.", "intermediate", "A characteristic description uses ser."],
  ["El barrio", " vacío esta noche.", "está", "es", "The neighbourhood is empty tonight.", "intermediate", "A current state uses estar."],
  ["La camisa", " azul.", "es", "está", "The shirt is blue.", "intermediate", "Colour as a characteristic uses ser."],
  ["La camisa", " mojada.", "está", "es", "The shirt is wet.", "intermediate", "A temporary condition uses estar."],
  ["La reunión", " a las tres.", "es", "está", "The meeting is at three.", "advanced", "Event time uses ser."],
  ["Los niños", " en el jardín.", "están", "son", "The children are in the garden.", "advanced", "People's physical location uses estar."],
  ["La película", " aburrida para mí.", "es", "está", "The film is boring to me.", "advanced", "Ser can present a quality of something."],
  ["Yo", " aburrido durante la película.", "estoy", "soy", "I am bored during the film.", "advanced", "Estar describes a person's current state."],
  ["El profesor", " enfermo esta semana.", "está", "es", "The teacher is ill this week.", "advanced", "Health states use estar."],
  ["El profesor", " muy paciente.", "es", "está", "The teacher is very patient.", "advanced", "A personal characteristic uses ser."],
  ["La puerta", " abierta porque hace calor.", "está", "es", "The door is open because it is hot.", "advanced", "A resulting condition uses estar."],
  ["La conferencia", " en el auditorio principal.", "es", "está", "The conference is in the main auditorium.", "advanced", "Events use ser for their location."],
] as const;

export const SER_ESTAR_QUESTIONS: Question[] = seed.map(([before, after, answer, alternateAnswer, en, level, explanation], index) => ({
  id: 2001 + index,
  before,
  after,
  infinitive: "ser / estar",
  answer,
  verbAnswer: answer,
  objectPronoun: alternateAnswer,
  explanation,
  translations: { en, pl: "" },
  subjectNumber: "singular",
  isActivity: false,
  indirectObject: "",
  tense: "present",
  level,
}));

export const SER_ESTAR_FORMS: Record<string, [string, string]> = {
  "ser / estar": ["ser", "estar"],
};
