import type { Question } from "./quiz-data";

const seed = [
  ["Yo", " de México.", "soy", "estoy", "I am from Mexico.", "basic", "Origin is expressed with ser."],
  ["Marta", " médica.", "es", "está", "Marta is a doctor.", "basic", "Professions use ser."],
  ["Nosotros", " estudiantes de español.", "somos", "estamos", "We are Spanish students.", "basic", "Identity and roles use ser."],
  ["La mesa", " de madera.", "es", "está", "The table is made of wood.", "basic", "Material is expressed with ser."],
  ["Hoy", " lunes.", "es", "está", "Today is Monday.", "basic", "Dates and days use ser."],
  ["Las llaves", " de Ana.", "son", "están", "The keys belong to Ana.", "basic", "Possession uses ser de."],
  ["El concierto", " en el teatro.", "es", "está", "The concert is at the theatre.", "basic", "An event location uses ser."],
  ["La ventana", " grande y luminosa.", "es", "está", "The window is large and bright.", "basic", "A defining description uses ser."],
  ["Yo", " en casa ahora.", "estoy", "soy", "I am at home now.", "basic", "Physical location uses estar."],
  ["Las mochilas", " debajo de la mesa.", "están", "son", "The backpacks are under the table.", "basic", "Physical location uses estar."],
  ["¿Cómo", " tú esta mañana?", "estás", "eres", "How are you this morning?", "basic", "A current state uses estar."],
  ["El café", " caliente.", "está", "es", "The coffee is hot.", "basic", "A temporary state uses estar."],
  ["Mis amigos", " cansados después del viaje.", "están", "son", "My friends are tired after the trip.", "basic", "A resulting state uses estar."],
  ["La puerta", " cerrada.", "está", "es", "The door is closed.", "basic", "A current condition uses estar."],
  ["El museo", " cerca de la estación.", "está", "es", "The museum is near the station.", "intermediate", "Physical location uses estar."],
  ["La sopa", " muy buena hoy.", "está", "es", "The soup tastes very good today.", "intermediate", "A tasted or experienced result uses estar."],
  ["Mi hermano", " listo para salir.", "está", "es", "My brother is ready to leave.", "intermediate", "Estar listo means to be ready."],
  ["Clara", " lista y curiosa.", "es", "está", "Clara is clever and curious.", "intermediate", "Ser listo means clever or smart."],
  ["El barrio", " tranquilo por la noche.", "es", "está", "The neighbourhood is quiet at night.", "intermediate", "A characteristic description uses ser."],
  ["El barrio", " vacío esta noche.", "está", "es", "The neighbourhood is empty tonight.", "intermediate", "A current state uses estar."],
  ["La camisa", " azul.", "es", "está", "The shirt is blue.", "intermediate", "Colour as a characteristic uses ser."],
  ["La camisa", " mojada.", "está", "es", "The shirt is wet.", "intermediate", "A temporary condition uses estar."],
  ["La reunión", " a las tres.", "es", "está", "The meeting is at three.", "advanced", "Event time uses ser."],
  ["Los niños", " en el jardín.", "están", "son", "The children are in the garden.", "advanced", "People's physical location uses estar."],
  ["La película", " aburrida para mí.", "es", "está", "The film is boring to me.", "advanced", "Ser can present a quality of something."],
  ["Yo", " aburrido durante la película.", "estoy", "soy", "I am bored during the film.", "advanced", "Estar describes a person's current state."],
  ["El profesor", " enfermo esta semana.", "está", "es", "The teacher is ill this week.", "advanced", "Health states use estar."],
  ["El profesor", " muy paciente.", "es", "está", "The teacher is very patient.", "advanced", "A personal characteristic uses ser."],
  ["La puerta", " abierta porque hace calor.", "está", "es", "The door is open because it is hot.", "advanced", "A resulting condition uses estar."],
  ["La conferencia", " en el auditorio principal.", "es", "está", "The conference is in the main auditorium.", "advanced", "Events use ser for their location."],

  // --- Issue #24, Stage 5: identity (profession, role, relationship) ---
  ["Yo", " ingeniera.", "soy", "estoy", "I am an engineer.", "basic", "Professions use ser."],
  ["Tú", " mi mejor amigo.", "eres", "estás", "You are my best friend.", "basic", "A close relationship or role uses ser."],
  ["Ella", " periodista.", "es", "está", "She is a journalist.", "basic", "Professions use ser."],
  ["Nosotros", " vecinos desde hace años.", "somos", "estamos", "We have been neighbours for years.", "basic", "A lasting role or relationship uses ser."],
  ["Ellos", " los dueños de la tienda.", "son", "están", "They are the owners of the shop.", "basic", "Ownership and identity use ser."],
  ["Mi tío", " abogado en Madrid.", "es", "está", "My uncle is a lawyer in Madrid.", "basic", "Profession uses ser even when a place follows."],
  ["Yo", " la capitana del equipo.", "soy", "estoy", "I am the team captain.", "basic", "A role or title uses ser."],
  ["Mis padres", " dentistas.", "son", "están", "My parents are dentists.", "basic", "Professions use ser."],
  ["Tú", " un buen compañero de trabajo.", "eres", "estás", "You are a good coworker.", "basic", "A description of role or character uses ser."],
  ["El señor García", " el director del colegio.", "es", "está", "Mr. García is the school principal.", "basic", "A title or position uses ser."],
  ["Nosotros", " hermanos, no primos.", "somos", "estamos", "We are brothers, not cousins.", "intermediate", "A family relationship uses ser."],
  ["Ana y Luis", " los organizadores del evento.", "son", "están", "Ana and Luis are the organisers of the event.", "intermediate", "A role uses ser."],
  ["Yo", " cliente habitual de esta cafetería.", "soy", "estoy", "I am a regular customer at this café.", "intermediate", "An ongoing role or identity uses ser."],
  ["Ustedes", " los nuevos socios de la empresa.", "son", "están", "You all are the new partners in the company.", "intermediate", "A role or position uses ser."],
  ["Ella", " la autora de esta novela.", "es", "está", "She is the author of this novel.", "intermediate", "Authorship and identity use ser."],

  // --- Origin ---
  ["Yo", " de Polonia.", "soy", "estoy", "I am from Poland.", "basic", "Origin uses ser."],
  ["Tú", " de una familia italiana.", "eres", "estás", "You are from an Italian family.", "basic", "Origin uses ser."],
  ["Estos quesos", " de Francia.", "son", "están", "These cheeses are from France.", "basic", "Origin uses ser."],
  ["El vino", " de la región de Rioja.", "es", "está", "The wine is from the Rioja region.", "basic", "Origin uses ser."],
  ["Nosotros", " de la misma ciudad.", "somos", "estamos", "We are from the same city.", "basic", "Origin uses ser."],
  ["Mi abuela", " de un pueblo pequeño.", "es", "está", "My grandmother is from a small village.", "basic", "Origin uses ser."],
  ["Esas naranjas", " de Valencia.", "son", "están", "Those oranges are from Valencia.", "intermediate", "Origin of produce uses ser."],
  ["Tú", " de padres extranjeros.", "eres", "estás", "You are the child of foreign parents.", "intermediate", "Origin or background uses ser."],
  ["El profesor", " de Argentina.", "es", "está", "The teacher is from Argentina.", "basic", "Origin uses ser."],
  ["Estas telas", " de la India.", "son", "están", "These fabrics are from India.", "intermediate", "Origin uses ser."],
  ["Yo", " originaria de un pueblo costero.", "soy", "estoy", "I originally come from a coastal town.", "intermediate", "Origin uses ser."],
  ["Mis compañeros", " de distintas partes del país.", "son", "están", "My colleagues are from different parts of the country.", "intermediate", "Origin uses ser."],
  ["Este café", " de Colombia.", "es", "está", "This coffee is from Colombia.", "basic", "Origin uses ser."],
  ["Nosotros", " de una tradición familiar muy antigua.", "somos", "estamos", "We come from a very old family tradition.", "advanced", "Origin and heritage use ser."],
  ["Ella", " de ascendencia mexicana.", "es", "está", "She is of Mexican descent.", "advanced", "Origin and heritage use ser."],

  // --- Defining characteristics (physical, personality, inherent qualities) ---
  ["Mi hermana", " muy generosa.", "es", "está", "My sister is very generous.", "basic", "A personality trait uses ser."],
  ["Tú", " alto y delgado.", "eres", "estás", "You are tall and thin.", "basic", "A physical characteristic uses ser."],
  ["Este edificio", " muy antiguo.", "es", "está", "This building is very old.", "basic", "A defining quality uses ser."],
  ["Los niños", " curiosos por naturaleza.", "son", "están", "Children are curious by nature.", "basic", "An inherent trait uses ser."],
  ["Yo", " bastante paciente.", "soy", "estoy", "I am quite patient.", "basic", "A personality trait uses ser."],
  ["Esta ciudad", " muy ruidosa.", "es", "está", "This city is very noisy.", "basic", "A defining characteristic uses ser."],
  ["Nosotros", " muy trabajadores.", "somos", "estamos", "We are very hardworking.", "basic", "A personality trait uses ser."],
  ["El examen", " bastante difícil.", "es", "está", "The exam is quite difficult.", "basic", "An inherent quality uses ser."],
  ["Sus ojos", " verdes.", "son", "están", "Her eyes are green.", "basic", "A physical feature uses ser."],
  ["Este barrio", " conocido por sus restaurantes.", "es", "está", "This neighbourhood is known for its restaurants.", "intermediate", "A defining feature uses ser."],
  ["Tú", " muy creativa.", "eres", "estás", "You are very creative.", "basic", "A personality trait uses ser."],
  ["El profesor", " muy exigente.", "es", "está", "The teacher is very demanding.", "basic", "A personality trait uses ser."],
  ["Mis padres", " bastante estrictos.", "son", "están", "My parents are quite strict.", "basic", "A personality trait uses ser."],
  ["Esta película", " larga y lenta.", "es", "está", "This film is long and slow.", "intermediate", "A defining quality uses ser."],
  ["El río", " ancho y profundo en esta parte.", "es", "está", "The river is wide and deep in this part.", "intermediate", "A defining geographic characteristic uses ser."],

  // --- Material and time/date ---
  ["La silla", " de plástico.", "es", "está", "The chair is made of plastic.", "basic", "Material uses ser."],
  ["Hoy", " miércoles.", "es", "está", "Today is Wednesday.", "basic", "Days of the week use ser."],
  ["", " las ocho de la mañana.", "son", "están", "It is eight in the morning.", "basic", "Clock time uses ser."],
  ["El concierto", " el próximo sábado.", "es", "está", "The concert is next Saturday.", "basic", "Event dates use ser."],
  ["Esta mesa", " de metal.", "es", "está", "This table is made of metal.", "basic", "Material uses ser."],
  ["Mañana", " el cumpleaños de Sara.", "es", "está", "Tomorrow is Sara's birthday.", "basic", "Dates use ser."],
  ["El anillo", " de oro.", "es", "está", "The ring is made of gold.", "basic", "Material uses ser."],
  ["Hoy", " tres de mayo.", "es", "está", "Today is the third of May.", "basic", "Calendar dates use ser."],
  ["La entrevista", " a las cinco.", "es", "está", "The interview is at five o'clock.", "basic", "Event time uses ser."],
  ["Estas copas", " de cristal.", "son", "están", "These glasses are made of crystal.", "basic", "Material uses ser."],
  ["", " la una y media.", "es", "está", "It is half past one.", "basic", "Clock time uses ser."],
  ["El examen final", " el viernes.", "es", "está", "The final exam is on Friday.", "basic", "Event dates use ser."],
  ["La estatua", " de bronce.", "es", "está", "The statue is made of bronze.", "intermediate", "Material uses ser."],
  ["La boda", " en agosto.", "es", "está", "The wedding is in August.", "intermediate", "Event date uses ser."],
  ["Esta manta", " de lana.", "es", "está", "This blanket is made of wool.", "intermediate", "Material uses ser."],

  // --- Location (physical location vs. an event's location) ---
  ["El supermercado", " a dos calles de aquí.", "está", "es", "The supermarket is two streets from here.", "basic", "Physical location uses estar."],
  ["Mis gafas", " encima de la mesa.", "están", "son", "My glasses are on the table.", "basic", "Physical location uses estar."],
  ["La boda", " en un jardín.", "es", "está", "The wedding is in a garden.", "intermediate", "An event's location uses ser."],
  ["El hospital", " al lado de la farmacia.", "está", "es", "The hospital is next to the pharmacy.", "basic", "Physical location uses estar."],
  ["La exposición", " en el centro cultural.", "es", "está", "The exhibition is at the cultural centre.", "intermediate", "An event's location uses ser."],
  ["Los libros", " en la estantería.", "están", "son", "The books are on the shelf.", "basic", "Physical location uses estar."],
  ["Yo", " en la sala de espera.", "estoy", "soy", "I am in the waiting room.", "basic", "Physical location uses estar."],
  ["La ceremonia", " en la plaza principal.", "es", "está", "The ceremony is in the main square.", "intermediate", "An event's location uses ser."],
  ["El parque", " detrás del colegio.", "está", "es", "The park is behind the school.", "basic", "Physical location uses estar."],
  ["Nosotros", " en la última fila.", "estamos", "somos", "We are in the last row.", "basic", "Physical location uses estar."],
  ["La feria", " fuera de la ciudad este año.", "es", "está", "The fair is outside the city this year.", "intermediate", "An event's location uses ser."],
  ["Tus llaves", " dentro del cajón.", "están", "son", "Your keys are inside the drawer.", "basic", "Physical location uses estar."],
  ["El aeropuerto", " lejos del centro.", "está", "es", "The airport is far from the city centre.", "basic", "Physical location uses estar."],
  ["La reunión anual", " en otra ciudad este año.", "es", "está", "The annual meeting is in another city this year.", "intermediate", "An event's location uses ser."],
  ["Los niños", " en el patio.", "están", "son", "The children are in the playground.", "basic", "A person's physical location uses estar."],

  // --- Conditions (temporary physical or emotional states) ---
  ["Yo", " muy cansada hoy.", "estoy", "soy", "I am very tired today.", "basic", "A temporary physical state uses estar."],
  ["La ventana", " abierta.", "está", "es", "The window is open.", "basic", "A current condition uses estar."],
  ["Mi hermano", " enfadado conmigo.", "está", "es", "My brother is angry with me.", "basic", "An emotional state uses estar."],
  ["El agua", " helada.", "está", "es", "The water is freezing cold.", "basic", "A temporary condition uses estar."],
  ["Nosotros", " preocupados por el examen.", "estamos", "somos", "We are worried about the exam.", "basic", "A temporary emotional state uses estar."],
  ["Las tiendas", " cerradas los domingos.", "están", "son", "The shops are closed on Sundays.", "basic", "A resulting condition uses estar, even when it happens regularly."],
  ["Yo", " emocionada por el viaje.", "estoy", "soy", "I am excited about the trip.", "basic", "A temporary emotional state uses estar."],
  ["El pastel", " todavía caliente.", "está", "es", "The cake is still warm.", "basic", "A temporary condition uses estar."],
  ["Mis padres", " de vacaciones esta semana.", "están", "son", "My parents are on vacation this week.", "basic", "A temporary situation uses estar."],
  ["Tú", " resfriado, ¿verdad?", "estás", "eres", "You have a cold, right?", "basic", "A temporary health condition uses estar."],
  ["La leche", " a punto de caducar.", "está", "es", "The milk is about to expire.", "intermediate", "A temporary situation uses estar."],
  ["El equipo", " nervioso antes del partido.", "está", "es", "The team is nervous before the match.", "intermediate", "A temporary emotional state uses estar."],
  ["Las calles", " mojadas después de la lluvia.", "están", "son", "The streets are wet after the rain.", "basic", "A resulting condition uses estar."],
  ["Yo", " un poco confundida con esta pregunta.", "estoy", "soy", "I am a bit confused by this question.", "intermediate", "A temporary mental state uses estar."],
  ["El ambiente", " tenso en la oficina hoy.", "está", "es", "The atmosphere is tense in the office today.", "intermediate", "A temporary situational state uses estar."],

  // --- Changing states / results of a change ---
  ["El trabajo", " ya terminado.", "está", "es", "The work is already finished.", "basic", "A resulting condition from a completed action uses estar."],
  ["La puerta", " rota desde ayer.", "está", "es", "The door has been broken since yesterday.", "basic", "A resulting state uses estar."],
  ["Después de la operación, mi abuelo", " mucho mejor.", "está", "es", "After the surgery, my grandfather is much better.", "intermediate", "A resulting or changed condition uses estar."],
  ["El pan", " duro; llevaba días fuera.", "está", "es", "The bread is hard; it had been out for days.", "intermediate", "A resulting condition uses estar."],
  ["Desde que empezó a estudiar más, ella", " mucho más segura en los exámenes.", "está", "es", "Since she started studying more, she is much more confident in exams.", "advanced", "A change of state over time uses estar."],
  ["El jarrón", " roto en pedazos.", "está", "es", "The vase is broken into pieces.", "basic", "A resulting state uses estar."],
  ["Después de tantos cambios, la empresa", " irreconocible.", "está", "es", "After so many changes, the company is unrecognisable.", "advanced", "A resulting state from change uses estar."],
  ["La fruta", " madura ya.", "está", "es", "The fruit is ripe now.", "basic", "A resulting condition uses estar."],
  ["El niño", " más alto que el año pasado.", "está", "es", "The boy has gotten taller than last year.", "intermediate", "A perceived change uses estar."],
  ["La habitación", " ordenada por fin.", "está", "es", "The room is tidy at last.", "basic", "A resulting condition uses estar."],
  ["Después del susto, todos", " más tranquilos.", "están", "son", "After the scare, everyone is calmer now.", "intermediate", "A resulting emotional state uses estar."],
  ["El proyecto", " casi acabado.", "está", "es", "The project is almost finished.", "basic", "A resulting condition uses estar."],
  ["Tu español", " mucho mejor que antes.", "está", "es", "Your Spanish is much better than before.", "intermediate", "A perceived improvement uses estar."],
  ["Las plantas", " secas después de tantos días de calor.", "están", "son", "The plants are dry after so many hot days.", "intermediate", "A resulting condition uses estar."],
  ["El coche", " reparado desde el lunes.", "está", "es", "The car has been repaired since Monday.", "intermediate", "A resulting state uses estar."],

  // --- Idiomatic ser/estar pairs (the adjective's meaning shifts with the verb) ---
  ["Ese documental", " bastante aburrido.", "es", "está", "That documentary is quite boring.", "intermediate", "Ser aburrido describes a boring quality."],
  ["Yo", " aburrido en la clase de historia.", "estoy", "soy", "I am bored in history class.", "intermediate", "Estar aburrido describes feeling bored."],
  ["Mi tío", " muy rico.", "es", "está", "My uncle is very wealthy.", "intermediate", "Ser rico means to be wealthy."],
  ["Esta sopa", " riquísima.", "está", "es", "This soup tastes delicious.", "intermediate", "Estar rico describes how food tastes."],
  ["Este puente", " seguro para cruzar.", "es", "está", "This bridge is safe to cross.", "intermediate", "Ser seguro describes a safe, reliable quality."],
  ["Yo", " segura de mi respuesta.", "estoy", "soy", "I am sure of my answer.", "intermediate", "Estar seguro means to feel certain."],
  ["Este plato", " malo; no lo pruebes.", "es", "está", "This dish is bad quality; don't try it.", "intermediate", "Ser malo describes an inherently poor quality."],
  ["Mi hijo", " malo desde ayer.", "está", "es", "My son has been sick since yesterday.", "intermediate", "Estar malo means to feel unwell."],
  ["Este plátano", " verde todavía.", "está", "es", "This banana is still unripe.", "basic", "Estar verde describes an unripe state."],
  ["Su color favorito", " verde.", "es", "está", "Her favourite colour is green.", "basic", "Ser verde describes an inherent colour."],
  ["Mi abuelo", " muy vivo para su edad.", "está", "es", "My grandfather is very lively for his age.", "advanced", "Estar vivo can describe a lively current state."],
  ["Esta ciudad", " muy viva por las noches.", "es", "está", "This city is very lively at night.", "advanced", "Ser vivo describes an inherent lively character."],
  ["Tú", " muy despierto para ser tan temprano.", "estás", "eres", "You are very alert for it being so early.", "advanced", "Estar despierto describes being currently awake or alert."],
  ["Mi sobrina", " muy despierta; aprende rápido.", "es", "está", "My niece is very sharp; she learns quickly.", "advanced", "Ser despierto describes an inherently quick-witted personality."],
  ["Ellos", " atentos a cada detalle del proyecto.", "están", "son", "They are attentive to every detail of the project right now.", "advanced", "Estar atento describes being currently attentive."],
] as const;

export const SER_ESTAR_QUESTIONS: Question[] = seed.map(([before, after, answer, alternateAnswer, en, level, explanation], index) => ({
  id: 2001 + index,
  before,
  after,
  infinitive: "ser / estar",
  answer,
  verbAnswer: answer,
  objectPronoun: alternateAnswer,
  explanation,
  translations: { en, pl: "" },
  subjectNumber: "singular",
  isActivity: false,
  indirectObject: "",
  tense: "present",
  level,
}));

export const SER_ESTAR_FORMS: Record<string, [string, string]> = {
  "ser / estar": ["ser", "estar"],
};
