// Generated by scripts/build-sourced-content.mjs. Do not edit by hand.
// Source and licensing details: docs/content-sources.md and docs/content-attribution.csv.

export const SOURCED_FLASHCARD_PAIRS: Record<string, { example: string; exampleEnglish: string }> = {
  "ser": {
    "example": "Quiero ser más paciente.",
    "exampleEnglish": "I want to be more patient."
  },
  "estar": {
    "example": "Voy a estar en casa esta tarde.",
    "exampleEnglish": "I'm going to be home this afternoon."
  },
  "haber": {
    "example": "Tiene que haber otra solución.",
    "exampleEnglish": "There has to be another solution."
  },
  "hacer": {
    "example": "Tengo que hacer la cena.",
    "exampleEnglish": "I have to make dinner."
  },
  "poder": {
    "example": "Para poder entrar al laboratorio, necesitas una tarjeta especial.",
    "exampleEnglish": "To be able to enter the laboratory, you need a special pass."
  },
  "decir": {
    "example": "¿Me vas a decir qué debería hacer a continuación?",
    "exampleEnglish": "Will you tell me what I should do next?"
  },
  "ir": {
    "example": "Vamos a ir al mercado el sábado.",
    "exampleEnglish": "We're going to go to the market on Saturday."
  },
  "ver": {
    "example": "¿Puedes ver ese edificio grande y blanco de allí?",
    "exampleEnglish": "Can you see the big white building over there?"
  },
  "dar": {
    "example": "Voy a dar mi opinión en la reunión.",
    "exampleEnglish": "I'm going to give my opinion at the meeting."
  },
  "saber": {
    "example": "Quiero saber la verdad.",
    "exampleEnglish": "I want to know the truth."
  },
  "querer": {
    "example": "Quiero aprender español.",
    "exampleEnglish": "I want to learn Spanish."
  },
  "llegar": {
    "example": "Al llegar a la estación, telefoneé a mi amigo.",
    "exampleEnglish": "I called my friend after arriving at the station."
  },
  "pasar": {
    "example": "No sé qué va a pasar mañana.",
    "exampleEnglish": "I don't know what's going to happen tomorrow."
  },
  "deber": {
    "example": "Debes descansar un poco.",
    "exampleEnglish": "You should rest a little."
  },
  "poner": {
    "example": "Clara decidió poner las plantas junto a la ventana.",
    "exampleEnglish": "Clara decided to put the plants beside the window."
  },
  "parecer": {
    "example": "La ruta puede parecer larga, pero el paisaje merece la pena.",
    "exampleEnglish": "The route may seem long, but the scenery is worth it."
  },
  "quedar": {
    "example": "Podemos quedar mañana por la tarde.",
    "exampleEnglish": "We can meet up tomorrow afternoon."
  },
  "creer": {
    "example": "No puedo creer esta noticia.",
    "exampleEnglish": "I can't believe this news."
  },
  "hablar": {
    "example": "Algunos de mis amigos saben hablar francés bastante bien.",
    "exampleEnglish": "Some of my friends can speak French fairly well."
  },
  "llevar": {
    "example": "Puedes llevar estas carpetas a la sala de reuniones.",
    "exampleEnglish": "You can take these folders to the meeting room."
  },
  "dejar": {
    "example": "Voy a dejar las llaves en la mesa.",
    "exampleEnglish": "I'm going to leave the keys on the table."
  },
  "seguir": {
    "example": "Vamos a seguir las instrucciones con cuidado.",
    "exampleEnglish": "We're going to follow the instructions carefully."
  },
  "encontrar": {
    "example": "Espero encontrar mis gafas pronto.",
    "exampleEnglish": "I hope to find my glasses soon."
  },
  "llamar": {
    "example": "Ahora estamos comiendo, ¿podría volver a llamar más tarde?",
    "exampleEnglish": "We are eating now. Could you please call back later?"
  },
  "venir": {
    "example": "El que quiera venir a mi fiesta puede venir.",
    "exampleEnglish": "Whoever wants to come to my party may come."
  },
  "pensar": {
    "example": "Necesito pensar en esta decisión.",
    "exampleEnglish": "I need to think about this decision."
  },
  "salir": {
    "example": "Estaba a punto de salir cuando sonó el teléfono.",
    "exampleEnglish": "I was about to leave when the phone rang."
  },
  "volver": {
    "example": "Él prometió volver y sin embargo no lo hizo.",
    "exampleEnglish": "He promised to return and yet he didn't."
  },
  "tomar": {
    "example": "Voy a tomar un café antes de trabajar.",
    "exampleEnglish": "I'm going to have a coffee before work."
  },
  "conocer": {
    "example": "Es difícil conocer a gente tan agradable como tú.",
    "exampleEnglish": "It's rare to meet nice people like you."
  },
  "vivir": {
    "example": "Quiero vivir cerca del mar algún día.",
    "exampleEnglish": "I want to live near the sea someday."
  },
  "sentir": {
    "example": "Puedo sentir el frío en las manos.",
    "exampleEnglish": "I can feel the cold in my hands."
  },
  "tratar": {
    "example": "Vamos a intentar tratar a los demás con respeto.",
    "exampleEnglish": "Let's try to treat each other with respect."
  },
  "mirar": {
    "example": "Pienso que mirar televisión es una pérdida de tiempo.",
    "exampleEnglish": "I think watching TV is a waste of time."
  },
  "contar": {
    "example": "Mi abuelo siempre cuenta historias interesantes.",
    "exampleEnglish": "My grandfather always tells interesting stories."
  },
  "empezar": {
    "example": "Vamos a empezar la clase en cinco minutos.",
    "exampleEnglish": "We're going to start class in five minutes."
  },
  "esperar": {
    "example": "Voy a esperar tu respuesta con calma.",
    "exampleEnglish": "I'm going to wait for your answer calmly."
  },
  "buscar": {
    "example": "Necesito buscar un regalo para mi hermana.",
    "exampleEnglish": "I need to look for a gift for my sister."
  },
  "existir": {
    "example": "Debe existir una forma más sencilla.",
    "exampleEnglish": "There must exist a simpler way."
  },
  "entrar": {
    "example": "Vamos a entrar por la puerta principal.",
    "exampleEnglish": "We're going to go in through the main door."
  },
  "trabajar": {
    "example": "El doctor le advirtió que dejara de trabajar tanto.",
    "exampleEnglish": "The doctor advised him to stop working too much."
  },
  "escribir": {
    "example": "Él intentó escribir todo lo que el profesor dijo.",
    "exampleEnglish": "He tried to write down everything the teacher said."
  },
  "perder": {
    "example": "No quiero perder el autobús.",
    "exampleEnglish": "I don't want to miss the bus."
  },
  "producir": {
    "example": "Esta fábrica va a producir más piezas este año.",
    "exampleEnglish": "This factory is going to produce more parts this year."
  },
  "ocurrir": {
    "example": "Accidentes de tráfico suelen ocurrir en días de lluvia.",
    "exampleEnglish": "Traffic accidents are likely to occur on rainy days."
  },
  "entender": {
    "example": "Necesito entender mejor esta lección.",
    "exampleEnglish": "I need to understand this lesson better."
  },
  "pedir": {
    "example": "Voy a pedir ayuda a mi vecino.",
    "exampleEnglish": "I'm going to ask my neighbour for help."
  },
  "recibir": {
    "example": "Cada participante va a recibir una copia del programa.",
    "exampleEnglish": "Each participant will receive a copy of the programme."
  },
  "recordar": {
    "example": "Quiero recordar este viaje para siempre.",
    "exampleEnglish": "I want to remember this trip forever."
  },
  "terminar": {
    "example": "Voy a terminar el informe esta noche.",
    "exampleEnglish": "I'm going to finish the report tonight."
  },
  "permitir": {
    "example": "El médico no le va a permitir viajar todavía.",
    "exampleEnglish": "The doctor isn't going to allow him to travel yet."
  },
  "aparecer": {
    "example": "Algunas estrellas empezaron a aparecer en el cielo nocturno.",
    "exampleEnglish": "Some stars began to appear in the night sky."
  },
  "conseguir": {
    "example": "¿No puedes conseguir a alguien más que te ayude?",
    "exampleEnglish": "Can't you get somebody else to help you?"
  },
  "comenzar": {
    "example": "¿Estás pensando seriamente en comenzar tu propio negocio?",
    "exampleEnglish": "Are you seriously thinking about starting your own business?"
  },
  "servir": {
    "example": "¿Me podría servir una copa de vino blanco?",
    "exampleEnglish": "Could I have a glass of white wine?"
  },
  "sacar": {
    "example": "Necesito sacar dinero del banco.",
    "exampleEnglish": "I need to take out money from the bank."
  },
  "necesitar": {
    "example": "Vas a necesitar un abrigo hoy.",
    "exampleEnglish": "You're going to need a coat today."
  },
  "mantener": {
    "example": "Quiero mantener esta rutina de ejercicio.",
    "exampleEnglish": "I want to keep up this exercise routine."
  },
  "resultar": {
    "example": "Con instrucciones claras, montar la estantería debería resultar sencillo.",
    "exampleEnglish": "With clear instructions, assembling the bookcase should prove straightforward."
  },
  "leer": {
    "example": "Deberías ser capaz de leer este libro con facilidad.",
    "exampleEnglish": "You should be able to read this book easily."
  },
  "caer": {
    "example": "El otoño llegó y las hojas comenzaron a caer.",
    "exampleEnglish": "Autumn came and the leaves started to fall."
  },
  "cambiar": {
    "example": "Vamos a cambiar los muebles de sitio.",
    "exampleEnglish": "We're going to move the furniture around."
  },
  "presentar": {
    "example": "Mañana Elena va a presentar los resultados de su investigación.",
    "exampleEnglish": "Tomorrow Elena will present the results of her research."
  },
  "crear": {
    "example": "Estoy interesado en crear mis propias páginas web.",
    "exampleEnglish": "I'm interested in creating my own web pages."
  },
  "abrir": {
    "example": "Dame las llaves para que pueda abrir la puerta.",
    "exampleEnglish": "Give me the keys so I can unlock the door."
  },
  "considerar": {
    "example": "Deberíamos considerar el problema desde la perspectiva de un niño.",
    "exampleEnglish": "We should consider the problem from a child's perspective."
  },
  "oír": {
    "example": "Creo que puedo oír música a lo lejos.",
    "exampleEnglish": "I think I can hear music in the distance."
  },
  "acabar": {
    "example": "Voy a acabar este libro esta semana.",
    "exampleEnglish": "I'm going to finish this book this week."
  },
  "convertir": {
    "example": "La reforma pretende convertir el antiguo mercado en una biblioteca.",
    "exampleEnglish": "The renovation aims to turn the old market into a library."
  },
  "ganar": {
    "example": "Ella tiene una buena oportunidad de ganar el premio.",
    "exampleEnglish": "She stands a good chance of winning the prize."
  },
  "formar": {
    "example": "Vamos a formar un equipo nuevo.",
    "exampleEnglish": "We're going to form a new team."
  },
  "traer": {
    "example": "¿Podrías ir a la tienda y traer algunos huevos?",
    "exampleEnglish": "Could you go to the store and grab some eggs?"
  },
  "partir": {
    "example": "El tren va a partir en unos minutos.",
    "exampleEnglish": "The train is about to depart in a few minutes."
  },
  "morir": {
    "example": "La planta puede morir si la tierra permanece seca.",
    "exampleEnglish": "The plant can die if the soil remains dry."
  },
  "aceptar": {
    "example": "Ella no tuvo más alternativa que aceptar su destino.",
    "exampleEnglish": "She had no choice but to accept her fate."
  },
  "realizar": {
    "example": "Queremos realizar un buen trabajo este trimestre.",
    "exampleEnglish": "We want to do a good job this quarter."
  },
  "suponer": {
    "example": "Voy a suponer que todo va bien.",
    "exampleEnglish": "I'm going to assume everything is fine."
  },
  "comprender": {
    "example": "Necesito comprender mejor este tema.",
    "exampleEnglish": "I need to understand this topic better."
  },
  "lograr": {
    "example": "¿Qué te gustaría lograr en los siguientes tres años?",
    "exampleEnglish": "What's something you'd like to achieve in the next three years?"
  },
  "explicar": {
    "example": "El profesor va a explicar la lección de nuevo.",
    "exampleEnglish": "The teacher is going to explain the lesson again."
  },
  "preguntar": {
    "example": "Voy a preguntar cuándo va a venir el tren.",
    "exampleEnglish": "I'll ask when the train will get in."
  },
  "tocar": {
    "example": "Mi hermana sabe tocar el piano.",
    "exampleEnglish": "My sister knows how to play the piano."
  },
  "reconocer": {
    "example": "Pude reconocer la melodía desde las primeras notas.",
    "exampleEnglish": "I could recognise the melody from the first notes."
  },
  "estudiar": {
    "example": "No tengo ganas de ponerme a estudiar esta noche.",
    "exampleEnglish": "I don't feel like studying at all tonight."
  },
  "alcanzar": {
    "example": "El accidente de tráfico me impidió alcanzar el tren.",
    "exampleEnglish": "The traffic accident prevented me from catching the train."
  },
  "nacer": {
    "example": "El bebé va a nacer en septiembre.",
    "exampleEnglish": "The baby is going to be born in September."
  },
  "dirigir": {
    "example": "Una arquitecta joven va a dirigir la restauración del teatro.",
    "exampleEnglish": "A young architect will lead the restoration of the theatre."
  },
  "correr": {
    "example": "Alicia prefiere correr por el parque antes del desayuno.",
    "exampleEnglish": "Alicia prefers to run through the park before breakfast."
  },
  "utilizar": {
    "example": "Los estudiantes deberían utilizar los libros de la biblioteca.",
    "exampleEnglish": "Students should make use of the books in the library."
  },
  "pagar": {
    "example": "Puedes pagar la entrada con tarjeta en la taquilla.",
    "exampleEnglish": "You can pay for the ticket by card at the box office."
  },
  "ayudar": {
    "example": "Quiero ayudar a mis vecinos con la mudanza.",
    "exampleEnglish": "I want to help my neighbours with the move."
  },
  "gustar": {
    "example": "Estaba seguro de que no te iba a gustar.",
    "exampleEnglish": "I was sure you wouldn't like it."
  },
  "jugar": {
    "example": "Los niños quieren jugar en el parque.",
    "exampleEnglish": "The children want to play at the park."
  },
  "escuchar": {
    "example": "Me gusta escuchar música mientras trabajo.",
    "exampleEnglish": "I like listening to music while I work."
  },
  "cumplir": {
    "example": "El proveedor debe cumplir todas las condiciones del contrato.",
    "exampleEnglish": "The supplier must fulfil all the terms of the contract."
  },
  "ofrecer": {
    "example": "El hotel va a ofrecer un descuento este mes.",
    "exampleEnglish": "The hotel is going to offer a discount this month."
  },
  "descubrir": {
    "example": "Quiero descubrir pueblos nuevos este verano.",
    "exampleEnglish": "I want to discover new villages this summer."
  },
  "levantar": {
    "example": "Entre los dos pudieron levantar la caja sin dañarla.",
    "exampleEnglish": "Together they managed to lift the box without damaging it."
  },
  "intentar": {
    "example": "Voy a intentar terminar hoy mismo.",
    "exampleEnglish": "I'm going to try to finish today."
  },
  "usar": {
    "example": "No me gusta usar la ropa de otras personas.",
    "exampleEnglish": "I do not like wearing anybody else's clothes."
  },
  "decidir": {
    "example": "Tenemos que decidir el destino del viaje.",
    "exampleEnglish": "We have to decide on the trip's destination."
  },
  "repetir": {
    "example": "¿Puedes repetir lo que acabas de decir, por favor?",
    "exampleEnglish": "Could you please repeat what you just said?"
  },
  "olvidar": {
    "example": "Esto es algo realmente importante que no deberías olvidar.",
    "exampleEnglish": "That's something really important that you shouldn't forget."
  },
  "aprender": {
    "example": "Quiero aprender a tocar la guitarra.",
    "exampleEnglish": "I want to learn to play the guitar."
  },
  "cerrar": {
    "example": "La encargada va a cerrar la tienda a las nueve.",
    "exampleEnglish": "The manager is going to close the shop at nine."
  },
  "comer": {
    "example": "¿Dónde me puedo lavar las manos antes de comer?",
    "exampleEnglish": "Where can I wash my hands before I eat?"
  },
  "cantar": {
    "example": "A mi hija le encanta cantar en el coro.",
    "exampleEnglish": "My daughter loves singing in the choir."
  },
  "bailar": {
    "example": "Vamos a bailar en la boda de mi prima.",
    "exampleEnglish": "We're going to dance at my cousin's wedding."
  },
  "comprar": {
    "example": "Necesito comprar pan de camino a casa.",
    "exampleEnglish": "I need to buy bread on the way home."
  },
  "vender": {
    "example": "Mis padres quieren vender la casa vieja.",
    "exampleEnglish": "My parents want to sell the old house."
  },
  "viajar": {
    "example": "En aquellos días, poca gente podía viajar al extranjero.",
    "exampleEnglish": "In those days, few people could travel abroad."
  },
  "caminar": {
    "example": "En aquellos tiempos, salía a caminar antes del desayuno.",
    "exampleEnglish": "In those days, I went out walking before breakfast."
  },
  "conducir": {
    "example": "Todavía no sé conducir un coche manual.",
    "exampleEnglish": "I still don't know how to drive a manual car."
  },
  "dormir": {
    "example": "Tenemos que dormir al menos ocho horas al día.",
    "exampleEnglish": "We must sleep at least eight hours a day."
  },
  "beber": {
    "example": "Conviene beber agua antes y después del ejercicio.",
    "exampleEnglish": "It is advisable to drink water before and after exercise."
  },
  "cocinar": {
    "example": "Me relaja cocinar los domingos.",
    "exampleEnglish": "Cooking on Sundays relaxes me."
  },
  "lavar": {
    "example": "¿Puedo lavar toda mi ropa de una sola vez?",
    "exampleEnglish": "May I wash all my laundry at once?"
  },
  "limpiar": {
    "example": "Quiero que todos me ayuden a limpiar la casa.",
    "exampleEnglish": "I want everyone to help me clean the house."
  },
  "cortar": {
    "example": "Este cuchillo está tan desafilado que no puede cortar.",
    "exampleEnglish": "This knife is so dull that it can't cut."
  },
  "romper": {
    "example": "Ten cuidado, ese jarrón se puede romper.",
    "exampleEnglish": "Be careful, that vase can break."
  },
  "enviar": {
    "example": "Pido disculpas por la demora en enviar la agenda.",
    "exampleEnglish": "I apologize for the delay in sending the agenda."
  },
  "enseñar": {
    "example": "Ella es capaz de enseñar tanto inglés como francés.",
    "exampleEnglish": "She is capable of teaching both English and French."
  },
  "mostrar": {
    "example": "Te voy a mostrar las fotos del viaje.",
    "exampleEnglish": "I'm going to show you the trip photos."
  },
  "compartir": {
    "example": "Me gusta compartir recetas con mis amigas.",
    "exampleEnglish": "I like sharing recipes with my friends."
  },
  "elegir": {
    "example": "El jurado deberá elegir el proyecto más sostenible.",
    "exampleEnglish": "The panel must choose the most sustainable project."
  },
  "incluir": {
    "example": "El precio va a incluir el desayuno.",
    "exampleEnglish": "The price is going to include breakfast."
  },
  "excluir": {
    "example": "Esta oferta va a excluir los fines de semana.",
    "exampleEnglish": "This offer is going to exclude weekends."
  },
  "mejorar": {
    "example": "Leer en voz alta puede mejorar tu pronunciación.",
    "exampleEnglish": "Reading aloud can improve your pronunciation."
  },
  "empeorar": {
    "example": "El tiempo puede empeorar por la tarde.",
    "exampleEnglish": "The weather might get worse in the afternoon."
  },
  "crecer": {
    "example": "Esta planta va a crecer muy rápido.",
    "exampleEnglish": "This plant is going to grow very fast."
  },
  "reducir": {
    "example": "Por lo tanto es necesario reducir el costo.",
    "exampleEnglish": "Therefore, it is necessary to reduce the cost."
  },
  "aumentar": {
    "example": "La empresa va a aumentar los precios.",
    "exampleEnglish": "The company is going to raise prices."
  },
  "bajar": {
    "example": "Voy a bajar la música un poco.",
    "exampleEnglish": "I'm going to turn the music down a bit."
  },
  "subir": {
    "example": "Vamos a subir la montaña este sábado.",
    "exampleEnglish": "We're going to climb the mountain this Saturday."
  },
  "regresar": {
    "example": "Espero regresar antes de que oscurezca.",
    "exampleEnglish": "I hope to return before it gets dark."
  },
  "permanecer": {
    "example": "Vamos a permanecer aquí unos días más.",
    "exampleEnglish": "We're going to stay here a few more days."
  },
  "mover": {
    "example": "Necesito mover el sofá de sitio.",
    "exampleEnglish": "I need to move the sofa to another spot."
  },
  "parar": {
    "example": "El árbitro de hockey intervino para parar la pelea.",
    "exampleEnglish": "The hockey referee intervened to stop the fight."
  },
  "continuar": {
    "example": "Vamos a continuar la clase después del descanso.",
    "exampleEnglish": "We're going to continue the class after the break."
  },
  "preparar": {
    "example": "No todos pueden preparar una buena taza de café.",
    "exampleEnglish": "Not everyone can make a good cup of coffee."
  },
  "responder": {
    "example": "Voy a responder tu mensaje enseguida.",
    "exampleEnglish": "I'm going to answer your message right away."
  },
  "añadir": {
    "example": "Creo que deberías añadir una pizca más de pimienta.",
    "exampleEnglish": "I think you should add a bit more pepper."
  },
  "quitar": {
    "example": "Voy a quitar el polvo de la estantería.",
    "exampleEnglish": "I'm going to dust off the shelf."
  },
  "quitarse": {
    "example": "Al entrar en casa, decidió quitarse el abrigo mojado.",
    "exampleEnglish": "On entering the house, she decided to take off her wet coat."
  },
  "vestir": {
    "example": "Mi madre suele vestir muy elegante.",
    "exampleEnglish": "My mother usually dresses very elegantly."
  },
  "llevarse": {
    "example": "Pienso que él puede llevarse bien con su vecino.",
    "exampleEnglish": "I think he can get along with his neighbor."
  },
  "levantarse": {
    "example": "Suelo levantarme a las siete cada día.",
    "exampleEnglish": "I usually get up at seven every day."
  },
  "sentarse": {
    "example": "Vamos a sentarnos cerca de la ventana.",
    "exampleEnglish": "We're going to sit near the window."
  },
  "acostarse": {
    "example": "No olvide apagar todas las luces antes de acostarse.",
    "exampleEnglish": "Don't forget to turn off all the lights before going to bed."
  },
  "despertarse": {
    "example": "Es difícil despertarse sin una taza de café fuerte.",
    "exampleEnglish": "It is hard to wake up without a strong cup of coffee."
  },
  "ducharse": {
    "example": "Es obligatorio ducharse antes de meterse en la piscina.",
    "exampleEnglish": "You must shower before entering the pool."
  },
  "bañarse": {
    "example": "A mis niños no les gusta bañarse.",
    "exampleEnglish": "My kids don't like taking baths."
  },
  "peinarse": {
    "example": "Voy a peinarme antes de la entrevista.",
    "exampleEnglish": "I'm going to comb my hair before the interview."
  },
  "afeitarse": {
    "example": "Mi padre suele afeitarse cada mañana.",
    "exampleEnglish": "My father usually shaves every morning."
  },
  "casar": {
    "example": "Ella quiere casar a su hija con un doctor.",
    "exampleEnglish": "She wants to marry her daughter to a doctor."
  },
  "casarse": {
    "example": "Ella prometió casarse con él, pero no lo hizo.",
    "exampleEnglish": "She promised to marry him, but she didn't."
  },
  "reunir": {
    "example": "Él trató de reunir los fragmentos de un jarrón roto.",
    "exampleEnglish": "He tried to put the fragments of a broken vase together."
  },
  "reunirse": {
    "example": "Vamos a reunirnos el lunes para hablar del proyecto.",
    "exampleEnglish": "We're going to meet on Monday to talk about the project."
  },
  "encontrarse": {
    "example": "Ella prometió encontrarse con él ayer por la noche.",
    "exampleEnglish": "She promised to meet him last night."
  },
  "preocupar": {
    "example": "El retraso empezó a preocupar a la familia.",
    "exampleEnglish": "The delay began to worry the family."
  },
  "preocuparse": {
    "example": "No hace falta preocuparse tanto por eso.",
    "exampleEnglish": "There's no need to worry so much about that."
  },
  "ocupar": {
    "example": "Esta caja va a ocupar mucho espacio.",
    "exampleEnglish": "This box is going to take up a lot of space."
  },
  "ocuparse": {
    "example": "Aquí no hay nadie que pueda ocuparse del problema.",
    "exampleEnglish": "There's no one here who can deal with the problem."
  },
  "llamarse": {
    "example": "En aquella época, el pueblo solía llamarse Villanueva del Río.",
    "exampleEnglish": "In those days, the village used to be called Villanueva del Río."
  },
  "sentirse": {
    "example": "Después de descansar, Marta empezó a sentirse mucho mejor.",
    "exampleEnglish": "After resting, Marta began to feel much better."
  },
  "acordar": {
    "example": "Los vecinos lograron acordar un horario para las obras.",
    "exampleEnglish": "The neighbours managed to agree on a schedule for the building work."
  },
  "acordarse": {
    "example": "No consigo acordarme de su nombre.",
    "exampleEnglish": "I can't manage to remember his name."
  },
  "olvidarse": {
    "example": "Espero no olvidarme las llaves otra vez.",
    "exampleEnglish": "I hope I don't forget my keys again."
  },
  "contestar": {
    "example": "Voy a contestar el correo por la tarde.",
    "exampleEnglish": "I'm going to answer the email in the afternoon."
  },
  "describir": {
    "example": "¿Puede describir la situación en la que se encontraba?",
    "exampleEnglish": "Can you describe the situation you were in?"
  },
  "comparar": {
    "example": "Vamos a comparar los dos presupuestos.",
    "exampleEnglish": "We're going to compare the two budgets."
  },
  "cambiarse": {
    "example": "Voy a cambiarme antes de salir a cenar.",
    "exampleEnglish": "I'm going to change clothes before going out to dinner."
  },
  "probar": {
    "example": "Quiero probar este plato nuevo del menú.",
    "exampleEnglish": "I want to try this new dish on the menu."
  },
  "prohibir": {
    "example": "El ayuntamiento decidió prohibir las barbacoas durante la sequía.",
    "exampleEnglish": "The council decided to ban barbecues during the drought."
  },
  "obligar": {
    "example": "Nunca te voy a obligar a casarte con él.",
    "exampleEnglish": "I will never force you to marry him."
  },
  "recomendar": {
    "example": "¿Me podrías recomendar un buen restaurante por aquí cerca?",
    "exampleEnglish": "Could you recommend a nice restaurant near here?"
  },
  "aconsejar": {
    "example": "Mi médico me suele aconsejar caminar más.",
    "exampleEnglish": "My doctor usually advises me to walk more."
  },
  "sugerir": {
    "example": "Voy a sugerir otra fecha para la cita.",
    "exampleEnglish": "I'm going to suggest a different date for the appointment."
  },
  "invitar": {
    "example": "¿La vas a invitar a ella a la fiesta?",
    "exampleEnglish": "Are you going to invite her to the party?"
  },
  "rechazar": {
    "example": "Él me hizo una oferta que no pude rechazar.",
    "exampleEnglish": "He made me an offer I couldn't refuse."
  },
  "negar": {
    "example": "No puedo negar que estoy nervioso.",
    "exampleEnglish": "I can't deny that I'm nervous."
  },
  "afirmar": {
    "example": "Sin pruebas sólidas, nadie debería afirmar que el cuadro es falso.",
    "exampleEnglish": "Without solid evidence, nobody should claim that the painting is fake."
  },
  "prometer": {
    "example": "Te prometo llamarte en cuanto llegue.",
    "exampleEnglish": "I promise to call you as soon as I arrive."
  },
  "fallar": {
    "example": "Un plan así está destinado a fallar.",
    "exampleEnglish": "Such a plan is bound to fail."
  },
  "ahorrar": {
    "example": "Lucía empezó a ahorrar para comprar una bicicleta.",
    "exampleEnglish": "Lucía began to save for a bicycle."
  },
  "gastar": {
    "example": "Conviene comparar precios antes de gastar los ahorros.",
    "exampleEnglish": "It is wise to compare prices before spending your savings."
  },
  "cobrar": {
    "example": "El taller va a cobrar la reparación mañana.",
    "exampleEnglish": "The garage is going to charge for the repair tomorrow."
  },
  "costar": {
    "example": "El viaje puede costar más de cien euros.",
    "exampleEnglish": "The trip can cost more than a hundred euros."
  },
  "valer": {
    "example": "Esta entrada puede valer más si el músico se hace famoso.",
    "exampleEnglish": "This ticket may be worth more if the musician becomes famous."
  },
  "preferir": {
    "example": "Prefiero viajar en tren.",
    "exampleEnglish": "I prefer to travel by train."
  },
  "odiar": {
    "example": "Odio esperar en filas largas.",
    "exampleEnglish": "I hate waiting in long lines."
  },
  "amar": {
    "example": "No puedo amar a nadie más que a ti.",
    "exampleEnglish": "I can't love anyone but you."
  },
  "encantar": {
    "example": "Sé que este libro te va a encantar.",
    "exampleEnglish": "I know you're going to love this book."
  },
  "molestar": {
    "example": "No quiero molestar a nadie mientras estudia.",
    "exampleEnglish": "I do not want to disturb anyone while they are studying."
  },
  "importar": {
    "example": "Lo que piensas puede importar mucho.",
    "exampleEnglish": "What you think can matter a lot."
  },
  "faltar": {
    "example": "Puede faltar una pieza.",
    "exampleEnglish": "A piece might be missing."
  },
  "doler": {
    "example": "Te prometo que no te va a doler.",
    "exampleEnglish": "It won't hurt, I promise."
  },
  "aburrir": {
    "example": "No te voy a aburrir con los detalles.",
    "exampleEnglish": "I won't bore you with the details."
  },
  "divertir": {
    "example": "El cuentacuentos consiguió divertir a niños y adultos.",
    "exampleEnglish": "The storyteller managed to entertain both children and adults."
  },
  "interesar": {
    "example": "La charla podría interesar a quienes estudian arquitectura sostenible.",
    "exampleEnglish": "The talk might interest people who study sustainable architecture."
  },
  "sorprender": {
    "example": "La respuesta puede sorprenderte.",
    "exampleEnglish": "The answer might surprise you."
  },
  "cansar": {
    "example": "Caminar tanto puede cansar a cualquiera.",
    "exampleEnglish": "Walking that much can tire anyone out."
  },
  "alegrar": {
    "example": "Me acabas de alegrar el día.",
    "exampleEnglish": "You just made my day."
  },
  "entristecer": {
    "example": "Ver el parque abandonado suele entristecer a los vecinos mayores.",
    "exampleEnglish": "Seeing the park neglected tends to sadden the older residents."
  },
  "asustar": {
    "example": "Ese ruido puede asustar al perro.",
    "exampleEnglish": "That noise can scare the dog."
  },
  "enfadar": {
    "example": "El retraso volvió a enfadar a los pasajeros.",
    "exampleEnglish": "The delay made the passengers angry again."
  },
  "calmar": {
    "example": "Un té caliente puede calmar los nervios.",
    "exampleEnglish": "A hot tea can calm the nerves."
  },
  "relajar": {
    "example": "Yo pienso que ahora nos podemos relajar.",
    "exampleEnglish": "I think we can relax now."
  },
  "temer": {
    "example": "No debes temer el cambio.",
    "exampleEnglish": "You shouldn't fear change."
  },
  "confiar": {
    "example": "Él es un hombre en quien siempre puedes confiar.",
    "exampleEnglish": "He is a man who can always be trusted."
  },
  "dudar": {
    "example": "Es normal dudar al principio.",
    "exampleEnglish": "It's normal to doubt yourself at first."
  },
  "planear": {
    "example": "Vamos a planear la ruta antes de reservar los hoteles.",
    "exampleEnglish": "We are going to plan the route before booking the hotels."
  },
  "organizar": {
    "example": "Necesito organizar mi escritorio hoy.",
    "exampleEnglish": "I need to organize my desk today."
  },
  "reservar": {
    "example": "Quiero reservar una mesa para cuatro a las seis.",
    "exampleEnglish": "I'd like to reserve a table for four at six."
  },
  "cancelar": {
    "example": "Una repentina enfermedad la forzó a cancelar su cita.",
    "exampleEnglish": "A sudden illness forced her to cancel her appointment."
  },
  "visitar": {
    "example": "El próximo domingo iremos a visitar a nuestra tía.",
    "exampleEnglish": "We are going to visit our aunt next Sunday."
  },
  "explorar": {
    "example": "Nos encanta explorar pueblos pequeños.",
    "exampleEnglish": "We love exploring small villages."
  },
  "quedarse": {
    "example": "Ella está acostumbrada a quedarse despierta toda la noche.",
    "exampleEnglish": "She is used to staying up all night."
  },
  "alojar": {
    "example": "Este hotel puede alojar a más de 1000 huéspedes.",
    "exampleEnglish": "This hotel can accommodate over 1,000 guests."
  },
  "alojarse": {
    "example": "Durante el congreso, los ponentes podrán alojarse junto a la estación.",
    "exampleEnglish": "During the conference, the speakers can stay near the station."
  },
  "volar": {
    "example": "Si yo fuera un pájaro, podría volar hasta ti.",
    "exampleEnglish": "If I were a bird, I could fly to you."
  },
  "montar": {
    "example": "A mi hijo le gusta montar en bicicleta.",
    "exampleEnglish": "My son likes riding his bike."
  },
  "nadar": {
    "example": "¿Esta tarde prefieres ir a navegar o a nadar?",
    "exampleEnglish": "Would you rather go sailing or swimming this afternoon?"
  },
  "andar": {
    "example": "Ella estaba tan cansada que no podía andar.",
    "exampleEnglish": "She was so tired that she couldn't walk."
  },
  "pasear": {
    "example": "Él salió a pasear con ella esta mañana.",
    "exampleEnglish": "He went for a walk with her this morning."
  },
  "cruzar": {
    "example": "Él fue el primer hombre en cruzar el Pacífico.",
    "exampleEnglish": "He was the first man to cross the Pacific."
  },
  "girar": {
    "example": "¿Qué ocurriría si la Tierra dejara de girar?",
    "exampleEnglish": "What would happen if the earth stopped spinning?"
  },
  "detener": {
    "example": "Levanté la mano para detener un taxi.",
    "exampleEnglish": "I held up my hand to stop a taxi."
  },
  "detenerse": {
    "example": "El coche se va a detener en el semáforo.",
    "exampleEnglish": "The car is going to stop at the traffic light."
  },
  "aparcar": {
    "example": "Voy a aparcar cerca de la entrada.",
    "exampleEnglish": "I'm going to park near the entrance."
  },
  "arrancar": {
    "example": "El coche no quiere arrancar esta mañana.",
    "exampleEnglish": "The car doesn't want to start this morning."
  },
  "frenar": {
    "example": "El conductor tuvo que frenar al ver el semáforo rojo.",
    "exampleEnglish": "The driver had to brake when he saw the red light."
  },
  "acelerar": {
    "example": "No hace falta acelerar tanto en esta curva.",
    "exampleEnglish": "There's no need to accelerate so much on this curve."
  },
  "saltar": {
    "example": "El perro puede saltar la valla del jardín.",
    "exampleEnglish": "The dog can jump over the garden fence."
  },
  "lanzar": {
    "example": "Van a lanzar el nuevo producto en abril.",
    "exampleEnglish": "They're going to launch the new product in April."
  },
  "tirar": {
    "example": "Voy a tirar estas cajas viejas.",
    "exampleEnglish": "I'm going to throw away these old boxes."
  },
  "recoger": {
    "example": "¿Te importaría recoger algo en el camino de regreso?",
    "exampleEnglish": "Would you mind picking up something on the way back?"
  },
  "guardar": {
    "example": "Deberías guardar tus objetos de valor en un lugar seguro.",
    "exampleEnglish": "You should keep your valuables in a safe place."
  },
  "hallar": {
    "example": "Espero hallar una solución pronto.",
    "exampleEnglish": "I hope to find a solution soon."
  },
  "esconder": {
    "example": "Ese secreto no se puede esconder para siempre.",
    "exampleEnglish": "That secret can't be kept forever."
  },
  "esconderse": {
    "example": "El estudio es muy pequeño, sin lugares donde esconderse.",
    "exampleEnglish": "The studio is very small, with no place to hide."
  },
  "observar": {
    "example": "Nos gusta observar los pájaros en el parque.",
    "exampleEnglish": "We like to observe the birds in the park."
  },
  "oler": {
    "example": "La cocina huele a pan recién hecho.",
    "exampleEnglish": "The kitchen smells like freshly baked bread."
  },
  "comentar": {
    "example": "Tengo un asunto complicado que quiero comentar contigo.",
    "exampleEnglish": "I have a complicated matter I want to discuss with you."
  },
  "conversar": {
    "example": "Es grosero conversar en medio de un concierto.",
    "exampleEnglish": "It's bad manners to talk during a concert."
  },
  "discutir": {
    "example": "Antes de discutir el presupuesto, revisemos las cifras.",
    "exampleEnglish": "Before discussing the budget, let us review the figures."
  },
  "gritar": {
    "example": "No hace falta gritar para que todos te oigan.",
    "exampleEnglish": "You do not need to shout for everyone to hear you."
  },
  "susurrar": {
    "example": "Para no despertar al bebé, tuvimos que susurrar en el pasillo.",
    "exampleEnglish": "To avoid waking the baby, we had to whisper in the corridor."
  },
  "firmar": {
    "example": "Lee todas las condiciones antes de firmar el contrato.",
    "exampleEnglish": "Read all the terms before signing the contract."
  },
  "copiar": {
    "example": "Puedes copiar la dirección en tu cuaderno.",
    "exampleEnglish": "You can copy the address into your notebook."
  },
  "borrar": {
    "example": "Está escrito a lápiz, así que lo podéis borrar.",
    "exampleEnglish": "It's written in pencil, so you can erase it."
  },
  "dibujar": {
    "example": "A mi hijo le encanta dibujar animales.",
    "exampleEnglish": "My son loves drawing animals."
  },
  "pintar": {
    "example": "Pintar es otra cosa que puedo hacer bastante bien.",
    "exampleEnglish": "Painting is another thing I can do fairly well."
  },
  "imprimir": {
    "example": "Este aparato puede imprimir sesenta páginas por minuto.",
    "exampleEnglish": "This machine can print sixty pages a minute."
  },
  "publicar": {
    "example": "Él acaba de publicar una interesante serie de artículos.",
    "exampleEnglish": "He has just published an interesting series of articles."
  },
  "encender": {
    "example": "Apreté el botón para encender la radio.",
    "exampleEnglish": "I pressed the button to turn the radio on."
  },
  "apagar": {
    "example": "Deberías apagar la luz antes de irte a dormir.",
    "exampleEnglish": "You should turn off the light before going to sleep."
  },
  "conectar": {
    "example": "Necesito conectar el portátil al proyector.",
    "exampleEnglish": "I need to connect the laptop to the projector."
  },
  "desconectar": {
    "example": "Conviene desconectar la tostadora antes de limpiarla.",
    "exampleEnglish": "It is sensible to unplug the toaster before cleaning it."
  },
  "cargar": {
    "example": "El personal ayudó a cargar las cajas en la furgoneta.",
    "exampleEnglish": "The staff helped load the boxes into the van."
  },
  "descargar": {
    "example": "Puedes descargar grabaciones de nativos en nuestra página web.",
    "exampleEnglish": "You can download audio files by native speakers from our website."
  },
  "instalar": {
    "example": "El hombre trató de instalar su propia antena.",
    "exampleEnglish": "The man tried to install his own antenna."
  },
  "actualizar": {
    "example": "Tengo que actualizar el sistema esta noche.",
    "exampleEnglish": "I have to update the system tonight."
  },
  "reparar": {
    "example": "El técnico va a reparar la lavadora mañana.",
    "exampleEnglish": "The technician is going to repair the washing machine tomorrow."
  },
  "funcionar": {
    "example": "No está claro que podamos hacer funcionar el motor.",
    "exampleEnglish": "It is doubtful if we can get the engine working."
  },
  "seleccionar": {
    "example": "Mantén pulsada la tecla Mayús para seleccionar varias fotografías.",
    "exampleEnglish": "Hold down the Shift key to select several photographs."
  },
  "pulsar": {
    "example": "Todo lo que tienes que hacer es pulsar el botón.",
    "exampleEnglish": "All you have to do is press the button."
  },
  "clicar": {
    "example": "Basta con clicar en el icono azul para abrir el calendario.",
    "exampleEnglish": "You only need to click the blue icon to open the calendar."
  },
  "navegar": {
    "example": "Ella estaba deseando irse a navegar con él.",
    "exampleEnglish": "She was looking forward to going sailing with him."
  },
  "eliminar": {
    "example": "Este filtro permite eliminar el ruido de fondo de la grabación.",
    "exampleEnglish": "This filter can remove background noise from the recording."
  },
  "editar": {
    "example": "Para editar una frase, haga clic en el icono de lápiz.",
    "exampleEnglish": "To edit a sentence, click on the pencil icon."
  },
  "revisar": {
    "example": "Voy a revisar el horario antes de comprar los billetes.",
    "exampleEnglish": "I am going to check the timetable before buying the tickets."
  },
  "comprobar": {
    "example": "Vamos a comprobar que todo funciona bien.",
    "exampleEnglish": "We're going to check that everything works well."
  },
  "medir": {
    "example": "Él se debe medir la presión sanguínea todos los días.",
    "exampleEnglish": "He has to have his blood pressure taken every day."
  },
  "calcular": {
    "example": "Los científicos fácilmente pueden calcular la distancia entre planetas.",
    "exampleEnglish": "Scientists can easily compute the distance between planets."
  },
  "sumar": {
    "example": "¿Puedes sumar estos números?",
    "exampleEnglish": "Can you add these numbers?"
  },
  "restar": {
    "example": "Para calcular el cambio, hay que restar dieciocho euros de cincuenta.",
    "exampleEnglish": "To calculate the change, you have to subtract eighteen euros from fifty."
  },
  "multiplicar": {
    "example": "La receta exige multiplicar todas las cantidades por tres.",
    "exampleEnglish": "The recipe requires you to multiply all the quantities by three."
  },
  "dividir": {
    "example": "Vamos a dividir la tarta en ocho trozos.",
    "exampleEnglish": "We're going to divide the cake into eight pieces."
  },
  "ordenar": {
    "example": "No tengo tiempo de ordenar mis libros antes de irme.",
    "exampleEnglish": "I have no time to put my books in order before I go."
  },
  "clasificar": {
    "example": "Nos llevó toda la tarde clasificar las cartas por fecha.",
    "exampleEnglish": "It took us all afternoon to sort the letters by date."
  },
  "agrupar": {
    "example": "Puedes agrupar las piezas según su forma y su color.",
    "exampleEnglish": "You can group the pieces according to their shape and colour."
  },
  "mezclar": {
    "example": "Vas a mezclar la harina con el azúcar.",
    "exampleEnglish": "You're going to mix the flour with the sugar."
  },
  "separar": {
    "example": "Ellos se quieren separar después de 40 años de matrimonio.",
    "exampleEnglish": "They want to separate after 40 years of marriage."
  },
  "pegar": {
    "example": "Usa cinta de papel para pegar el dibujo a la cartulina.",
    "exampleEnglish": "Use masking tape to stick the drawing to the card."
  },
  "unir": {
    "example": "Necesitamos un nuevo líder para unir a nuestra empresa.",
    "exampleEnglish": "We need a new leader to pull our company together."
  },
  "llenar": {
    "example": "Voy a llenar la botella de agua.",
    "exampleEnglish": "I'm going to fill the water bottle."
  },
  "vaciar": {
    "example": "El camarero salió a vaciar las botellas en el contenedor verde.",
    "exampleEnglish": "The waiter went out to empty the bottles into the green recycling bin."
  },
  "cubrir": {
    "example": "Ese dinero es suficiente para cubrir los gastos.",
    "exampleEnglish": "That's enough money to cover the expenses."
  },
  "pausar": {
    "example": "No olvides pausar la grabación cuando termine la entrevista.",
    "exampleEnglish": "Do not forget to pause the recording when the interview ends."
  },
  "reiniciar": {
    "example": "¿Probaste a reiniciar el ordenador?",
    "exampleEnglish": "Did you try restarting the computer?"
  },
  "practicar": {
    "example": "A mí me gusta tanto ver como practicar deportes.",
    "exampleEnglish": "I like both watching and playing sports."
  },
  "memorizar": {
    "example": "Tenemos que memorizar este poema para la próxima clase.",
    "exampleEnglish": "We have to memorize this poem by the next class."
  },
  "imaginar": {
    "example": "¿Te puedes imaginar cómo sería la vida sin televisión?",
    "exampleEnglish": "Can you imagine what life would be like without television?"
  },
  "soñar": {
    "example": "Me gusta soñar con viajes largos.",
    "exampleEnglish": "I like to dream about long trips."
  },
  "desear": {
    "example": "Todos podemos desear algo mejor.",
    "exampleEnglish": "We can all wish for something better."
  },
  "evitar": {
    "example": "Debemos evitar que este tipo de incidente se repita.",
    "exampleEnglish": "We must prevent this type of incident from recurring."
  },
  "tener": {
    "example": "Quiero tener más tiempo libre.",
    "exampleEnglish": "I want to have more free time."
  },
  "convertirse": {
    "example": "La idea puede convertirse en un proyecto.",
    "exampleEnglish": "The idea can turn into a project."
  },
  "disminuir": {
    "example": "Es necesaria la cooperación de los empleados para disminuir los gastos.",
    "exampleEnglish": "The employees need to cooperate to lower expenses."
  },
  "desarrollar": {
    "example": "El equipo espera desarrollar una batería más duradera.",
    "exampleEnglish": "The team hopes to develop a longer-lasting battery."
  },
  "construir": {
    "example": "El coste de construir el ferrocarril era demasiado alto.",
    "exampleEnglish": "The cost of building the railroad was very high."
  },
  "destruir": {
    "example": "La humedad puede destruir documentos antiguos en pocos meses.",
    "exampleEnglish": "Damp can destroy old documents within a few months."
  },
  "fabricar": {
    "example": "La cooperativa aprendió a fabricar jabón con aceite usado.",
    "exampleEnglish": "The cooperative learnt to make soap from used oil."
  },
  "alquilar": {
    "example": "Queremos alquilar un piso cerca del centro.",
    "exampleEnglish": "We want to rent a flat near the centre."
  },
  "devolver": {
    "example": "Tengo que devolver este libro a la biblioteca.",
    "exampleEnglish": "I have to return this book to the library."
  },
  "prestar": {
    "example": "¿Me puedes prestar tu paraguas?",
    "exampleEnglish": "Can you lend me your umbrella?"
  },
  "mandar": {
    "example": "Olvidé mandar tarjetas de año nuevo a mis amigos.",
    "exampleEnglish": "I forgot to send New Year's cards to my friends."
  },
  "entregar": {
    "example": "Tengo que entregar el proyecto el viernes.",
    "exampleEnglish": "I have to hand in the project on Friday."
  },
  "invertir": {
    "example": "El gobierno debería invertir más dinero en la agricultura.",
    "exampleEnglish": "The government should invest more money in agriculture."
  },
  "descansar": {
    "example": "El anciano se detuvo un momento para descansar.",
    "exampleEnglish": "The old man stopped for a moment to rest."
  },
  "despertar": {
    "example": "La luz del amanecer suele despertar a los pájaros del jardín.",
    "exampleEnglish": "The light at dawn usually wakes the birds in the garden."
  },
  "sentar": {
    "example": "La anfitriona decidió sentar a los invitados cerca de la ventana.",
    "exampleEnglish": "The host decided to seat the guests near the window."
  },
  "acostar": {
    "example": "Voy a acostar al bebé después del baño.",
    "exampleEnglish": "I am going to put the baby to bed after the bath."
  },
  "vestirse": {
    "example": "Los niños dependen de los padres para alimentarse y vestirse.",
    "exampleEnglish": "Children depend on their parents for food and clothing."
  },
  "desnudar": {
    "example": "La enfermera va a desnudar al paciente para la revisión.",
    "exampleEnglish": "The nurse is going to undress the patient for the check-up."
  },
  "desnudarse": {
    "example": "Los nadadores entraron en los vestuarios para desnudarse.",
    "exampleEnglish": "The swimmers went into the changing rooms to get undressed."
  },
  "lavarse": {
    "example": "Voy a lavarme las manos antes de comer.",
    "exampleEnglish": "I'm going to wash my hands before eating."
  },
  "duchar": {
    "example": "Después del paseo, tuvimos que duchar al perro.",
    "exampleEnglish": "After the walk, we had to shower the dog."
  },
  "bañar": {
    "example": "¿A quién le toca bañar al perro?",
    "exampleEnglish": "Whose turn is it to give the dog a bath?"
  },
  "peinar": {
    "example": "Voy a peinar a mi hija para el colegio.",
    "exampleEnglish": "I'm going to comb my daughter's hair for school."
  },
  "afeitar": {
    "example": "El barbero va a afeitar al cliente con cuidado.",
    "exampleEnglish": "The barber is going to shave the customer carefully."
  },
  "maquillar": {
    "example": "Una artista vino a maquillar a los actores antes del estreno.",
    "exampleEnglish": "A make-up artist came to do the actors' make-up before the première."
  },
  "maquillarse": {
    "example": "Voy a maquillarme antes de la fiesta.",
    "exampleEnglish": "I'm going to put on makeup before the party."
  },
  "desayunar": {
    "example": "¿Tú crees que desayunar todos los días es importante?",
    "exampleEnglish": "Do you think that eating breakfast every day is important?"
  },
  "almorzar": {
    "example": "Vamos a almorzar en aquel restaurante cerca de la oficina.",
    "exampleEnglish": "We're going to have lunch at that restaurant near the office."
  },
  "cenar": {
    "example": "Vamos a cenar temprano hoy.",
    "exampleEnglish": "We're going to have dinner early today."
  },
  "merendar": {
    "example": "Cuando salíamos del colegio, solíamos merendar pan con chocolate.",
    "exampleEnglish": "When we left school, we used to have bread and chocolate as an afternoon snack."
  },
  "calentar": {
    "example": "Voy a calentar la sopa para la cena.",
    "exampleEnglish": "I'm going to heat up the soup for dinner."
  },
  "enfriar": {
    "example": "Es mejor enfriar el vino blanco antes de servirlo.",
    "exampleEnglish": "It's better to chill white wine before you serve it."
  },
  "hervir": {
    "example": "Ni siquiera sé hervir agua, mucho menos asar un pavo.",
    "exampleEnglish": "I cannot even boil water, much less roast a turkey."
  },
  "freír": {
    "example": "Hace tanto calor afuera que podrías freír un huevo.",
    "exampleEnglish": "It's so hot outside, you could fry an egg."
  },
  "hornear": {
    "example": "Hoy voy a hornear una tarta de melocotón.",
    "exampleEnglish": "I'm going to bake a peach pie today."
  },
  "pelar": {
    "example": "Voy a pelar las patatas antes de poner agua a hervir.",
    "exampleEnglish": "I am going to peel the potatoes before boiling the water."
  },
  "echar": {
    "example": "Recuerda echar una pizca de sal antes de servir la sopa.",
    "exampleEnglish": "Remember to add a pinch of salt before serving the soup."
  },
  "secar": {
    "example": "Voy a secar la ropa antes de guardarla.",
    "exampleEnglish": "I'm going to dry the clothes before putting them away."
  },
  "planchar": {
    "example": "Hace falta planchar esta camisa.",
    "exampleEnglish": "This shirt needs to be ironed."
  },
  "barrer": {
    "example": "Voy a barrer la cocina después de cenar.",
    "exampleEnglish": "I'm going to sweep the kitchen after dinner."
  },
  "fregar": {
    "example": "¿Quieres que te ayude a fregar los platos?",
    "exampleEnglish": "Would you like me to help you with washing the dishes?"
  },
  "arreglar": {
    "example": "Necesito arreglar la bicicleta este fin de semana.",
    "exampleEnglish": "I need to fix the bike this weekend."
  },
  "reciclar": {
    "example": "La oficina empezó a reciclar todo el papel usado.",
    "exampleEnglish": "The office began to recycle all its used paper."
  },
  "plantar": {
    "example": "Cuando tenía 14 años, él empezó a plantar fresas.",
    "exampleEnglish": "When he was 14, he started to plant strawberries."
  },
  "regar": {
    "example": "No es bueno regar las plantas a pleno sol.",
    "exampleEnglish": "It's not good to water plants in direct sunlight."
  },
  "cuidar": {
    "example": "Ella ayudó a su madre a cuidar del bebé.",
    "exampleEnglish": "She assisted her mother in caring for the baby."
  },
  "alimentar": {
    "example": "Preferiría alimentar a mi perro antes de que comamos.",
    "exampleEnglish": "I would rather feed my dog before we eat."
  },
  "adoptar": {
    "example": "Queremos adoptar un gato del refugio.",
    "exampleEnglish": "We want to adopt a cat from the shelter."
  },
  "criar": {
    "example": "Mis abuelos suelen criar gallinas en el pueblo.",
    "exampleEnglish": "My grandparents usually raise chickens in the village."
  },
  "cazar": {
    "example": "¿Cuándo fue la última vez que fueron a cazar?",
    "exampleEnglish": "When was the last time you went hunting?"
  },
  "pescar": {
    "example": "Era un buen día así que fuimos a pescar.",
    "exampleEnglish": "It was a nice day so we went fishing."
  },
  "morder": {
    "example": "Tiene el mal hábito de morder el lápiz.",
    "exampleEnglish": "He has the bad habit of chewing his pencil."
  },
  "ladrar": {
    "example": "Ella oyó a un perro ladrar a lo lejos.",
    "exampleEnglish": "She heard a dog barking in the distance."
  },
  "maullar": {
    "example": "Oímos al gato maullar detrás de la puerta cerrada.",
    "exampleEnglish": "We heard the cat miaow behind the closed door."
  },
  "fotografiar": {
    "example": "A mi hermano le encanta fotografiar montañas.",
    "exampleEnglish": "My brother loves taking pictures of mountains."
  },
  "grabar": {
    "example": "Se necesitaron muchos meses para grabar esa película.",
    "exampleEnglish": "It took several months to shoot that film."
  },
  "filmar": {
    "example": "El director eligió filmar la última escena al amanecer.",
    "exampleEnglish": "The director chose to film the final scene at dawn."
  },
  "entrenar": {
    "example": "¿Por qué son los perros más fáciles de entrenar que los gatos?",
    "exampleEnglish": "Why are dogs easier to train than cats?"
  },
  "competir": {
    "example": "Tuve que competir con él por un ascenso.",
    "exampleEnglish": "I had to compete with him for promotion."
  },
  "empatar": {
    "example": "Un gol en el último minuto permitió al Betis empatar el partido.",
    "exampleEnglish": "A goal in the final minute allowed Betis to draw the match."
  },
  "marcar": {
    "example": "El reloj acaba de marcar las tres.",
    "exampleEnglish": "The clock has just struck three."
  },
  "atrapar": {
    "example": "¿Qué tipo de cebo usaste para atrapar estos peces?",
    "exampleEnglish": "What kind of bait did you use to catch these fish?"
  },
  "golpear": {
    "example": "Las gotas de lluvia empezaron a golpear suavemente el cristal.",
    "exampleEnglish": "The raindrops began to tap gently against the windowpane."
  },
  "patear": {
    "example": "El defensa corrió hacia el balón para patear desde lejos.",
    "exampleEnglish": "The defender ran towards the ball to kick it from long range."
  },
  "pedalear": {
    "example": "Tras el descanso, aún nos quedaban veinte kilómetros por pedalear.",
    "exampleEnglish": "After the break, we still had twenty kilometres left to cycle."
  },
  "esquiar": {
    "example": "Queremos esquiar en los Pirineos este invierno.",
    "exampleEnglish": "We want to ski in the Pyrenees this winter."
  },
  "patinar": {
    "example": "Yo no esquío pero me gusta mucho patinar.",
    "exampleEnglish": "I don't ski, but I really like to skate."
  },
  "escalar": {
    "example": "Me gusta escalar árboles de vez en cuando.",
    "exampleEnglish": "I enjoy climbing trees every once in a while."
  },
  "despegar": {
    "example": "El avión va a despegar en cuanto se despeje la pista.",
    "exampleEnglish": "The plane will take off as soon as the runway is clear."
  },
  "aterrizar": {
    "example": "Un helicóptero es capaz de despegar y aterrizar verticalmente.",
    "exampleEnglish": "A helicopter is able to take off and land straight up and down."
  },
  "facturar": {
    "example": "La aerolínea permite facturar una maleta de hasta veinte kilos.",
    "exampleEnglish": "The airline allows passengers to check in one suitcase weighing up to twenty kilos."
  },
  "embarcar": {
    "example": "Los pasajeros deben embarcar por la puerta doce.",
    "exampleEnglish": "Passengers must board at gate twelve."
  },
  "informar": {
    "example": "Voy a informar al equipo de los cambios.",
    "exampleEnglish": "I'm going to inform the team of the changes."
  },
  "confirmar": {
    "example": "Necesito confirmar la reserva del restaurante.",
    "exampleEnglish": "I need to confirm the restaurant reservation."
  },
  "avisar": {
    "example": "¿Me podría avisar cuándo me tengo que bajar?",
    "exampleEnglish": "Would you please tell me when to get off?"
  },
  "anunciar": {
    "example": "La empresa espera anunciar los resultados el próximo jueves.",
    "exampleEnglish": "The company expects to announce the results next Thursday."
  },
  "comunicar": {
    "example": "Nos podemos comunicar en francés.",
    "exampleEnglish": "We can communicate in French."
  },
  "traducir": {
    "example": "¿Puedo ayudar a traducir la página web a otras lenguas?",
    "exampleEnglish": "Can I help translate the website into other languages?"
  },
  "pronunciar": {
    "example": "No estoy seguro de cómo pronunciar esta palabra.",
    "exampleEnglish": "I am not sure how to pronounce the word."
  },
  "deletrear": {
    "example": "¿Podría deletrear su nombre, por favor?",
    "exampleEnglish": "Could you spell your name, please?"
  },
  "corregir": {
    "example": "¿Puedes corregir este informe antes de las 5 de la tarde?",
    "exampleEnglish": "Can you correct this report before 5:00 p.m.?"
  },
  "aprobar": {
    "example": "Estudié mucho, de modo que pude aprobar el examen.",
    "exampleEnglish": "I studied hard so that I could pass the examination."
  },
  "suspender": {
    "example": "Está claro que te van a suspender si no estudias más.",
    "exampleEnglish": "You'll definitely fail if you don't study more."
  },
  "examinar": {
    "example": "Los dentistas toman rayos x para examinar tus dientes.",
    "exampleEnglish": "Dentists take X-rays to examine your teeth."
  },
  "evaluar": {
    "example": "Es difícil evaluar su capacidad.",
    "exampleEnglish": "It's difficult to evaluate his ability."
  },
  "completar": {
    "example": "Necesito completar este formulario hoy.",
    "exampleEnglish": "I need to complete this form today."
  },
  "rellenar": {
    "example": "Tienes que rellenar todos los campos del formulario.",
    "exampleEnglish": "You have to fill in all the fields on the form."
  },
  "investigar": {
    "example": "Investigar las causas del cáncer es muy costoso.",
    "exampleEnglish": "Investigating the causes of cancer is very expensive."
  },
  "analizar": {
    "example": "Tenemos que analizar eso.",
    "exampleEnglish": "We have to analyze that."
  },
  "experimentar": {
    "example": "No tenga miedo de experimentar cosas nuevas.",
    "exampleEnglish": "Don't be afraid to try new things."
  },
  "demostrar": {
    "example": "Voy a demostrar que tengo razón.",
    "exampleEnglish": "I'm going to prove that I'm right."
  },
  "concluir": {
    "example": "Necesito concluir esta tarea antes de que se haga de noche.",
    "exampleEnglish": "I need to finish this work before it gets dark."
  },
  "gestionar": {
    "example": "Él tiene la capacidad suficiente para gestionar un negocio.",
    "exampleEnglish": "He has enough ability to manage a business."
  },
  "liderar": {
    "example": "Ellos ponen en duda su capacidad para liderar.",
    "exampleEnglish": "They question your ability to lead."
  },
  "colaborar": {
    "example": "Vamos a colaborar con otra empresa este año.",
    "exampleEnglish": "We're going to collaborate with another company this year."
  },
  "participar": {
    "example": "No pude participar en el encuentro por estar enfermo.",
    "exampleEnglish": "I wasn't able to attend the meeting due to illness."
  },
  "asistir": {
    "example": "¿Vas a asistir a la reunión de esta noche?",
    "exampleEnglish": "Are you going to attend the meeting tonight?"
  },
  "proponer": {
    "example": "Voy a proponer una idea nueva en la reunión.",
    "exampleEnglish": "I'm going to propose a new idea at the meeting."
  },
  "negociar": {
    "example": "Vamos a negociar el precio del coche.",
    "exampleEnglish": "We're going to negotiate the price of the car."
  },
  "contratar": {
    "example": "Queremos contratar a alguien que hable un francés fluido.",
    "exampleEnglish": "We want to hire someone who can speak French fluently."
  },
  "despedir": {
    "example": "Ha salido al aeropuerto a despedir a un amigo.",
    "exampleEnglish": "He went to the airport to see his friend off."
  },
  "emplear": {
    "example": "Esta fábrica va a emplear a cien trabajadores.",
    "exampleEnglish": "This factory is going to employ a hundred workers."
  },
  "solicitar": {
    "example": "Eres demasiado joven para solicitar el empleo.",
    "exampleEnglish": "You're too young to apply for the job."
  },
  "contactar": {
    "example": "Voy a contactar con el proveedor mañana.",
    "exampleEnglish": "I'm going to contact the supplier tomorrow."
  },
  "apoyar": {
    "example": "Vamos a apoyar tu decisión pase lo que pase.",
    "exampleEnglish": "We're going to support your decision no matter what."
  },
  "resolver": {
    "example": "A fin de cuentas, nadie pudo resolver el problema.",
    "exampleEnglish": "No one could solve the problem after all."
  },
  "solucionar": {
    "example": "Aquí no hay nadie que pueda solucionar el problema.",
    "exampleEnglish": "There's no one here who can deal with the problem."
  },
  "implementar": {
    "example": "El hospital tardará meses en implementar el nuevo protocolo.",
    "exampleEnglish": "The hospital will take months to implement the new protocol."
  },
  "diseñar": {
    "example": "No te sería muy difícil diseñar un nuevo sitio web.",
    "exampleEnglish": "It wouldn't be too hard to design a new website for you."
  },
  "programar": {
    "example": "Te enseñaré a programar, pero no hoy.",
    "exampleEnglish": "I will teach you to program, but not today."
  },
  "depurar": {
    "example": "Necesitamos depurar el programa antes de mostrárselo al cliente.",
    "exampleEnglish": "We need to debug the program before showing it to the client."
  },
  "desplegar": {
    "example": "El equipo acordó desplegar la actualización durante la madrugada.",
    "exampleEnglish": "The team agreed to deploy the update overnight."
  },
  "documentar": {
    "example": "Cada investigador debe documentar los cambios en el experimento.",
    "exampleEnglish": "Each researcher must document the changes to the experiment."
  },
  "planificar": {
    "example": "Reunimos varios mapas para planificar la ruta por los Pirineos.",
    "exampleEnglish": "We gathered several maps to plan the route through the Pyrenees."
  },
  "estimar": {
    "example": "Resulta difícil estimar el coste sin conocer las medidas exactas.",
    "exampleEnglish": "It is difficult to estimate the cost without knowing the exact measurements."
  },
  "priorizar": {
    "example": "Ante tantas averías, el taller debe priorizar las reparaciones urgentes.",
    "exampleEnglish": "With so many faults, the garage must prioritise urgent repairs."
  },
  "asignar": {
    "example": "Corresponde a la coordinadora asignar un tutor a cada alumno.",
    "exampleEnglish": "It is the coordinator's responsibility to assign a tutor to each pupil."
  },
  "monitorizar": {
    "example": "Instalaron sensores para monitorizar la humedad del invernadero.",
    "exampleEnglish": "They installed sensors to monitor the humidity in the greenhouse."
  },
  "controlar": {
    "example": "Necesito controlar mejor mis gastos.",
    "exampleEnglish": "I need to control my spending better."
  },
  "asegurar": {
    "example": "Voy a asegurar que todo esté listo mañana.",
    "exampleEnglish": "I'm going to make sure everything is ready tomorrow."
  },
  "proteger": {
    "example": "Ella arriesgó su vida para proteger a su hijo.",
    "exampleEnglish": "She risked her life to protect her child."
  },
  "bloquear": {
    "example": "Voy a bloquear este número desconocido.",
    "exampleEnglish": "I'm going to block this unknown number."
  },
  "desbloquear": {
    "example": "Una huella dactilar permite desbloquear el teléfono sin contraseña.",
    "exampleEnglish": "A fingerprint lets you unlock the phone without a password."
  },
  "registrarse": {
    "example": "Quien quiera asistir deberá registrarse antes del viernes.",
    "exampleEnglish": "Anyone wishing to attend must register before Friday."
  },
  "iniciar": {
    "example": "Vamos a iniciar la reunión en cinco minutos.",
    "exampleEnglish": "We're going to start the meeting in five minutes."
  },
  "acceder": {
    "example": "No consigo acceder a mi cuenta.",
    "exampleEnglish": "I can't manage to access my account."
  },
  "denegar": {
    "example": "El banco puede denegar el préstamo si faltan documentos.",
    "exampleEnglish": "The bank may refuse the loan if any documents are missing."
  },
  "recuperar": {
    "example": "Tengo que trabajar duro para recuperar el tiempo perdido.",
    "exampleEnglish": "I have to work hard to make up for lost time."
  },
  "renombrar": {
    "example": "Decidieron renombrar la plaza en honor a la poeta local.",
    "exampleEnglish": "They decided to rename the square in honour of the local poet."
  },
  "sincronizar": {
    "example": "Al conectar el reloj, empieza a sincronizar los datos automáticamente.",
    "exampleEnglish": "When you connect the watch, it starts synchronising the data automatically."
  },
  "exportar": {
    "example": "Voy a exportar los datos a una hoja de cálculo.",
    "exampleEnglish": "I'm going to export the data to a spreadsheet."
  },
  "filtrar": {
    "example": "Vamos a filtrar los resultados por fecha.",
    "exampleEnglish": "We're going to filter the results by date."
  },
  "desmarcar": {
    "example": "Para dejar de recibir publicidad, debes desmarcar esta casilla.",
    "exampleEnglish": "To stop receiving advertising, you must untick this box."
  },
  "avanzar": {
    "example": "¿Puedes avanzar para que podamos cerrar la puerta?",
    "exampleEnglish": "Could you move forward so we can close the door?"
  },
  "retroceder": {
    "example": "Vamos a retroceder un poco en el vídeo.",
    "exampleEnglish": "We're going to go back a bit in the video."
  },
  "ocultar": {
    "example": "Él trató de ocultar lo que realmente estaba pasando.",
    "exampleEnglish": "He tried to hide what was really going on."
  },
  "expandir": {
    "example": "Quisiera expandir mi vocabulario.",
    "exampleEnglish": "I want to increase my vocabulary."
  },
  "contraer": {
    "example": "Compartir agujas aumenta el riesgo de contraer una infección.",
    "exampleEnglish": "Sharing needles increases the risk of contracting an infection."
  },
  "activar": {
    "example": "Tienes que activar el sonido de tu micrófono.",
    "exampleEnglish": "You have to unmute your microphone."
  },
  "desactivar": {
    "example": "Me gustaría averiguar cómo desactivar comentarios en mi blog.",
    "exampleEnglish": "I wish I could figure out how to disable comments on my blog."
  },
  "configurar": {
    "example": "Voy a configurar el router esta tarde.",
    "exampleEnglish": "I'm going to configure the router this afternoon."
  },
  "ajustar": {
    "example": "Necesito ajustar el volumen de la tele.",
    "exampleEnglish": "I need to adjust the TV volume."
  },
  "restablecer": {
    "example": "Introduce tu correo electrónico para restablecer la contraseña.",
    "exampleEnglish": "Enter your email address to reset your password."
  },
  "duplicar": {
    "example": "Un buen verano podría duplicar la cosecha de tomates.",
    "exampleEnglish": "A good summer could double the tomato harvest."
  },
  "arrastrar": {
    "example": "Evita arrastrar la mesa porque podrías rayar el suelo.",
    "exampleEnglish": "Avoid dragging the table because you might scratch the floor."
  },
  "soltar": {
    "example": "El pescador decidió soltar el pez en el río.",
    "exampleEnglish": "The fisherman decided to release the fish into the river."
  },
  "deslizar": {
    "example": "Hay que deslizar la tarjeta por la ranura con la banda hacia abajo.",
    "exampleEnglish": "You need to swipe the card through the slot with the strip facing downwards."
  },
  "acercar": {
    "example": "¿Te puedes acercar más?",
    "exampleEnglish": "Can you get any closer?"
  },
  "alejar": {
    "example": "La policía intentó alejar a los curiosos del edificio.",
    "exampleEnglish": "The police tried to move the onlookers away from the building."
  },
  "escanear": {
    "example": "Me pidieron escanear el pasaporte y enviar una copia legible.",
    "exampleEnglish": "They asked me to scan my passport and send a legible copy."
  },
  "archivar": {
    "example": "Voy a archivar estos correos antiguos.",
    "exampleEnglish": "I'm going to archive these old emails."
  },
  "mencionar": {
    "example": "Quiero mencionar tu ayuda en el informe.",
    "exampleEnglish": "I want to mention your help in the report."
  },
  "notificar": {
    "example": "La clínica se comprometió a notificar cualquier cambio de horario.",
    "exampleEnglish": "The clinic undertook to notify us of any change to the timetable."
  },
  "suscribir": {
    "example": "Puedes suscribir a toda la oficina al boletín mensual.",
    "exampleEnglish": "You can subscribe the whole office to the monthly newsletter."
  },
  "renovar": {
    "example": "Tengo que renovar el pasaporte este año.",
    "exampleEnglish": "I have to renew my passport this year."
  },
  "vencer": {
    "example": "Cuatro ases es una mano difícil de vencer.",
    "exampleEnglish": "Four aces is a tough hand to beat."
  },
  "caducar": {
    "example": "Este permiso suele caducar dos años después de su expedición.",
    "exampleEnglish": "This permit usually expires two years after it is issued."
  },
  "reclamar": {
    "example": "Los pasajeros hicieron cola para reclamar una indemnización.",
    "exampleEnglish": "The passengers queued to claim compensation."
  },
  "reembolsar": {
    "example": "La tienda prometió reembolsar el importe en cinco días laborables.",
    "exampleEnglish": "The shop promised to refund the amount within five working days."
  },
  "donar": {
    "example": "La biblioteca anima a los vecinos a donar libros usados.",
    "exampleEnglish": "The library encourages residents to donate used books."
  },
  "regalar": {
    "example": "Te voy a regalar una bicicleta para tu cumpleaños.",
    "exampleEnglish": "I will give you a bicycle for your birthday."
  },
  "inspeccionar": {
    "example": "Dos ingenieros bajaron al túnel para inspeccionar las grietas.",
    "exampleEnglish": "Two engineers went down into the tunnel to inspect the cracks."
  },
  "pesar": {
    "example": "Puedes pesar la harina directamente en este recipiente.",
    "exampleEnglish": "You can weigh the flour directly in this bowl."
  },
  "registrar": {
    "example": "El termómetro puede registrar variaciones de una décima de grado.",
    "exampleEnglish": "The thermometer can record variations of one tenth of a degree."
  },
  "vigilar": {
    "example": "El guardia va a vigilar el edificio esta noche.",
    "exampleEnglish": "The guard is going to watch the building tonight."
  },
  "denunciar": {
    "example": "No te voy a denunciar.",
    "exampleEnglish": "I won't press charges."
  },
  "rescatar": {
    "example": "Estuve a punto de ahogarme al intentar rescatar a un chico.",
    "exampleEnglish": "I came near being drowned, trying to rescue a boy."
  },
  "salvar": {
    "example": "El médico pudo salvar al paciente a tiempo.",
    "exampleEnglish": "The doctor was able to save the patient in time."
  },
  "atacar": {
    "example": "Este hongo puede atacar las raíces de los árboles jóvenes.",
    "exampleEnglish": "This fungus can attack the roots of young trees."
  },
  "defender": {
    "example": "Tenemos que defender nuestro país cueste lo que cueste.",
    "exampleEnglish": "We have to defend our country at any cost."
  },
  "luchar": {
    "example": "Vamos a luchar por mantener nuestros derechos.",
    "exampleEnglish": "We're going to fight to keep our rights."
  },
  "matar": {
    "example": "Una helada tardía puede matar los brotes jóvenes.",
    "exampleEnglish": "A late frost can kill young shoots."
  },
  "herir": {
    "example": "No quiero herir tus sentimientos.",
    "exampleEnglish": "I don't want to hurt your feelings."
  },
  "curar": {
    "example": "La fisioterapia ayudó a curar la lesión sin cirugía.",
    "exampleEnglish": "Physiotherapy helped heal the injury without surgery."
  },
  "sanar": {
    "example": "La herida necesita tiempo y reposo para sanar por completo.",
    "exampleEnglish": "The wound needs time and rest to heal completely."
  },
  "diagnosticar": {
    "example": "Solo un especialista puede diagnosticar esa enfermedad con certeza.",
    "exampleEnglish": "Only a specialist can diagnose that illness with certainty."
  },
  "recetar": {
    "example": "La médica decidió recetar un antibiótico distinto.",
    "exampleEnglish": "The doctor decided to prescribe a different antibiotic."
  },
  "respirar": {
    "example": "¿Tienes dificultades para respirar con facilidad cuando caminas?",
    "exampleEnglish": "Do you get short of breath easily when walking?"
  },
  "toser": {
    "example": "Empezó a toser mucho durante la reunión.",
    "exampleEnglish": "Someone started coughing a lot during the meeting."
  },
  "estornudar": {
    "example": "He visto estornudar a mi perro, pero nunca a mi gato.",
    "exampleEnglish": "I've seen my dog sneeze but never my cat."
  },
  "sangrar": {
    "example": "Me rasqué la cabeza tanto que me comenzó a sangrar.",
    "exampleEnglish": "I scratched my head so hard it started bleeding."
  },
  "suceder": {
    "example": "Algo parecido puede suceder otra vez.",
    "exampleEnglish": "Something similar can happen again."
  },
  "pertenecer": {
    "example": "Esos países solían pertenecer a Francia.",
    "exampleEnglish": "Those countries used to belong to France."
  },
  "depender": {
    "example": "No debes depender de la ayuda de los demás.",
    "exampleEnglish": "You mustn't depend on others for help."
  },
  "significar": {
    "example": "Un cambio de color puede significar que la fruta está madura.",
    "exampleEnglish": "A change in colour can mean that the fruit is ripe."
  },
  "representar": {
    "example": "Cada símbolo puede representar una estación distinta del año.",
    "exampleEnglish": "Each symbol can represent a different season of the year."
  },
  "establecer": {
    "example": "El comité acordó establecer un horario fijo para las reuniones.",
    "exampleEnglish": "The committee agreed to establish a fixed schedule for meetings."
  },
  "celebrar": {
    "example": "Es solo que no tengo ganas de celebrar mi cumpleaños.",
    "exampleEnglish": "I just don't feel like celebrating my birthday."
  },
  "aprovechar": {
    "example": "Quiero aprovechar el buen tiempo este fin de semana.",
    "exampleEnglish": "I want to take advantage of the good weather this weekend."
  },
  "manejar": {
    "example": "No tengo ni idea de cómo manejar este problema.",
    "exampleEnglish": "I have no idea how to handle this problem."
  },
  "admitir": {
    "example": "Cuesta admitir un error, pero hacerlo permite corregirlo.",
    "exampleEnglish": "It is hard to admit a mistake, but doing so makes it possible to correct it."
  },
  "abandonar": {
    "example": "El capitán dio la orden de abandonar el barco.",
    "exampleEnglish": "The captain gave the order to abandon the ship."
  },
  "aplicar": {
    "example": "Voy a aplicar los mismos cambios al otro archivo.",
    "exampleEnglish": "I'm going to apply the same changes to the other file."
  },
  "causar": {
    "example": "Ese ruido puede causar problemas en el vecindario.",
    "exampleEnglish": "That noise can cause problems in the neighbourhood."
  },
  "conceder": {
    "example": "Tras revisar la solicitud, el juez optó por conceder la libertad provisional.",
    "exampleEnglish": "After reviewing the application, the judge chose to grant bail."
  },
  "conservar": {
    "example": "Me gusta conservar mi ropa el máximo tiempo posible.",
    "exampleEnglish": "I like to keep my clothes for as long as possible."
  },
  "contener": {
    "example": "Tuve que contener la risa durante la representación.",
    "exampleEnglish": "I had to hold back my laughter during the performance."
  },
  "contribuir": {
    "example": "Todos queremos contribuir a este proyecto.",
    "exampleEnglish": "We all want to contribute to this project."
  },
  "desaparecer": {
    "example": "Mi dinero parece desaparecer para el final de mes.",
    "exampleEnglish": "My money seems to disappear by the end of the month."
  },
  "exigir": {
    "example": "Los clientes van a exigir una explicación.",
    "exampleEnglish": "The customers are going to demand an explanation."
  },
  "expresar": {
    "example": "No existen palabras para expresar lo increíble que eres.",
    "exampleEnglish": "No words can express how amazing you are."
  },
  "indicar": {
    "example": "Las flechas azules van a indicar la salida más cercana.",
    "exampleEnglish": "The blue arrows will indicate the nearest exit."
  }
};
