// Generated by scripts/build-sourced-content.mjs. Do not edit by hand.
// Source and licensing details: docs/content-sources.md and docs/content-attribution.csv.

export const SOURCED_FLASHCARD_PAIRS: Record<string, { example: string; exampleEnglish: string }> = {
  "ser": {
    "example": "Quiero ser más paciente.",
    "exampleEnglish": "I want to be more patient."
  },
  "estar": {
    "example": "¿Cómo puedes estar tan optimista con respecto al futuro?",
    "exampleEnglish": "How can you be so optimistic about the future?"
  },
  "haber": {
    "example": "Eso tiene que haber pasado mientras yo estaba fuera.",
    "exampleEnglish": "That must've taken place while I was away."
  },
  "hacer": {
    "example": "¡Este pozo de petróleo me va a hacer rico!",
    "exampleEnglish": "This oil well is going to make me rich."
  },
  "poder": {
    "example": "Para poder entrar al laboratorio, necesitas una tarjeta especial.",
    "exampleEnglish": "To be able to enter the laboratory, you need a special pass."
  },
  "decir": {
    "example": "¿Me vas a decir qué debería hacer a continuación?",
    "exampleEnglish": "Will you tell me what I should do next?"
  },
  "ir": {
    "example": "¿Dónde sueles ir a que te corten el pelo?",
    "exampleEnglish": "Where do you usually go to get a haircut?"
  },
  "ver": {
    "example": "¿Puedes ver ese edificio grande y blanco de allí?",
    "exampleEnglish": "Can you see the big white building over there?"
  },
  "dar": {
    "example": "Mira por el retrovisor antes de dar marcha atrás.",
    "exampleEnglish": "Look in the rear-view mirror before backing up."
  },
  "saber": {
    "example": "Hacenos saber si estás disponible la semana que viene.",
    "exampleEnglish": "Let us know if you're available next week."
  },
  "querer": {
    "example": "Creo que podrías querer echar un vistazo a esto.",
    "exampleEnglish": "I think you might want to check this out."
  },
  "llegar": {
    "example": "Al llegar a la estación, telefoneé a mi amigo.",
    "exampleEnglish": "I called my friend after arriving at the station."
  },
  "pasar": {
    "example": "Él ha estado haciendo pasar mis ideas como suyas.",
    "exampleEnglish": "He's been passing off my ideas as his."
  },
  "deber": {
    "example": "Antes de aceptar el préstamo, calcula cuánto vas a deber al banco.",
    "exampleEnglish": "Before accepting the loan, calculate how much you will owe the bank."
  },
  "poner": {
    "example": "Clara decidió poner las plantas junto a la ventana.",
    "exampleEnglish": "Clara decided to put the plants beside the window."
  },
  "parecer": {
    "example": "La ruta puede parecer larga, pero el paisaje merece la pena.",
    "exampleEnglish": "The route may seem long, but the scenery is worth it."
  },
  "quedar": {
    "example": "¿Te vas a quedar ahí parado todo el día?",
    "exampleEnglish": "Are you just going to stand there all day?"
  },
  "creer": {
    "example": "No puedo creer que dejé que Tom hiciera eso.",
    "exampleEnglish": "I can't believe I let Tom do that."
  },
  "hablar": {
    "example": "Algunos de mis amigos saben hablar francés bastante bien.",
    "exampleEnglish": "Some of my friends can speak French fairly well."
  },
  "llevar": {
    "example": "Puedes llevar estas carpetas a la sala de reuniones.",
    "exampleEnglish": "You can take these folders to the meeting room."
  },
  "dejar": {
    "example": "No puedo dejar de pensar en lo que vi.",
    "exampleEnglish": "I can't stop thinking about what I saw."
  },
  "seguir": {
    "example": "Decidimos seguir ocultos durante dos o tres días mas.",
    "exampleEnglish": "We decided to lie hidden for a few days."
  },
  "encontrar": {
    "example": "A dondequiera que vayas, vas a encontrar lo mismo.",
    "exampleEnglish": "Wherever you go, you will find the same thing."
  },
  "llamar": {
    "example": "Ahora estamos comiendo, ¿podría volver a llamar más tarde?",
    "exampleEnglish": "We are eating now. Could you please call back later?"
  },
  "venir": {
    "example": "El que quiera venir a mi fiesta puede venir.",
    "exampleEnglish": "Whoever wants to come to my party may come."
  },
  "pensar": {
    "example": "Necesito pensar en esta decisión.",
    "exampleEnglish": "I need to think about this decision."
  },
  "salir": {
    "example": "Estaba a punto de salir cuando sonó el teléfono.",
    "exampleEnglish": "I was about to leave when the phone rang."
  },
  "volver": {
    "example": "Él prometió volver y sin embargo no lo hizo.",
    "exampleEnglish": "He promised to return and yet he didn't."
  },
  "tomar": {
    "example": "Hubiera sido mejor que le preguntaras qué camino tomar.",
    "exampleEnglish": "You had better ask him which way to take."
  },
  "conocer": {
    "example": "Es difícil conocer a gente tan agradable como tú.",
    "exampleEnglish": "It's rare to meet nice people like you."
  },
  "vivir": {
    "example": "El sueño de Tom es vivir en las montañas.",
    "exampleEnglish": "Tom's dream is to live in the mountains."
  },
  "sentir": {
    "example": "Algunos animales pueden sentir la llegada de una tormenta.",
    "exampleEnglish": "Some animals can sense the coming of a storm."
  },
  "tratar": {
    "example": "Vamos a intentar tratar a los demás con respeto.",
    "exampleEnglish": "Let's try to treat each other with respect."
  },
  "mirar": {
    "example": "Pienso que mirar televisión es una pérdida de tiempo.",
    "exampleEnglish": "I think watching TV is a waste of time."
  },
  "contar": {
    "example": "Él sabe alemán y francés, sin contar el inglés.",
    "exampleEnglish": "He knows German and French, not to mention English."
  },
  "empezar": {
    "example": "Imagina empezar a hipar y que no pudieras parar.",
    "exampleEnglish": "Imagine if you started hiccoughing and you couldn't stop."
  },
  "esperar": {
    "example": "Los hombres estamos acostumbrados a esperar a las mujeres.",
    "exampleEnglish": "We men are used to waiting for the women."
  },
  "buscar": {
    "example": "¿A qué hora querés que te pase a buscar?",
    "exampleEnglish": "What time do you want me to pick you up?"
  },
  "existir": {
    "example": "Los hechos no dejan de existir por ser ignorados.",
    "exampleEnglish": "Facts do not cease to exist because they are ignored."
  },
  "entrar": {
    "example": "Quítate los zapatos antes de entrar a un templo.",
    "exampleEnglish": "Take off your shoes before going into a temple."
  },
  "trabajar": {
    "example": "El doctor le advirtió que dejara de trabajar tanto.",
    "exampleEnglish": "The doctor advised him to stop working too much."
  },
  "escribir": {
    "example": "Él intentó escribir todo lo que el profesor dijo.",
    "exampleEnglish": "He tried to write down everything the teacher said."
  },
  "perder": {
    "example": "¿Comer sólo vegetales te puede ayudar a perder peso?",
    "exampleEnglish": "Can eating just vegetables help you lose weight?"
  },
  "producir": {
    "example": "Mediante la ingeniería genética, el maíz puede producir sus propios pesticidas.",
    "exampleEnglish": "Through genetic engineering, corn can produce its own pesticides."
  },
  "ocurrir": {
    "example": "Accidentes de tráfico suelen ocurrir en días de lluvia.",
    "exampleEnglish": "Traffic accidents are likely to occur on rainy days."
  },
  "entender": {
    "example": "Tom fingió no entender lo que Mary estaba diciendo.",
    "exampleEnglish": "Tom pretended not to understand what Mary was saying."
  },
  "pedir": {
    "example": "Tuve que pedir prestado dinero para comprar el coche.",
    "exampleEnglish": "I had to borrow money to purchase the car."
  },
  "recibir": {
    "example": "Cada participante va a recibir una copia del programa.",
    "exampleEnglish": "Each participant will receive a copy of the programme."
  },
  "recordar": {
    "example": "Tom admitió que siempre tiene problemas para recordar nombres.",
    "exampleEnglish": "Tom admitted that he always has trouble remembering names."
  },
  "terminar": {
    "example": "Tom consiguió terminar de escribir su reporte a tiempo.",
    "exampleEnglish": "Tom managed to finish writing his report in time."
  },
  "permitir": {
    "example": "Este año no me puedo permitir un coche nuevo.",
    "exampleEnglish": "I can't afford a new car this year."
  },
  "aparecer": {
    "example": "Algunas estrellas empezaron a aparecer en el cielo nocturno.",
    "exampleEnglish": "Some stars began to appear in the night sky."
  },
  "conseguir": {
    "example": "¿No puedes conseguir a alguien más que te ayude?",
    "exampleEnglish": "Can't you get somebody else to help you?"
  },
  "comenzar": {
    "example": "¿Estás pensando seriamente en comenzar tu propio negocio?",
    "exampleEnglish": "Are you seriously thinking about starting your own business?"
  },
  "servir": {
    "example": "¿Me podría servir una copa de vino blanco?",
    "exampleEnglish": "Could I have a glass of white wine?"
  },
  "sacar": {
    "example": "A un rábano no se le puede sacar sangre.",
    "exampleEnglish": "You can't get blood out of a turnip."
  },
  "necesitar": {
    "example": "¿Crees que vas a necesitar que Tom te ayude?",
    "exampleEnglish": "Do you think you'll need Tom's help?"
  },
  "mantener": {
    "example": "Tú tienes que aprender a mantener la boca cerrada.",
    "exampleEnglish": "You've got to learn to hold your tongue."
  },
  "resultar": {
    "example": "Con instrucciones claras, montar la estantería debería resultar sencillo.",
    "exampleEnglish": "With clear instructions, assembling the bookcase should prove straightforward."
  },
  "leer": {
    "example": "Deberías ser capaz de leer este libro con facilidad.",
    "exampleEnglish": "You should be able to read this book easily."
  },
  "caer": {
    "example": "El otoño llegó y las hojas comenzaron a caer.",
    "exampleEnglish": "Autumn came and the leaves started to fall."
  },
  "cambiar": {
    "example": "Me pregunto qué le habrá hecho cambiar de idea.",
    "exampleEnglish": "I wonder what has made him change his mind."
  },
  "presentar": {
    "example": "Mañana Elena va a presentar los resultados de su investigación.",
    "exampleEnglish": "Tomorrow Elena will present the results of her research."
  },
  "crear": {
    "example": "Estoy interesado en crear mis propias páginas web.",
    "exampleEnglish": "I'm interested in creating my own web pages."
  },
  "abrir": {
    "example": "Dame las llaves para que pueda abrir la puerta.",
    "exampleEnglish": "Give me the keys so I can unlock the door."
  },
  "considerar": {
    "example": "Deberíamos considerar el problema desde la perspectiva de un niño.",
    "exampleEnglish": "We should consider the problem from a child's perspective."
  },
  "oír": {
    "example": "Ella colapsó en llanto al oír las malas noticias.",
    "exampleEnglish": "On hearing the bad news, she burst into tears."
  },
  "acabar": {
    "example": "Tom no puede acabar este trabajo en un día.",
    "exampleEnglish": "Tom can't finish this job in a day."
  },
  "convertir": {
    "example": "La reforma pretende convertir el antiguo mercado en una biblioteca.",
    "exampleEnglish": "The renovation aims to turn the old market into a library."
  },
  "ganar": {
    "example": "Ella tiene una buena oportunidad de ganar el premio.",
    "exampleEnglish": "She stands a good chance of winning the prize."
  },
  "formar": {
    "example": "Quien quiera formar parte de nuestro club será bienvenido.",
    "exampleEnglish": "Whoever wants to join our club will be welcome."
  },
  "traer": {
    "example": "¿Podrías ir a la tienda y traer algunos huevos?",
    "exampleEnglish": "Could you go to the store and grab some eggs?"
  },
  "partir": {
    "example": "El tren va a partir del andén cuatro a las ocho.",
    "exampleEnglish": "The train will depart from platform four at eight o'clock."
  },
  "morir": {
    "example": "La planta puede morir si la tierra permanece seca.",
    "exampleEnglish": "The plant can die if the soil remains dry."
  },
  "aceptar": {
    "example": "Ella no tuvo más alternativa que aceptar su destino.",
    "exampleEnglish": "She had no choice but to accept her fate."
  },
  "realizar": {
    "example": "Los computadores son capaces de realizar trabajo extremadamente complicado.",
    "exampleEnglish": "Computers are capable of doing extremely complicated work."
  },
  "suponer": {
    "example": "Su acento da a suponer que él es un extranjero.",
    "exampleEnglish": "His accent suggests he is a foreigner."
  },
  "comprender": {
    "example": "Tom no pudo comprender de qué estaba hablando Mary.",
    "exampleEnglish": "Tom couldn't figure out what Mary was talking about."
  },
  "lograr": {
    "example": "¿Qué te gustaría lograr en los siguientes tres años?",
    "exampleEnglish": "What's something you'd like to achieve in the next three years?"
  },
  "explicar": {
    "example": "Estoy sin palabras para explicar la ausencia de Tom.",
    "exampleEnglish": "I'm at a loss to explain Tom's absence."
  },
  "preguntar": {
    "example": "Voy a preguntar cuándo va a venir el tren.",
    "exampleEnglish": "I'll ask when the train will get in."
  },
  "tocar": {
    "example": "Tom no puede tocar muy bien el tin whistle.",
    "exampleEnglish": "Tom can't play the tin whistle very well."
  },
  "reconocer": {
    "example": "Pude reconocer la melodía desde las primeras notas.",
    "exampleEnglish": "I could recognise the melody from the first notes."
  },
  "estudiar": {
    "example": "No tengo ganas de ponerme a estudiar esta noche.",
    "exampleEnglish": "I don't feel like studying at all tonight."
  },
  "alcanzar": {
    "example": "El accidente de tráfico me impidió alcanzar el tren.",
    "exampleEnglish": "The traffic accident prevented me from catching the train."
  },
  "nacer": {
    "example": "Todos mis bisabuelos fallecieron antes de nacer yo.",
    "exampleEnglish": "All of my great-grandparents died before I was born."
  },
  "dirigir": {
    "example": "Una arquitecta joven va a dirigir la restauración del teatro.",
    "exampleEnglish": "A young architect will lead the restoration of the theatre."
  },
  "correr": {
    "example": "Alicia prefiere correr por el parque antes del desayuno.",
    "exampleEnglish": "Alicia prefers to run through the park before breakfast."
  },
  "utilizar": {
    "example": "Los estudiantes deberían utilizar los libros de la biblioteca.",
    "exampleEnglish": "Students should make use of the books in the library."
  },
  "pagar": {
    "example": "Puedes pagar la entrada con tarjeta en la taquilla.",
    "exampleEnglish": "You can pay for the ticket by card at the box office."
  },
  "ayudar": {
    "example": "Me alegro de que Tom nos vaya a ayudar.",
    "exampleEnglish": "I'm glad Tom is going to help us."
  },
  "gustar": {
    "example": "Estaba seguro de que no te iba a gustar.",
    "exampleEnglish": "I was sure you wouldn't like it."
  },
  "jugar": {
    "example": "Se me da mejor cocinar que jugar al tenis.",
    "exampleEnglish": "I can cook better than I can play tennis."
  },
  "escuchar": {
    "example": "¿De quién fue el discurso más difícil de escuchar?",
    "exampleEnglish": "Whose speech was the hardest to listen to?"
  },
  "cumplir": {
    "example": "El proveedor debe cumplir todas las condiciones del contrato.",
    "exampleEnglish": "The supplier must fulfil all the terms of the contract."
  },
  "ofrecer": {
    "example": "Te puedo ofrecer algunas predicciones estadísticas de los ingresos esperados.",
    "exampleEnglish": "I can provide you with some statistical predictions of expected revenues."
  },
  "descubrir": {
    "example": "Necesito descubrir quién le dio ese consejo a Tom.",
    "exampleEnglish": "I need to find out who gave Tom that advice."
  },
  "levantar": {
    "example": "Entre los dos pudieron levantar la caja sin dañarla.",
    "exampleEnglish": "Together they managed to lift the box without damaging it."
  },
  "intentar": {
    "example": "No puedes conseguir lo imposible sin intentar lo absurdo.",
    "exampleEnglish": "You cannot achieve the impossible without attempting the absurd."
  },
  "usar": {
    "example": "No me gusta usar la ropa de otras personas.",
    "exampleEnglish": "I do not like wearing anybody else's clothes."
  },
  "decidir": {
    "example": "Tom tiene edad suficiente para decidir por sí mismo.",
    "exampleEnglish": "Tom is old enough to make his own decisions."
  },
  "repetir": {
    "example": "¿Puedes repetir lo que acabas de decir, por favor?",
    "exampleEnglish": "Could you please repeat what you just said?"
  },
  "olvidar": {
    "example": "Esto es algo realmente importante que no deberías olvidar.",
    "exampleEnglish": "That's something really important that you shouldn't forget."
  },
  "aprender": {
    "example": "Tenemos que aprender a andar antes de poder correr.",
    "exampleEnglish": "We must learn to walk before we can run."
  },
  "cerrar": {
    "example": "La encargada va a cerrar la tienda a las nueve.",
    "exampleEnglish": "The manager is going to close the shop at nine."
  },
  "comer": {
    "example": "¿Dónde me puedo lavar las manos antes de comer?",
    "exampleEnglish": "Where can I wash my hands before I eat?"
  },
  "cantar": {
    "example": "Tom no sabía que Mary pudiera cantar tan bien.",
    "exampleEnglish": "Tom didn't know Mary could sing so well."
  },
  "bailar": {
    "example": "Tom no pudo encontrar a nadie con quien bailar.",
    "exampleEnglish": "Tom couldn't find anyone to dance with."
  },
  "comprar": {
    "example": "A Tom le gustaría comprar una casa en Boston.",
    "exampleEnglish": "Tom would like to buy a house in Boston."
  },
  "vender": {
    "example": "¿Estás pensando seriamente en vender esto en eBay?",
    "exampleEnglish": "Are you seriously thinking about selling this on eBay?"
  },
  "viajar": {
    "example": "En aquellos días, poca gente podía viajar al extranjero.",
    "exampleEnglish": "In those days, few people could travel abroad."
  },
  "caminar": {
    "example": "En aquellos tiempos, salía a caminar antes del desayuno.",
    "exampleEnglish": "In those days, I went out walking before breakfast."
  },
  "conducir": {
    "example": "¿Cuándo fue la última vez que enseñaste a conducir?",
    "exampleEnglish": "When was the last time you taught driving?"
  },
  "dormir": {
    "example": "Tenemos que dormir al menos ocho horas al día.",
    "exampleEnglish": "We must sleep at least eight hours a day."
  },
  "beber": {
    "example": "Conviene beber agua antes y después del ejercicio.",
    "exampleEnglish": "It is advisable to drink water before and after exercise."
  },
  "cocinar": {
    "example": "Todavía no le ha cogido el tranquillo a cocinar.",
    "exampleEnglish": "She hasn't got the knack of cooking yet."
  },
  "lavar": {
    "example": "¿Puedo lavar toda mi ropa de una sola vez?",
    "exampleEnglish": "May I wash all my laundry at once?"
  },
  "limpiar": {
    "example": "Quiero que todos me ayuden a limpiar la casa.",
    "exampleEnglish": "I want everyone to help me clean the house."
  },
  "cortar": {
    "example": "Este cuchillo está tan desafilado que no puede cortar.",
    "exampleEnglish": "This knife is so dull that it can't cut."
  },
  "romper": {
    "example": "No podés hacer un omelet sin romper los huevos.",
    "exampleEnglish": "You can't make an omelet without breaking eggs."
  },
  "enviar": {
    "example": "Pido disculpas por la demora en enviar la agenda.",
    "exampleEnglish": "I apologize for the delay in sending the agenda."
  },
  "enseñar": {
    "example": "Ella es capaz de enseñar tanto inglés como francés.",
    "exampleEnglish": "She is capable of teaching both English and French."
  },
  "mostrar": {
    "example": "¿Me podés mostrar en este mapa dónde vivís?",
    "exampleEnglish": "Can you show me where you live on this map?"
  },
  "compartir": {
    "example": "Él tuvo que compartir una recámara con su hermano.",
    "exampleEnglish": "He had to share a bedroom with his brother."
  },
  "elegir": {
    "example": "El jurado deberá elegir el proyecto más sostenible.",
    "exampleEnglish": "The panel must choose the most sustainable project."
  },
  "incluir": {
    "example": "Vamos a incluir los agradecimientos de siempre.",
    "exampleEnglish": "We will include the usual acknowledgments."
  },
  "excluir": {
    "example": "Sería injusto excluir a Marta del equipo por llegar tarde una vez.",
    "exampleEnglish": "It would be unfair to exclude Marta from the team for being late once."
  },
  "mejorar": {
    "example": "Leer en voz alta puede mejorar tu pronunciación.",
    "exampleEnglish": "Reading aloud can improve your pronunciation."
  },
  "empeorar": {
    "example": "Para empeorar las cosas, su esposa se enfermó.",
    "exampleEnglish": "To make matters worse, his wife fell ill."
  },
  "crecer": {
    "example": "Se dejó crecer la barba mientras estaba de vacaciones.",
    "exampleEnglish": "He grew a beard while he was on holiday."
  },
  "reducir": {
    "example": "Por lo tanto es necesario reducir el costo.",
    "exampleEnglish": "Therefore, it is necessary to reduce the cost."
  },
  "aumentar": {
    "example": "Si el medicamento no surte efecto, quizá deberíamos aumentar la dosis.",
    "exampleEnglish": "If the medicine isn't working, maybe we should up the dosage."
  },
  "bajar": {
    "example": "Una cucharada de azúcar ayuda a bajar la medicina.",
    "exampleEnglish": "A spoonful of sugar helps the medicine go down."
  },
  "subir": {
    "example": "¿Cómo puedo subir una foto a tu página web?",
    "exampleEnglish": "How can I upload a photo to your website?"
  },
  "regresar": {
    "example": "Hoy por hoy no pienso regresar a mi país.",
    "exampleEnglish": "Under present circumstances, I don't intend to return to my country."
  },
  "permanecer": {
    "example": "¿Por qué tuviste que permanecer en Boston tanto tiempo?",
    "exampleEnglish": "Why did you have to stay in Boston for so long?"
  },
  "mover": {
    "example": "Tom debía haber ayudado a Mary a mover el sillón.",
    "exampleEnglish": "Tom should have helped Mary move the sofa."
  },
  "parar": {
    "example": "El árbitro de hockey intervino para parar la pelea.",
    "exampleEnglish": "The hockey referee intervened to stop the fight."
  },
  "continuar": {
    "example": "Tom trabajó hasta que estuvo demasiado cansado para continuar.",
    "exampleEnglish": "Tom worked until he was too tired to continue."
  },
  "preparar": {
    "example": "No todos pueden preparar una buena taza de café.",
    "exampleEnglish": "Not everyone can make a good cup of coffee."
  },
  "responder": {
    "example": "Tom no pudo responder todas las preguntas de Mary.",
    "exampleEnglish": "Tom couldn't answer all of Mary's questions."
  },
  "añadir": {
    "example": "Creo que deberías añadir una pizca más de pimienta.",
    "exampleEnglish": "I think you should add a bit more pepper."
  },
  "quitar": {
    "example": "Usa un paño húmedo para quitar la mancha de la mesa.",
    "exampleEnglish": "Use a damp cloth to remove the stain from the table."
  },
  "quitarse": {
    "example": "Al entrar en casa, decidió quitarse el abrigo mojado.",
    "exampleEnglish": "On entering the house, she decided to take off her wet coat."
  },
  "vestir": {
    "example": "La diseñadora decidió vestir al actor con un traje azul oscuro.",
    "exampleEnglish": "The designer decided to dress the actor in a dark blue suit."
  },
  "llevarse": {
    "example": "Pienso que él puede llevarse bien con su vecino.",
    "exampleEnglish": "I think he can get along with his neighbor."
  },
  "levantarse": {
    "example": "Él está acostumbrado a levantarse temprano en la mañana.",
    "exampleEnglish": "He's accustomed to getting up early in the morning."
  },
  "sentarse": {
    "example": "Tom no puede sentarse quieto ni por un momento.",
    "exampleEnglish": "Tom can't sit still for a moment."
  },
  "acostarse": {
    "example": "No olvide apagar todas las luces antes de acostarse.",
    "exampleEnglish": "Don't forget to turn off all the lights before going to bed."
  },
  "despertarse": {
    "example": "Es difícil despertarse sin una taza de café fuerte.",
    "exampleEnglish": "It is hard to wake up without a strong cup of coffee."
  },
  "ducharse": {
    "example": "Es obligatorio ducharse antes de meterse en la piscina.",
    "exampleEnglish": "You must shower before entering the pool."
  },
  "bañarse": {
    "example": "A mis niños no les gusta bañarse.",
    "exampleEnglish": "My kids don't like taking baths."
  },
  "peinarse": {
    "example": "Antes de la ceremonia, Lucía subió a peinarse frente al espejo grande.",
    "exampleEnglish": "Before the ceremony, Lucía went upstairs to do her hair in front of the large mirror."
  },
  "afeitarse": {
    "example": "El rostro de Tom se siente áspero porque debe afeitarse.",
    "exampleEnglish": "Tom's face feels rough because he needs to shave."
  },
  "casar": {
    "example": "Ella quiere casar a su hija con un doctor.",
    "exampleEnglish": "She wants to marry her daughter to a doctor."
  },
  "casarse": {
    "example": "Ella prometió casarse con él, pero no lo hizo.",
    "exampleEnglish": "She promised to marry him, but she didn't."
  },
  "reunir": {
    "example": "Él trató de reunir los fragmentos de un jarrón roto.",
    "exampleEnglish": "He tried to put the fragments of a broken vase together."
  },
  "reunirse": {
    "example": "Él se escabulló para reunirse con una chica.",
    "exampleEnglish": "He snuck out to meet up with a girl."
  },
  "encontrarse": {
    "example": "Ella prometió encontrarse con él ayer por la noche.",
    "exampleEnglish": "She promised to meet him last night."
  },
  "preocupar": {
    "example": "El retraso empezó a preocupar a la familia.",
    "exampleEnglish": "The delay began to worry the family."
  },
  "preocuparse": {
    "example": "Preocuparse es como pagar una deuda que no tienes.",
    "exampleEnglish": "Worrying is like paying a debt you don't owe."
  },
  "ocupar": {
    "example": "Sé que no puedo ocupar el lugar de Tom.",
    "exampleEnglish": "I know I can't take Tom's place."
  },
  "ocuparse": {
    "example": "Aquí no hay nadie que pueda ocuparse del problema.",
    "exampleEnglish": "There's no one here who can deal with the problem."
  },
  "llamarse": {
    "example": "En aquella época, el pueblo solía llamarse Villanueva del Río.",
    "exampleEnglish": "In those days, the village used to be called Villanueva del Río."
  },
  "sentirse": {
    "example": "Después de descansar, Marta empezó a sentirse mucho mejor.",
    "exampleEnglish": "After resting, Marta began to feel much better."
  },
  "acordar": {
    "example": "Los vecinos lograron acordar un horario para las obras.",
    "exampleEnglish": "The neighbours managed to agree on a schedule for the building work."
  },
  "acordarse": {
    "example": "Tom no logra acordarse de la dirección de Mary.",
    "exampleEnglish": "Tom can't remember Mary's address."
  },
  "olvidarse": {
    "example": "Tom todavía no puede olvidarse de Mary.",
    "exampleEnglish": "Tom still can't get Mary out of his head."
  },
  "contestar": {
    "example": "Estoy manejando, así que no puedo contestar el teléfono.",
    "exampleEnglish": "I'm driving, so I can't answer the phone."
  },
  "describir": {
    "example": "¿Puede describir la situación en la que se encontraba?",
    "exampleEnglish": "Can you describe the situation you were in?"
  },
  "comparar": {
    "example": "Se puede comparar un libro con un amigo.",
    "exampleEnglish": "A book can be compared to a friend."
  },
  "cambiarse": {
    "example": "Tom quiere cambiarse la ropa mojada por algo seco.",
    "exampleEnglish": "Tom wants to change out of his wet clothes into something dry."
  },
  "probar": {
    "example": "¿Puedes probar que lo que dijiste es verdad?",
    "exampleEnglish": "Can you prove that what you said is true?"
  },
  "prohibir": {
    "example": "El ayuntamiento decidió prohibir las barbacoas durante la sequía.",
    "exampleEnglish": "The council decided to ban barbecues during the drought."
  },
  "obligar": {
    "example": "Nunca te voy a obligar a casarte con él.",
    "exampleEnglish": "I will never force you to marry him."
  },
  "recomendar": {
    "example": "¿Me podrías recomendar un buen restaurante por aquí cerca?",
    "exampleEnglish": "Could you recommend a nice restaurant near here?"
  },
  "aconsejar": {
    "example": "¿Qué me podés aconsejar?",
    "exampleEnglish": "What advice can you give me?"
  },
  "sugerir": {
    "example": "Tom no puede creer que María acaba de sugerir eso.",
    "exampleEnglish": "Tom can't believe Mary just suggested that."
  },
  "invitar": {
    "example": "¿La vas a invitar a ella a la fiesta?",
    "exampleEnglish": "Are you going to invite her to the party?"
  },
  "rechazar": {
    "example": "Él me hizo una oferta que no pude rechazar.",
    "exampleEnglish": "He made me an offer I couldn't refuse."
  },
  "negar": {
    "example": "Nadie puede negar el hecho de que el fuego quema.",
    "exampleEnglish": "No one can deny the fact that fire burns."
  },
  "afirmar": {
    "example": "Sin pruebas sólidas, nadie debería afirmar que el cuadro es falso.",
    "exampleEnglish": "Without solid evidence, nobody should claim that the painting is fake."
  },
  "prometer": {
    "example": "Tienes que prometer que no quitarás la cuerda.",
    "exampleEnglish": "You must promise not to take the rope off."
  },
  "fallar": {
    "example": "Un plan así está destinado a fallar.",
    "exampleEnglish": "Such a plan is bound to fail."
  },
  "ahorrar": {
    "example": "Lucía empezó a ahorrar para comprar una bicicleta.",
    "exampleEnglish": "Lucía began to save for a bicycle."
  },
  "gastar": {
    "example": "Conviene comparar precios antes de gastar los ahorros.",
    "exampleEnglish": "It is wise to compare prices before spending your savings."
  },
  "cobrar": {
    "example": "Yo creo que Tom debe cobrar su dinero.",
    "exampleEnglish": "I think Tom should ask for his money back."
  },
  "costar": {
    "example": "¿Cuánto más estimas que pueda llegar a costar?",
    "exampleEnglish": "How much more do you think it'll cost?"
  },
  "valer": {
    "example": "Esta entrada puede valer más si el músico se hace famoso.",
    "exampleEnglish": "This ticket may be worth more if the musician becomes famous."
  },
  "preferir": {
    "example": "Al probar ambos colchones, Rosa confesó preferir el más firme.",
    "exampleEnglish": "After trying both mattresses, Rosa admitted that she preferred the firmer one."
  },
  "odiar": {
    "example": "Se dice que los animales no pueden odiar.",
    "exampleEnglish": "They say that animals aren't able to hate."
  },
  "amar": {
    "example": "No puedo amar a nadie más que a ti.",
    "exampleEnglish": "I can't love anyone but you."
  },
  "encantar": {
    "example": "Sé que este libro te va a encantar.",
    "exampleEnglish": "I know you're going to love this book."
  },
  "molestar": {
    "example": "No quiero molestar a nadie mientras estudia.",
    "exampleEnglish": "I do not want to disturb anyone while they are studying."
  },
  "importar": {
    "example": "Ella es linda sin importar lo que se ponga.",
    "exampleEnglish": "She is beautiful, no matter what she wears."
  },
  "faltar": {
    "example": "Procura no faltar a la cita con la orientadora.",
    "exampleEnglish": "Try not to miss the appointment with the adviser."
  },
  "doler": {
    "example": "Te prometo que no te va a doler.",
    "exampleEnglish": "It won't hurt, I promise."
  },
  "aburrir": {
    "example": "No te voy a aburrir con los detalles.",
    "exampleEnglish": "I won't bore you with the details."
  },
  "divertir": {
    "example": "El cuentacuentos consiguió divertir a niños y adultos.",
    "exampleEnglish": "The storyteller managed to entertain both children and adults."
  },
  "interesar": {
    "example": "La charla podría interesar a quienes estudian arquitectura sostenible.",
    "exampleEnglish": "The talk might interest people who study sustainable architecture."
  },
  "sorprender": {
    "example": "La respuesta puede sorprenderte.",
    "exampleEnglish": "The answer might surprise you."
  },
  "cansar": {
    "example": "Me estoy empezando a cansar de oír música navideña por donde quiera que voy.",
    "exampleEnglish": "I'm getting tired of hearing Christmas music everywhere I go."
  },
  "alegrar": {
    "example": "Me acabas de alegrar el día.",
    "exampleEnglish": "You just made my day."
  },
  "entristecer": {
    "example": "Ver el parque abandonado suele entristecer a los vecinos mayores.",
    "exampleEnglish": "Seeing the park neglected tends to sadden the older residents."
  },
  "asustar": {
    "example": "Solo quise asustar a Tom, no herirlo.",
    "exampleEnglish": "I just meant to scare Tom, not to hurt him."
  },
  "enfadar": {
    "example": "El retraso volvió a enfadar a los pasajeros.",
    "exampleEnglish": "The delay made the passengers angry again."
  },
  "calmar": {
    "example": "Tom y Mary están intentando calmar a John.",
    "exampleEnglish": "Tom and Mary are trying to calm John down."
  },
  "relajar": {
    "example": "Yo pienso que ahora nos podemos relajar.",
    "exampleEnglish": "I think we can relax now."
  },
  "temer": {
    "example": "No tienes nada que temer excepto al miedo mismo.",
    "exampleEnglish": "You have nothing to fear but fear itself."
  },
  "confiar": {
    "example": "Él es un hombre en quien siempre puedes confiar.",
    "exampleEnglish": "He is a man who can always be trusted."
  },
  "dudar": {
    "example": "Dudar de sí mismo es la primera señal de inteligencia.",
    "exampleEnglish": "To have doubts about oneself is the first sign of intelligence."
  },
  "planear": {
    "example": "Vamos a planear la ruta antes de reservar los hoteles.",
    "exampleEnglish": "We are going to plan the route before booking the hotels."
  },
  "organizar": {
    "example": "Ella trató de convencerlo de organizar un boicot.",
    "exampleEnglish": "She tried to persuade him to organize a boycott."
  },
  "reservar": {
    "example": "Quiero reservar una mesa para cuatro a las seis.",
    "exampleEnglish": "I'd like to reserve a table for four at six."
  },
  "cancelar": {
    "example": "Una repentina enfermedad la forzó a cancelar su cita.",
    "exampleEnglish": "A sudden illness forced her to cancel her appointment."
  },
  "visitar": {
    "example": "El próximo domingo iremos a visitar a nuestra tía.",
    "exampleEnglish": "We are going to visit our aunt next Sunday."
  },
  "explorar": {
    "example": "Estamos a punto de explorar territorio virgen.",
    "exampleEnglish": "We're about to explore some uncharted territory."
  },
  "quedarse": {
    "example": "Ella está acostumbrada a quedarse despierta toda la noche.",
    "exampleEnglish": "She is used to staying up all night."
  },
  "alojar": {
    "example": "Este hotel puede alojar a más de 1000 huéspedes.",
    "exampleEnglish": "This hotel can accommodate over 1,000 guests."
  },
  "alojarse": {
    "example": "Durante el congreso, los ponentes podrán alojarse junto a la estación.",
    "exampleEnglish": "During the conference, the speakers can stay near the station."
  },
  "volar": {
    "example": "Si yo fuera un pájaro, podría volar hasta ti.",
    "exampleEnglish": "If I were a bird, I could fly to you."
  },
  "montar": {
    "example": "Me gusta montar un caballo de vez en cuando.",
    "exampleEnglish": "I like to ride a horse now and then."
  },
  "nadar": {
    "example": "¿Esta tarde prefieres ir a navegar o a nadar?",
    "exampleEnglish": "Would you rather go sailing or swimming this afternoon?"
  },
  "andar": {
    "example": "Ella estaba tan cansada que no podía andar.",
    "exampleEnglish": "She was so tired that she couldn't walk."
  },
  "pasear": {
    "example": "Él salió a pasear con ella esta mañana.",
    "exampleEnglish": "He went for a walk with her this morning."
  },
  "cruzar": {
    "example": "Él fue el primer hombre en cruzar el Pacífico.",
    "exampleEnglish": "He was the first man to cross the Pacific."
  },
  "girar": {
    "example": "¿Qué ocurriría si la Tierra dejara de girar?",
    "exampleEnglish": "What would happen if the earth stopped spinning?"
  },
  "detener": {
    "example": "Levanté la mano para detener un taxi.",
    "exampleEnglish": "I held up my hand to stop a taxi."
  },
  "detenerse": {
    "example": "Tom quería detenerse y pensar.",
    "exampleEnglish": "Tom wanted to stop and think."
  },
  "aparcar": {
    "example": "Vi el coche de Tom aparcar en el camino de entrada.",
    "exampleEnglish": "I saw Tom's car pull into the driveway."
  },
  "arrancar": {
    "example": "El niño trató de arrancar la rama muerta con un serrucho.",
    "exampleEnglish": "The boy tried to saw off the dead branch."
  },
  "frenar": {
    "example": "El conductor tuvo que frenar al ver el semáforo rojo.",
    "exampleEnglish": "The driver had to brake when he saw the red light."
  },
  "acelerar": {
    "example": "¿Por qué no intentamos acelerar las cosas?",
    "exampleEnglish": "Why don't we try to speed things up?"
  },
  "saltar": {
    "example": "Tom no quería saltar a través de la zanja.",
    "exampleEnglish": "Tom didn't want to jump across the ditch."
  },
  "lanzar": {
    "example": "Selena Gomez acaba de lanzar su segundo disco.",
    "exampleEnglish": "Selena Gomez has just released her second album."
  },
  "tirar": {
    "example": "A pesar de nuestro apoyo, decidió tirar la toalla.",
    "exampleEnglish": "In spite of our encouragement, he decided to throw in the towel."
  },
  "recoger": {
    "example": "¿Te importaría recoger algo en el camino de regreso?",
    "exampleEnglish": "Would you mind picking up something on the way back?"
  },
  "guardar": {
    "example": "Deberías guardar tus objetos de valor en un lugar seguro.",
    "exampleEnglish": "You should keep your valuables in a safe place."
  },
  "hallar": {
    "example": "Le aseguro que hacemos todo lo que podemos para hallar a Tom.",
    "exampleEnglish": "I assure you we're doing everything we can to find Tom."
  },
  "esconder": {
    "example": "Ese secreto no se puede esconder para siempre.",
    "exampleEnglish": "That secret can't be kept forever."
  },
  "esconderse": {
    "example": "El estudio es muy pequeño, sin lugares donde esconderse.",
    "exampleEnglish": "The studio is very small, with no place to hide."
  },
  "observar": {
    "example": "Tom podía observar que María se estaba poniendo muy nerviosa.",
    "exampleEnglish": "Tom could see Mary was getting very nervous."
  },
  "oler": {
    "example": "Tom podía oler el desayuno cocinándose en la cocina.",
    "exampleEnglish": "Tom could smell breakfast cooking in the kitchen."
  },
  "comentar": {
    "example": "Tengo un asunto complicado que quiero comentar contigo.",
    "exampleEnglish": "I have a complicated matter I want to discuss with you."
  },
  "conversar": {
    "example": "Es grosero conversar en medio de un concierto.",
    "exampleEnglish": "It's bad manners to talk during a concert."
  },
  "discutir": {
    "example": "Antes de discutir el presupuesto, revisemos las cifras.",
    "exampleEnglish": "Before discussing the budget, let us review the figures."
  },
  "gritar": {
    "example": "No hace falta gritar para que todos te oigan.",
    "exampleEnglish": "You do not need to shout for everyone to hear you."
  },
  "susurrar": {
    "example": "Para no despertar al bebé, tuvimos que susurrar en el pasillo.",
    "exampleEnglish": "To avoid waking the baby, we had to whisper in the corridor."
  },
  "firmar": {
    "example": "Lee todas las condiciones antes de firmar el contrato.",
    "exampleEnglish": "Read all the terms before signing the contract."
  },
  "copiar": {
    "example": "Puedes copiar la dirección en tu cuaderno.",
    "exampleEnglish": "You can copy the address into your notebook."
  },
  "borrar": {
    "example": "Está escrito a lápiz, así que lo podéis borrar.",
    "exampleEnglish": "It's written in pencil, so you can erase it."
  },
  "dibujar": {
    "example": "¿Cuáles son las cosas más difíciles de dibujar?",
    "exampleEnglish": "What are the most difficult things to draw?"
  },
  "pintar": {
    "example": "Pintar es otra cosa que puedo hacer bastante bien.",
    "exampleEnglish": "Painting is another thing I can do fairly well."
  },
  "imprimir": {
    "example": "Este aparato puede imprimir sesenta páginas por minuto.",
    "exampleEnglish": "This machine can print sixty pages a minute."
  },
  "publicar": {
    "example": "Él acaba de publicar una interesante serie de artículos.",
    "exampleEnglish": "He has just published an interesting series of articles."
  },
  "encender": {
    "example": "Apreté el botón para encender la radio.",
    "exampleEnglish": "I pressed the button to turn the radio on."
  },
  "apagar": {
    "example": "Deberías apagar la luz antes de irte a dormir.",
    "exampleEnglish": "You should turn off the light before going to sleep."
  },
  "conectar": {
    "example": "¿Tienes la sensación de que no puedes conectar con otra gente?",
    "exampleEnglish": "Do you feel you can't connect with other people?"
  },
  "desconectar": {
    "example": "Conviene desconectar la tostadora antes de limpiarla.",
    "exampleEnglish": "It is sensible to unplug the toaster before cleaning it."
  },
  "cargar": {
    "example": "El personal ayudó a cargar las cajas en la furgoneta.",
    "exampleEnglish": "The staff helped load the boxes into the van."
  },
  "descargar": {
    "example": "Puedes descargar grabaciones de nativos en nuestra página web.",
    "exampleEnglish": "You can download audio files by native speakers from our website."
  },
  "instalar": {
    "example": "El hombre trató de instalar su propia antena.",
    "exampleEnglish": "The man tried to install his own antenna."
  },
  "actualizar": {
    "example": "Tom tiene que actualizar su página web.",
    "exampleEnglish": "Tom needs to update his website."
  },
  "reparar": {
    "example": "El costo de reparar el techo la dejó pasmada.",
    "exampleEnglish": "The cost of repairing the roof shocked her."
  },
  "funcionar": {
    "example": "No está claro que podamos hacer funcionar el motor.",
    "exampleEnglish": "It is doubtful if we can get the engine working."
  },
  "seleccionar": {
    "example": "Mantén pulsada la tecla Mayús para seleccionar varias fotografías.",
    "exampleEnglish": "Hold down the Shift key to select several photographs."
  },
  "pulsar": {
    "example": "Todo lo que tienes que hacer es pulsar el botón.",
    "exampleEnglish": "All you have to do is press the button."
  },
  "clicar": {
    "example": "Basta con clicar en el icono azul para abrir el calendario.",
    "exampleEnglish": "You only need to click the blue icon to open the calendar."
  },
  "navegar": {
    "example": "Ella estaba deseando irse a navegar con él.",
    "exampleEnglish": "She was looking forward to going sailing with him."
  },
  "eliminar": {
    "example": "Este filtro permite eliminar el ruido de fondo de la grabación.",
    "exampleEnglish": "This filter can remove background noise from the recording."
  },
  "editar": {
    "example": "Para editar una frase, haga clic en el icono de lápiz.",
    "exampleEnglish": "To edit a sentence, click on the pencil icon."
  },
  "revisar": {
    "example": "Voy a revisar el horario antes de comprar los billetes.",
    "exampleEnglish": "I am going to check the timetable before buying the tickets."
  },
  "comprobar": {
    "example": "Tom revisó su billetera para comprobar cuánto dinero tenía.",
    "exampleEnglish": "Tom checked his wallet to see how much money he had."
  },
  "medir": {
    "example": "Él se debe medir la presión sanguínea todos los días.",
    "exampleEnglish": "He has to have his blood pressure taken every day."
  },
  "calcular": {
    "example": "Los científicos fácilmente pueden calcular la distancia entre planetas.",
    "exampleEnglish": "Scientists can easily compute the distance between planets."
  },
  "sumar": {
    "example": "¿Puedes sumar estos números?",
    "exampleEnglish": "Can you add these numbers?"
  },
  "restar": {
    "example": "Para calcular el cambio, hay que restar dieciocho euros de cincuenta.",
    "exampleEnglish": "To calculate the change, you have to subtract eighteen euros from fifty."
  },
  "multiplicar": {
    "example": "La receta exige multiplicar todas las cantidades por tres.",
    "exampleEnglish": "The recipe requires you to multiply all the quantities by three."
  },
  "dividir": {
    "example": "Esa crisis amenazaba con dividir a la nación.",
    "exampleEnglish": "That crisis threatened to split the nation in two."
  },
  "ordenar": {
    "example": "No tengo tiempo de ordenar mis libros antes de irme.",
    "exampleEnglish": "I have no time to put my books in order before I go."
  },
  "clasificar": {
    "example": "Nos llevó toda la tarde clasificar las cartas por fecha.",
    "exampleEnglish": "It took us all afternoon to sort the letters by date."
  },
  "agrupar": {
    "example": "Puedes agrupar las piezas según su forma y su color.",
    "exampleEnglish": "You can group the pieces according to their shape and colour."
  },
  "mezclar": {
    "example": "No me gusta mezclar trabajo con placer.",
    "exampleEnglish": "I don't like to mix business with pleasure."
  },
  "separar": {
    "example": "Ellos se quieren separar después de 40 años de matrimonio.",
    "exampleEnglish": "They want to separate after 40 years of marriage."
  },
  "pegar": {
    "example": "Usa cinta de papel para pegar el dibujo a la cartulina.",
    "exampleEnglish": "Use masking tape to stick the drawing to the card."
  },
  "unir": {
    "example": "Necesitamos un nuevo líder para unir a nuestra empresa.",
    "exampleEnglish": "We need a new leader to pull our company together."
  },
  "llenar": {
    "example": "Tom tuvo que llenar un montón de formularios.",
    "exampleEnglish": "Tom had to fill out lots of forms."
  },
  "vaciar": {
    "example": "El camarero salió a vaciar las botellas en el contenedor verde.",
    "exampleEnglish": "The waiter went out to empty the bottles into the green recycling bin."
  },
  "cubrir": {
    "example": "Ese dinero es suficiente para cubrir los gastos.",
    "exampleEnglish": "That's enough money to cover the expenses."
  },
  "pausar": {
    "example": "No olvides pausar la grabación cuando termine la entrevista.",
    "exampleEnglish": "Do not forget to pause the recording when the interview ends."
  },
  "reiniciar": {
    "example": "¿Probaste a reiniciar el ordenador?",
    "exampleEnglish": "Did you try restarting the computer?"
  },
  "practicar": {
    "example": "A mí me gusta tanto ver como practicar deportes.",
    "exampleEnglish": "I like both watching and playing sports."
  },
  "memorizar": {
    "example": "Tenemos que memorizar este poema para la próxima clase.",
    "exampleEnglish": "We have to memorize this poem by the next class."
  },
  "imaginar": {
    "example": "¿Te puedes imaginar cómo sería la vida sin televisión?",
    "exampleEnglish": "Can you imagine what life would be like without television?"
  },
  "soñar": {
    "example": "Solo quien tiene el coraje de soñar cambia el mundo.",
    "exampleEnglish": "Only those who dare to dream change the world."
  },
  "desear": {
    "example": "Para hacer dinero, uno debe primero desear el dinero.",
    "exampleEnglish": "To make money one must want money."
  },
  "evitar": {
    "example": "Debemos evitar que este tipo de incidente se repita.",
    "exampleEnglish": "We must prevent this type of incident from recurring."
  },
  "tener": {
    "example": "¿Sabías que los hombres pueden tener cáncer de mama?",
    "exampleEnglish": "Did you know that men can get breast cancer?"
  },
  "convertirse": {
    "example": "Tom en realidad nunca quiso convertirse en músico profesional.",
    "exampleEnglish": "Tom never really wanted to become a professional musician."
  },
  "disminuir": {
    "example": "Es necesaria la cooperación de los empleados para disminuir los gastos.",
    "exampleEnglish": "The employees need to cooperate to lower expenses."
  },
  "desarrollar": {
    "example": "El equipo espera desarrollar una batería más duradera.",
    "exampleEnglish": "The team hopes to develop a longer-lasting battery."
  },
  "construir": {
    "example": "El coste de construir el ferrocarril era demasiado alto.",
    "exampleEnglish": "The cost of building the railroad was very high."
  },
  "destruir": {
    "example": "La humedad puede destruir documentos antiguos en pocos meses.",
    "exampleEnglish": "Damp can destroy old documents within a few months."
  },
  "fabricar": {
    "example": "La cooperativa aprendió a fabricar jabón con aceite usado.",
    "exampleEnglish": "The cooperative learnt to make soap from used oil."
  },
  "alquilar": {
    "example": "Le costó 50 dólares alquilar un coche en Hawái.",
    "exampleEnglish": "It cost him 50 dollars to rent a car in Hawaii."
  },
  "devolver": {
    "example": "Le tengo que devolver el dinero a Tomás.",
    "exampleEnglish": "I have to give the money back to Tom."
  },
  "prestar": {
    "example": "Deberían prestar más atención a lo que dicen.",
    "exampleEnglish": "You should pay more attention to what you say."
  },
  "mandar": {
    "example": "Olvidé mandar tarjetas de año nuevo a mis amigos.",
    "exampleEnglish": "I forgot to send New Year's cards to my friends."
  },
  "entregar": {
    "example": "No le quiero entregar mi llave a Tom.",
    "exampleEnglish": "I don't want to give Tom my key."
  },
  "invertir": {
    "example": "El gobierno debería invertir más dinero en la agricultura.",
    "exampleEnglish": "The government should invest more money in agriculture."
  },
  "descansar": {
    "example": "El anciano se detuvo un momento para descansar.",
    "exampleEnglish": "The old man stopped for a moment to rest."
  },
  "despertar": {
    "example": "La luz del amanecer suele despertar a los pájaros del jardín.",
    "exampleEnglish": "The light at dawn usually wakes the birds in the garden."
  },
  "sentar": {
    "example": "La anfitriona decidió sentar a los invitados cerca de la ventana.",
    "exampleEnglish": "The host decided to seat the guests near the window."
  },
  "acostar": {
    "example": "Voy a acostar al bebé después del baño.",
    "exampleEnglish": "I am going to put the baby to bed after the bath."
  },
  "vestirse": {
    "example": "Los niños dependen de los padres para alimentarse y vestirse.",
    "exampleEnglish": "Children depend on their parents for food and clothing."
  },
  "desnudar": {
    "example": "El viento de otoño empezó a desnudar los árboles de hojas.",
    "exampleEnglish": "The autumn wind began to strip the leaves from the trees."
  },
  "desnudarse": {
    "example": "Los nadadores entraron en los vestuarios para desnudarse.",
    "exampleEnglish": "The swimmers went into the changing rooms to get undressed."
  },
  "lavarse": {
    "example": "Tom usó agua y jabón para lavarse las manos.",
    "exampleEnglish": "Tom used soap and water to wash his hands."
  },
  "duchar": {
    "example": "Después del paseo, tuvimos que duchar al perro.",
    "exampleEnglish": "After the walk, we had to shower the dog."
  },
  "bañar": {
    "example": "¿A quién le toca bañar al perro?",
    "exampleEnglish": "Whose turn is it to give the dog a bath?"
  },
  "peinar": {
    "example": "Ella siempre se hace peinar por un famoso peluquero.",
    "exampleEnglish": "She always has her hair done by a famous hairdresser."
  },
  "afeitar": {
    "example": "Debería haber probado esta máquina de afeitar antes de comprarla.",
    "exampleEnglish": "I should've tried out this electric razor before buying it."
  },
  "maquillar": {
    "example": "Una artista vino a maquillar a los actores antes del estreno.",
    "exampleEnglish": "A make-up artist came to do the actors' make-up before the première."
  },
  "maquillarse": {
    "example": "Mary terminó de maquillarse.",
    "exampleEnglish": "Mary finished putting on her makeup."
  },
  "desayunar": {
    "example": "¿Tú crees que desayunar todos los días es importante?",
    "exampleEnglish": "Do you think that eating breakfast every day is important?"
  },
  "almorzar": {
    "example": "A lo mejor nos podríamos juntar alguna vez y almorzar.",
    "exampleEnglish": "Maybe we could get together sometime and have lunch."
  },
  "cenar": {
    "example": "Pensé que Tom daría un paseo antes de cenar.",
    "exampleEnglish": "I thought Tom would take a walk before dinner."
  },
  "merendar": {
    "example": "Cuando salíamos del colegio, solíamos merendar pan con chocolate.",
    "exampleEnglish": "When we left school, we used to have bread and chocolate as an afternoon snack."
  },
  "calentar": {
    "example": "Calentar el agua no cambia su composición química.",
    "exampleEnglish": "Heating water does not change its chemical composition."
  },
  "enfriar": {
    "example": "Es mejor enfriar el vino blanco antes de servirlo.",
    "exampleEnglish": "It's better to chill white wine before you serve it."
  },
  "hervir": {
    "example": "Ni siquiera sé hervir agua, mucho menos asar un pavo.",
    "exampleEnglish": "I cannot even boil water, much less roast a turkey."
  },
  "freír": {
    "example": "Hace tanto calor afuera que podrías freír un huevo.",
    "exampleEnglish": "It's so hot outside, you could fry an egg."
  },
  "hornear": {
    "example": "Hoy voy a hornear una tarta de melocotón.",
    "exampleEnglish": "I'm going to bake a peach pie today."
  },
  "pelar": {
    "example": "Voy a pelar las patatas antes de poner agua a hervir.",
    "exampleEnglish": "I am going to peel the potatoes before boiling the water."
  },
  "echar": {
    "example": "Recuerda echar una pizca de sal antes de servir la sopa.",
    "exampleEnglish": "Remember to add a pinch of salt before serving the soup."
  },
  "secar": {
    "example": "Secar este tejido a alta temperatura podría causar encogimiento.",
    "exampleEnglish": "Drying this fabric at a high temperature may cause shrinkage."
  },
  "planchar": {
    "example": "Hace falta planchar esta camisa.",
    "exampleEnglish": "This shirt needs to be ironed."
  },
  "barrer": {
    "example": "Todo lo que tienes que hacer es barrer el piso.",
    "exampleEnglish": "All you have to do is sweep the floor."
  },
  "fregar": {
    "example": "¿Quieres que te ayude a fregar los platos?",
    "exampleEnglish": "Would you like me to help you with washing the dishes?"
  },
  "arreglar": {
    "example": "Me las apañé para arreglar mi coche yo mismo.",
    "exampleEnglish": "I managed to repair my car by myself."
  },
  "reciclar": {
    "example": "La oficina empezó a reciclar todo el papel usado.",
    "exampleEnglish": "The office began to recycle all its used paper."
  },
  "plantar": {
    "example": "Cuando tenía 14 años, él empezó a plantar fresas.",
    "exampleEnglish": "When he was 14, he started to plant strawberries."
  },
  "regar": {
    "example": "No es bueno regar las plantas a pleno sol.",
    "exampleEnglish": "It's not good to water plants in direct sunlight."
  },
  "cuidar": {
    "example": "Ella ayudó a su madre a cuidar del bebé.",
    "exampleEnglish": "She assisted her mother in caring for the baby."
  },
  "alimentar": {
    "example": "Preferiría alimentar a mi perro antes de que comamos.",
    "exampleEnglish": "I would rather feed my dog before we eat."
  },
  "adoptar": {
    "example": "Algunos insectos pueden adoptar el color de su entorno.",
    "exampleEnglish": "Some insects can take on the color of their surroundings."
  },
  "criar": {
    "example": "Tenía la esperanza de criar a mis hijos en Boston.",
    "exampleEnglish": "I was hoping to raise my kids in Boston."
  },
  "cazar": {
    "example": "¿Cuándo fue la última vez que fueron a cazar?",
    "exampleEnglish": "When was the last time you went hunting?"
  },
  "pescar": {
    "example": "Era un buen día así que fuimos a pescar.",
    "exampleEnglish": "It was a nice day so we went fishing."
  },
  "morder": {
    "example": "Tiene el mal hábito de morder el lápiz.",
    "exampleEnglish": "He has the bad habit of chewing his pencil."
  },
  "ladrar": {
    "example": "Ella oyó a un perro ladrar a lo lejos.",
    "exampleEnglish": "She heard a dog barking in the distance."
  },
  "maullar": {
    "example": "Oímos al gato maullar detrás de la puerta cerrada.",
    "exampleEnglish": "We heard the cat miaow behind the closed door."
  },
  "fotografiar": {
    "example": "A mi hermano le encanta fotografiar montañas.",
    "exampleEnglish": "My brother loves taking pictures of mountains."
  },
  "grabar": {
    "example": "Se necesitaron muchos meses para grabar esa película.",
    "exampleEnglish": "It took several months to shoot that film."
  },
  "filmar": {
    "example": "El director eligió filmar la última escena al amanecer.",
    "exampleEnglish": "The director chose to film the final scene at dawn."
  },
  "entrenar": {
    "example": "¿Por qué son los perros más fáciles de entrenar que los gatos?",
    "exampleEnglish": "Why are dogs easier to train than cats?"
  },
  "competir": {
    "example": "Tuve que competir con él por un ascenso.",
    "exampleEnglish": "I had to compete with him for promotion."
  },
  "empatar": {
    "example": "Un gol en el último minuto permitió al Betis empatar el partido.",
    "exampleEnglish": "A goal in the final minute allowed Betis to draw the match."
  },
  "marcar": {
    "example": "El reloj acaba de marcar las tres.",
    "exampleEnglish": "The clock has just struck three."
  },
  "atrapar": {
    "example": "¿Qué tipo de cebo usaste para atrapar estos peces?",
    "exampleEnglish": "What kind of bait did you use to catch these fish?"
  },
  "golpear": {
    "example": "Las gotas de lluvia empezaron a golpear suavemente el cristal.",
    "exampleEnglish": "The raindrops began to tap gently against the windowpane."
  },
  "patear": {
    "example": "El defensa corrió hacia el balón para patear desde lejos.",
    "exampleEnglish": "The defender ran towards the ball to kick it from long range."
  },
  "pedalear": {
    "example": "Tras el descanso, aún nos quedaban veinte kilómetros por pedalear.",
    "exampleEnglish": "After the break, we still had twenty kilometres left to cycle."
  },
  "esquiar": {
    "example": "Yo quiero comprar un par de botas de esquiar.",
    "exampleEnglish": "I want to buy a pair of ski boots."
  },
  "patinar": {
    "example": "Yo no esquío pero me gusta mucho patinar.",
    "exampleEnglish": "I don't ski, but I really like to skate."
  },
  "escalar": {
    "example": "Me gusta escalar árboles de vez en cuando.",
    "exampleEnglish": "I enjoy climbing trees every once in a while."
  },
  "despegar": {
    "example": "El avión va a despegar en cuanto se despeje la pista.",
    "exampleEnglish": "The plane will take off as soon as the runway is clear."
  },
  "aterrizar": {
    "example": "Un helicóptero es capaz de despegar y aterrizar verticalmente.",
    "exampleEnglish": "A helicopter is able to take off and land straight up and down."
  },
  "facturar": {
    "example": "La aerolínea permite facturar una maleta de hasta veinte kilos.",
    "exampleEnglish": "The airline allows passengers to check in one suitcase weighing up to twenty kilos."
  },
  "embarcar": {
    "example": "Los pasajeros deben embarcar por la puerta doce.",
    "exampleEnglish": "Passengers must board at gate twelve."
  },
  "informar": {
    "example": "Creo que deberíamos informar a los padres de Tom.",
    "exampleEnglish": "I think we should notify Tom's parents."
  },
  "confirmar": {
    "example": "No hay modo de confirmar que él esté vivo.",
    "exampleEnglish": "There is no way to confirm that he is alive."
  },
  "avisar": {
    "example": "¿Me podría avisar cuándo me tengo que bajar?",
    "exampleEnglish": "Would you please tell me when to get off?"
  },
  "anunciar": {
    "example": "La empresa espera anunciar los resultados el próximo jueves.",
    "exampleEnglish": "The company expects to announce the results next Thursday."
  },
  "comunicar": {
    "example": "Nos podemos comunicar en francés.",
    "exampleEnglish": "We can communicate in French."
  },
  "traducir": {
    "example": "¿Puedo ayudar a traducir la página web a otras lenguas?",
    "exampleEnglish": "Can I help translate the website into other languages?"
  },
  "pronunciar": {
    "example": "No estoy seguro de cómo pronunciar esta palabra.",
    "exampleEnglish": "I am not sure how to pronounce the word."
  },
  "deletrear": {
    "example": "¿Podría deletrear su nombre, por favor?",
    "exampleEnglish": "Could you spell your name, please?"
  },
  "corregir": {
    "example": "¿Puedes corregir este informe antes de las 5 de la tarde?",
    "exampleEnglish": "Can you correct this report before 5:00 p.m.?"
  },
  "aprobar": {
    "example": "Estudié mucho, de modo que pude aprobar el examen.",
    "exampleEnglish": "I studied hard so that I could pass the examination."
  },
  "suspender": {
    "example": "Está claro que te van a suspender si no estudias más.",
    "exampleEnglish": "You'll definitely fail if you don't study more."
  },
  "examinar": {
    "example": "Los dentistas toman rayos x para examinar tus dientes.",
    "exampleEnglish": "Dentists take X-rays to examine your teeth."
  },
  "evaluar": {
    "example": "Es difícil evaluar su capacidad.",
    "exampleEnglish": "It's difficult to evaluate his ability."
  },
  "completar": {
    "example": "Tom debería ser capaz de completar el trabajo rápido.",
    "exampleEnglish": "Tom should be able to complete the job quickly."
  },
  "rellenar": {
    "example": "Tom vino aquí a ayudarnos a rellenar estos formularios.",
    "exampleEnglish": "Tom came here to help us fill out these forms."
  },
  "investigar": {
    "example": "Investigar las causas del cáncer es muy costoso.",
    "exampleEnglish": "Investigating the causes of cancer is very expensive."
  },
  "analizar": {
    "example": "Tenemos que analizar eso.",
    "exampleEnglish": "We have to analyze that."
  },
  "experimentar": {
    "example": "No tenga miedo de experimentar cosas nuevas.",
    "exampleEnglish": "Don't be afraid to try new things."
  },
  "demostrar": {
    "example": "Ella está tratando de demostrar la existencia de los fantasmas.",
    "exampleEnglish": "She is trying to prove the existence of ghosts."
  },
  "concluir": {
    "example": "Necesito concluir esta tarea antes de que se haga de noche.",
    "exampleEnglish": "I need to finish this work before it gets dark."
  },
  "gestionar": {
    "example": "Él tiene la capacidad suficiente para gestionar un negocio.",
    "exampleEnglish": "He has enough ability to manage a business."
  },
  "liderar": {
    "example": "Ellos ponen en duda su capacidad para liderar.",
    "exampleEnglish": "They question your ability to lead."
  },
  "colaborar": {
    "example": "Tom fue acusado de colaborar con el enemigo.",
    "exampleEnglish": "Tom was accused of collaborating with the enemy."
  },
  "participar": {
    "example": "No pude participar en el encuentro por estar enfermo.",
    "exampleEnglish": "I wasn't able to attend the meeting due to illness."
  },
  "asistir": {
    "example": "¿Vas a asistir a la reunión de esta noche?",
    "exampleEnglish": "Are you going to attend the meeting tonight?"
  },
  "proponer": {
    "example": "Está claro que nadie más tiene algo nuevo que proponer.",
    "exampleEnglish": "It is clear that no one has anything new to suggest."
  },
  "negociar": {
    "example": "Mi amigo quiere negociar con casas sudamericanas.",
    "exampleEnglish": "My friend wants to do business with South American firms."
  },
  "contratar": {
    "example": "Queremos contratar a alguien que hable un francés fluido.",
    "exampleEnglish": "We want to hire someone who can speak French fluently."
  },
  "despedir": {
    "example": "Ha salido al aeropuerto a despedir a un amigo.",
    "exampleEnglish": "He went to the airport to see his friend off."
  },
  "emplear": {
    "example": "Tom convenció a Mary de emplear a John.",
    "exampleEnglish": "Tom convinced Mary to hire John."
  },
  "solicitar": {
    "example": "Eres demasiado joven para solicitar el empleo.",
    "exampleEnglish": "You're too young to apply for the job."
  },
  "contactar": {
    "example": "Un caballero lo intentó contactar durante su ausencia, señor.",
    "exampleEnglish": "A gentleman called in your absence, sir."
  },
  "apoyar": {
    "example": "Tom está aquí para apoyar a Mary.",
    "exampleEnglish": "Tom is here to support Mary."
  },
  "resolver": {
    "example": "A fin de cuentas, nadie pudo resolver el problema.",
    "exampleEnglish": "No one could solve the problem after all."
  },
  "solucionar": {
    "example": "Aquí no hay nadie que pueda solucionar el problema.",
    "exampleEnglish": "There's no one here who can deal with the problem."
  },
  "implementar": {
    "example": "El hospital tardará meses en implementar el nuevo protocolo.",
    "exampleEnglish": "The hospital will take months to implement the new protocol."
  },
  "diseñar": {
    "example": "No te sería muy difícil diseñar un nuevo sitio web.",
    "exampleEnglish": "It wouldn't be too hard to design a new website for you."
  },
  "programar": {
    "example": "Te enseñaré a programar, pero no hoy.",
    "exampleEnglish": "I will teach you to program, but not today."
  },
  "depurar": {
    "example": "Necesitamos depurar el programa antes de mostrárselo al cliente.",
    "exampleEnglish": "We need to debug the program before showing it to the client."
  },
  "desplegar": {
    "example": "El equipo acordó desplegar la actualización durante la madrugada.",
    "exampleEnglish": "The team agreed to deploy the update overnight."
  },
  "documentar": {
    "example": "Cada investigador debe documentar los cambios en el experimento.",
    "exampleEnglish": "Each researcher must document the changes to the experiment."
  },
  "planificar": {
    "example": "Reunimos varios mapas para planificar la ruta por los Pirineos.",
    "exampleEnglish": "We gathered several maps to plan the route through the Pyrenees."
  },
  "estimar": {
    "example": "Resulta difícil estimar el coste sin conocer las medidas exactas.",
    "exampleEnglish": "It is difficult to estimate the cost without knowing the exact measurements."
  },
  "priorizar": {
    "example": "Ante tantas averías, el taller debe priorizar las reparaciones urgentes.",
    "exampleEnglish": "With so many faults, the garage must prioritise urgent repairs."
  },
  "asignar": {
    "example": "Corresponde a la coordinadora asignar un tutor a cada alumno.",
    "exampleEnglish": "It is the coordinator's responsibility to assign a tutor to each pupil."
  },
  "monitorizar": {
    "example": "Instalaron sensores para monitorizar la humedad del invernadero.",
    "exampleEnglish": "They installed sensors to monitor the humidity in the greenhouse."
  },
  "controlar": {
    "example": "Tom hizo lo que pudo para controlar su temperamento.",
    "exampleEnglish": "Tom did his best to keep temper under control."
  },
  "asegurar": {
    "example": "Te puedo asegurar que tu honestidad paga a la larga.",
    "exampleEnglish": "I can assure you that honesty pays in the long run."
  },
  "proteger": {
    "example": "Ella arriesgó su vida para proteger a su hijo.",
    "exampleEnglish": "She risked her life to protect her child."
  },
  "bloquear": {
    "example": "Tom admitió que fue quien se dejó las ventanas sin bloquear.",
    "exampleEnglish": "Tom admitted he was the one who left the windows unlocked."
  },
  "desbloquear": {
    "example": "Una huella dactilar permite desbloquear el teléfono sin contraseña.",
    "exampleEnglish": "A fingerprint lets you unlock the phone without a password."
  },
  "registrarse": {
    "example": "Quien quiera asistir deberá registrarse antes del viernes.",
    "exampleEnglish": "Anyone wishing to attend must register before Friday."
  },
  "iniciar": {
    "example": "¿Has visto a Tom intentar iniciar un fuego?",
    "exampleEnglish": "Have you seen Tom try to start a fire?"
  },
  "acceder": {
    "example": "Parece que Tom no puede acceder a sus datos.",
    "exampleEnglish": "Tom can't seem to access his data."
  },
  "denegar": {
    "example": "El banco puede denegar el préstamo si faltan documentos.",
    "exampleEnglish": "The bank may refuse the loan if any documents are missing."
  },
  "recuperar": {
    "example": "Tengo que trabajar duro para recuperar el tiempo perdido.",
    "exampleEnglish": "I have to work hard to make up for lost time."
  },
  "renombrar": {
    "example": "Decidieron renombrar la plaza en honor a la poeta local.",
    "exampleEnglish": "They decided to rename the square in honour of the local poet."
  },
  "sincronizar": {
    "example": "Al conectar el reloj, empieza a sincronizar los datos automáticamente.",
    "exampleEnglish": "When you connect the watch, it starts synchronising the data automatically."
  },
  "exportar": {
    "example": "No puedo averiguar cómo exportar mis direcciones de correo electrónico a un archivo de texto.",
    "exampleEnglish": "I can't figure out how to export my email addresses to a text file."
  },
  "filtrar": {
    "example": "Si tus ventanas no son herméticas, se va a filtrar humedad.",
    "exampleEnglish": "If your windows are not airtight, moisture will seep in."
  },
  "desmarcar": {
    "example": "Para dejar de recibir publicidad, debes desmarcar esta casilla.",
    "exampleEnglish": "To stop receiving advertising, you must untick this box."
  },
  "avanzar": {
    "example": "¿Puedes avanzar para que podamos cerrar la puerta?",
    "exampleEnglish": "Could you move forward so we can close the door?"
  },
  "retroceder": {
    "example": "Es mejor retroceder que perderse.",
    "exampleEnglish": "It's better to walk back than to get lost."
  },
  "ocultar": {
    "example": "Él trató de ocultar lo que realmente estaba pasando.",
    "exampleEnglish": "He tried to hide what was really going on."
  },
  "expandir": {
    "example": "Quisiera expandir mi vocabulario.",
    "exampleEnglish": "I want to increase my vocabulary."
  },
  "contraer": {
    "example": "Compartir agujas aumenta el riesgo de contraer una infección.",
    "exampleEnglish": "Sharing needles increases the risk of contracting an infection."
  },
  "activar": {
    "example": "Tienes que activar el sonido de tu micrófono.",
    "exampleEnglish": "You have to unmute your microphone."
  },
  "desactivar": {
    "example": "Me gustaría averiguar cómo desactivar comentarios en mi blog.",
    "exampleEnglish": "I wish I could figure out how to disable comments on my blog."
  },
  "configurar": {
    "example": "El técnico regresará mañana para configurar el rúter.",
    "exampleEnglish": "The technician will return tomorrow to configure the router."
  },
  "ajustar": {
    "example": "Tom trató de ajustar la temperatura de la ducha.",
    "exampleEnglish": "Tom tried to adjust the temperature of the shower."
  },
  "restablecer": {
    "example": "Introduce tu correo electrónico para restablecer la contraseña.",
    "exampleEnglish": "Enter your email address to reset your password."
  },
  "duplicar": {
    "example": "Un buen verano podría duplicar la cosecha de tomates.",
    "exampleEnglish": "A good summer could double the tomato harvest."
  },
  "arrastrar": {
    "example": "Evita arrastrar la mesa porque podrías rayar el suelo.",
    "exampleEnglish": "Avoid dragging the table because you might scratch the floor."
  },
  "soltar": {
    "example": "El pescador decidió soltar el pez en el río.",
    "exampleEnglish": "The fisherman decided to release the fish into the river."
  },
  "deslizar": {
    "example": "Hay que deslizar la tarjeta por la ranura con la banda hacia abajo.",
    "exampleEnglish": "You need to swipe the card through the slot with the strip facing downwards."
  },
  "acercar": {
    "example": "¿Te puedes acercar más?",
    "exampleEnglish": "Can you get any closer?"
  },
  "alejar": {
    "example": "La policía intentó alejar a los curiosos del edificio.",
    "exampleEnglish": "The police tried to move the onlookers away from the building."
  },
  "escanear": {
    "example": "Me pidieron escanear el pasaporte y enviar una copia legible.",
    "exampleEnglish": "They asked me to scan my passport and send a legible copy."
  },
  "archivar": {
    "example": "Tom se olvidó de archivar sus impuestos.",
    "exampleEnglish": "Tom forgot to file his taxes."
  },
  "mencionar": {
    "example": "Él tiene muchos sellos extranjeros, sin mencionar los japoneses.",
    "exampleEnglish": "He has many foreign stamps, not to mention Japanese ones."
  },
  "notificar": {
    "example": "La clínica se comprometió a notificar cualquier cambio de horario.",
    "exampleEnglish": "The clinic undertook to notify us of any change to the timetable."
  },
  "suscribir": {
    "example": "Puedes suscribir a toda la oficina al boletín mensual.",
    "exampleEnglish": "You can subscribe the whole office to the monthly newsletter."
  },
  "renovar": {
    "example": "Tom necesita renovar su pasaporte antes del quince del próximo mes.",
    "exampleEnglish": "Tom needs to renew his passport before the fifteenth of next month."
  },
  "vencer": {
    "example": "Cuatro ases es una mano difícil de vencer.",
    "exampleEnglish": "Four aces is a tough hand to beat."
  },
  "caducar": {
    "example": "Este permiso suele caducar dos años después de su expedición.",
    "exampleEnglish": "This permit usually expires two years after it is issued."
  },
  "reclamar": {
    "example": "Los pasajeros hicieron cola para reclamar una indemnización.",
    "exampleEnglish": "The passengers queued to claim compensation."
  },
  "reembolsar": {
    "example": "La tienda prometió reembolsar el importe en cinco días laborables.",
    "exampleEnglish": "The shop promised to refund the amount within five working days."
  },
  "donar": {
    "example": "La biblioteca anima a los vecinos a donar libros usados.",
    "exampleEnglish": "The library encourages residents to donate used books."
  },
  "regalar": {
    "example": "Te voy a regalar una bicicleta para tu cumpleaños.",
    "exampleEnglish": "I will give you a bicycle for your birthday."
  },
  "inspeccionar": {
    "example": "Dos ingenieros bajaron al túnel para inspeccionar las grietas.",
    "exampleEnglish": "Two engineers went down into the tunnel to inspect the cracks."
  },
  "pesar": {
    "example": "Puedes pesar la harina directamente en este recipiente.",
    "exampleEnglish": "You can weigh the flour directly in this bowl."
  },
  "registrar": {
    "example": "El termómetro puede registrar variaciones de una décima de grado.",
    "exampleEnglish": "The thermometer can record variations of one tenth of a degree."
  },
  "vigilar": {
    "example": "No necesito vigilar a Tom todo el tiempo.",
    "exampleEnglish": "I don't need to watch Tom all the time."
  },
  "denunciar": {
    "example": "No te voy a denunciar.",
    "exampleEnglish": "I won't press charges."
  },
  "rescatar": {
    "example": "Estuve a punto de ahogarme al intentar rescatar a un chico.",
    "exampleEnglish": "I came near being drowned, trying to rescue a boy."
  },
  "salvar": {
    "example": "Tom es el único que puede salvar al mundo.",
    "exampleEnglish": "Tom is the only one who can save the world."
  },
  "atacar": {
    "example": "Este hongo puede atacar las raíces de los árboles jóvenes.",
    "exampleEnglish": "This fungus can attack the roots of young trees."
  },
  "defender": {
    "example": "Tenemos que defender nuestro país cueste lo que cueste.",
    "exampleEnglish": "We have to defend our country at any cost."
  },
  "luchar": {
    "example": "Debe usted luchar contra esa tendencia que tiene.",
    "exampleEnglish": "You've got to fight that tendency of yours."
  },
  "matar": {
    "example": "Una helada tardía puede matar los brotes jóvenes.",
    "exampleEnglish": "A late frost can kill young shoots."
  },
  "herir": {
    "example": "Tom no quiso herir los sentimientos de Mary.",
    "exampleEnglish": "Tom didn't mean to hurt Mary's feelings."
  },
  "curar": {
    "example": "La fisioterapia ayudó a curar la lesión sin cirugía.",
    "exampleEnglish": "Physiotherapy helped heal the injury without surgery."
  },
  "sanar": {
    "example": "La herida necesita tiempo y reposo para sanar por completo.",
    "exampleEnglish": "The wound needs time and rest to heal completely."
  },
  "diagnosticar": {
    "example": "Solo un especialista puede diagnosticar esa enfermedad con certeza.",
    "exampleEnglish": "Only a specialist can diagnose that illness with certainty."
  },
  "recetar": {
    "example": "La médica decidió recetar un antibiótico distinto.",
    "exampleEnglish": "The doctor decided to prescribe a different antibiotic."
  },
  "respirar": {
    "example": "¿Tienes dificultades para respirar con facilidad cuando caminas?",
    "exampleEnglish": "Do you get short of breath easily when walking?"
  },
  "toser": {
    "example": "Yo paré de toser luego de dos días.",
    "exampleEnglish": "I stopped coughing after two days."
  },
  "estornudar": {
    "example": "He visto estornudar a mi perro, pero nunca a mi gato.",
    "exampleEnglish": "I've seen my dog sneeze but never my cat."
  },
  "sangrar": {
    "example": "Me rasqué la cabeza tanto que me comenzó a sangrar.",
    "exampleEnglish": "I scratched my head so hard it started bleeding."
  },
  "suceder": {
    "example": "Tom me preguntó qué pensaba que iba a suceder.",
    "exampleEnglish": "Tom asked me what I thought was going to happen."
  },
  "pertenecer": {
    "example": "Esos países solían pertenecer a Francia.",
    "exampleEnglish": "Those countries used to belong to France."
  },
  "depender": {
    "example": "No debes depender de la ayuda de los demás.",
    "exampleEnglish": "You mustn't depend on others for help."
  },
  "significar": {
    "example": "Un cambio de color puede significar que la fruta está madura.",
    "exampleEnglish": "A change in colour can mean that the fruit is ripe."
  },
  "representar": {
    "example": "Cada símbolo puede representar una estación distinta del año.",
    "exampleEnglish": "Each symbol can represent a different season of the year."
  },
  "establecer": {
    "example": "El comité acordó establecer un horario fijo para las reuniones.",
    "exampleEnglish": "The committee agreed to establish a fixed schedule for meetings."
  },
  "celebrar": {
    "example": "Es solo que no tengo ganas de celebrar mi cumpleaños.",
    "exampleEnglish": "I just don't feel like celebrating my birthday."
  },
  "aprovechar": {
    "example": "Las literas son una forma de aprovechar el espacio.",
    "exampleEnglish": "Bunk beds are a way to save space."
  },
  "manejar": {
    "example": "No tengo ni idea de cómo manejar este problema.",
    "exampleEnglish": "I have no idea how to handle this problem."
  },
  "admitir": {
    "example": "Cuesta admitir un error, pero hacerlo permite corregirlo.",
    "exampleEnglish": "It is hard to admit a mistake, but doing so makes it possible to correct it."
  },
  "abandonar": {
    "example": "El capitán dio la orden de abandonar el barco.",
    "exampleEnglish": "The captain gave the order to abandon the ship."
  },
  "aplicar": {
    "example": "Tom se hizo aplicar una inyección para la gripa.",
    "exampleEnglish": "Tom got a flu shot."
  },
  "causar": {
    "example": "Esto significó que eran demasiado débiles para causar más problemas.",
    "exampleEnglish": "This meant they were too weak to cause more trouble."
  },
  "conceder": {
    "example": "Tras revisar la solicitud, el juez optó por conceder la libertad provisional.",
    "exampleEnglish": "After reviewing the application, the judge chose to grant bail."
  },
  "conservar": {
    "example": "Me gusta conservar mi ropa el máximo tiempo posible.",
    "exampleEnglish": "I like to keep my clothes for as long as possible."
  },
  "contener": {
    "example": "Tuve que contener la risa durante la representación.",
    "exampleEnglish": "I had to hold back my laughter during the performance."
  },
  "contribuir": {
    "example": "Tom me preguntó si acaso estaría dispuesto a contribuir algo de dinero.",
    "exampleEnglish": "Tom asked me if I would be willing to contribute some money."
  },
  "desaparecer": {
    "example": "Mi dinero parece desaparecer para el final de mes.",
    "exampleEnglish": "My money seems to disappear by the end of the month."
  },
  "exigir": {
    "example": "Tenemos derecho a exigir un futuro seguro para nosotros y las generaciones futuras.",
    "exampleEnglish": "We have a right to demand a safe future for ourselves and future generations."
  },
  "expresar": {
    "example": "No existen palabras para expresar lo increíble que eres.",
    "exampleEnglish": "No words can express how amazing you are."
  },
  "indicar": {
    "example": "Las flechas azules van a indicar la salida más cercana.",
    "exampleEnglish": "The blue arrows will indicate the nearest exit."
  }
};
